<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head profile="http://gmpg.org/xfn/11">
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	
	<title>Talk&#8217;N Tours Audio Blog &#8212; Free Podcasts &amp; Audio Guides</title>
	
	<meta name="generator" content="WordPress 3.1.3" /> <!-- leave this for stats -->
	
	<link rel="stylesheet" href="http://talk-n-tours.com/blog/wp-content/themes/Cutline-1-1.4-2ColumnRight/style.css" type="text/css" media="screen" />
	<link rel="stylesheet" href="http://talk-n-tours.com/blog/wp-content/themes/Cutline-1-1.4-2ColumnRight/custom.css" type="text/css" media="screen" />
	<!--[if lte IE 7]>
	<link rel="stylesheet" type="text/css" href="http://talk-n-tours.com/blog/wp-content/themes/Cutline-1-1.4-2ColumnRight/ie7.css" media="screen" />
	<![endif]-->
	<!--[if lte IE 6]>
	<link rel="stylesheet" type="text/css" href="http://talk-n-tours.com/blog/wp-content/themes/Cutline-1-1.4-2ColumnRight/ie6.css" media="screen" />
	<![endif]-->
	<link rel="alternate" type="application/rss+xml" title="Talk&#8217;N Tours Audio Blog RSS Feed" href="http://talk-n-tours.com/blog/feed" />
	<link rel="pingback" href="http://talk-n-tours.com/blog/xmlrpc.php" />
						
	<script type="text/javascript">//<![CDATA[
	// Google Analytics for WordPress by Yoast v4.1 | http://yoast.com/wordpress/google-analytics/
	var _gaq = _gaq || [];
	_gaq.push(['_setAccount','UA-2302608-1']);
	_gaq.push(['_trackPageview','/404.html?page=' + document.location.pathname + document.location.search + '&from=' + document.referrer],['_trackPageLoadTime']);
	(function() {
		var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	})();
	//]]></script>
<link rel="EditURI" type="application/rsd+xml" title="RSD" href="http://talk-n-tours.com/blog/xmlrpc.php?rsd" />
<link rel="wlwmanifest" type="application/wlwmanifest+xml" href="http://talk-n-tours.com/blog/wp-includes/wlwmanifest.xml" /> 
<link rel='index' title='Talk&#8217;N Tours Audio Blog' href='http://talk-n-tours.com/blog' />
<meta name="generator" content="WordPress 3.1.3" />

<!-- Start Of Script Generated By cforms v11.6.1 [Oliver Seidel | www.deliciousdays.com] -->
<link rel="stylesheet" type="text/css" href="http://talk-n-tours.com/blog/wp-content/plugins/cforms-v11.6.1/styling/cforms.css" />
<script type="text/javascript" src="http://talk-n-tours.com/blog/wp-content/plugins/cforms-v11.6.1/js/cforms.js"></script>
<!-- End Of Script Generated By cforms -->


<!-- WP Menubar 4.10: start CSS -->
<link rel="stylesheet" href="http://talk-n-tours.com/blog/wp-content/plugins/menubar-templates/Suckerfish_41/sf-grey.css" type="text/css" media="screen" />
<!-- WP Menubar 4.10: end CSS -->
<script type="text/javascript" src="http://talk-n-tours.com/blog/wp-content/plugins/powerpress/player.js"></script>
<script type="text/javascript"><!--
function powerpress_pinw(pinw){window.open('http://talk-n-tours.com/blog/?powerpress_pinw='+pinw, 'PowerPressPlayer','toolbar=0,status=0,resizable=1,width=460,height=320');	return false;}
powerpress_url = 'http://talk-n-tours.com/blog/wp-content/plugins/powerpress/';
//-->
</script>
</head>
<body class="custom">
<!-- WP Menubar 4.10: start menu NewMain, template Suckerfish_41, CSS sf-grey.css -->

<script type="text/javascript">
// <![CDATA[
	wpm1_Hover = function() {
	var wpmEls = document.getElementById("wpm1").getElementsByTagName("li");
	for (var i=0; i<wpmEls.length; i++) {
		wpmEls[i].onmouseover = function() {
			this.className += " wpmhover";
		}
		wpmEls[i].onmouseout = function() {
			this.className = this.className.replace(new RegExp(" wpmhover\\b"), "");
		}
	}
}
if (window.attachEvent) window.attachEvent("onload", wpm1_Hover);
// ]]>
</script>

<div class="sf-grey-before"></div>
<div id="wpm1" class="sf-grey">
<ul><li><a href="http://www.talk-n-tours.com" >HOME</a></li><li><a style="cursor:default;" >TOURS</a><ul><li><a href="http://www.talk-n-tours.com/catalog/tour.php?tour=sydney" >SYDNEY HEART OF THE CITY</a></li><li><a href="http://www.talk-n-tours.com/catalog/tour.php?tour=rocks" >THE ROCKS SYDNEY WALK</a></li><li><a href="http://www.talk-n-tours.com/catalog/tour.php?tour=melbourne" >MARVELLOUS MELBOURNE</a></li><li><a href="http://www.talk-n-tours.com/catalog/tour.php?tour=auckland" >AUCKLAND NEW ZEALAND</a></li><li><a href="http://www.talk-n-tours.com/catalog/tour.php?tour=devonport" >DEVONPORT NEW ZEALAND</a></li></ul></li><li><a style="cursor:default;" >DESTINATION GUIDES</a><ul><li><a href="http://www.talk-n-tours.com/catalog/destination.php?dest=australia" >AUSTRALIA</a><ul><li><a href="http://www.talk-n-tours.com/catalog/destination.php?dest=sydney" >SYDNEY</a></li><li><a href="http://www.talk-n-tours.com/catalog/destination.php?dest=sydney" >MELBOURNE</a></li></ul></li><li><a href="http://www.talk-n-tours.com/catalog/tour.php?tour=new_zealand" >NEW ZEALAND</a><ul><li><a href="http://www.talk-n-tours.com/catalog/tour.php?tour=auckland" >AUCKLAND NEW ZEALAND</a></li></ul></li></ul></li><li><a href="http://talk-n-tours.com/blog" >FREE PODCASTS</a></li><li><a href="http://www.talk-n-tours.com/catalog/faq.php" >FAQ</a></li><li><a href="http://www.talk-n-tours.com/catalog/shopping_cart.php" >SHOPPING CART</a></li><li><a style="cursor:default;" >PRIVACY & USAGE</a><ul><li><a href="http://www.talk-n-tours.com/catalog/privacy.php" >PRIVACY POLICY</a></li><li><a href="http://www.talk-n-tours.com/catalog/conditions.php" >AGREEMENT TO TERMS OF USE</a></li></ul></li><li><a href="http://www.talk-n-tours.com/catalog/about.php" >ABOUT</a></li><li><a href="http://www.talk-n-tours.com/catalog/links.php" >LINKS</a></li></ul>
</div>
<div class="sf-grey-after"></div>
<!-- WP Menubar 4.10: end menu NewMain, template Suckerfish_41, CSS sf-grey.css -->
<div id="container">
<!-- <script type="text/javascript">var MenuLinkedBy="AllWebMenus [4]",awmMenuName="tnt",awmBN="646";awmAltUrl="";</script><script charset="UTF-8" src="http://www.talk-n-tours.com/tnt.js" type="text/javascript"></script><script type="text/javascript">awmBuildMenu("osCsid=");
</script> -->

	<div id="masthead">

		<h1><a href="http://talk-n-tours.com/blog">Talk&#8217;N Tours Audio Blog</a></h1>
		<h3>Free Podcasts &amp; Audio Guides</h3>
	</div>

	<ul id="nav">
		<li ><a href="http://talk-n-tours.com/blog">home</a></li>
		<li class="page_item page-item-220"><a href="http://talk-n-tours.com/blog/about" title="about">about</a></li>
<li class="page_item page-item-225"><a href="http://talk-n-tours.com/blog/contact" title="contact">contact</a></li>
		<li class="rss"><a href="http://talk-n-tours.com/blog/feed">RSS</a></li>
	</ul>
	
	<div id="header_img">
				<img src="http://talk-n-tours.com/blog/wp-content/themes/Cutline-1-1.4-2ColumnRight/images/header_5.jpg" width="770px" height="140px" alt="Talk&#8217;N Tours Audio Blog header image 5" title="Talk&#8217;N Tours Audio Blog header image 5" />
			</div>
	<div id="content_box">
	
		<div id="content" class="pages">
			<h2>Easy, tiger. This is a 404 page.</h2>
			<div class="entry">
				<p>You are <em>totally</em> in the wrong place. Do not pass GO; do not collect $200. This is an error page. You might have stumbled here by accident or the post you are looking for is no longer here.</p>
				<p>Please, try one of the following:</p>
				<ul>
					<li>Hit the "back" button on your browser.</li>
					<li>Head on over to the <a href="http://talk-n-tours.com/blog">front page</a>.</li>
					<li>Try searching using the form in the sidebar.</li>
					<li>Click on a link in the sidebar.</li>
					<li>Use the navigation menu at the top of the page.</li>
				</ul>
			</div>
		</div>

		<div id="sidebar">
	<ul class="sidebar_list">
		<li id="search-2" class="widget widget_search"><form method="get" id="search_form" action="http://talk-n-tours.com/blog/">
	<input type="text" class="search_input" value="To search, type and hit enter" name="s" id="s" onfocus="if (this.value == 'To search, type and hit enter') {this.value = '';}" onblur="if (this.value == '') {this.value = 'To search, type and hit enter';}" />
	<input type="hidden" id="searchsubmit" value="Search" />
</form>
</li>
<li id="categories-416651011" class="widget widget_categories"><h2 class="widgettitle">Categories</h2>
		<ul>
	<li class="cat-item cat-item-4"><a href="http://talk-n-tours.com/blog/category/free-audio-guides/australia-audio-guides" title="View all posts filed under Australia Audio Guides">Australia Audio Guides</a>
</li>
	<li class="cat-item cat-item-75"><a href="http://talk-n-tours.com/blog/category/australian-history" title="View all posts filed under Australian History">Australian History</a>
</li>
	<li class="cat-item cat-item-17"><a href="http://talk-n-tours.com/blog/category/free-audio-guides/fairs-festivals" title="View all posts filed under Fairs &amp; Festivals">Fairs &amp; Festivals</a>
</li>
	<li class="cat-item cat-item-3"><a href="http://talk-n-tours.com/blog/category/free-audio-guides" title="View all posts filed under Free Audio Guides">Free Audio Guides</a>
</li>
	<li class="cat-item cat-item-44"><a href="http://talk-n-tours.com/blog/category/new-zealand-activities" title="View all posts filed under New Zealand Activities">New Zealand Activities</a>
</li>
	<li class="cat-item cat-item-22"><a href="http://talk-n-tours.com/blog/category/free-audio-guides/new-zealand-audio-guides" title="View all posts filed under New Zealand Audio Guides">New Zealand Audio Guides</a>
</li>
		</ul>
</li>
		<li id="recent-posts-2" class="widget widget_recent_entries">		<h2 class="widgettitle">Recent Posts</h2>
		<ul>
				<li><a href="http://talk-n-tours.com/blog/australian-history/new-england-australia-chinese-history-preserved" title="New England Australia &#8211; Chinese History Preserved">New England Australia &#8211; Chinese History Preserved</a></li>
				<li><a href="http://talk-n-tours.com/blog/free-audio-guides/new-england-australia-eastview-estate-winery" title="New England Australia – Eastview Estate Winery">New England Australia – Eastview Estate Winery</a></li>
				<li><a href="http://talk-n-tours.com/blog/australian-history/preserving-history-personal-memoirs" title="Preserving History with Personal Memoirs">Preserving History with Personal Memoirs</a></li>
				<li><a href="http://talk-n-tours.com/blog/australian-history/historic-maritime-photo-collection-sydney-australia" title="Historic Maritime Photo Collection Sydney Australia">Historic Maritime Photo Collection Sydney Australia</a></li>
				<li><a href="http://talk-n-tours.com/blog/free-audio-guides/india-australia-friendship-fair" title="India Australia Friendship Fair">India Australia Friendship Fair</a></li>
				</ul>
		</li>
<li id="linkcat-2" class="widget widget_links"><h2 class="widgettitle">Blogroll</h2>

	<ul class='xoxo blogroll'>
<li><a href="http://www.qwert.net" title="Local search specialist" target="" onclick="javascript:_gaq.push(['_trackEvent','outbound-blogroll','http://www.qwert.net']);">Qwert.net</a></li>

	</ul>
</li>

<li id="tag_cloud-2" class="widget widget_tag_cloud"><h2 class="widgettitle">Tags</h2>
<div class="tagcloud"><a href='http://talk-n-tours.com/blog/tag/alternative-healing' class='tag-link-20' title='1 topic' style='font-size: 8pt;'>alternative healing</a>
<a href='http://talk-n-tours.com/blog/tag/art-gallery' class='tag-link-45' title='1 topic' style='font-size: 8pt;'>art gallery</a>
<a href='http://talk-n-tours.com/blog/tag/auckland' class='tag-link-24' title='3 topics' style='font-size: 12.6666666667pt;'>Auckland</a>
<a href='http://talk-n-tours.com/blog/tag/audio' class='tag-link-6' title='15 topics' style='font-size: 22pt;'>audio</a>
<a href='http://talk-n-tours.com/blog/tag/audio-guide' class='tag-link-13' title='13 topics' style='font-size: 21.2222222222pt;'>audio guide</a>
<a href='http://talk-n-tours.com/blog/tag/australia' class='tag-link-5' title='15 topics' style='font-size: 22pt;'>australia</a>
<a href='http://talk-n-tours.com/blog/tag/australian-beach' class='tag-link-21' title='4 topics' style='font-size: 14.2222222222pt;'>australian beach</a>
<a href='http://talk-n-tours.com/blog/tag/beach' class='tag-link-16' title='2 topics' style='font-size: 10.8pt;'>beach</a>
<a href='http://talk-n-tours.com/blog/tag/beach-safety' class='tag-link-15' title='2 topics' style='font-size: 10.8pt;'>beach safety</a>
<a href='http://talk-n-tours.com/blog/tag/boat' class='tag-link-28' title='2 topics' style='font-size: 10.8pt;'>boat</a>
<a href='http://talk-n-tours.com/blog/tag/boutique' class='tag-link-52' title='2 topics' style='font-size: 10.8pt;'>boutique</a>
<a href='http://talk-n-tours.com/blog/tag/cafe' class='tag-link-53' title='2 topics' style='font-size: 10.8pt;'>cafe</a>
<a href='http://talk-n-tours.com/blog/tag/central-coast' class='tag-link-11' title='6 topics' style='font-size: 16.5555555556pt;'>central coast</a>
<a href='http://talk-n-tours.com/blog/tag/cheap' class='tag-link-10' title='4 topics' style='font-size: 14.2222222222pt;'>cheap</a>
<a href='http://talk-n-tours.com/blog/tag/dargaville' class='tag-link-39' title='1 topic' style='font-size: 8pt;'>Dargaville</a>
<a href='http://talk-n-tours.com/blog/tag/davistown' class='tag-link-26' title='1 topic' style='font-size: 8pt;'>Davistown</a>
<a href='http://talk-n-tours.com/blog/tag/davistown-putt-putt-regatta' class='tag-link-25' title='1 topic' style='font-size: 8pt;'>Davistown Putt Putt Regatta</a>
<a href='http://talk-n-tours.com/blog/tag/european' class='tag-link-48' title='1 topic' style='font-size: 8pt;'>european</a>
<a href='http://talk-n-tours.com/blog/tag/fair' class='tag-link-18' title='1 topic' style='font-size: 8pt;'>fair</a>
<a href='http://talk-n-tours.com/blog/tag/free-audio-guide' class='tag-link-38' title='8 topics' style='font-size: 18.1111111111pt;'>free audio guide</a>
<a href='http://talk-n-tours.com/blog/tag/free-audio-tour' class='tag-link-37' title='6 topics' style='font-size: 16.5555555556pt;'>free audio tour</a>
<a href='http://talk-n-tours.com/blog/tag/guide' class='tag-link-7' title='5 topics' style='font-size: 15.4666666667pt;'>guide</a>
<a href='http://talk-n-tours.com/blog/tag/history' class='tag-link-46' title='6 topics' style='font-size: 16.5555555556pt;'>history</a>
<a href='http://talk-n-tours.com/blog/tag/kauri-coast' class='tag-link-41' title='1 topic' style='font-size: 8pt;'>kauri coast</a>
<a href='http://talk-n-tours.com/blog/tag/kauri-gum' class='tag-link-40' title='1 topic' style='font-size: 8pt;'>kauri gum</a>
<a href='http://talk-n-tours.com/blog/tag/kids' class='tag-link-8' title='1 topic' style='font-size: 8pt;'>kids</a>
<a href='http://talk-n-tours.com/blog/tag/maori' class='tag-link-47' title='1 topic' style='font-size: 8pt;'>maori</a>
<a href='http://talk-n-tours.com/blog/tag/melbourne' class='tag-link-32' title='2 topics' style='font-size: 10.8pt;'>Melbourne</a>
<a href='http://talk-n-tours.com/blog/tag/melbourne-laneways' class='tag-link-33' title='2 topics' style='font-size: 10.8pt;'>Melbourne Laneways</a>
<a href='http://talk-n-tours.com/blog/tag/museum' class='tag-link-43' title='2 topics' style='font-size: 10.8pt;'>museum</a>
<a href='http://talk-n-tours.com/blog/tag/new-zealand' class='tag-link-23' title='4 topics' style='font-size: 14.2222222222pt;'>New Zealand</a>
<a href='http://talk-n-tours.com/blog/tag/nsw' class='tag-link-12' title='7 topics' style='font-size: 17.3333333333pt;'>nsw</a>
<a href='http://talk-n-tours.com/blog/tag/pakeha' class='tag-link-49' title='1 topic' style='font-size: 8pt;'>pakeha</a>
<a href='http://talk-n-tours.com/blog/tag/party' class='tag-link-9' title='1 topic' style='font-size: 8pt;'>party</a>
<a href='http://talk-n-tours.com/blog/tag/psychic' class='tag-link-19' title='1 topic' style='font-size: 8pt;'>psychic</a>
<a href='http://talk-n-tours.com/blog/tag/putt-putt' class='tag-link-27' title='1 topic' style='font-size: 8pt;'>Putt Putt</a>
<a href='http://talk-n-tours.com/blog/tag/regatta' class='tag-link-30' title='1 topic' style='font-size: 8pt;'>regatta</a>
<a href='http://talk-n-tours.com/blog/tag/rotary' class='tag-link-31' title='1 topic' style='font-size: 8pt;'>rotary</a>
<a href='http://talk-n-tours.com/blog/tag/shopping' class='tag-link-36' title='4 topics' style='font-size: 14.2222222222pt;'>shopping</a>
<a href='http://talk-n-tours.com/blog/tag/sydney' class='tag-link-50' title='5 topics' style='font-size: 15.4666666667pt;'>Sydney</a>
<a href='http://talk-n-tours.com/blog/tag/the-rocks' class='tag-link-51' title='1 topic' style='font-size: 8pt;'>The Rocks</a>
<a href='http://talk-n-tours.com/blog/tag/vic' class='tag-link-34' title='1 topic' style='font-size: 8pt;'>Vic</a>
<a href='http://talk-n-tours.com/blog/tag/victoria' class='tag-link-35' title='1 topic' style='font-size: 8pt;'>Victoria</a>
<a href='http://talk-n-tours.com/blog/tag/west-coast' class='tag-link-42' title='1 topic' style='font-size: 8pt;'>west coast</a>
<a href='http://talk-n-tours.com/blog/tag/wooden-boat' class='tag-link-29' title='2 topics' style='font-size: 10.8pt;'>wooden boat</a></div>
</li>
<li id="archives-2" class="widget widget_archive"><h2 class="widgettitle">Archives</h2>
		<ul>
			<li><a href='http://talk-n-tours.com/blog/2010/03' title='March 2010'>March 2010</a></li>
	<li><a href='http://talk-n-tours.com/blog/2010/01' title='January 2010'>January 2010</a></li>
	<li><a href='http://talk-n-tours.com/blog/2009/12' title='December 2009'>December 2009</a></li>
	<li><a href='http://talk-n-tours.com/blog/2009/09' title='September 2009'>September 2009</a></li>
	<li><a href='http://talk-n-tours.com/blog/2009/08' title='August 2009'>August 2009</a></li>
	<li><a href='http://talk-n-tours.com/blog/2009/07' title='July 2009'>July 2009</a></li>
	<li><a href='http://talk-n-tours.com/blog/2009/06' title='June 2009'>June 2009</a></li>
	<li><a href='http://talk-n-tours.com/blog/2009/05' title='May 2009'>May 2009</a></li>
	<li><a href='http://talk-n-tours.com/blog/2009/04' title='April 2009'>April 2009</a></li>
	<li><a href='http://talk-n-tours.com/blog/2009/03' title='March 2009'>March 2009</a></li>
	<li><a href='http://talk-n-tours.com/blog/2008/08' title='August 2008'>August 2008</a></li>
	<li><a href='http://talk-n-tours.com/blog/2008/02' title='February 2008'>February 2008</a></li>
	<li><a href='http://talk-n-tours.com/blog/2007/11' title='November 2007'>November 2007</a></li>
	<li><a href='http://talk-n-tours.com/blog/2007/02' title='February 2007'>February 2007</a></li>
		</ul>
</li>
	</ul>
</div>		
	</div>

	<div id="footer">
		<p>&copy; 2006&ndash;2007 Talk&#8217;N Tours Audio Blog &mdash; <a href="http://talk-n-tours.com/blog/sitemap/">Sitemap</a> &mdash; <a href="http://cutline.tubetorial.com/">Cutline</a> by <a href="http://www.tubetorial.com">Chris Pearson</a></p>
			</div>
</div>

</body>
</html>