<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
	<title>Familie Schuh - wer gehört dazu?  - Home</title>
	<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
	<meta name="description" content="Beruf und Multiple Sklerose
Familie und Multiple Sklerose
Verbeamtung mit MS" />
<meta name="keywords" content="Alexander Schuh, Leben mit MS, Ratschläge zum Umgang mit Multipler Sklerose, Katholischer Bläserkreis Langenzenn, Daniela Schuh, Alexander Schuh, Musiklehrer, Wolfgang-Borchert-Gymnasium Langenzenn" />
<meta name="author" content="Familie Schuh, Langenzenn" />
<meta name="robots" content="index,follow" />
	<style type="text/css">
	<!--
		body { font-family:Tahoma; font-size:11px; text-decoration:none; margin: 0% 0% 0% 0%; }
		.headline { font-family:Tahoma; font-size:10px; font-style:none; color:#FACE61; text-decoration:none; }
		.cont, TD { font-family:Tahoma; font-size:10px; font-style:none; color:#818181; text-decoration:none; }
		a { font-family: Tahoma; color:#172F47; text-decoration: none;	font-size:10px}
		a:visited { font-family: Tahoma; color:#172F47; text-decoration: none;	font-size:10px}
		a:hover { font-family: Tahoma; color:#e12e76; text-decoration: underline;	font-size:10px}
			//-->
	</style>
</head>
<body bgcolor="#670000" style="margin: 0 0 0 0;">
<head>
<meta name="AUTHOR" content="familieschuh">
<meta name="COPYRIGHT" content="Copyright (c) 2006 by familieschuh "/>
<meta name="KEYWORDS" content=(Bsp:Php, Java, Html .../>
<meta name="DESCRIPTION" content="Rennmäuse, Kleinkind, Beruf, Familie, Wolfgang-Borchert-Gymnasium Langenzenn, Multiple Sklerose, MS und glückliches Leben, Leben mit Multipler Sklerose, Alexanders MS und Beruf, Alexanders MS und Freizeit, Alexanders MS und Familie,
Bergurlaub und Mulitple Sklerose, Alexander Schuh, Daniela Schuh"/>
<br><style type="text/css">
#ad-cfcd br {
		display: none;
}
</style>
<table height="102" id="ad-cfcd">
<tr>
<td height="102">
<iframe src="http://ads.webme.com/banner.php?pos=bw" frameborder="0" width="728" height="90" scrolling="no"></iframe></td>
</tr>
</table>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
	<tr>
		<td background="http://theme.webme.com/designs/colourful/images_rot/head_bg.gif" class="edit_header1">
			<table width="1000" border="0" cellspacing="0" cellpadding="0">
				<tr>
					<td height="141" align="left" valign="top" background="http://img.webme.com/pic/f/familieschuh/headerred23.jpg" class="edit_header2">
						<table width="100%" border="0" cellspacing="5" cellpadding="0">
							<tr>
								<td width="34%" height="70" align="right" valign="bottom"><font color="#141313" style="font-size: 24px" face="impact">Familie Schuh - wer gehört dazu? </font></td>
								<td width="66%" align="left" valign="bottom" class="headline">&nbsp;</td>
							</tr>
							<tr>
								<td align="right" valign="bottom">&nbsp;</td>
								<td class="headline"></td>
							</tr>
						</table></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td align="left" valign="top">
			<table width="1000" border="0" cellspacing="0" cellpadding="0">
				<tr>
					<td width="525" bgcolor="#31434D"></td>
					<td width="2"></td>
					<td width="247" height="1" bgcolor="#31434D"></td>
					<td width="2"></td>
					<td width="224" bgcolor="#31434D"></td>
				</tr>
				<tr>
					<td align="left" valign="top">
						<table width="100%" border="0" cellspacing="0" cellpadding="0">
							<tr>
								<td bgcolor="#1B242B">
									<table width="100%" border="0" cellspacing="2" cellpadding="0">
										<tr>
											<td>
												<table width="100%" border="0" cellspacing="0" cellpadding="0">
													<tr>
														<td background="http://theme.webme.com/designs/colourful/images_rot/cont_head_bg.gif" height="36" class="edit_content_header">
															<table width="100%" border="0" cellspacing="0" cellpadding="0">
																<tr>
																	<td width="2%">&nbsp;</td>
																	<td width="77%" class="headline"><strong>Home</strong></td>
																	<td width="21%" class="headline">07.06.2012 02:57:26</td>
																</tr>
															</table></td>
													</tr>
													<tr>
														<td height="3"><img src="http://theme.webme.com/designs/colourful/images_rot/line.gif" width="521" height="3"></td>
													</tr>
													<tr>
														<td background="http://theme.webme.com/designs/colourful/images_rot/cat_bg.gif" height="53">
															<table width="100%" border="0" cellspacing="0" cellpadding="0" class="edit_content_header2">
																<tr>
																	<td width="98%" height="30">&nbsp;</td>
																	<td width="2%">&nbsp;</td>
																</tr>
																<tr>
																	<td align="right" class="headline"></td>
																	<td>&nbsp;</td>
																</tr>
															</table>
														</td>
													</tr>
													<tr>
														<td height="3"><img src="http://theme.webme.com/designs/colourful/images_rot/line.gif" width="521" height="3"></td>
													</tr>
													<tr>
														<td bgcolor="#FFFFFF">
															<table width="100%" border="0" cellspacing="0" cellpadding="5">
																<tr>
																	<td class="cont" height="150"><div style="width: 510; overflow: auto;"><div align="center"><font size="5" face="Comic Sans MS" color="#990000">Herzlich Willkommen auf der Homepage der Familie Schuh!</font><br />
<font size="5" face="Comic Sans MS" color="#990000"> Auf diesen Seiten m&ouml;chten wir ein bisschen &uuml;ber unsere Tiere und uns berichten.<br />
</font><br />
<font size="5" face="Comic Sans MS" color="#990000"> Viel Spa&szlig; beim St&ouml;bern.</font></div>
<font size="5" face="Comic Sans MS" color="#990000"><br />
</font>
<div align="center">
<div align="left"><font size="5" face="Comic Sans MS" color="#990000">&nbsp; <img width="215" height="203" alt="" src="http://img.webme.com/pic/f/familieschuh/danielaundalexander.jpg" /></font><font size="5" face="Comic Sans MS" color="#990000"><img width="245" height="178" src="http://img.webme.com/pic/f/familieschuh/manueldamalsundheute.jpg" alt="" /></font></div>
<font size="5" face="Comic Sans MS" color="#990000"><br />
</font></div>
<br />
<br />
<br />
<font size="5" face="Comic Sans MS" color="#ff9933"><br />
</font></div></td>
																</tr>
															</table>
														</td>
													</tr>
													<tr>
														<td bgcolor="#FFFFFF"><img src="http://theme.webme.com/designs/colourful/images_rot/line.gif" width="521" height="3"></td>
													</tr>
													<tr>
														<td height="22" bgcolor="#F1F1F1">&nbsp;</td>
													</tr>
													<tr>
														<td bgcolor="#FFFFFF"><img src="http://theme.webme.com/designs/colourful/images_rot/line.gif" width="521" height="3"></td>
													</tr>
													<tr>
														<td bgcolor="#FFFFFF" height="2"></td>
													</tr>
												</table>
											</td>
										</tr>
									</table>
								</td>
							</tr>
						</table>
					</td>
					<td></td>
					<td align="left" valign="top">
						<table width="100%" border="0" cellspacing="0" cellpadding="0">
							<tr>
								<td bgcolor="#1B262C">
									<table width="100%" border="0" cellspacing="2" cellpadding="0">
										<tr>
											<td>
												<table width="100%" border="0" cellspacing="0" cellpadding="0">
													<tr>
														<td background="http://theme.webme.com/designs/colourful/images_rot/navi_head_bg.gif" height="36">
															<table width="100%" border="0" cellspacing="0" cellpadding="0" class="edit_nav_header">
																<tr>
																	<td width="5%">&nbsp;</td>
																	<td width="95%" class="headline"><strong>Da gehts lang!</strong></td>
																</tr>
															</table>
														</td>
													</tr>
													<tr>
														<td height="37" background="http://theme.webme.com/designs/colourful/images_rot/navi_bg.gif" onclick="window.location.href='#'" onMouseOver="this.style.backgroundImage='url(http://theme.webme.com/designs/colourful/images_rot/navi_over.gif)'; this.style.cursor='hand';" onMouseOut="this.style.backgroundImage=''" class="edit_nav_bg">
															<table width="100%" border="0" cellspacing="0" cellpadding="0">
																<tr>
																	<td width="5%">&nbsp;</td>
																	<td width="95%" class="nav"><a href="/Alexander.htm" class="menu"><u><i><b><font color=#B31A06>Alexander</font></b></i></u></a></td>
																</tr>
															</table></td>
													</tr>
													<tr>
														<td height="37" background="http://theme.webme.com/designs/colourful/images_rot/navi_bg.gif" onclick="window.location.href='#'" onMouseOver="this.style.backgroundImage='url(http://theme.webme.com/designs/colourful/images_rot/navi_over.gif)'; this.style.cursor='hand';" onMouseOut="this.style.backgroundImage=''" class="edit_nav_bg">
															<table width="100%" border="0" cellspacing="0" cellpadding="0">
																<tr>
																	<td width="5%">&nbsp;</td>
																	<td width="95%" class="nav"><a href="/Manuel-Pascal.htm" class="menu"><u><i><b><font color=#C90505>Manuel Pascal</font></b></i></u></a></td>
																</tr>
															</table></td>
													</tr>
													<tr>
														<td height="37" background="http://theme.webme.com/designs/colourful/images_rot/navi_bg.gif" onclick="window.location.href='#'" onMouseOver="this.style.backgroundImage='url(http://theme.webme.com/designs/colourful/images_rot/navi_over.gif)'; this.style.cursor='hand';" onMouseOut="this.style.backgroundImage=''" class="edit_nav_bg">
															<table width="100%" border="0" cellspacing="0" cellpadding="0">
																<tr>
																	<td width="5%">&nbsp;</td>
																	<td width="95%" class="nav"><a href="/Unsere-Tiere.htm" class="menu"><u><i><b><font color=#C70B0B>Unsere Tiere</font></b></i></u></a></td>
																</tr>
															</table></td>
													</tr>
													<tr>
														<td height="37" background="http://theme.webme.com/designs/colourful/images_rot/navi_bg.gif" onclick="window.location.href='#'" onMouseOver="this.style.backgroundImage='url(http://theme.webme.com/designs/colourful/images_rot/navi_over.gif)'; this.style.cursor='hand';" onMouseOut="this.style.backgroundImage=''" class="edit_nav_bg">
															<table width="100%" border="0" cellspacing="0" cellpadding="0">
																<tr>
																	<td width="5%">&nbsp;</td>
																	<td width="95%" class="nav"><a href="/Kontakt.htm" class="menu"><u><i><b><font color=#B40808>Kontakt</font></b></i></u></a></td>
																</tr>
															</table></td>
													</tr>
													<tr>
														<td height="37" background="http://theme.webme.com/designs/colourful/images_rot/navi_bg.gif" onclick="window.location.href='#'" onMouseOver="this.style.backgroundImage='url(http://theme.webme.com/designs/colourful/images_rot/navi_over.gif)'; this.style.cursor='hand';" onMouseOut="this.style.backgroundImage=''" class="edit_nav_bg">
															<table width="100%" border="0" cellspacing="0" cellpadding="0">
																<tr>
																	<td width="5%">&nbsp;</td>
																	<td width="95%" class="nav"><a href="/Bildergalerie.htm" class="menu"><u><i><b><font color=#AD4444>Bildergalerie</font></b></i></u></a></td>
																</tr>
															</table></td>
													</tr>
													<tr>
														<td height="37" background="http://theme.webme.com/designs/colourful/images_rot/navi_bg.gif" onclick="window.location.href='#'" onMouseOver="this.style.backgroundImage='url(http://theme.webme.com/designs/colourful/images_rot/navi_over.gif)'; this.style.cursor='hand';" onMouseOut="this.style.backgroundImage=''" class="edit_nav_bg">
															<table width="100%" border="0" cellspacing="0" cellpadding="0">
																<tr>
																	<td width="5%">&nbsp;</td>
																	<td width="95%" class="nav"><a href="/Daniela.htm" class="menu"><u><i><b><font color=#BE0404>Daniela</font></b></i></u></a></td>
																</tr>
															</table></td>
													</tr>
													<tr>
														<td height="37" background="http://theme.webme.com/designs/colourful/images_rot/navi_bg.gif" onclick="window.location.href='#'" onMouseOver="this.style.backgroundImage='url(http://theme.webme.com/designs/colourful/images_rot/navi_over.gif)'; this.style.cursor='hand';" onMouseOut="this.style.backgroundImage=''" class="edit_nav_bg">
															<table width="100%" border="0" cellspacing="0" cellpadding="0">
																<tr>
																	<td width="5%">&nbsp;</td>
																	<td width="95%" class="nav"><a href="/Home.htm" class="menu"><u><i><b><font color=#B80505>Home</font></b></i></u></a></td>
																</tr>
															</table></td>
													</tr>
													<tr>
														<td height="37" background="http://theme.webme.com/designs/colourful/images_rot/navi_bg.gif" onclick="window.location.href='#'" onMouseOver="this.style.backgroundImage='url(http://theme.webme.com/designs/colourful/images_rot/navi_over.gif)'; this.style.cursor='hand';" onMouseOut="this.style.backgroundImage=''" class="edit_nav_bg">
															<table width="100%" border="0" cellspacing="0" cellpadding="0">
																<tr>
																	<td width="5%">&nbsp;</td>
																	<td width="95%" class="nav"><a href="/G.ae.stebuch.htm" class="menu"><u><i><b><font color=#F50B0B>Gästebuch</font></b></i></u></a></td>
																</tr>
															</table></td>
													</tr>
													<tr>
														<td height="37" background="http://theme.webme.com/designs/colourful/images_rot/navi_bg.gif" onclick="window.location.href='#'" onMouseOver="this.style.backgroundImage='url(http://theme.webme.com/designs/colourful/images_rot/navi_over.gif)'; this.style.cursor='hand';" onMouseOut="this.style.backgroundImage=''" class="edit_nav_bg">
															<table width="100%" border="0" cellspacing="0" cellpadding="0">
																<tr>
																	<td width="5%">&nbsp;</td>
																	<td width="95%" class="nav"><a href="/Mein-Rolli-Podcast.htm" class="menu"><u><i><b><font color=#FD0C0C>Mein Rolli Podcast</font></b></i></u></a></td>
																</tr>
															</table></td>
													</tr>
												</table>
											</td>
										</tr>
									</table>
								</td>
							</tr>
						</table>
						<br>
						<div style="padding-left:5px">
							Copyright by Familie Schuh in Franken						</div>

					</td>
					<td></td>
					<td align="left" valign="top">
						<table width="100%" border="0" cellspacing="0" cellpadding="0">
							<tr>
								<td bgcolor="#1B262C">
									<table width="100%" border="0" cellspacing="2" cellpadding="0">
										<tr>
											<td>
												<table width="100%" border="0" cellspacing="0" cellpadding="0">
													<tr>
														<td background="http://theme.webme.com/designs/colourful/images_rot/misc_head_bg.gif" height="36">
															<table width="100%" border="0" cellspacing="0" cellpadding="0" class="edit_rechts_header">
																<tr>
																	<td width="6%">&nbsp;</td>
																	<td width="94%" class="headline"><strong>Neues von Manuel</strong></td>
																</tr>
															</table>
														</td>
													</tr>
													<tr>
														<td bgcolor="#FFFFFF" height="1"></td>
													</tr>
													<tr>
														<td height="36" bgcolor="#ECECEC" style="padding-left:7px">
Unser "kleiner" Manuel ist nun schon 5 und ein stolzes Vorschulkind. 														</td>
													</tr>
												</table>
											</td>
										</tr>
									</table>
								</td>
							</tr>
							<tr>
								<td height="2"></td>
							</tr>
							<tr>
								<td bgcolor="#1B262C">
									<table width="100%" border="0" cellspacing="2" cellpadding="0">
										<tr>
											<td>
												<table width="100%" border="0" cellspacing="0" cellpadding="0">
													<tr>
														<td background="http://theme.webme.com/designs/colourful/images_rot/misc_head_bg.gif" height="36">
															<table width="100%" border="0" cellspacing="0" cellpadding="0" class="edit_rechts_header">
																<tr>
																	<td width="6%">&nbsp;</td>
																	<td width="94%" class="headline"><strong>Neues von Amira</strong></td>
																</tr>
															</table>
														</td>
													</tr>
													<tr>
														<td bgcolor="#FFFFFF" height="1"></td>
													</tr>
													<tr>
														<td height="36" bgcolor="#ECECEC" style="padding-left:7px">Amira hat uns im Frühsommer leider verlassen, nachdem sie sich mit einem Auto angelegt hat.</td>
													</tr>
												</table>
											</td>
										</tr>
									</table>
								</td>
							</tr>
							<tr>
								<td height="2"></td>
							</tr>
							<tr>
								<td bgcolor="#1B262C">
									<table width="100%" border="0" cellspacing="2" cellpadding="0">
										<tr>
											<td>
												<table width="100%" border="0" cellspacing="0" cellpadding="0">
													<tr>
														<td background="http://theme.webme.com/designs/colourful/images_rot/misc_head_bg.gif" height="36">
															<table width="100%" border="0" cellspacing="0" cellpadding="0" class="edit_rechts_header">
																<tr>
																	<td width="6%">&nbsp;</td>
																	<td width="94%" class="headline"><strong>Neues von unseren Rennern</strong></td>
																</tr>
															</table>
														</td>
													</tr>
													<tr>
														<td bgcolor="#FFFFFF" height="1"></td>
													</tr>
													<tr>
														<td height="36" bgcolor="#ECECEC" style="padding-left:7px">Von meinen Mäusen ist nun mehr leider nur noch ein Mäuserich übrig!</td>
													</tr>
												</table>
											</td>
										</tr>
									</table>
								</td>
							</tr>
							<tr>
								<td height="2"></td>
							</tr>
							<tr>
								<td bgcolor="#1B262C">
									<table width="100%" border="0" cellspacing="2" cellpadding="0">
										<tr>
											<td>
												<table width="100%" border="0" cellspacing="0" cellpadding="0">
													<tr>
														<td background="http://theme.webme.com/designs/colourful/images_rot/misc_head_bg.gif" height="36">
															<table width="100%" border="0" cellspacing="0" cellpadding="0" class="edit_rechts_header">
																<tr>
																	<td width="6%">&nbsp;</td>
																	<td width="94%" class="headline"><strong>Neues von Alexander</strong></td>
																</tr>
															</table>
														</td>
													</tr>
													<tr>
														<td bgcolor="#FFFFFF" height="1"></td>
													</tr>
													<tr>
														<td height="36" bgcolor="#ECECEC" style="padding-left:7px">Es ist vollbracht:<br />
Der 01.11.2009 ist der Tag, an dem mein Traum endlich in Erfüllung gegangen ist: <br />
Nach 3 langen Jahren ist der Kampf mit den Windmühlen erfolgreich zu Ende gegangen und ich habe<br />
<br />
meine LEBENSZEITVERBEAMTUNG erlangt!</td>
													</tr>
												</table>
											</td>
										</tr>
									</table>
								</td>
							</tr>
							<tr>
								<td height="2"></td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>
<font color="white" style="font-size: 11px;	font-family: Tahoma, Arial, Helvetica, sans-serif"><font color="#D8AA14">Bisher haben sich schon 7672 Besucherhierher verirrt!</font></font>
<iframe src="http://www.homepage-baukasten.de/cookie.php?visit=familieschuh&auth1=1d7769511e3ec344e7640d2a44f025e1&auth2=dfa96622127292b867ef1ae193f009dd&auth3=6065cd4c65e5eae1d3412f047c51b560&auth4=881d14d4c8ebad0ab3b00c8c829e2248&auth5=27bd031b3f36244973456e8e73ca006c&mode=track" style="display:none;width:1px;height:1px;"></iframe>
<script src="http://www.google-analytics.com/urchin.js" type="text/javascript" ></script>
<script type="text/javascript">
	_uacct = "UA-2594508-8";
	urchinTracker(); 
_uff = 0;
_uacct = "UA-2594508-34";
urchinTracker(); 
_uff = 0;
_uacct = "UA-2594508-49";
urchinTracker(); 
</script>                                                                                                                                                                                                                                                                                                                                                                                                                                <script type="text/javascript" src="http://ads.webme.com/layer.php"></script></body>
</html>