<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
    <!-- Generated by OpenX 2.8.5 -->
    <script type='text/javascript' src='http://advertising.grupodial.cl/www/delivery/spcjs.php?id=1'></script>

        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="robots" content="index,follow" />
        
            <title>Radio Zero - 97.7 FM en Santiago</title>
    		
        <meta name="author" content="John Doe" />
        
        <link rel="canonical" href="http://radiozero.cl" />
        <link rel="alternate" type="application/rss+xml" href="http://radiozero.cl/feed/rss/" title="RSS"/>
        <link rel="shortcut icon" type="image/x-icon" href="/assets/img/favicon.png" />
        
        <!-- @mainStyles -->
        <link rel="stylesheet" type="text/css" href="/assets/css/corporate.css" media="screen, projection" />
        <link rel="stylesheet" type="text/css" href="/assets/css/helpers.css" media="screen, projection" />
        <link rel="stylesheet" type="text/css" href="/assets/css/structure.css" media="screen, projection" />
        <link rel="stylesheet" type="text/css" href="/assets/css/print.css" media="print" />
        <!-- /@mainStyles -->
        
        <!-- @scripts -->
        <script type="text/javascript" src="/assets/js/jquery.1.4.2.min.js"></script>
        <script type="text/javascript" src="/assets/aux/galleria/galleria.js"></script>
        <script type="text/javascript" src="/assets/js/swfobject.js"></script>
        <script type="text/javascript" src="/assets/js/audio-player.js"></script>
        <script type="text/javascript" src="/assets/js/tweet.js"></script>
        

        <script type="text/javascript">
            function parseLast10(xml) {
		clearAirInformation();//agregado por dps
                $(xml).find('track').each(function() {
                    if($(this).find('hora').text() == '00:00') {
                        return false;
                    }
                    
                    $('.last10 ul').append('<li><span>' + $(this).find('hora').text() + '</span> ' + $(this).find('cancion').text() + '</li>');
                });
            }
            
            function parseSongInfo(xml) {
                $(xml).find('actual').each(function() {
                    var onAir = $(this).find('aire').text();
                    var sInfo = onAir.split(' - ')
                    
                    $('.player .songtitle').html(sInfo[1]);
                    $('.player .artist').html(sInfo[0]);
                    
                    $('.player .cover img').attr('src', $(this).find('imagen').text());
                    $('.player .cover img').attr('alt', sInfo[0]);
                    
                    var nDuration = $(this).find('duracionh').text();
                    //var xDuration = nDuration / 60;
                    //var yDuration = Math.floor(xDuration);
                    //var zDuration = (xDuration - yDuration) * 60;
                    
                    //$('.player .duration').html(yDuration + ':' + Math.floor(zDuration));
					$('.player .duration').html(nDuration);
                });
            }
            
            function airInformation() {
	    var numerillo = Math.floor(Math.random()*500000);// agregado por dps
                $.ajax({
                    type: 'GET',
                    url: '/last10.xml?t='+numerillo,
                    dataType: 'xml',
                    success: parseLast10
                });
                
                $.ajax({
                    type: 'GET',
                    url: '/letra.xml?t='+numerillo,
                    dataType: 'xml',
                    success: parseSongInfo
                });
            }
            
            function clearAirInformation() {
                $('.last10 ul').html('');
            }
            
            setInterval('airInformation()', 5000);
            
            $(document).ready(function() {
                airInformation();
                
                                
                $('.listen-up').click(function () {
                    window.open(this.href, 'Player', 'height=412,width=600,resizable=0,scrollbars=0,location=0');  
                    
                    return false; 
                });
                
                $('header form input').focus(function() {
                    $(this).attr('value', '');
                });
            });
        </script>
        <!-- /@scripts -->
        
        <!-- @wpHead (cagó todo xD) -->
        <link rel='stylesheet' id='wp-polls-css'  href='http://radiozero.cl/wp-content/plugins/wp-polls/polls-css.css?ver=2.50' type='text/css' media='all' />
<link rel='stylesheet' id='contact-form-7-css'  href='http://radiozero.cl/wp-content/plugins/contact-form-7/styles.css?ver=2.4.1' type='text/css' media='all' />
<script type='text/javascript' src='http://radiozero.cl/wp-includes/js/swfobject.js?ver=2.2'></script>
<script type='text/javascript' src='http://radiozero.cl/wp-includes/js/jquery/jquery.js?ver=1.4.2'></script>
<link rel="EditURI" type="application/rsd+xml" title="RSD" href="http://radiozero.cl/xmlrpc.php?rsd" />
<link rel="wlwmanifest" type="application/wlwmanifest+xml" href="http://radiozero.cl/wp-includes/wlwmanifest.xml" /> 
<link rel='index' title='Radio Zero' href='http://radiozero.cl/' />
<meta name="generator" content="WordPress 3.0" />
<script type="text/javascript" src="http://radiozero.cl/wp-content/plugins/audio-player/assets/audio-player.js?ver=2.0.4.1"></script>
<script type="text/javascript">AudioPlayer.setup("http://radiozero.cl/wp-content/plugins/audio-player/assets/player.swf?ver=2.0.4.1", {width:"580",animation:"no",encode:"yes",initialvolume:"100",remaining:"no",noinfo:"no",buffer:"5",checkpolicy:"no",rtl:"no",bg:"E5E5E5",text:"333333",leftbg:"CCCCCC",lefticon:"333333",volslider:"666666",voltrack:"FFFFFF",rightbg:"B4B4B4",rightbghover:"999999",righticon:"333333",righticonhover:"FFFFFF",track:"FFFFFF",loader:"f00000",border:"CCCCCC",tracker:"DDDDDD",skip:"666666",pagebg:"FFFFFF",transparentpagebg:"yes"});</script>
<script type="text/javascript">
//<![CDATA[
var _wpcf7 = { cached: 1 };
//]]>
</script>
<style type="text/css">
.wp-polls .pollbar {
	margin: 1px;
	font-size: 6px;
	line-height: 8px;
	height: 8px;
	background: #dd2228;
	border: 1px solid #dd2228;
}
</style>
<!-- Vipers Video Quicktags v6.3.0 | http://www.viper007bond.com/wordpress-plugins/vipers-video-quicktags/ -->
<style type="text/css">
.vvqbox { display: block; max-width: 100%; visibility: visible !important; margin: 10px auto; } .vvqbox img { max-width: 100%; height: 100%; } .vvqbox object { max-width: 100%; } 
</style>
<script type="text/javascript">
// <![CDATA[
	var vvqflashvars = {};
	var vvqparams = { wmode: "opaque", allowfullscreen: "true", allowscriptaccess: "always" };
	var vvqattributes = {};
	var vvqexpressinstall = "http://radiozero.cl/wp-content/plugins/vipers-video-quicktags/resources/expressinstall.swf";
// ]]>
</script>
        <!-- /@wpHead -->
        
        <!-- @browserExceptions -->
        <!--[if IE 6]>
        <![endif]-->
        
        <!--[if lt IE 8]>
            <link rel="stylesheet" type="text/css" href="/assets/css/ie7.css" media="screen, projection" />
        <![endif]-->
    
        <!--[if lt IE 9]>
            <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        <!-- /@browserExceptions -->
    </head>
    
        <body id="home" class="">
        <!-- @corporateBar -->
    	<div class="corporate">
    		<ul>
    			<li class="grupodial-logo"><a href="http://www.grupodial.cl/" target="_blank"><img src="/assets/img/logo-grupodial-corporatebar.gif" alt="Grupo Dial" /></a></li>
    			<li><a href="http://www.duna.cl/" target="_blank">Duna</a></li>
    			<li><a href="http://www.beethovenfm.cl/" target="_blank">Beethoven</a></li>
    			<li><a href="http://www.radiozero.cl/" target="_blank">Zero</a></li>
    			<li><a href="http://www.carolina.cl/" target="_blank">Carolina</a></li>
    			<li><a href="http://www.radiodisney.cl/" target="_blank">Disney</a></li>
    			<li><a href="http://www.paulafm.cl/" target="_blank">Paula FM</a></li>
    		</ul>
    	</div>
    	<!-- /@corporateBar -->
    	
        <!-- @wrap -->
        <div id="wrap">
            <!-- @header -->
            <header class="cf">
                <h1 class="fl"><a href="http://radiozero.cl" class="txt-replace">Radio Zero</a></h1>
                
                <nav class="fr cf">
                    <ul class="fl cf">
                        <li class="current-cat-parent"><a href="http://radiozero.cl">Portada</a></li>
                        	<li class="cat-item cat-item-1"><a href="http://radiozero.cl/contenidos/programas/" title="Ver todos los artículos de Programas">Programas</a>
</li>
	<li class="cat-item cat-item-81"><a href="http://radiozero.cl/contenidos/podcasts/" title="Ver todos los artículos de Podcasts">Podcasts</a>
</li>
	<li class="cat-item cat-item-4"><a href="http://radiozero.cl/contenidos/micros/" title="Ver todos los artículos de Micros">Micros</a>
</li>
	<li class="cat-item cat-item-5"><a href="http://radiozero.cl/contenidos/concursos/" title="Ver todos los artículos de Concursos">Concursos</a>
</li>
	<li class="cat-item cat-item-7"><a href="http://radiozero.cl/contenidos/zero-tv/" title="Ver todos los artículos de Zero TV">Zero TV</a>
</li>
						<li><a href="http://sesiones.radiozero.cl/">Sesiones</a></li>
                    </ul>
                    
                    <form action="http://radiozero.cl" method="get" role="search" class="fr">
                        <input type="text" id="s" name="s" value="búsqueda..." />
                    </form>
                </nav>
                
                <ul class="social">
                    <li><a href="http://radiozero.cl/feed/rss/" title="Suscríbete a nuestro RSS"><img src="/assets/img/ico-rss.png" alt="RSS" /></a></li>
                    <li><a href="http://www.facebook.com/pages/Zero-977/125997044146246" title="Radio Zero en Facebook"><img src="/assets/img/ico-facebook.png" alt="Facebook" /></a></li>
                    <li><a href="http://twitter.com/radiozero977" title="Radio Zero en Twitter"><img src="/assets/img/ico-twitter.png" alt="Twitter" /></a></li>
                </ul>
            </header>
            <!-- @header -->
            

            

            <!-- @promo -->

            <section id="promo" class="section cf">

                <div id="slider" class="fl">

                    

                </div>

                

                <script type="text/javascript">

					var so = new SWFObject ('/assets/aux/promo.swf', 'slider', '610', '360', '9', '#000000');

					so.addVariable('CONFIG_URL','/contenidos/mega-destacados/');

					so.addVariable('STYLESHEET','/assets/aux/promo-style.swf');

					so.addParam('wmode', 'transparent');

					so.write('slider');

				</script>

                

                <div class="player fr">

                    <hgroup class="cf">

                        <strong class="fl">Al aire en Zero <span>97.7</span></strong>

                        <a href="http://vivo.radiozero.cl/player/" class="listen-up fr">Escucha Aquí</a>

                    </hgroup>

                    

                    <div class="inside cf">

                        <div class="cover fl">

                            <img src="/assets/img/default-cover.jpg" alt="Radio Zero" width="64" height="64" />

                            <span class="plastic"></span>

                        </div>

                        

                        <div class="songinfo">

                            <span class="songtitle">97.7</span><br />

                            <span class="artist">Zero</span><br />

                            <span class="duration">0</span>

                            <span class="rating"></span>

                        </div>

                        

                        <a href="#" class="toggle-last10">Revisa las 10 últimas programadas ↓</a>

                    </div>

                    

                    <div class="last10">

                        <strong>Las 10 últimas programadas</strong>

                        

                        <ul>

                        </ul>

                    </div>

                    

                    <div class="ad300">

              			<script type='text/javascript'><!--//<![CDATA[

   var m3_u = (location.protocol=='https:'?'https://advertising.grupodial.cl/www/delivery/ajs.php':'http://advertising.grupodial.cl/www/delivery/ajs.php');

   var m3_r = Math.floor(Math.random()*99999999999);

   if (!document.MAX_used) document.MAX_used = ',';

   document.write ("<scr"+"ipt type='text/javascript' src='"+m3_u);

   document.write ("?zoneid=1");

   document.write ('&amp;cb=' + m3_r);

   if (document.MAX_used != ',') document.write ("&amp;exclude=" + document.MAX_used);

   document.write (document.charset ? '&amp;charset='+document.charset : (document.characterSet ? '&amp;charset='+document.characterSet : ''));

   document.write ("&amp;loc=" + escape(window.location));

   if (document.referrer) document.write ("&amp;referer=" + escape(document.referrer));

   if (document.context) document.write ("&context=" + escape(document.context));

   if (document.mmm_fo) document.write ("&amp;mmm_fo=1");

   document.write ("'><\/scr"+"ipt>");

//]]>--></script><noscript><a href='http://advertising.grupodial.cl/www/delivery/ck.php?n=af8c41fc&amp;cb=INSERT_RANDOM_NUMBER_HERE' target='_blank'><img src='http://advertising.grupodial.cl/www/delivery/avw.php?zoneid=1&amp;cb=INSERT_RANDOM_NUMBER_HERE&amp;n=af8c41fc' border='0' alt='' /></a></noscript>



					</div>

                

                    <script type="text/javascript">

                        $('.toggle-last10').toggle(

                            function() {

                                $('.player .ad300').slideUp('4000');

                                $('.player .last10').delay('100').slideDown('4000');

                                $('.toggle-last10').delay('100').html('Mostrar publicidad ↓');

                            },

                            function() {

                                $('.player .last10').slideUp('4000');

                                $('.player .ad300').delay('100').slideDown('4000');

                                $('.toggle-last10').delay('100').html('Las 10 últimas programadas ↓');

                            }

                        );

                    </script>

                </div>

            </section>

            <!-- /@promo -->

            <div style="margin: 20px 0;">
                <script type='text/javascript'><!--// <![CDATA[
    /* [id51] radiozero.cl - Gigante */
    OA_show(51);
// ]]> --></script><noscript><a target='_blank' href='http://advertising.grupodial.cl/www/delivery/ck.php?n=044d32b'><img border='0' alt='' src='http://advertising.grupodial.cl/www/delivery/avw.php?zoneid=51&amp;n=044d32b' /></a></noscript>
            </div>

            <!-- @today -->

            <!--<section id="today" class="home-featured section cf">

                <div class="highlights fl cf">

                    <hgroup>

                        <h3>Hoy en Zero</h3>

                        <span>Te presentamos</span>

                    </hgroup>

                    

                    
                    <article>

                        <div>

                            <a href="http://radiozero.cl/2012/05/10/seguimos-celebrando-una-decada-del-alta-fidelidad/" class="pic"><img width="80" height="80" src="http://radiozero.cl/media/2012/05/zero_liguria_afhome-80x80.jpg" class="attachment-80x80" alt="zero_liguria_afhome" title="zero_liguria_afhome" /></a>

                            <a href="http://radiozero.cl/2012/05/10/seguimos-celebrando-una-decada-del-alta-fidelidad/" class="title">Seguimos celebrando una década del Alta Fidelidad</a>

                            <p class="overview">Volvemos al Bar Liguria de Manuel Montt. Desde las 1930. Sal...</p>

                        </div>

                        

                        <span class="comment-count">1</span>

                        <a href="http://radiozero.cl/2012/05/10/seguimos-celebrando-una-decada-del-alta-fidelidad/" class="more">Leer Más</a>

                    </article>

                    
                    <article>

                        <div>

                            <a href="http://radiozero.cl/2012/05/03/10-anos-de-alta-fidelidad-seguimos-celebrando/" class="pic"><img width="80" height="80" src="http://radiozero.cl/media/2012/04/liguria_home-80x80.jpg" class="attachment-80x80" alt="liguria_home" title="liguria_home" /></a>

                            <a href="http://radiozero.cl/2012/05/03/10-anos-de-alta-fidelidad-seguimos-celebrando/" class="title">10 años de Alta Fidelidad&#8230; seguimos celebrando</a>

                            <p class="overview">Seguimos celebrando, y volvemos al Bar Liguria de Manuel Mon...</p>

                        </div>

                        

                        <span class="comment-count">0</span>

                        <a href="http://radiozero.cl/2012/05/03/10-anos-de-alta-fidelidad-seguimos-celebrando/" class="more">Leer Más</a>

                    </article>

                    
                    <article>

                        <div>

                            <a href="http://radiozero.cl/2012/04/19/celebramos-10-anos-de-alta-fidelidad/" class="pic"><img width="80" height="80" src="http://radiozero.cl/media/2012/04/liguria_home-80x80.jpg" class="attachment-80x80" alt="liguria_home" title="liguria_home" /></a>

                            <a href="http://radiozero.cl/2012/04/19/celebramos-10-anos-de-alta-fidelidad/" class="title">Celebramos 10 años de Alta Fidelidad</a>

                            <p class="overview">Para iniciar los festejos de una década al aire, hoy transmi...</p>

                        </div>

                        

                        <span class="comment-count">1</span>

                        <a href="http://radiozero.cl/2012/04/19/celebramos-10-anos-de-alta-fidelidad/" class="more">Leer Más</a>

                    </article>

                    
                </div>

            </section>-->

            <!-- /@today -->
            
            <!-- photoContest -->
            <!--<style>#galleria { height: 563px; } #photo-contest { height: 676px; }</style>
            <section id="photo-contest" class="home-featured section cf">
                <hgroup>
                    <h3>Tu mundo, tu casa</h3>
                    <span>Concurso de fotografía</span>
                </hgroup>
                
                <p style="margin-bottom: 15px;">Te presentamos las fotografías finalistas en nuestro concurso "Tu mundo, tu casa" que organizamos junto a la Galería Animal.</p>
                
                <div id="galleria">
                    <img src="http://archivos2.digitalproserver.com/zerofile/photocontest/Alfredo_Mendez_S-T1.jpg" alt="Autor: Alfredo Méndez, Título: S-T1" />
                    <img src="http://archivos2.digitalproserver.com/zerofile/photocontest/Alfredo_Mendez_S-T2.jpg" alt="Autor: Alfredo Méndez, Título: S-T2" />
                    <img src="http://archivos2.digitalproserver.com/zerofile/photocontest/Alonso_Fuentes_Que_importa_la_lluvia_acida.jpg" alt="Autor: Alonso Fuentes, Título: Qué importa la lluvia ácida" />
                    <img src="http://archivos2.digitalproserver.com/zerofile/photocontest/Andrea_Spoerer_Las brisas.jpg" alt="Autor: Andrea Spoerer, Título: Las Brisas" />
                    <img src="http://archivos2.digitalproserver.com/zerofile/photocontest/Constanza_Gazmuri_Energia_limpia_para_Chile.jpg" alt="Autor: Constanza Gazmuri, Título: Energía limpia para Chile" />
                    <img src="http://archivos2.digitalproserver.com/zerofile/photocontest/Cristal_Nicole_Ferret_Mi_casa_no_tiene_puertas_ni_ventanas_tiene_amaneceres.jpg" alt="Autor: Cristal Nicole Ferret, Título: Mi casa no tiene puertas ni ventanas, tiene amaneceres" />
                    <img src="http://archivos2.digitalproserver.com/zerofile/photocontest/Cristian_Campos_No_mas_bolsas_plasticas.jpg" alt="Autor: Cristián Campos, Título: No más bolsas plásticas" />
                    <img src="http://archivos2.digitalproserver.com/zerofile/photocontest/Cristian_Campos_Nos_estamos_ahogando.jpg" alt="Autor: Cristián Campos, Título: Nos estamos ahogando" />
                    <img src="http://archivos2.digitalproserver.com/zerofile/photocontest/Cristian_Perez_Habana_I.jpg" alt="Autor: Cristián Pérez, Título: Habana I" />
                    <img src="http://archivos2.digitalproserver.com/zerofile/photocontest/Daniel_Aguayo_Lecho.jpg" alt="Autor: Daniel Aguayo, Título: Lecho" />
                    <img src="http://archivos2.digitalproserver.com/zerofile/photocontest/Emilio_Fuentes_Planta_vs_animal.jpg" alt="Autor: Emilio Fuentes, Título: Planta vs Animal" />
                    <img src="http://archivos2.digitalproserver.com/zerofile/photocontest/Florencio_Velasco_Voy_y_vuelvo.jpg" alt="Autor: Florencio Velasco, Título: Voy y vuelvo" />
                    <img src="http://archivos2.digitalproserver.com/zerofile/photocontest/Francisco_Javier_Dagnino_Bicirretrato.jpg" alt="Autor: Francisco Javier Dagnino, Título: Bicirretrato" />
                    <img src="http://archivos2.digitalproserver.com/zerofile/photocontest/Humberto_Diaz_Bolsaire.jpg" alt="Autor: Humberto Díaz, Título: Bolsaire" />
                    <img src="http://archivos2.digitalproserver.com/zerofile/photocontest/Humberto_Diaz_Post_show.jpg" alt="Autor: Humberto Díaz, Título: Post show" />
                    <img src="http://archivos2.digitalproserver.com/zerofile/photocontest/Jose_Francisco_Veliz_Erradicacion_de_500_toneladas_de_basura_rio_Maipo_2010.jpg" alt="Autor: José Francisco Véliz, Título: Erradicación de 500 toneladas de basura "Río Maipo 2010"" />
                    <img src="http://archivos2.digitalproserver.com/zerofile/photocontest/Jose_Francisco_Veliz_Erradicacion_de_3500_neumaticos_ribera_sur_rio_Maipo_2010.jpg" alt="Autor: José Francisco Véliz, Título: Erradicación de 3500 nuemáticos ribera sur río Maipo 2010" />
    				<img src="http://archivos2.digitalproserver.com/zerofile/photocontest/Manuela_Ovalle_Langerqi-carne.jpg" alt="Autor: Manuela Ovalle Langerqi, Título: Carne" />
                    <img src="http://archivos2.digitalproserver.com/zerofile/photocontest/Manuela_Ovalle_Todo.jpg" alt="Autor: Manuela Ovalle, Título: Todo" />
                    <img src="http://archivos2.digitalproserver.com/zerofile/photocontest/Maria_de_los_angeles_Fernandez_Casazero1.jpg" alt="Autor: María de los Ángles Ferández, Título: Casazero Nº1" />
                    <img src="http://archivos2.digitalproserver.com/zerofile/photocontest/Maria_de_los_Angeles_Fernandez_Casazero2.jpg" alt="Autor: María de los Ángeles Ferández, Título: Casazero Nº2" />
                    <img src="http://archivos2.digitalproserver.com/zerofile/photocontest/Maria_Francisca_Montes_Agua_de_parra.jpg" alt="Autor: María Francisca Montes, Título: Agua de parra" />
                    <img src="http://archivos2.digitalproserver.com/zerofile/photocontest/Maria_Francisca_Montes_Cultivo.jpg" alt="Autor: María Francisca Montes, Título: Cultivo" />
                    <img src="http://archivos2.digitalproserver.com/zerofile/photocontest/Paulina_Bravo_La corbata_verde.jpg" alt="Autor: Paulina Bravo, Título: La corbata verde" />
                    <img src="http://archivos2.digitalproserver.com/zerofile/photocontest/Pedro SEPULVEDA_Paris_sera_una_fiesta.jpg" alt="Autor: Pedro Sepúlveda, Título: París será una fiesta" />
                    <img src="http://archivos2.digitalproserver.com/zerofile/photocontest/Pedro_SEPULVEDA_Far_away_from_Burzaco.jpg" alt="Autor: Pedro Sepúlveda, Título: Far away from Burzaco" />
                    <img src="http://archivos2.digitalproserver.com/zerofile/photocontest/Sergio_Mancilla_Cachupin_el_perro_que_queria_ser_fotografo.jpg" alt="Autor: Sergio Mancilla, Título: Cachupín, el perro que quería ser fotógrafo" />
                    <img src="http://archivos2.digitalproserver.com/zerofile/photocontest/Sergio_Mancilla_Hielo_on_the_rocks.jpg" alt="Autor: Sergio Mancilla, Título: Hielo on the rocks!" />
                    
                </div>
            </section>
            
            <script>
                Galleria.loadTheme('/assets/aux/galleria/themes/classic/galleria.classic.js');
                $('#galleria').galleria();
            </script> -->
            <!-- /photoContest -->
            
            <!-- @featured -->

            <section id="featured" class="home-featured section cf">

                
                <!-- @highlights -->

                <div class="highlights fl cf">

                    <hgroup>

                        <h3>Espacios</h3>

                        <span>Lo nuevo en Zero</span>

                    </hgroup>

                    
                    
                    <div class="a-group first cf">
                    <a href="/contenidos/radar/" class="group-label">Radar</a>
                                        
                    <article>

                        <div>

                            <a href="http://radiozero.cl/2012/06/06/jolie-madame/" class="pic"><img width="80" height="80" src="http://radiozero.cl/media/2012/06/jolie-madame-80x80.jpg" class="attachment-80x80" alt="scanner, retoque: collage Claudia Donoso" title="scanner, retoque: collage Claudia Donoso" /></a>

                            <a href="http://radiozero.cl/2012/06/06/jolie-madame/" class="title">Jolie Madame</a>

                            <p class="overview">Una exposición de collages de Claudia Donso,</p>

                        </div>

                        

                        <span class="comment-count">0</span>

                        <a href="http://radiozero.cl/2012/06/06/jolie-madame/" class="more">Leer Más</a>

                    </article>

                                        
                    <article>

                        <div>

                            <a href="http://radiozero.cl/2012/06/06/club-de-escritura/" class="pic"><img width="80" height="80" src="http://radiozero.cl/media/2012/06/taller-80x80.jpg" class="attachment-80x80" alt="taller" title="taller" /></a>

                            <a href="http://radiozero.cl/2012/06/06/club-de-escritura/" class="title">Club de Escritura</a>

                            <p class="overview">Manda tu relato y participa de este taller a cargo de la esc...</p>

                        </div>

                        

                        <span class="comment-count">0</span>

                        <a href="http://radiozero.cl/2012/06/06/club-de-escritura/" class="more">Leer Más</a>

                    </article>

                                        </div>
                    
                    <div class="a-group cf">
                    <a href="/contenidos/redes/" class="group-label">Redes</a>
                                        
                    <article>

                        <div>

                            <a href="http://radiozero.cl/2012/06/05/haz-musica-en-vimeo/" class="pic"><img width="80" height="80" src="http://radiozero.cl/media/2012/06/vimeo-sound-80x80.jpg" class="attachment-80x80" alt="vimeo-sound" title="vimeo-sound" /></a>

                            <a href="http://radiozero.cl/2012/06/05/haz-musica-en-vimeo/" class="title">Haz música en Vimeo</a>

                            <p class="overview">Con dos nuevas aplicaciones que te permiten modificar y alma...</p>

                        </div>

                        

                        <span class="comment-count">0</span>

                        <a href="http://radiozero.cl/2012/06/05/haz-musica-en-vimeo/" class="more">Leer Más</a>

                    </article>

                                        
                    <article>

                        <div>

                            <a href="http://radiozero.cl/2012/06/05/partycloud-fm/" class="pic"><img width="80" height="80" src="http://radiozero.cl/media/2012/06/partycloud-80x80.jpg" class="attachment-80x80" alt="partycloud" title="partycloud" /></a>

                            <a href="http://radiozero.cl/2012/06/05/partycloud-fm/" class="title">PartyCloud.fm</a>

                            <p class="overview">Crea tu propia radio con más de 20 millones de canciones.</p>

                        </div>

                        

                        <span class="comment-count">0</span>

                        <a href="http://radiozero.cl/2012/06/05/partycloud-fm/" class="more">Leer Más</a>

                    </article>

                                        </div>
                    
                    <div class="a-group cf">
                    <a href="/contenidos/zero-emision/" class="group-label">Zero Emisión</a>
                                        
                    <article>

                        <div>

                            <a href="http://radiozero.cl/2012/06/05/pegamento-ecologico/" class="pic"><img width="80" height="80" src="http://radiozero.cl/media/2012/06/pegamento-ecologico-80x80.jpg" class="attachment-80x80" alt="pegamento-ecologico" title="pegamento-ecologico" /></a>

                            <a href="http://radiozero.cl/2012/06/05/pegamento-ecologico/" class="title">Pegamento Ecológico</a>

                            <p class="overview">Fabrícalo con simples ingredientes caseros</p>

                        </div>

                        

                        <span class="comment-count">0</span>

                        <a href="http://radiozero.cl/2012/06/05/pegamento-ecologico/" class="more">Leer Más</a>

                    </article>

                                        
                    <article>

                        <div>

                            <a href="http://radiozero.cl/2012/06/05/upcycling/" class="pic"><img width="80" height="80" src="http://radiozero.cl/media/2012/06/upcycling-80x80.jpg" class="attachment-80x80" alt="upcycling" title="upcycling" /></a>

                            <a href="http://radiozero.cl/2012/06/05/upcycling/" class="title">Upcycling</a>

                            <p class="overview">Transformar un desecho en algo nuevo</p>

                        </div>

                        

                        <span class="comment-count">0</span>

                        <a href="http://radiozero.cl/2012/06/05/upcycling/" class="more">Leer Más</a>

                    </article>

                                        </div>

                    <div class="a-group cf">
                    <a href="/contenidos/la-vuelta-al-mundo/" class="group-label">La vuelta al mundo</a>
                                        
                    <article>

                        <div>

                            <a href="http://radiozero.cl/2012/06/06/reclamos-en-la-oea/" class="pic"><img width="80" height="80" src="http://radiozero.cl/media/2012/06/lvam_evooea-80x80.jpg" class="attachment-80x80" alt="lvam_evooea" title="lvam_evooea" /></a>

                            <a href="http://radiozero.cl/2012/06/06/reclamos-en-la-oea/" class="title">Reclamos en la OEA</a>

                            <p class="overview">Con más ruido que compromisos terminó la cumbre de la OEA en...</p>

                        </div>

                        

                        <span class="comment-count">0</span>

                        <a href="http://radiozero.cl/2012/06/06/reclamos-en-la-oea/" class="more">Leer Más</a>

                    </article>

                                        
                    <article>

                        <div>

                            <a href="http://radiozero.cl/2012/06/05/siria-en-las-puertas-de-la-guerra-civil/" class="pic"><img width="80" height="80" src="http://radiozero.cl/media/2012/06/lvam-houla-siria-80x80.jpg" class="attachment-80x80" alt="lvam-houla-siria" title="lvam-houla-siria" /></a>

                            <a href="http://radiozero.cl/2012/06/05/siria-en-las-puertas-de-la-guerra-civil/" class="title">Siria en las puertas de la guerra civil</a>

                            <p class="overview">La incapacidad de las potencias extranjeras, la falta de org...</p>

                        </div>

                        

                        <span class="comment-count">0</span>

                        <a href="http://radiozero.cl/2012/06/05/siria-en-las-puertas-de-la-guerra-civil/" class="more">Leer Más</a>

                    </article>

                                        </div>
                    
                    <div class="a-group cf">
                    <a href="/contenidos/numeros-reales/" class="group-label">Números reales</a>
                                        
                    <article>

                        <div>

                            <a href="http://radiozero.cl/2011/11/10/baja-la-aprobacion-a-la-pena-de-muerte/" class="pic"><img width="80" height="80" src="http://radiozero.cl/media/2011/11/toma3-80x80.jpg" class="attachment-80x80" alt="toma3" title="toma3" /></a>

                            <a href="http://radiozero.cl/2011/11/10/baja-la-aprobacion-a-la-pena-de-muerte/" class="title">Baja la aprobación a la pena de muerte</a>

                            <p class="overview">La más baja de la historia en Estados Unidos.</p>

                        </div>

                        

                        <span class="comment-count">0</span>

                        <a href="http://radiozero.cl/2011/11/10/baja-la-aprobacion-a-la-pena-de-muerte/" class="more">Leer Más</a>

                    </article>

                                        
                    <article>

                        <div>

                            <a href="http://radiozero.cl/2011/11/10/porcentaje-de-violencia/" class="pic"><img width="80" height="80" src="http://radiozero.cl/media/2011/11/mexico-el-pais-mas-violento-80x80.jpg" class="attachment-80x80" alt="mexico-el-pais-mas-violento" title="mexico-el-pais-mas-violento" /></a>

                            <a href="http://radiozero.cl/2011/11/10/porcentaje-de-violencia/" class="title">Porcentaje de violencia</a>

                            <p class="overview">Casi la mitad de los países más violentos del mundo está en ...</p>

                        </div>

                        

                        <span class="comment-count">2</span>

                        <a href="http://radiozero.cl/2011/11/10/porcentaje-de-violencia/" class="more">Leer Más</a>

                    </article>

                                        </div>

                    <a href="http://radiozero.cl/contenidos/micros/" class="more-news">Ver Más Artículos &rarr;</a>

                </div>

                <!-- /@highlights -->

                

                <!-- @podcast -->

                <div class="podcast fr">

                    <hgroup>

                        <h3>Podcast</h3>

                        <span>Los últimos 6</span>

                    </hgroup>

                    

                    <script type="text/javascript">

                        AudioPlayer.setup('/assets/aux/audio-player.swf', {  

                            width: 218,

                            transparentpagebg: 'yes',

                            animation: 'no',

                            initialvolume: 100

                        });

                    </script>

                    

                    
                    <article>

                        <a href="http://radiozero.cl/2012/06/06/podcast-divertimento-06-de-junio-2/" class="title">Podcast Divertimento, 06 de junio</a>

                        <span class="comment-count">0 Comentarios</span>

                        

                        <div id="podcast-33653">

                            <script type="text/javascript">

                                AudioPlayer.embed('podcast-33653', {

                                    soundFile: 'http://radiozero.cl/media/2012/06/DIV_060612.mp3',

                                    artists: 'Podcast Divertimento, 06 de junio',

                                    titles: 'Radio Zero'

                                });

                            </script>

                        </div>

                    </article>

                    
                    <article>

                        <a href="http://radiozero.cl/2012/06/06/podcast-desde-zero-06-de-junio-juan-gabriel-valdes/" class="title">Podcast Desde Zero, 06 de junio: Juan Gabriel Valdés</a>

                        <span class="comment-count">12 Comentarios</span>

                        

                        <div id="podcast-33617">

                            <script type="text/javascript">

                                AudioPlayer.embed('podcast-33617', {

                                    soundFile: 'http://radiozero.cl/media/2012/06/DZ_060612.mp3',

                                    artists: 'Podcast Desde Zero, 06 de junio: Juan Gabriel Valdés',

                                    titles: 'Radio Zero'

                                });

                            </script>

                        </div>

                    </article>

                    
                    <article>

                        <a href="http://radiozero.cl/2012/06/06/podcast-pagina-zero-06-de-junio/" class="title">Podcast Página Zero, 06 de junio</a>

                        <span class="comment-count">0 Comentarios</span>

                        

                        <div id="podcast-33613">

                            <script type="text/javascript">

                                AudioPlayer.embed('podcast-33613', {

                                    soundFile: 'http://radiozero.cl/media/2012/06/PZ_060612.mp3',

                                    artists: 'Podcast Página Zero, 06 de junio',

                                    titles: 'Radio Zero'

                                });

                            </script>

                        </div>

                    </article>

                    
                    <article>

                        <a href="http://radiozero.cl/2012/06/05/podcast-gran-capital-05-de-junio-pablo-simonetti/" class="title">Podcast Gran Capital, 05 de junio: Pablo Simonetti</a>

                        <span class="comment-count">0 Comentarios</span>

                        

                        <div id="podcast-33611">

                            <script type="text/javascript">

                                AudioPlayer.embed('podcast-33611', {

                                    soundFile: 'http://radiozero.cl/media/2012/06/GC_050612.mp3',

                                    artists: 'Podcast Gran Capital, 05 de junio: Pablo Simonetti',

                                    titles: 'Radio Zero'

                                });

                            </script>

                        </div>

                    </article>

                    
                    <article>

                        <a href="http://radiozero.cl/2012/06/05/podcast-divertimento-05-de-junio/" class="title">Podcast Divertimento, 05 de junio</a>

                        <span class="comment-count">0 Comentarios</span>

                        

                        <div id="podcast-33597">

                            <script type="text/javascript">

                                AudioPlayer.embed('podcast-33597', {

                                    soundFile: 'http://radiozero.cl/media/2012/06/DIV_050612.mp3',

                                    artists: 'Podcast Divertimento, 05 de junio',

                                    titles: 'Radio Zero'

                                });

                            </script>

                        </div>

                    </article>

                    
                    <article>

                        <a href="http://radiozero.cl/2012/06/05/podcast-desde-zero-05-de-junio-roberto-mendez-y-annie-dufey/" class="title">Podcast Desde Zero, 05 de junio: Roberto Méndez y Annie Dufey</a>

                        <span class="comment-count">7 Comentarios</span>

                        

                        <div id="podcast-33561">

                            <script type="text/javascript">

                                AudioPlayer.embed('podcast-33561', {

                                    soundFile: 'http://radiozero.cl/media/2012/06/DZ_0506121.mp3',

                                    artists: 'Podcast Desde Zero, 05 de junio: Roberto Méndez y Annie Dufey',

                                    titles: 'Radio Zero'

                                });

                            </script>

                        </div>

                    </article>

                    
                </div>

                <!-- /@podcast -->
				
				<div style="width: 300px; float: right; margin-top: 20px;"><script type='text/javascript'><!--// <![CDATA[
    /* [id61] radiozero.cl - @página bajo Podcast */
    OA_show(61);
// ]]> --></script><noscript><a target='_blank' href='http://advertising.grupodial.cl/www/delivery/ck.php?n=3d7758e'><img border='0' alt='' src='http://advertising.grupodial.cl/www/delivery/avw.php?zoneid=61&amp;n=3d7758e' /></a></noscript></div>

            </section>

            <!-- /@featured -->


<!-- @adBlock -->

            <div id="partnership2" class="ad-block section cf">

                <div class="b1">

                <script type='text/javascript'><!--// <![CDATA[

   /* [id37] radiozero.cl - Caluga Izquiera (Zona superior) */

   OA_show(37);

// ]]> --></script><noscript><a target='_blank' href='http://advertising.grupodial.cl/www/delivery/ck.php?n=6da1030'><img border='0' alt='' src='http://advertising.grupodial.cl/www/delivery/avw.php?zoneid=37&amp;n=6da1030' /></a></noscript>

                    

				</div>

                

                <div class="b2">

                <script type='text/javascript'><!--// <![CDATA[

   /* [id38] radiozero.cl - Caluga Central (Zona superior) */

   OA_show(38);

// ]]> --></script><noscript><a target='_blank' href='http://advertising.grupodial.cl/www/delivery/ck.php?n=d305022'><img border='0' alt='' src='http://advertising.grupodial.cl/www/delivery/avw.php?zoneid=38&amp;n=d305022' /></a></noscript>

                    

                </div>

                

                <div class="b3">

<script type='text/javascript'><!--// <![CDATA[
    /* [id39] radiozero.cl - Caluga Derecha (Zona superior) */
    OA_show(39);
// ]]> --></script><noscript><a target='_blank' href='http://advertising.grupodial.cl/www/delivery/ck.php?n=dcf1958'><img border='0' alt='' src='http://advertising.grupodial.cl/www/delivery/avw.php?zoneid=39&amp;n=dcf1958' /></a></noscript>

                    

                </div>

            </div>

            <!-- /@adBlock -->


            <!-- @miscContent -->

            <section id="misc-content" class="section cf">

               <div class="highlights2 fl">
                <hgroup>

                        <h3>Destacados</h3>

                        <span>Noticias en Zero</span>

                    </hgroup>
                                    
                    <article>

                        <div>

                            <a href="http://radiozero.cl/2012/06/04/podcast-desde-zero-04-de-junio-manuel-jose-ossandon-y-jorge-contesse/" class="pic"><img width="80" height="80" src="http://radiozero.cl/media/2012/06/JorgeContesse-2012-80x80.jpg" class="attachment-80x80" alt="JorgeContesse-2012" title="JorgeContesse-2012" /></a>

                            <a href="http://radiozero.cl/2012/06/04/podcast-desde-zero-04-de-junio-manuel-jose-ossandon-y-jorge-contesse/" class="title">Podcast Desde Zero, 04 de junio: Manuel José Ossandón y Jorge Contesse</a>

                            <p class="overview">Conversamos con el alcalde RN de Puente Alto sobre el gobier...</p>

                        </div>

                        

                        <span class="comment-count">4</span>

                        <a href="http://radiozero.cl/2012/06/04/podcast-desde-zero-04-de-junio-manuel-jose-ossandon-y-jorge-contesse/" class="more">Leer Más</a>

                    </article>

                                        
                    <article>

                        <div>

                            <a href="http://radiozero.cl/2012/06/01/el-pinchadiscos-01-de-junio-maxxi-soundsystem/" class="pic"><img width="80" height="80" src="http://radiozero.cl/media/2012/06/maxxi-soundsystem-80x80.jpg" class="attachment-80x80" alt="maxxi-soundsystem" title="maxxi-soundsystem" /></a>

                            <a href="http://radiozero.cl/2012/06/01/el-pinchadiscos-01-de-junio-maxxi-soundsystem/" class="title">El Pinchadiscos, 01 de junio: Maxxi Soundsystem</a>

                            <p class="overview">A las 23.00 un set del dj inglés Sam Watts, alias Maxxi Soun...</p>

                        </div>

                        

                        <span class="comment-count">0</span>

                        <a href="http://radiozero.cl/2012/06/01/el-pinchadiscos-01-de-junio-maxxi-soundsystem/" class="more">Leer Más</a>

                    </article>

                                        
                    <article>

                        <div>

                            <a href="http://radiozero.cl/2012/06/01/podcast-desde-zero-01-de-junio-cristian-larroulet/" class="pic"><img width="80" height="80" src="http://radiozero.cl/media/2010/12/cristian-larroulet-80x80.jpg" class="attachment-80x80" alt="cristian-larroulet" title="cristian-larroulet" /></a>

                            <a href="http://radiozero.cl/2012/06/01/podcast-desde-zero-01-de-junio-cristian-larroulet/" class="title">Podcast Desde Zero, 01 de junio: Cristián Larroulet</a>

                            <p class="overview">Hablamos con René Muga, gerente general de la Asociación de ...</p>

                        </div>

                        

                        <span class="comment-count">14</span>

                        <a href="http://radiozero.cl/2012/06/01/podcast-desde-zero-01-de-junio-cristian-larroulet/" class="more">Leer Más</a>

                    </article>

                                        
                    <article>

                        <div>

                            <a href="http://radiozero.cl/2012/05/31/entrevista-a-francisco-javier-cuadra-en-desde-zero/" class="pic"><img width="80" height="80" src="http://radiozero.cl/media/2012/05/fjcuadra-80x80.jpg" class="attachment-80x80" alt="fjcuadra" title="fjcuadra" /></a>

                            <a href="http://radiozero.cl/2012/05/31/entrevista-a-francisco-javier-cuadra-en-desde-zero/" class="title">Entrevista a Francisco Javier Cuadra en Desde Zero</a>

                            <p class="overview">El ex ministro de Pinochet y ex embajador ante la Santa Sede...</p>

                        </div>

                        

                        <span class="comment-count">2</span>

                        <a href="http://radiozero.cl/2012/05/31/entrevista-a-francisco-javier-cuadra-en-desde-zero/" class="more">Leer Más</a>

                    </article>

                                        
                    <p class="txtr"><a href="http://radiozero.cl/contenidos/noticias/" class="more-news">Ver Más Noticias &rarr;</a><p>
               </div>

                


                <!-- @zeroTv -->

                <div class="zerotv fl">

                    <hgroup>

                        <h3><img src="/assets/img/title-zerotv.png" alt="Zero TV" /></h3>

                    </hgroup>

                    

                    
                    <article>

                        <a href="http://radiozero.cl/2012/06/06/sesiones-zero-12-fernando-milagros/" class="title">Sesiones Zero 12: Fernando Milagros</a>

                        <p class="overview">En una nueva versión del programa que también es un concierto y como siempre desde el Centro Mori de Bellavista y en directo por Radio Zero, el próximo 20 de junio desde las 20 hrs. podremos escuchar ...</p>

                        

                        <div class="embed">

                            
                            <object width="280" height="170"><param name="movie" value="http://www.youtube.com/v/TqZby4Xb2GE&hl=en_US&fs=1&color1=0x5d1719&color2=0xcd311b&hd=1"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/TqZby4Xb2GE&hl=en_US&fs=1&color1=0x5d1719&color2=0xcd311b&hd=1" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="280" height="170"></embed></object>

                            
                        </div>

                    </article>

                     

                    

                    <ul class="last-videos">

                        
                        <li><a href="http://radiozero.cl/2012/06/04/album-de-la-semana-amy-winehouse-back-to-black/">Álbum de la semana: Amy Winehouse / Back to Black</a></li>

                        
                        <li><a href="http://radiozero.cl/2012/05/28/passion-pit-we-take-a-walk/">Passion Pit &#8211; We take a walk</a></li>

                        
                        <li><a href="http://radiozero.cl/2012/05/28/gossip-perfect-world/">Gossip &#8211; Perfect World</a></li>

                        
                        <li><a href="http://radiozero.cl/2012/05/28/flight-facilities-with-you/">Flight Facilities &#8211; With you</a></li>

                        
                        <li><a href="http://radiozero.cl/2012/05/28/capital-cities-safe-and-sound/">Capital Cities &#8211; Safe and Sound</a></li>

                        
                        <li><a href="http://radiozero.cl/2012/05/18/album-de-la-semana-r-e-m-monster/">Álbum de la semana: R.E.M. / Monster</a></li>

                        
                        <li><a href="http://radiozero.cl/2012/05/08/album-de-la-semana-michael-jackson-thriller/">Álbum de la semana- Michael Jackson/ Thriller</a></li>

                        
                        <li><a href="http://radiozero.cl/2012/05/07/astro-colombo/">Astro – Colombo</a></li>

                        
                        <li><a href="http://radiozero.cl/2012/05/07/santigold-disparate-youth/">Santigold – Disparate Youth</a></li>

                        
                        <li><a href="http://radiozero.cl/2012/05/07/the-black-keys-lonely-boy/">The Black Keys – Lonely Boy</a></li>

                        
                        <li><a href="http://radiozero.cl/2012/05/07/here-we-go-magic-how-do-i-know/">Here We Go Magic – “How Do I Know”</a></li>

                        
                        <li><a href="http://radiozero.cl/2012/05/04/murio-adam-yauch-de-beastie-boys/">Murió Adam Yauch de Beastie Boys</a></li>

                        
                    </ul>

                </div>

                <!-- /@zeroTv -->

                

                <!-- @social -->

                <div class="social-networks fr">

                    <script src="http://widgets.twimg.com/j/2/widget.js"></script>

                    <script>

                        new TWTR.Widget({

                          version: 2,

                          type: 'search',

                          search: 'FROM:@radiozero977 OR @desdezero977 OR @divertimento977 OR @grancapital977',

                          interval: 6000,

                          title: 'Radio Zero en Twitter',

                          subject: '@radiozero977',

                          width: 300,

                          height: 540,

                          theme: {

                            shell: {

                              background: '#333',

                              color: '#ffffff'

                            },

                            tweets: {

                              background: '#ffffff',

                              color: '#444444',

                              links: '#dc2427'

                            }

                          },

                          features: {

                            scrollbar: false,

                            loop: true,

                            live: true,

                            hashtags: true,

                            timestamp: true,

                            avatars: true,

                            behavior: 'default'

                          }

                        }).render().start();

                    </script>

                </div>

                <!-- /@social -->

            </section>

            <!-- /@miscContent -->

            

            <!-- @adBlock -->

            <div class="ad-block section cf">

                <div class="ad728 fl">

                 

                 <script type='text/javascript'><!--//<![CDATA[

   var m3_u = (location.protocol=='https:'?'https://advertising.grupodial.cl/www/delivery/ajs.php':'http://advertising.grupodial.cl/www/delivery/ajs.php');

   var m3_r = Math.floor(Math.random()*99999999999);

   if (!document.MAX_used) document.MAX_used = ',';

   document.write ("<scr"+"ipt type='text/javascript' src='"+m3_u);

   document.write ("?zoneid=2");

   document.write ('&amp;cb=' + m3_r);

   if (document.MAX_used != ',') document.write ("&amp;exclude=" + document.MAX_used);

   document.write (document.charset ? '&amp;charset='+document.charset : (document.characterSet ? '&amp;charset='+document.characterSet : ''));

   document.write ("&amp;loc=" + escape(window.location));

   if (document.referrer) document.write ("&amp;referer=" + escape(document.referrer));

   if (document.context) document.write ("&context=" + escape(document.context));

   if (document.mmm_fo) document.write ("&amp;mmm_fo=1");

   document.write ("'><\/scr"+"ipt>");

//]]>--></script><noscript><a href='http://advertising.grupodial.cl/www/delivery/ck.php?n=a6f30ed3&amp;cb=INSERT_RANDOM_NUMBER_HERE' target='_blank'><img src='http://advertising.grupodial.cl/www/delivery/avw.php?zoneid=2&amp;cb=INSERT_RANDOM_NUMBER_HERE&amp;n=a6f30ed3' border='0' alt='' /></a></noscript>

                 

                </div>

                

                <div class="ad200 fr">

                

                <script type='text/javascript'><!--//<![CDATA[

   var m3_u = (location.protocol=='https:'?'https://advertising.grupodial.cl/www/delivery/ajs.php':'http://advertising.grupodial.cl/www/delivery/ajs.php');

   var m3_r = Math.floor(Math.random()*99999999999);

   if (!document.MAX_used) document.MAX_used = ',';

   document.write ("<scr"+"ipt type='text/javascript' src='"+m3_u);

   document.write ("?zoneid=3");

   document.write ('&amp;cb=' + m3_r);

   if (document.MAX_used != ',') document.write ("&amp;exclude=" + document.MAX_used);

   document.write (document.charset ? '&amp;charset='+document.charset : (document.characterSet ? '&amp;charset='+document.characterSet : ''));

   document.write ("&amp;loc=" + escape(window.location));

   if (document.referrer) document.write ("&amp;referer=" + escape(document.referrer));

   if (document.context) document.write ("&context=" + escape(document.context));

   if (document.mmm_fo) document.write ("&amp;mmm_fo=1");

   document.write ("'><\/scr"+"ipt>");

//]]>--></script><noscript><a href='http://advertising.grupodial.cl/www/delivery/ck.php?n=a4137e3f&amp;cb=INSERT_RANDOM_NUMBER_HERE' target='_blank'><img src='http://advertising.grupodial.cl/www/delivery/avw.php?zoneid=3&amp;cb=INSERT_RANDOM_NUMBER_HERE&amp;n=a4137e3f' border='0' alt='' /></a></noscript>



                

                </div>

            </div>

            <!-- /@adBlock -->

            

            <!-- @adBlock -->
            <div id="partnership" class="ad-block section cf">
                <div class="b1">
                    <script type='text/javascript'><!--// <![CDATA[
    /* [id4] radiozero.cl - caluga footer izquierda */
    OA_show(4);
// ]]> --></script><noscript><a target='_blank' href='http://advertising.grupodial.cl/www/delivery/ck.php?n=f2c20c1'><img border='0' alt='' src='http://advertising.grupodial.cl/www/delivery/avw.php?zoneid=4&amp;n=f2c20c1' /></a></noscript>
                </div>
                
                <div class="b2">
                    <script type='text/javascript'><!--// <![CDATA[
    /* [id5] radiozero.cl - caluga footer central */
    OA_show(5);
// ]]> --></script><noscript><a target='_blank' href='http://advertising.grupodial.cl/www/delivery/ck.php?n=ebcc63a'><img border='0' alt='' src='http://advertising.grupodial.cl/www/delivery/avw.php?zoneid=5&amp;n=ebcc63a' /></a></noscript>
                </div>
                
                <div class="b3">
                    <script type='text/javascript'><!--// <![CDATA[
    /* [id6] radiozero.cl - caluga footer derecha */
    OA_show(6);
// ]]> --></script><noscript><a target='_blank' href='http://advertising.grupodial.cl/www/delivery/ck.php?n=d9eb82a'><img border='0' alt='' src='http://advertising.grupodial.cl/www/delivery/avw.php?zoneid=6&amp;n=d9eb82a' /></a></noscript>
                </div>
            </div>
            <!-- /@adBlock -->
            
            <!-- @footer -->
            <footer>
                <div class="wrapper cf">
                                        
                    <div class="disclaimer fl">
                        <p><img src="/assets/img/logo-radiozero-s.png" alt="" class="fl" style="margin-right: 20px;" />Av. Santa MarÃ­a 2670, Piso 2, Providencia, Santiago<br />Â©2010, Radio Zero. Grupo de Radios Dial. <a href="#">Algunos derechos reservados (CC)</a>.</p>
                    </div>
                    
                    <div class="partners txtr fr" style="width: 400px; padding-top: 12px;">
                        <a href="http://www.certifica.com/" target="_blank"><img src="/assets/img/logo-certifica.png" alt="Certifica Metrics" /></a>
                        
                        <a href="http://www.iab.cl/" target="_blank" style="display: inline-block; margin-left: 10px;"><img src="/assets/img/logo-iab.png" alt="IAB Chile" /></a>
                        
                        <a href="http://www.grupodial.cl/" target="_blank" style="display: inline-block; margin-left: 10px;"><img src="/assets/img/logo-dial.png" alt="Grupo Dial" /></a>
                    </div>
                </div>
            </footer>
            <!-- /@footer -->
            
            <script type='text/javascript'>
/* <![CDATA[ */
var pollsL10n = {
	ajax_url: "http://radiozero.cl/wp-content/plugins/wp-polls/wp-polls.php",
	text_wait: "Your last request is still being processed. Please wait a while ...",
	text_valid: "Please choose a valid poll answer.",
	text_multiple: "Maximum number of choices allowed: ",
	show_loading: "1",
	show_fading: "1"
};
/* ]]> */
</script>
<script type='text/javascript' src='http://radiozero.cl/wp-content/plugins/wp-polls/polls-js.js?ver=2.50'></script>
<script type='text/javascript' src='http://radiozero.cl/wp-content/plugins/contact-form-7/jquery.form.js?ver=2.47'></script>
<script type='text/javascript' src='http://radiozero.cl/wp-content/plugins/contact-form-7/scripts.js?ver=2.4.1'></script>
            
            <script type='text/javascript'><!--//<![CDATA[
   var ox_u = 'http://advertising.grupodial.cl/www/delivery/al.php?zoneid=47&target=_blank&cb=INSERT_RANDOM_NUMBER_HERE&layerstyle=simple&align=center&valign=top&padding=20&closetime=10&padding=20&shifth=0&shiftv=0&closebutton=f&backcolor=FFFFFF&bordercolor=000000';
   if (document.context) ox_u += '&context=' + escape(document.context);
   document.write("<scr"+"ipt type='text/javascript' src='" + ox_u + "'></scr"+"ipt>");
//]]>--></script>
            
            <div style="visibility: hidden;">
                <script language="JavaScript1.4" src="http://resource.latercera.cl/js/certifica-js14.js"></script>
                <script type="text/javascript" src="http://resource.latercera.cl/js/certifica.js"></script>
                <script type="text/javascript">
                    tagCertifica(25581, "url");
                </script>
            </div>
			
			<div id="fb-root"></div>
			<script>
				(function(d, s, id) {
  				var js, fjs = d.getElementsByTagName(s)[0];
  				if (d.getElementById(id)) return;
  				js = d.createElement(s); js.id = id;
  				js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=195281680520368";
  				fjs.parentNode.insertBefore(js, fjs);
				}(document, 'script', 'facebook-jssdk'));
			</script>

            <script type="text/javascript">
              var _gaq = _gaq || [];
              _gaq.push(['_setAccount', 'UA-31497548-1']);
              _gaq.push(['_trackPageview']);
            
              (function() {
                var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
              })();
            </script>
        </div>
        <!-- /@wrap -->
    </body>
</html>