<html> 
  <head>
    <title>tonis-podcasts.tk</title>
    <meta http-equiv="refresh" content="2; URL=http://domain.dot.tk/p/?d=TONIS-PODCASTS&i=77.188.236.104&c=49&ro=0&ref=unknown&_=1339030747788"/>
    <script type="text/javascript">
    <!--
      function redir(){ var $fwd = 'http://domain.dot.tk/p/?d=TONIS-PODCASTS&i=77.188.236.104&c=49&ro=0&ref=unknown&_=1339030747788'; if(window.parent){ window.parent.location=$fwd; }else{ window.location=$fwd; }}
    //-->
    </script>
  </head>
  <body onload="redir()">
    <script language="text/javascript">
    <!--
      window.setTimeout('redir();', 500 * 1);
    //-->
    </script>
  </body>
</html>
