<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en-US">

<head profile="http://gmpg.org/xfn/11">

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

<title> </title>

<link rel="stylesheet" href="http://www.joeaveragepoker.com/blog/wp-content/themes/f2/style.css" type="text/css" media="screen" />
<link rel="stylesheet" href="http://www.joeaveragepoker.com/blog/wp-content/themes/f2/print.css" type="text/css" media="print" />

<link rel="pingback" href="http://www.joeaveragepoker.com/blog/xmlrpc.php" />

<link rel="alternate" type="application/rss+xml" title=" &raquo; Feed" href="http://www.joeaveragepoker.com/blog/index.php/feed/" />
<link rel="alternate" type="application/rss+xml" title=" &raquo; Comments Feed" href="http://www.joeaveragepoker.com/blog/index.php/comments/feed/" />
				
	<script type="text/javascript">//<![CDATA[
	// Google Analytics for WordPress by Yoast v4.2.2 | http://yoast.com/wordpress/google-analytics/
	var _gaq = _gaq || [];
	_gaq.push(['_setAccount','UA-26600725-1']);
	_gaq.push(['_trackPageview'],['_trackPageLoadTime']);
	(function() {
		var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	})();
	//]]></script>
<link rel="EditURI" type="application/rsd+xml" title="RSD" href="http://www.joeaveragepoker.com/blog/xmlrpc.php?rsd" />
<link rel="wlwmanifest" type="application/wlwmanifest+xml" href="http://www.joeaveragepoker.com/blog/wp-includes/wlwmanifest.xml" /> 
<meta name="generator" content="WordPress 3.3.1" />

<!-- Fluid Blue customized styles generated by functions.php -->
<style type="text/css">
#header {
	background-image: url('http://www.joeaveragepoker.com/blog/wp-content/themes/f2-custom/images/TopHeader.jpg');
	background-color: #cc3300;
	height: 200px;
}
#hmenu {
	display: none;
}
#headerlogo h1 a {
	color: #ffffff;
}
#headerlogo div.description {
	color: #ffffff;
}
#container {
	padding-right: 240px;
	padding-left: 240px;
}
#wrapper {
	border-right-width: 240px;
	margin-right: -240px;
	border-left-width: 240px;
	margin-left: -240px;
}
#sidebar_right {
	width: 200px;
	margin-right: -240px;
	font-size: 1em;
}
#sidebar_left {
	width: 200px;
	margin-left: -240px;
	font-size: 1em;
}
.postentry p {
	font-size: 1em;
}
.postentry ul {
	font-size: 1em;
}
.postentry ol {
	font-size: 1em;
}
</style>
<link rel="stylesheet" href="http://www.joeaveragepoker.com/blog/wp-content/themes/f2/rounded-corners.css" type="text/css" media="screen" />

</head>

<body class="home blog">
<div id="page">

<div id="header">
	<div id="headerlogo">
		<h1><a href="http://www.joeaveragepoker.com/blog" title=": "></a></h1>
		<div class="description"></div>
	</div> 
</div>

<div id="hmenu"> <!-- Horizontal navigation menu -->
<a style="display:none;" href="#content">Skip to content</a>
<ul>
	<li><a href="http://www.joeaveragepoker.com/blog">Home</a></li>
	<li class="page_item page-item-2"><a href="http://www.joeaveragepoker.com/blog/index.php/wsop-playing-the-main-event/">WSOP – Playing the Main Event</a></li>
<li class="page_item page-item-9"><a href="http://www.joeaveragepoker.com/blog/index.php/texas-holdem-rules/">Texas Hold&#8217;em Rules</a></li>
<li class="page_item page-item-11"><a href="http://www.joeaveragepoker.com/blog/index.php/playing-pot-limit-tournaments/">Playing Pot-Limit Tournaments</a></li>
<li class="page_item page-item-13"><a href="http://www.joeaveragepoker.com/blog/index.php/big-stack-mistake/">Big Stack Mistake</a></li>
<li class="page_item page-item-15"><a href="http://www.joeaveragepoker.com/blog/index.php/big-blind-play/">Big Blind Play</a></li>
<li class="page_item page-item-18"><a href="http://www.joeaveragepoker.com/blog/index.php/playing-bottom-two-pair/">Playing Bottom Two Pair</a></li>
<li class="page_item page-item-21"><a href="http://www.joeaveragepoker.com/blog/index.php/dangers-of-slow-playing/">Dangers of Slow Playing</a></li>
<li class="page_item page-item-23"><a href="http://www.joeaveragepoker.com/blog/index.php/how-many-re-buys/">How Many Re-Buys</a></li>
<li class="page_item page-item-27"><a href="http://www.joeaveragepoker.com/blog/index.php/approximating-odds/">Approximating Odds</a></li>
<li class="page_item page-item-29"><a href="http://www.joeaveragepoker.com/blog/index.php/playing-passively/">Playing Passively</a></li>
<li class="page_item page-item-34"><a href="http://www.joeaveragepoker.com/blog/index.php/sit-n-goes-made-easy/">Sit N Goes Made Easy</a></li>
<li class="page_item page-item-37"><a href="http://www.joeaveragepoker.com/blog/index.php/how-big-a-bankroll/">How Big a Bankroll</a></li>
<li class="page_item page-item-39"><a href="http://www.joeaveragepoker.com/blog/index.php/small-pot-poker/">Small Pot Poker</a></li>
<li class="page_item page-item-41"><a href="http://www.joeaveragepoker.com/blog/index.php/tournament-tips/">Tournament Tips</a></li>
<li class="page_item page-item-43"><a href="http://www.joeaveragepoker.com/blog/index.php/pre-flop-rankings/">Pre-Flop Rankings</a></li>
<li class="page_item page-item-45"><a href="http://www.joeaveragepoker.com/blog/index.php/betting-basics/">Betting Basics</a></li>
<li class="page_item page-item-48"><a href="http://www.joeaveragepoker.com/blog/index.php/big-draws-in-limit-holdem/">Big Draws in Limit Hold &#8216;em</a></li>
<li class="page_item page-item-51"><a href="http://www.joeaveragepoker.com/blog/index.php/5-card-draw-poker-rules/">5 Card Draw Poker Rules</a></li>
<li class="page_item page-item-53"><a href="http://www.joeaveragepoker.com/blog/index.php/7-card-stud-hilo-rules/">7 Card Stud Hi/Lo Rules</a></li>
<li class="page_item page-item-57"><a href="http://www.joeaveragepoker.com/blog/index.php/7-card-stud-poker-rules/">7 Card Stud Poker Rules</a></li>
<li class="page_item page-item-61"><a href="http://www.joeaveragepoker.com/blog/index.php/omaha-hilo-rules/">Omaha Hi/Lo Rules</a></li>
<li class="page_item page-item-63"><a href="http://www.joeaveragepoker.com/blog/index.php/omaha-poker-rules/">Omaha Poker Rules</a></li>
<li class="page_item page-item-65"><a href="http://www.joeaveragepoker.com/blog/index.php/poker-definitions/">Poker Definitions</a></li>
<li class="page_item page-item-67"><a href="http://www.joeaveragepoker.com/blog/index.php/poker-hand-rankings/">Poker Hand Rankings</a></li>
<li class="page_item page-item-72"><a href="http://www.joeaveragepoker.com/blog/index.php/get-started-in-stud-8-poker/">Get Started in Stud 8 Poker</a></li>
<li class="page_item page-item-74"><a href="http://www.joeaveragepoker.com/blog/index.php/thoughts-on-omaha-8/">Thoughts on Omaha-8</a></li>
<li class="page_item page-item-76"><a href="http://www.joeaveragepoker.com/blog/index.php/representing-a-bluff/">Representing a Bluff</a></li>
<li class="page_item page-item-78"><a href="http://www.joeaveragepoker.com/blog/index.php/fourth-street-in-stud-poker/">Fourth Street in Stud Poker</a></li>
<li class="page_item page-item-127"><a href="http://www.joeaveragepoker.com/blog/index.php/meet-the-hosts/">Meet the Hosts</a></li>
<li class="page_item page-item-131"><a href="http://www.joeaveragepoker.com/blog/index.php/advertise-with-joe-average-poker/">Advertise</a></li>
<li class="page_item page-item-138"><a href="http://www.joeaveragepoker.com/blog/index.php/terms-of-use/">Terms of Use</a></li>
<li class="page_item page-item-141"><a href="http://www.joeaveragepoker.com/blog/index.php/contact-us/">Contact Us</a></li>
<li class="page_item page-item-187"><a href="http://www.joeaveragepoker.com/blog/index.php/got-a-poker-question/">Got a Poker Question?</a></li>
	<li class="hmenu_rss"><a href="http://www.joeaveragepoker.com/blog/index.php/feed/">Feed</a></li>
</ul>
</div>

<div id="container">
<div id="wrapper">

	<div id="content">

			
						
			<div class="post-503 post type-post status-publish format-standard hentry category-poker-show" id="post-503">
				<h2 class="posttitle"><a href="http://www.joeaveragepoker.com/blog/index.php/2012/03/30/click-the-link-to-see-some-great-pics-of-vintage-las-vegas-gaming-chips/" rel="bookmark" title="Permanent Link to Click the link to see some great pics of Vintage Las Vegas Gaming Chips">Click the link to see some great pics of Vintage Las Vegas Gaming Chips</a></h2>
				<div class="postmetadata">
								<span class="postdate">30 March 2012, 12:05 pm</span>
								</div>
				
				<div class="postentry">
					<div class="wp-caption aligncenter" style="width: 610px"><a href="http://acidcow.com/pics/30804-vintage-las-vegas-gaming-chips-40-pics.html" onclick="javascript:_gaq.push(['_trackEvent','outbound-article','http://acidcow.com']);"><img title="Check out this collection of Vintage Gaming Chips" src="http://acidcow.com/pics/20120329/vegas_gaming_chips_09.jpg" alt="" width="600" height="597" /></a><p class="wp-caption-text">Check out these Vintage Gaming Chips</p></div>
				</div>
		
				<div class="postmetadata">
					<div class="posttagscat">
										<span class="postcat">Filed under&nbsp;<a href="http://www.joeaveragepoker.com/blog/index.php/category/poker-show/" title="View all posts in Poker Show" rel="category tag">Poker Show</a>.</span>
															</div>

					<span class="postcomment">
					<a href="http://www.joeaveragepoker.com/blog/index.php/2012/03/30/click-the-link-to-see-some-great-pics-of-vintage-las-vegas-gaming-chips/#respond" title="Comment on Click the link to see some great pics of Vintage Las Vegas Gaming Chips">Comment</a>					</span>
										
				 </div>
			</div>
	
						
			<div class="post-487 post type-post status-publish format-standard hentry category-general-poker" id="post-487">
				<h2 class="posttitle"><a href="http://www.joeaveragepoker.com/blog/index.php/2012/02/09/wpt-live-streaming-for-free/" rel="bookmark" title="Permanent Link to WPT Live Streaming&#8230;and it&#8217;s FREE">WPT Live Streaming&#8230;and it&#8217;s FREE</a></h2>
				<div class="postmetadata">
								<span class="postdate">9 February 2012, 9:22 am</span>
								</div>
				
				<div class="postentry">
					<p style="text-align: center;">Check out the WPT Website for <a href="http://www.worldpokertour.com/Live_Streaming/index.aspx?cmpgn_id6552bnr_id106/" onclick="javascript:_gaq.push(['_trackEvent','outbound-article','http://www.worldpokertour.com']);" target="_blank">FREE Live Streaming</a> of Current Poker Tournaments.</p>
<p style="text-align: center;"><a href="http://www.worldpokertour.com/Live_Streaming/index.aspx?cmpgn_id6552bnr_id106/" onclick="javascript:_gaq.push(['_trackEvent','outbound-article','http://www.worldpokertour.com']);" target="_blank"><img class="aligncenter size-medium wp-image-495" title="WPT-Logo-350px" src="http://www.joeaveragepoker.com/blog/wp-content/uploads/2012/02/WPT-Logo-350px-300x144.jpg" alt="" width="300" height="144" /></a></p>
				</div>
		
				<div class="postmetadata">
					<div class="posttagscat">
										<span class="postcat">Filed under&nbsp;<a href="http://www.joeaveragepoker.com/blog/index.php/category/general-poker/" title="View all posts in General Poker" rel="category tag">General Poker</a>.</span>
															</div>

					<span class="postcomment">
					<a href="http://www.joeaveragepoker.com/blog/index.php/2012/02/09/wpt-live-streaming-for-free/#respond" title="Comment on WPT Live Streaming&#8230;and it&#8217;s FREE">Comment</a>					</span>
										
				 </div>
			</div>
	
						
			<div class="post-479 post type-post status-publish format-standard hentry category-general-poker" id="post-479">
				<h2 class="posttitle"><a href="http://www.joeaveragepoker.com/blog/index.php/2012/02/09/a-small-dose-of-poker-humor-to-start-your-day-off-right/" rel="bookmark" title="Permanent Link to A Small Dose of Poker Humor to Start Your Day Off Right">A Small Dose of Poker Humor to Start Your Day Off Right</a></h2>
				<div class="postmetadata">
								<span class="postdate">9 February 2012, 9:04 am</span>
								</div>
				
				<div class="postentry">
					<p><a href="http://www.joeaveragepoker.com/blog/wp-content/uploads/2012/02/83941.jpg" ><img class="aligncenter size-medium wp-image-482" title="Chameleons" src="http://www.joeaveragepoker.com/blog/wp-content/uploads/2012/02/83941-232x300.jpg" alt="" width="232" height="300" /></a></p>
				</div>
		
				<div class="postmetadata">
					<div class="posttagscat">
										<span class="postcat">Filed under&nbsp;<a href="http://www.joeaveragepoker.com/blog/index.php/category/general-poker/" title="View all posts in General Poker" rel="category tag">General Poker</a>.</span>
															</div>

					<span class="postcomment">
					<a href="http://www.joeaveragepoker.com/blog/index.php/2012/02/09/a-small-dose-of-poker-humor-to-start-your-day-off-right/#respond" title="Comment on A Small Dose of Poker Humor to Start Your Day Off Right">Comment</a>					</span>
										
				 </div>
			</div>
	
						
			<div class="post-439 post type-post status-publish format-standard hentry category-what-would-you-do tag-what-would-you-do" id="post-439">
				<h2 class="posttitle"><a href="http://www.joeaveragepoker.com/blog/index.php/2012/02/06/what-would-you-do-feb-29/" rel="bookmark" title="Permanent Link to What Would You Do? Feb 29">What Would You Do? Feb 29</a></h2>
				<div class="postmetadata">
								<span class="postdate">6 February 2012, 1:09 pm</span>
								</div>
				
				<div class="postentry">
					<p><em><strong><span style="color: #cc0000;">Submit responses no later than Feb 29, 2012 </span></strong></em></p>
<p>This hand is from a $2/5 NL game at Nautica in the flats of Cleveland, Ohio.  I&#8217;m in mid-position with pocket Kings, Kc/Kd. There&#8217;s one limper, 2 fold and it&#8217;s on me and I make it $30 (pretty standard raise for this game).  I get 2 callers behind me and the limper in front of me calls.  There&#8217;s $127 in the pot.</p>
<p>The flop is 5h/2d/Qd.   Limper checks, I bet out $100 and get called by both players behind me.  Limper folds. The turn is 3h. Still decent for me.  I have about $450 in front of me. Now I need to decide what would be the best way to maximize this hand. Do I check and let one of the others make a move at this pot, or do I make an average bet or go all in and possibly end the hand here?  WHAT WOULD YOU DO??? </p>
<p>Please comment below or email your answer to <a href="mailto:robin@joeaveragepoker.com?subject=Response%20to%20What%20Would%20You%20Do????">Robin@joeaveragepoker.com</a>.</p>
<p><span style="color: #999999;">Winning responses will receive a ClubWPT T-shirt. Winners from NE Ohio will also receive a 60 minute Massage from <a title="Stow Massage" href="http://www.stowmassage.com" onclick="javascript:_gaq.push(['_trackEvent','outbound-article','http://www.stowmassage.com']);">Stow Massage</a>. All entries will be entered into grand prize drawing done prior to 2012 WSOP.</span></p>
				</div>
		
				<div class="postmetadata">
					<div class="posttagscat">
										<span class="postcat">Filed under&nbsp;<a href="http://www.joeaveragepoker.com/blog/index.php/category/poker-show/what-would-you-do/" title="View all posts in What Would You Do?" rel="category tag">What Would You Do?</a>.</span>
										<span class="posttags">Tagged&nbsp;<a href="http://www.joeaveragepoker.com/blog/index.php/tag/what-would-you-do/" rel="tag">What Would You Do?</a></span>					</div>

					<span class="postcomment">
					<a href="http://www.joeaveragepoker.com/blog/index.php/2012/02/06/what-would-you-do-feb-29/#respond" title="Comment on What Would You Do? Feb 29">Comment</a>					</span>
										
				 </div>
			</div>
	
						
			<div class="post-456 post type-post status-publish format-standard hentry category-news-and-updates category-poker-show tag-news-and-updates tag-updates tag-webcast" id="post-456">
				<h2 class="posttitle"><a href="http://www.joeaveragepoker.com/blog/index.php/2012/02/06/jap-webcast-part-1-poker-news-and-updates/" rel="bookmark" title="Permanent Link to JAP Webcast Part 1: Poker News and Updates">JAP Webcast Part 1: Poker News and Updates</a></h2>
				<div class="postmetadata">
								<span class="postdate">6 February 2012, 12:53 pm</span>
								</div>
				
				<div class="postentry">
					<p><iframe width="640" height="360" src="http://www.youtube.com/embed/Iw9tFcRjTMk" frameborder="0" allowfullscreen></iframe></p>
				</div>
		
				<div class="postmetadata">
					<div class="posttagscat">
										<span class="postcat">Filed under&nbsp;<a href="http://www.joeaveragepoker.com/blog/index.php/category/poker-show/news-and-updates/" title="View all posts in News and Updates" rel="category tag">News and Updates</a>, <a href="http://www.joeaveragepoker.com/blog/index.php/category/poker-show/" title="View all posts in Poker Show" rel="category tag">Poker Show</a>.</span>
										<span class="posttags">Tagged&nbsp;<a href="http://www.joeaveragepoker.com/blog/index.php/tag/news-and-updates/" rel="tag">News and Updates</a>, <a href="http://www.joeaveragepoker.com/blog/index.php/tag/updates/" rel="tag">Updates</a>, <a href="http://www.joeaveragepoker.com/blog/index.php/tag/webcast/" rel="tag">Webcast</a></span>					</div>

					<span class="postcomment">
					<a href="http://www.joeaveragepoker.com/blog/index.php/2012/02/06/jap-webcast-part-1-poker-news-and-updates/#respond" title="Comment on JAP Webcast Part 1: Poker News and Updates">Comment</a>					</span>
										
				 </div>
			</div>
	
						
			<div class="post-453 post type-post status-publish format-standard hentry category-news-and-updates category-poker-show category-what-would-you-do tag-news-and-updates tag-webcast tag-what-would-you-do" id="post-453">
				<h2 class="posttitle"><a href="http://www.joeaveragepoker.com/blog/index.php/2012/02/06/jap-webcast-part-2-what-would-you-do-winning-response-and-february-poker-schedule/" rel="bookmark" title="Permanent Link to JAP Webcast Part 2: &#8220;What Would You Do?&#8221; Winning Response and February Poker Schedule">JAP Webcast Part 2: &#8220;What Would You Do?&#8221; Winning Response and February Poker Schedule</a></h2>
				<div class="postmetadata">
								<span class="postdate">6 February 2012, 12:52 pm</span>
								</div>
				
				<div class="postentry">
					<p><iframe width="640" height="360" src="http://www.youtube.com/embed/AjcDyk9JqBo" frameborder="0" allowfullscreen></iframe></p>
				</div>
		
				<div class="postmetadata">
					<div class="posttagscat">
										<span class="postcat">Filed under&nbsp;<a href="http://www.joeaveragepoker.com/blog/index.php/category/poker-show/news-and-updates/" title="View all posts in News and Updates" rel="category tag">News and Updates</a>, <a href="http://www.joeaveragepoker.com/blog/index.php/category/poker-show/" title="View all posts in Poker Show" rel="category tag">Poker Show</a>, <a href="http://www.joeaveragepoker.com/blog/index.php/category/poker-show/what-would-you-do/" title="View all posts in What Would You Do?" rel="category tag">What Would You Do?</a>.</span>
										<span class="posttags">Tagged&nbsp;<a href="http://www.joeaveragepoker.com/blog/index.php/tag/news-and-updates/" rel="tag">News and Updates</a>, <a href="http://www.joeaveragepoker.com/blog/index.php/tag/webcast/" rel="tag">Webcast</a>, <a href="http://www.joeaveragepoker.com/blog/index.php/tag/what-would-you-do/" rel="tag">What Would You Do?</a></span>					</div>

					<span class="postcomment">
					<a href="http://www.joeaveragepoker.com/blog/index.php/2012/02/06/jap-webcast-part-2-what-would-you-do-winning-response-and-february-poker-schedule/#respond" title="Comment on JAP Webcast Part 2: &#8220;What Would You Do?&#8221; Winning Response and February Poker Schedule">Comment</a>					</span>
										
				 </div>
			</div>
	
						
			<div class="post-450 post type-post status-publish format-standard hentry category-interviews-wpt category-poker-show tag-interviews-wpt tag-webcast" id="post-450">
				<h2 class="posttitle"><a href="http://www.joeaveragepoker.com/blog/index.php/2012/02/06/jap-webcast-part-3-interview-adam-pliska-wpt-president/" rel="bookmark" title="Permanent Link to JAP Webcast Part 3: Interview: Adam Pliska, WPT President">JAP Webcast Part 3: Interview: Adam Pliska, WPT President</a></h2>
				<div class="postmetadata">
								<span class="postdate">6 February 2012, 12:50 pm</span>
								</div>
				
				<div class="postentry">
					<p><iframe width="640" height="360" src="http://www.youtube.com/embed/J5Frzh9p3jg" frameborder="0" allowfullscreen></iframe></p>
				</div>
		
				<div class="postmetadata">
					<div class="posttagscat">
										<span class="postcat">Filed under&nbsp;<a href="http://www.joeaveragepoker.com/blog/index.php/category/poker-show/interviews-wpt/" title="View all posts in Interviews: WPT" rel="category tag">Interviews: WPT</a>, <a href="http://www.joeaveragepoker.com/blog/index.php/category/poker-show/" title="View all posts in Poker Show" rel="category tag">Poker Show</a>.</span>
										<span class="posttags">Tagged&nbsp;<a href="http://www.joeaveragepoker.com/blog/index.php/tag/interviews-wpt/" rel="tag">Interviews: WPT</a>, <a href="http://www.joeaveragepoker.com/blog/index.php/tag/webcast/" rel="tag">Webcast</a></span>					</div>

					<span class="postcomment">
					<a href="http://www.joeaveragepoker.com/blog/index.php/2012/02/06/jap-webcast-part-3-interview-adam-pliska-wpt-president/#respond" title="Comment on JAP Webcast Part 3: Interview: Adam Pliska, WPT President">Comment</a>					</span>
										
				 </div>
			</div>
	
						
			<div class="post-443 post type-post status-publish format-standard hentry category-poker-show category-what-were-they-thinking category-what-would-you-do tag-webcast tag-what-were-they-thinking tag-what-would-you-do" id="post-443">
				<h2 class="posttitle"><a href="http://www.joeaveragepoker.com/blog/index.php/2012/02/06/jap-show-part-4-what-would-you-do-what-were-they-thinking-and-thought-for-the-day/" rel="bookmark" title="Permanent Link to JAP Webcast Part 4: &#8220;What Would You Do?&#8221; Poker Hand, &#8220;What Were They Thinking?&#8221;, and Thought for the Day">JAP Webcast Part 4: &#8220;What Would You Do?&#8221; Poker Hand, &#8220;What Were They Thinking?&#8221;, and Thought for the Day</a></h2>
				<div class="postmetadata">
								<span class="postdate">6 February 2012, 12:46 pm</span>
								</div>
				
				<div class="postentry">
					<p><iframe width="640" height="360" src="http://www.youtube.com/embed/ZhYJt2HbowA" frameborder="0" allowfullscreen></iframe></p>
				</div>
		
				<div class="postmetadata">
					<div class="posttagscat">
										<span class="postcat">Filed under&nbsp;<a href="http://www.joeaveragepoker.com/blog/index.php/category/poker-show/" title="View all posts in Poker Show" rel="category tag">Poker Show</a>, <a href="http://www.joeaveragepoker.com/blog/index.php/category/what-were-they-thinking/" title="View all posts in What Were They Thinking?" rel="category tag">What Were They Thinking?</a>, <a href="http://www.joeaveragepoker.com/blog/index.php/category/poker-show/what-would-you-do/" title="View all posts in What Would You Do?" rel="category tag">What Would You Do?</a>.</span>
										<span class="posttags">Tagged&nbsp;<a href="http://www.joeaveragepoker.com/blog/index.php/tag/webcast/" rel="tag">Webcast</a>, <a href="http://www.joeaveragepoker.com/blog/index.php/tag/what-were-they-thinking/" rel="tag">What Were They Thinking?</a>, <a href="http://www.joeaveragepoker.com/blog/index.php/tag/what-would-you-do/" rel="tag">What Would You Do?</a></span>					</div>

					<span class="postcomment">
					<a href="http://www.joeaveragepoker.com/blog/index.php/2012/02/06/jap-show-part-4-what-would-you-do-what-were-they-thinking-and-thought-for-the-day/#respond" title="Comment on JAP Webcast Part 4: &#8220;What Would You Do?&#8221; Poker Hand, &#8220;What Were They Thinking?&#8221;, and Thought for the Day">Comment</a>					</span>
										
				 </div>
			</div>
	
						
			<div class="post-432 post type-post status-publish format-standard hentry category-what-would-you-do tag-what-would-you-do" id="post-432">
				<h2 class="posttitle"><a href="http://www.joeaveragepoker.com/blog/index.php/2012/01/06/what-would-you-do-jan-31/" rel="bookmark" title="Permanent Link to What Would You Do? Jan 31">What Would You Do? Jan 31</a></h2>
				<div class="postmetadata">
								<span class="postdate">6 January 2012, 11:46 am</span>
								</div>
				
				<div class="postentry">
					<p><em><strong><span style="color: #cc0000;">Submit responses no later than Jan 31, 2012 </span></strong></em></p>
<p>This hand is from a recent $2/5 NL cash game. The game had just got off and I had close to $400 in front of me. I&#8217;m UTG and look down at 2 red nines. I raise it to $25 to go, pretty average bet for this game.  I end up with 5 callers, which include both SB, BB, button and 2 random mid position callers.</p>
<p>The flop is 9c/2h/3d. SAFE!!!!  Both blinds check and I decide to slow-play this one and check.  The next 3 players also check&#8230;which wasn&#8217;t suppose to happen. Thought someone would go after this one.</p>
<p>Turn is a 7/c Board is beginning to gel. Both blinds check and I bet out $120 into a $150 pot. Next 2 players fold, button wakes up and goes ALL-IN for $200. Both blinds fold. I&#8217;ve got the nuts and my decision now is to just smoothe call and possibly bring in the remaining player or come over the top for a total of $375 and push the remaining player out to limit the potential draws against me. WHAT WOULD YOU DO????????</p>
<p>Please comment below or email your answer to <a href="mailto:robin@joeaveragepoker.com?subject=Response%20to%20What%20Would%20You%20Do????">Robin@joeaveragepoker.com</a>.</p>
<p><span style="color: #999999;">Winning responses will receive a ClubWPT T-shirt. Winners from NE Ohio will also receive a 60 minute Massage from <a title="Stow Massage" href="http://www.stowmassage.com" onclick="javascript:_gaq.push(['_trackEvent','outbound-article','http://www.stowmassage.com']);">Stow Massage</a>. All entries will be entered into grand prize drawing done prior to 2012 WSOP.</span></p>
<p><strong><span style="color: #cc0000;">Winning Response </span></strong></p>
<p>This weeks winner is Jordan from Nashville, Tennessee. Jordan said, at this point I would come over the top. You probably won&#8217;t push the other player out, but you will earn a bigger payday&#8230;as long as they don&#8217;t hit their draw.<br />
Hope you took the pot down!!</p>
<p>Jordan, I did just that and the other player did call. The river was an 8h&#8230;no flush, but both players were on a 5/6&#8230;one of them clubs. Oh well they both chopped up my $$$$&#8230;UGH!!!</p>
<p>Thanks to Everyone who responded and Jordan wins the WPT Shirt.</p>
				</div>
		
				<div class="postmetadata">
					<div class="posttagscat">
										<span class="postcat">Filed under&nbsp;<a href="http://www.joeaveragepoker.com/blog/index.php/category/poker-show/what-would-you-do/" title="View all posts in What Would You Do?" rel="category tag">What Would You Do?</a>.</span>
										<span class="posttags">Tagged&nbsp;<a href="http://www.joeaveragepoker.com/blog/index.php/tag/what-would-you-do/" rel="tag">What Would You Do?</a></span>					</div>

					<span class="postcomment">
					<a href="http://www.joeaveragepoker.com/blog/index.php/2012/01/06/what-would-you-do-jan-31/#respond" title="Comment on What Would You Do? Jan 31">Comment</a>					</span>
										
				 </div>
			</div>
	
						
			<div class="post-429 post type-post status-publish format-standard hentry category-news-and-updates category-poker-show tag-news-and-updates tag-webcast" id="post-429">
				<h2 class="posttitle"><a href="http://www.joeaveragepoker.com/blog/index.php/2012/01/06/jap-webcast-part-1-poker-news-and-updates-january-poker-tournaments/" rel="bookmark" title="Permanent Link to JAP Webcast Part 1: Poker News and Updates / January Poker Tournaments">JAP Webcast Part 1: Poker News and Updates / January Poker Tournaments</a></h2>
				<div class="postmetadata">
								<span class="postdate">6 January 2012, 11:36 am</span>
								</div>
				
				<div class="postentry">
					<p><span style="text-align: center; display: block;"><iframe width="480" height="360" src="http://www.youtube.com/embed/gtkpvK-eAug" frameborder="0" allowfullscreen></iframe></span></p>
				</div>
		
				<div class="postmetadata">
					<div class="posttagscat">
										<span class="postcat">Filed under&nbsp;<a href="http://www.joeaveragepoker.com/blog/index.php/category/poker-show/news-and-updates/" title="View all posts in News and Updates" rel="category tag">News and Updates</a>, <a href="http://www.joeaveragepoker.com/blog/index.php/category/poker-show/" title="View all posts in Poker Show" rel="category tag">Poker Show</a>.</span>
										<span class="posttags">Tagged&nbsp;<a href="http://www.joeaveragepoker.com/blog/index.php/tag/news-and-updates/" rel="tag">News and Updates</a>, <a href="http://www.joeaveragepoker.com/blog/index.php/tag/webcast/" rel="tag">Webcast</a></span>					</div>

					<span class="postcomment">
					<a href="http://www.joeaveragepoker.com/blog/index.php/2012/01/06/jap-webcast-part-1-poker-news-and-updates-january-poker-tournaments/#comments" title="Comment on JAP Webcast Part 1: Poker News and Updates / January Poker Tournaments">1 Comment</a>					</span>
										
				 </div>
			</div>
	
		
		<div class="navigation">
			<div class="alignleft"><a href="http://www.joeaveragepoker.com/blog/index.php/page/2/" >&laquo; Older Entries</a></div>
			<div class="alignright"></div>
		</div>
		
	
	</div>
	<div id="sidebar_left" class="sidebar">
		<ul>
			<li id="text-4" class="widget widget_text">			<div class="textwidget"><tr>
    <td align="center" valign="top"><div align="center">
      <p><a href="http://www.joeaveragepoker.com/blog/index.php" ><img src="http://joeaveragepoker.sectorlink.org/blog/wp-content/themes/f2-custom/images/LeftCloumnLogo.gif" alt="The Joe Average Poker Show" width="200" height="159" border="0" /></a></p>
      <p align="left">Whether you are new to the game or a seasoned pro, this is the show for today&rsquo;s poker player.</p>
      <p align="left"> The Joe Average Poker Show is dedicated to bringing you the latest news, strategies and insightful interviews with the people who shape the poker world.</p>
      <blockquote>
        <p align="left"> &bull; Phil Hellmuth<br />
&bull; Daniel Negreanu<br />
&bull; Annie Duke<br />
&bull; Steve Lipscomb<br />
&bull; Gavin Smith<br />
&bull; Mark Seif<br />
&bull; And More!</p>
      </blockquote>
      <p align="left"> Each week the show is filled with entertaining segments and witty commentary from the hosts Brad, Charles and Robin.</p>
    </div></td>
  </tr>
  <hr align="center" width="200" size="1" /></div>
		</li>
<li id="pages-6" class="widget widget_pages"><h2 class="widgettitle">About the Show</h2>
		<ul>
			<li class="page_item page-item-131"><a href="http://www.joeaveragepoker.com/blog/index.php/advertise-with-joe-average-poker/">Advertise</a></li>
<li class="page_item page-item-141"><a href="http://www.joeaveragepoker.com/blog/index.php/contact-us/">Contact Us</a></li>
<li class="page_item page-item-187"><a href="http://www.joeaveragepoker.com/blog/index.php/got-a-poker-question/">Got a Poker Question?</a></li>
<li class="page_item page-item-127"><a href="http://www.joeaveragepoker.com/blog/index.php/meet-the-hosts/">Meet the Hosts</a></li>
<li class="page_item page-item-138"><a href="http://www.joeaveragepoker.com/blog/index.php/terms-of-use/">Terms of Use</a></li>
		</ul>
		</li>
<li id="categories-3" class="widget widget_categories"><h2 class="widgettitle">Site Features</h2>
		<ul>
	<li class="cat-item cat-item-14"><a href="http://www.joeaveragepoker.com/blog/index.php/category/general-poker/" title="View all posts filed under General Poker">General Poker</a>
</li>
	<li class="cat-item cat-item-7"><a href="http://www.joeaveragepoker.com/blog/index.php/category/poker-show/" title="Joe Average Poker Webcasts and Updates">Poker Show</a>
<ul class='children'>
	<li class="cat-item cat-item-11"><a href="http://www.joeaveragepoker.com/blog/index.php/category/poker-show/interviews-wpt/" title="Interviews : WPT">Interviews: WPT</a>
</li>
	<li class="cat-item cat-item-10"><a href="http://www.joeaveragepoker.com/blog/index.php/category/poker-show/news-and-updates/" title="Poker News and Updates">News and Updates</a>
	<ul class='children'>
	<li class="cat-item cat-item-12"><a href="http://www.joeaveragepoker.com/blog/index.php/category/poker-show/news-and-updates/regional-news-midwest/" title="Regional Poker News and Updates from Ohio and Surrounding Areas">Regional News : Midwest</a>
</li>
	</ul>
</li>
	<li class="cat-item cat-item-3"><a href="http://www.joeaveragepoker.com/blog/index.php/category/poker-show/what-would-you-do/" title="What Would You Do?">What Would You Do?</a>
</li>
</ul>
</li>
	<li class="cat-item cat-item-1"><a href="http://www.joeaveragepoker.com/blog/index.php/category/robins-posts/" title="View all posts filed under Robin&#039;s Posts">Robin&#039;s Posts</a>
</li>
	<li class="cat-item cat-item-13"><a href="http://www.joeaveragepoker.com/blog/index.php/category/what-were-they-thinking/" title="View all posts filed under What Were They Thinking?">What Were They Thinking?</a>
</li>
		</ul>
</li>
		<li id="recent-posts-3" class="widget widget_recent_entries">		<h2 class="widgettitle">Recent Posts</h2>
		<ul>
				<li><a href="http://www.joeaveragepoker.com/blog/index.php/2012/03/30/click-the-link-to-see-some-great-pics-of-vintage-las-vegas-gaming-chips/" title="Click the link to see some great pics of Vintage Las Vegas Gaming Chips">Click the link to see some great pics of Vintage Las Vegas Gaming Chips</a></li>
				<li><a href="http://www.joeaveragepoker.com/blog/index.php/2012/02/09/wpt-live-streaming-for-free/" title="WPT Live Streaming&#8230;and it&#8217;s FREE">WPT Live Streaming&#8230;and it&#8217;s FREE</a></li>
				<li><a href="http://www.joeaveragepoker.com/blog/index.php/2012/02/09/a-small-dose-of-poker-humor-to-start-your-day-off-right/" title="A Small Dose of Poker Humor to Start Your Day Off Right">A Small Dose of Poker Humor to Start Your Day Off Right</a></li>
				<li><a href="http://www.joeaveragepoker.com/blog/index.php/2012/02/06/what-would-you-do-feb-29/" title="What Would You Do? Feb 29">What Would You Do? Feb 29</a></li>
				<li><a href="http://www.joeaveragepoker.com/blog/index.php/2012/02/06/jap-webcast-part-1-poker-news-and-updates/" title="JAP Webcast Part 1: Poker News and Updates">JAP Webcast Part 1: Poker News and Updates</a></li>
				</ul>
		</li>
<li id="archives-2" class="widget widget_archive"><h2 class="widgettitle">Archives</h2>
		<ul>
			<li><a href='http://www.joeaveragepoker.com/blog/index.php/2012/03/' title='March 2012'>March 2012</a></li>
	<li><a href='http://www.joeaveragepoker.com/blog/index.php/2012/02/' title='February 2012'>February 2012</a></li>
	<li><a href='http://www.joeaveragepoker.com/blog/index.php/2012/01/' title='January 2012'>January 2012</a></li>
	<li><a href='http://www.joeaveragepoker.com/blog/index.php/2011/12/' title='December 2011'>December 2011</a></li>
	<li><a href='http://www.joeaveragepoker.com/blog/index.php/2011/11/' title='November 2011'>November 2011</a></li>
	<li><a href='http://www.joeaveragepoker.com/blog/index.php/2011/10/' title='October 2011'>October 2011</a></li>
	<li><a href='http://www.joeaveragepoker.com/blog/index.php/2009/12/' title='December 2009'>December 2009</a></li>
	<li><a href='http://www.joeaveragepoker.com/blog/index.php/2009/11/' title='November 2009'>November 2009</a></li>
	<li><a href='http://www.joeaveragepoker.com/blog/index.php/2009/10/' title='October 2009'>October 2009</a></li>
	<li><a href='http://www.joeaveragepoker.com/blog/index.php/2008/11/' title='November 2008'>November 2008</a></li>
	<li><a href='http://www.joeaveragepoker.com/blog/index.php/2008/10/' title='October 2008'>October 2008</a></li>
	<li><a href='http://www.joeaveragepoker.com/blog/index.php/2008/09/' title='September 2008'>September 2008</a></li>
	<li><a href='http://www.joeaveragepoker.com/blog/index.php/2008/02/' title='February 2008'>February 2008</a></li>
	<li><a href='http://www.joeaveragepoker.com/blog/index.php/2008/01/' title='January 2008'>January 2008</a></li>
		</ul>
</li>
<li id="text-3" class="widget widget_text"><h2 class="widgettitle">Our Sponsors&#8230;</h2>
			<div class="textwidget"><div align="center">  
  <p><a href="http://www.clubwpt.com?cmpgn_id=6552&bnr_id=106" onclick="javascript:_gaq.push(['_trackEvent','outbound-widget','http://www.clubwpt.com?cmpgn_id=6552&amp;bnr_id=106']);"><img src="http://affiliates.theclubservices.com/banners/bnrimg.php?id=106&cmpgn_id=6552&prdct_id=1" alt="Play online poker with thousands of real people for FREE" width="200" border="0"></a></p>
  <p><a href="http://www.stowmassage.com/coupon-full-page.htm" onclick="javascript:_gaq.push(['_trackEvent','outbound-widget','http://www.stowmassage.com']);" target="_blank"><img src="http://joeaveragepoker.sectorlink.org/blog/wp-content/themes/f2-custom/images/Stow-Massage-300x150.gif" alt="Relax! You're at Stow Massage" width="200" height="100" border="0" /></a>
  </p>
  <p><img src="http://joeaveragepoker.sectorlink.org/blog/wp-content/themes/f2-custom/images/BurninLuvBanner300x150.gif" alt="Custom Poker Tables" width="200" height="100" />
</p>
  <hr align="center" width="200" size="1" />
</div></div>
		</li>
		</ul>
	</div>
	<div id="sidebar_right" class="sidebar">
		<ul>
			
			<li id="search-4" class="widget widget_search"><h2 class="widgettitle">Search</h2>
<form role="search" method="get" id="searchform" action="http://www.joeaveragepoker.com/blog/" >
	<div><label class="screen-reader-text" for="s">Search for:</label>
	<input type="text" value="" name="s" id="s" />
	<input type="submit" id="searchsubmit" value="Search" />
	</div>
	</form></li>
<li id="calendar-4" class="widget widget_calendar"><h2 class="widgettitle">&nbsp;</h2>
<div id="calendar_wrap"><table id="wp-calendar">
	<caption>June 2012</caption>
	<thead>
	<tr>
		<th scope="col" title="Monday">M</th>
		<th scope="col" title="Tuesday">T</th>
		<th scope="col" title="Wednesday">W</th>
		<th scope="col" title="Thursday">T</th>
		<th scope="col" title="Friday">F</th>
		<th scope="col" title="Saturday">S</th>
		<th scope="col" title="Sunday">S</th>
	</tr>
	</thead>

	<tfoot>
	<tr>
		<td colspan="3" id="prev"><a href="http://www.joeaveragepoker.com/blog/index.php/2012/03/" title="View posts for March 2012">&laquo; Mar</a></td>
		<td class="pad">&nbsp;</td>
		<td colspan="3" id="next" class="pad">&nbsp;</td>
	</tr>
	</tfoot>

	<tbody>
	<tr>
		<td colspan="4" class="pad">&nbsp;</td><td>1</td><td>2</td><td>3</td>
	</tr>
	<tr>
		<td>4</td><td>5</td><td id="today">6</td><td>7</td><td>8</td><td>9</td><td>10</td>
	</tr>
	<tr>
		<td>11</td><td>12</td><td>13</td><td>14</td><td>15</td><td>16</td><td>17</td>
	</tr>
	<tr>
		<td>18</td><td>19</td><td>20</td><td>21</td><td>22</td><td>23</td><td>24</td>
	</tr>
	<tr>
		<td>25</td><td>26</td><td>27</td><td>28</td><td>29</td><td>30</td>
		<td class="pad" colspan="1">&nbsp;</td>
	</tr>
	</tbody>
	</table></div></li>
<li id="pages-3" class="widget widget_pages"><h2 class="widgettitle">Hold&#8217;em Strategy</h2>
		<ul>
			<li class="page_item page-item-27"><a href="http://www.joeaveragepoker.com/blog/index.php/approximating-odds/">Approximating Odds</a></li>
<li class="page_item page-item-45"><a href="http://www.joeaveragepoker.com/blog/index.php/betting-basics/">Betting Basics</a></li>
<li class="page_item page-item-15"><a href="http://www.joeaveragepoker.com/blog/index.php/big-blind-play/">Big Blind Play</a></li>
<li class="page_item page-item-48"><a href="http://www.joeaveragepoker.com/blog/index.php/big-draws-in-limit-holdem/">Big Draws in Limit Hold &#8216;em</a></li>
<li class="page_item page-item-13"><a href="http://www.joeaveragepoker.com/blog/index.php/big-stack-mistake/">Big Stack Mistake</a></li>
<li class="page_item page-item-21"><a href="http://www.joeaveragepoker.com/blog/index.php/dangers-of-slow-playing/">Dangers of Slow Playing</a></li>
<li class="page_item page-item-37"><a href="http://www.joeaveragepoker.com/blog/index.php/how-big-a-bankroll/">How Big a Bankroll</a></li>
<li class="page_item page-item-23"><a href="http://www.joeaveragepoker.com/blog/index.php/how-many-re-buys/">How Many Re-Buys</a></li>
<li class="page_item page-item-18"><a href="http://www.joeaveragepoker.com/blog/index.php/playing-bottom-two-pair/">Playing Bottom Two Pair</a></li>
<li class="page_item page-item-29"><a href="http://www.joeaveragepoker.com/blog/index.php/playing-passively/">Playing Passively</a></li>
<li class="page_item page-item-11"><a href="http://www.joeaveragepoker.com/blog/index.php/playing-pot-limit-tournaments/">Playing Pot-Limit Tournaments</a></li>
<li class="page_item page-item-43"><a href="http://www.joeaveragepoker.com/blog/index.php/pre-flop-rankings/">Pre-Flop Rankings</a></li>
<li class="page_item page-item-34"><a href="http://www.joeaveragepoker.com/blog/index.php/sit-n-goes-made-easy/">Sit N Goes Made Easy</a></li>
<li class="page_item page-item-39"><a href="http://www.joeaveragepoker.com/blog/index.php/small-pot-poker/">Small Pot Poker</a></li>
<li class="page_item page-item-41"><a href="http://www.joeaveragepoker.com/blog/index.php/tournament-tips/">Tournament Tips</a></li>
<li class="page_item page-item-2"><a href="http://www.joeaveragepoker.com/blog/index.php/wsop-playing-the-main-event/">WSOP – Playing the Main Event</a></li>
		</ul>
		</li>
<li id="pages-4" class="widget widget_pages"><h2 class="widgettitle">Poker Rules</h2>
		<ul>
			<li class="page_item page-item-51"><a href="http://www.joeaveragepoker.com/blog/index.php/5-card-draw-poker-rules/">5 Card Draw Poker Rules</a></li>
<li class="page_item page-item-53"><a href="http://www.joeaveragepoker.com/blog/index.php/7-card-stud-hilo-rules/">7 Card Stud Hi/Lo Rules</a></li>
<li class="page_item page-item-57"><a href="http://www.joeaveragepoker.com/blog/index.php/7-card-stud-poker-rules/">7 Card Stud Poker Rules</a></li>
<li class="page_item page-item-61"><a href="http://www.joeaveragepoker.com/blog/index.php/omaha-hilo-rules/">Omaha Hi/Lo Rules</a></li>
<li class="page_item page-item-63"><a href="http://www.joeaveragepoker.com/blog/index.php/omaha-poker-rules/">Omaha Poker Rules</a></li>
<li class="page_item page-item-9"><a href="http://www.joeaveragepoker.com/blog/index.php/texas-holdem-rules/">Texas Hold&#8217;em Rules</a></li>
		</ul>
		</li>
<li id="pages-5" class="widget widget_pages"><h2 class="widgettitle">General Poker Info</h2>
		<ul>
			<li class="page_item page-item-78"><a href="http://www.joeaveragepoker.com/blog/index.php/fourth-street-in-stud-poker/">Fourth Street in Stud Poker</a></li>
<li class="page_item page-item-72"><a href="http://www.joeaveragepoker.com/blog/index.php/get-started-in-stud-8-poker/">Get Started in Stud 8 Poker</a></li>
<li class="page_item page-item-65"><a href="http://www.joeaveragepoker.com/blog/index.php/poker-definitions/">Poker Definitions</a></li>
<li class="page_item page-item-67"><a href="http://www.joeaveragepoker.com/blog/index.php/poker-hand-rankings/">Poker Hand Rankings</a></li>
<li class="page_item page-item-76"><a href="http://www.joeaveragepoker.com/blog/index.php/representing-a-bluff/">Representing a Bluff</a></li>
<li class="page_item page-item-74"><a href="http://www.joeaveragepoker.com/blog/index.php/thoughts-on-omaha-8/">Thoughts on Omaha-8</a></li>
		</ul>
		</li>
<li id="text-5" class="widget widget_text">			<div class="textwidget"><hr align="center" width="200" size="1" />
  <table  width="100%" border="1" align="center"  cellpadding="3" cellspacing="2" bordercolor="#CCCCCC" bgcolor="#FFFFFF">
    <tr>
      <td align="center" valign="middle">
        <div align="center">
          <h3 align="center"><span class="Headers">Get the Gear</span></h3>
          <p><a href="http://www.cafepress.com/joeaveragepoker" onclick="javascript:_gaq.push(['_trackEvent','outbound-widget','http://www.cafepress.com']);"><img src="http://joeaveragepoker.sectorlink.org/blog/wp-content/themes/f2-custom/images/JapGearImage02.gif" alt="Joe Average Poker Promo" width="130" height="150" border="0" /></a></p>
        </div>        
        <p align="left"><span class="subcopy">Shirts, hats and more... Check out all our great poker merchandise at <a href="http://www.cafepress.com/joeaveragepoker" onclick="javascript:_gaq.push(['_trackEvent','outbound-widget','http://www.cafepress.com']);">the Poker Store&hellip;</a> 'cause when you look cool - you play cool!</span></p></td>
    </tr>
  </table>
  <br />
  <table  width="100%" border="1" align="center"  cellpadding="3" cellspacing="2" bordercolor="#CCCCCC" bgcolor="#FFFFFF">
    <tr>
      <td align="center" valign="top">
        <div align="center">
          <h3 align="center"><span class="Headers">Protect the Game</span></h3>
          <p><a href="http://www.pokerplayersalliance.org/" onclick="javascript:_gaq.push(['_trackEvent','outbound-widget','http://www.pokerplayersalliance.org']);" target="_blank"><img src="http://joeaveragepoker.sectorlink.org/blog/wp-content/themes/f2-custom/images/FreedomBanner.gif" alt="Freedom of Choice" width="175" height="150" border="0" /></a></p>
        </div>        
        <p align="left"><span class="subcopy">The <a href="http://www.pokerplayersalliance.org/" onclick="javascript:_gaq.push(['_trackEvent','outbound-widget','http://www.pokerplayersalliance.org']);" target="_blank">Poker Players Alliance</a> urges you to take action and tell lawmakers to keep their hands off of poker.</span><font color="#000000" size="2" face="Verdana">
          <noscript>
          </noscript>
              </font></p></td>
    </tr>
  </table>
  <hr align="center" width="200" size="1" /></div>
		</li>
		</ul>
	</div>

</div> <!-- wrapper -->
</div> <!-- container -->
<div id="footer">
	<div>© 2009 The Joe Average Poker Show</div>
	<div id="footer_credit">
	Powered by <a href="http://wordpress.org/" title="Powered by WordPress.">WordPress</a>. Theme <a href="http://srinig.com/wordpress/themes/f2/">F2</a>.</div> 
	<!-- 20 queries. 1.922 seconds. -->
	</div>
</div> <!-- page -->
<!-- Start of StatCounter Code -->
<script type="text/javascript">
var sc_project=2730521;
var sc_invisible=1;
var sc_security="0a35d7fe";
</script>
<script type="text/javascript"
src="http://www.statcounter.com/counter/counter_xhtml.js"></script>
<noscript><div class="statcounter"><a title="tumblr
statistics" href="http://statcounter.com/tumblr/"
class="statcounter"><img class="statcounter"
src="http://c.statcounter.com/2730521/0/0a35d7fe/1/"
alt="tumblr statistics" /></a></div></noscript>
<!-- End of StatCounter Code -->
</body>
</html>
