<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" media="screen" href="/~d/styles/rss2enclosuresfull.xsl"?><?xml-stylesheet type="text/css" media="screen" href="http://feeds.feedburner.com/~d/styles/itemcontent.css"?><rss xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:media="http://search.yahoo.com/mrss/" xmlns:feedburner="http://rssnamespace.org/feedburner/ext/1.0" version="2.0">

    
            
            
            
            
            
            
            
        
    
    
    

    
  <channel>
      
      <title>Tales of Silicon Valley from CNET TV</title>
      <itunes:author>CNETTV.com</itunes:author>
      <link>http://cnettv.cnet.com/</link>
      <copyright>2008 CNET.com</copyright>
      <description>Silicon Valley is full of stories: some pretty, some not. Tom Merritt invites you to experience the untold story behind the tech giants you only think you know. These are their stories.</description>
      
              <managingEditor>feedback-cnettv@cnet.com (CNETTV)</managingEditor>
          
      <webMaster>feedback-cnettv@cnet.com (CNETTV)</webMaster>
      <language>en-us</language>
      <itunes:explicit>no</itunes:explicit>
      <itunes:subtitle>Silicon Valley is full of stories: some pretty, some not.</itunes:subtitle>
      <itunes:summary>Silicon Valley is full of stories: some pretty, some not. Tom Merritt invites you to experience the untold story behind the tech giants you only think you know. These are their stories.</itunes:summary>
      <itunes:image href="http://www.cnet.com/i/pod/images/talesofsiliconvalley_600x600.jpg" />
      <image><link>http://www.cnettv.com/</link><url>http://www.cnet.com/i/pod/images/talesofsiliconvalley_300x300.jpg</url><title>Tales of Silicon Valley from CNET TV</title></image>
      
              <category>News</category>
              
              
          
      <lastBuildDate>Wed, 06 Jun 2012 06:00:59 PDT</lastBuildDate>
      <pubDate>Wed, 06 Jun 2012 06:00:59 PDT</pubDate>
      <docs>http://blogs.law.harvard.edu/tech/rss</docs>
      


















    


    
    
    
    
    
    
    
    
    
    
    

    
    
        
        
            
        
            
        
    
    
    
        
            
            
            
        
    

    
    
    
    
    
    
    
    
    
    
    

    
    
        
        
            
        
            
        
    
    
    
        
            
            
            
        
    

    
    
    
    
    
    
    
    
    
    
    

    
    
        
        
            
        
            
        
    
    
    
        
            
            
            
        
    

    
    
    
    
    
    
    
    
    
    
    

    
    
        
        
            
        
            
        
    
    
    
        
            
            
            
        
    

    
    
    
    
    
    
    
    
    
    
    

    
        
    
    
        
        
            
        
            
        
    
    
    
        
            
            
            
        
    

    
    
    
    
    
    
    
    
    
    
    

    
        
    
    
        
        
            
        
            
        
    
    
    
        
            
            
            
        
    

    
    
    
    
    
    
    
    
    
    
    

    
        
    
    
        
        
            
        
            
        
    
    
    
        
            
            
            
        
    

    
    
    
    
    
    
    
    
    
    
    

    
        
    
    
        
        
            
        
            
        
    
    
    
        
            
            
            
        
    

    
    
    
    
    
    
    
    
    
    
    

    
        
    
    
        
        
            
        
            
        
    
    
    
        
            
            
            
        
    

    
    
    
    
    
    
    
    
    
    
    

    
        
    
    
        
        
            
        
            
        
    
    
    
        
            
            
            
        
    


  <feedburner:info uri="cnet/talesofsiliconvalley" /><atom10:link xmlns:atom10="http://www.w3.org/2005/Atom" rel="hub" href="http://pubsubhubbub.appspot.com/" /><media:credit role="author">CNETTV.com</media:credit><media:copyright>2008 CNET.com</media:copyright><media:rating>nonadult</media:rating><media:thumbnail url="http://www.cnet.com/i/pod/images/talesofsiliconvalley_600x600.jpg" /><media:keywords>silicon,valley,san,jose,tech,apple,jobs,computer,interview,humor</media:keywords><media:description type="plain">Silicon Valley is full of stories: some pretty, some not.</media:description><media:category scheme="http://www.itunes.com/dtds/podcast-1.0.dtd">Technology</media:category><itunes:owner><itunes:email>podcast@cnet.com</itunes:email><itunes:name>CNETTV.com</itunes:name></itunes:owner><itunes:keywords>silicon,valley,san,jose,tech,apple,jobs,computer,interview,humor</itunes:keywords><itunes:category text="Technology" /><atom10:link xmlns:atom10="http://www.w3.org/2005/Atom" rel="self" type="application/rss+xml" href="http://siliconvalleypodcast.cnettv.com" /><feedburner:feedFlare href="http://add.my.yahoo.com/rss?url=http%3A%2F%2Fsiliconvalleypodcast.cnettv.com" src="http://us.i1.yimg.com/us.yimg.com/i/us/my/addtomyyahoo4.gif">Subscribe with My Yahoo!</feedburner:feedFlare><feedburner:feedFlare href="http://www.newsgator.com/ngs/subscriber/subext.aspx?url=http%3A%2F%2Fsiliconvalleypodcast.cnettv.com" src="http://www.newsgator.com/images/ngsub1.gif">Subscribe with NewsGator</feedburner:feedFlare><feedburner:feedFlare href="http://www.bloglines.com/sub/http://siliconvalleypodcast.cnettv.com" src="http://www.bloglines.com/images/sub_modern11.gif">Subscribe with Bloglines</feedburner:feedFlare><feedburner:feedFlare href="http://www.netvibes.com/subscribe.php?url=http%3A%2F%2Fsiliconvalleypodcast.cnettv.com" src="http://www.netvibes.com/img/add2netvibes.gif">Subscribe with Netvibes</feedburner:feedFlare><feedburner:feedFlare href="http://fusion.google.com/add?feedurl=http%3A%2F%2Fsiliconvalleypodcast.cnettv.com" src="http://buttons.googlesyndication.com/fusion/add.gif">Subscribe with Google</feedburner:feedFlare><feedburner:feedFlare href="http://www.pageflakes.com/subscribe.aspx?url=http%3A%2F%2Fsiliconvalleypodcast.cnettv.com" src="http://www.pageflakes.com/ImageFile.ashx?instanceId=Static_4&amp;fileName=ATP_blu_91x17.gif">Subscribe with Pageflakes</feedburner:feedFlare><feedburner:feedFlare href="http://odeo.com/listen/subscribe?feed=http%3A%2F%2Fsiliconvalleypodcast.cnettv.com" src="http://odeo.com/img/badge-channel-black.gif">Subscribe with ODEO</feedburner:feedFlare><feedburner:feedFlare href="http://www.podnova.com/add.srf?url=http%3A%2F%2Fsiliconvalleypodcast.cnettv.com" src="http://www.podnova.com/img_chicklet_podnova.gif">Subscribe with Podnova</feedburner:feedFlare></channel>

</rss>
