<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:wfw="http://wellformedweb.org/CommentAPI/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:sy="http://purl.org/rss/1.0/modules/syndication/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/">
  <channel>
    <title>Total Debt Relief Blog - Podcasts powered by Odiogo</title>
    <atom:link href="http://www.totaldebtrelief.net/total-debt-relief-blog/feed/" rel="self" type="application/rss+xml" />
    <link>http://www.totaldebtrelief.net/total-debt-relief-blog</link>
    <description>Total Debt Relief Blog</description>
    <lastBuildDate>Thu, 10 May 2012 21:44:37 +0000</lastBuildDate>
    <language>en</language>
    <sy:updatePeriod>hourly</sy:updatePeriod>
    <sy:updateFrequency>1</sy:updateFrequency>
    <generator>http://wordpress.org/?v=3.3.2</generator>
    <item>
      <title>Californians Examine The Supposed Rewards Of Credit Card Debt</title>
      <link>http://www.totaldebtrelief.net/total-debt-relief-blog/californians-examine-the-supposed-rewards-of-credit-card-debt/</link>
      <comments>http://www.totaldebtrelief.net/total-debt-relief-blog/californians-examine-the-supposed-rewards-of-credit-card-debt/#comments</comments>
      <pubDate>Thu, 10 May 2012 21:44:37 +0000</pubDate>
      <dc:creator>channel</dc:creator>
      <category><![CDATA[Uncategorized]]></category>
      <guid isPermaLink="false">http://www.totaldebtrelief.net/total-debt-relief-blog/?p=1016</guid>
      <description>“It might not technically count as fraud according to the Federal Trade Commission,” said nationally syndicated consumer watchdog columnist Amanda Hardison, “but the multinational businesses offering these kinds of programs have enough attorneys on retainer to bend the letter of &amp;#8230; &lt;a href="http://www.totaldebtrelief.net/total-debt-relief-blog/californians-examine-the-supposed-rewards-of-credit-card-debt/"&gt;Continue reading &lt;span class="meta-nav"&gt;&amp;#8594;&lt;/span&gt;&lt;/a&gt;&lt;br&gt;&lt;a type="audio/mpeg" href="http://podcasts.odiogo.com/get_mp3.mp3?f=/total-debt-relief-blog/Total_Debt_Relief_Blog-Californians_Examine_The_Supposed_Rewards_Of_Credit_Card_Debt.mp3"&gt;Click here to play&lt;/a&gt;&lt;br&gt;</description>
      <content:encoded><![CDATA[<p>“It might not technically count as fraud according to the Federal Trade Commission,” said nationally syndicated consumer watchdog columnist Amanda Hardison, “but the multinational businesses offering these kinds of programs have enough attorneys on retainer to bend the letter of the law to their favor.”  A vocal opponent of the rewards trend in the process of transforming the American consumer finance industry, Ms. Hardison recently had the unhappy experience of investigating one of these perks of membership firsthand.</p>
<p>“My sister&#8217;s boy had always been bright about the debt relief, keeping a check on his spending and moving his balances around to reap the benefits of introductory rates set at zero percent or close to it, like we&#8217;d talked about.  The <a title="debt consolidation" href="http://www.totaldebtrelief.net/debt-consolidation/">debt consolidation</a> waltz isn&#8217;t going to eliminate the credit card totals any time soon, but, for a new Master&#8217;s grad just hoping to avoid bankruptcy until he gets a job and sees the paychecks rolling in, there&#8217;s also not much risk so long as you don&#8217;t do something so stupid as move every single dollar you owe onto a card charging twenty two percent interest just because the rewards points guarantees a week at your favorite golfer&#8217;s fantasy camp.”</p>
<p>A little checking &#8212; less than ten minutes over a popular internet search engine, all told &#8212; unearthed a surprising piece of information about the golfer&#8217;s holiday that so captivated her nephew.  According to Ms. Hardison, the sprawling and dangerously over leveraged enterprise had been financed by the PGA standout just before the real estate speculation bubble (which surely had some impact upon pricing up the acres of prime Southern California real estate) exploded any hope of ever seeing a return upon the original investment.</p>
<p>“If you pull out a statement and do the math for costs versus &#8216;rewards&#8217;, you&#8217;re going to be nauseated by how much money is just thrown away on this illusion of grabbing something for nothing.  Honestly, from a certain perspective, this is the clearest piece of evidence yet that commercial banks fully expect their customers to keep paying the least amount requested rather than working out a seventh grade equation to see if the fees are in any way commensurate with the products actually offered.  I&#8217;d say the government should do something, but Obama&#8217;s done everything but force Bank of American to change their insignia to Mr. Yuk, and, still, people see what they want to see.”</p>
<p>As part of a de facto debt settlement agreement whispered about by gossip sites covering the men&#8217;s tour, the aging pro had agreed to donate his name and his services to the multinational lending corporation as a handshake short sell that forgave whatever additional sums were owed in return for specialized instruction of &#8216;preferred members&#8217; chosen by the corporate bank for the vastly popular marketing stratagem, which some analysts believe has lured more than seven figures of debt consolidation toward a card whose rates are among the highest in the industry.</p>
<p>“Even if you&#8217;re not sitting down with a calculator every month to dissect the new bill and estimate how long credit card debt relief would take if you kept just paying minimums,” Ms. Hardison said, referencing the recent federal legislation, “shouldn&#8217;t you be at least a little bit curious about how the pot of gold wound up at the end of the rainbow?  If I&#8217;ve learned anything during my time on this earth, it all comes down to three things.  There really isn&#8217;t any such thing as a free lunch, always look a gift horse in the mouth, and, if your credit card company offers any rewards, get ready for a horsemeat luncheon.”</p>
]]></content:encoded>
      <wfw:commentRss>http://www.totaldebtrelief.net/total-debt-relief-blog/californians-examine-the-supposed-rewards-of-credit-card-debt/feed/</wfw:commentRss>
      <slash:comments>0</slash:comments>
      <enclosure url="http://podcasts.odiogo.com/get_mp3.mp3?f=/total-debt-relief-blog/Total_Debt_Relief_Blog-Californians_Examine_The_Supposed_Rewards_Of_Credit_Card_Debt.mp3" length="1754046" type="audio/mpeg" />
    </item>
    <item>
      <title>Credit Card Debt Burdened Americans Rise Up Against Corporate Banks</title>
      <link>http://www.totaldebtrelief.net/total-debt-relief-blog/credit-card-debt-burdened-americans-rise-up-against-corporate-banks/</link>
      <comments>http://www.totaldebtrelief.net/total-debt-relief-blog/credit-card-debt-burdened-americans-rise-up-against-corporate-banks/#comments</comments>
      <pubDate>Fri, 04 May 2012 16:46:09 +0000</pubDate>
      <dc:creator>channel</dc:creator>
      <category><![CDATA[Uncategorized]]></category>
      <guid isPermaLink="false">http://www.totaldebtrelief.net/total-debt-relief-blog/?p=1010</guid>
      <description>After tens of thousands of account holders abandoned their all purpose corporate banking institutions for a wide array of local credit unions last November in a remarkable display of consumer protest, most onlookers experienced with the over arching trends typically &amp;#8230; &lt;a href="http://www.totaldebtrelief.net/total-debt-relief-blog/credit-card-debt-burdened-americans-rise-up-against-corporate-banks/"&gt;Continue reading &lt;span class="meta-nav"&gt;&amp;#8594;&lt;/span&gt;&lt;/a&gt;&lt;br&gt;&lt;a type="audio/mpeg" href="http://podcasts.odiogo.com/get_mp3.mp3?f=/total-debt-relief-blog/Total_Debt_Relief_Blog-Credit_Card_Debt_Burdened_Americans_Rise_Up_Against_Corporate_Banks.mp3"&gt;Click here to play&lt;/a&gt;&lt;br&gt;</description>
      <content:encoded><![CDATA[<p>After tens of thousands of account holders abandoned their all purpose corporate banking institutions for a wide array of local credit unions last November in a remarkable display of consumer protest, most onlookers experienced with the over arching trends typically guiding American finance predicted the newly chastened conglomerates would emphasize a responsive warmth and sensitivity to customer concerns directly afterward.  Alas, the corporate image of the banking monoliths remains as impassive and unapologetic as ever, even in the midst of continuing economic despair damaging so many families even during this putative period of recovery.</p>
<p>Considering that the successive introduction of pointless and callously mercenary charges &#8212; a five dollar fee for debit cards attached to Bank of America checking accounts was widely portrayed throughout the media as the straw that broke the creditor&#8217;s back &#8212; essentially led to the mass exodus, one would&#8217;ve assumed the superbanks already the target enemy of social protestors across the country (Occupy Wall Street forces regularly holding impromptu debt settlement jubilee demonstrations within B of A lobbies) might decide against hurtling nuisance expenses at proud citizens doing all that they can just to avoid bankruptcy.</p>
<p>“If the banking centers honestly wanted to change public perception, the blueprint isn&#8217;t all that difficult,” said Maria Leery, a business historian and author of Taking It To The Bank: Checking And Cross Checking Amidst United States Financial Institutions.  “Franchises fall out of favor all of the time, you know, but the chain restaurants have learned to take their lumps, change up the insignia, apologize to the consumer base, and weather the storm just long enough for the famously short memories of the American public to gloss over the details.  That&#8217;s what has people so riled about bank of America and the rest of the corporate lenders.  There&#8217;s a system in place!”</p>
<p>Indeed, the more politically progressive men and women manning the frontlines of the Occupy movement have repeatedly called into question the viability of these corporations above all else.  “Our electorate apparently finds no fault with the superbanks holding dominion over both the credit card debt and the <a title="mortgage loans" href="http://www.totaldebtrelief.net/credit-card-debt/credit-card-debt-equity-mortgage-loans/">mortgage loans</a> consolidating credit card debt relief, but, ignore the way things are supposed to be handled, that&#8217;s an unforgivable slight.”  To a certain extent, Leery and other fiscal authorities believe the widely shared view of banking institutions as irredeemably arrogant may be ultimately based in their none too distant origins.</p>
<p>A generation or two ago, the banking centers prized within American communities had no reason to pander to the whims of the market or jostle one another aside in the rush for new clientele.  If anything, bank executives aspired to a certain imperious air of divine purpose meant to reassure consumers of a fundamental stolidity &#8212; essaying in all aspects the model of respectability, better to convince the townspeople their savings would be secure &#8212; that has very little to do with adopting the measure of humility modern audiences seem to require.  “Credit cards and the fantastical profits they brought along changed the role of the banks for good,” Leery said.  “They&#8217;re in the thick of the hunt for their share of the dollar the same as anyone else.  You start incorporating all manner of services, from financial counseling to debt relief to unsecured lending, and, to meet the demands of the marketplace, you occasionally have to serve.”</p>
]]></content:encoded>
      <wfw:commentRss>http://www.totaldebtrelief.net/total-debt-relief-blog/credit-card-debt-burdened-americans-rise-up-against-corporate-banks/feed/</wfw:commentRss>
      <slash:comments>0</slash:comments>
      <enclosure url="http://podcasts.odiogo.com/get_mp3.mp3?f=/total-debt-relief-blog/Total_Debt_Relief_Blog-Credit_Card_Debt_Burdened_Americans_Rise_Up_Against_Corporate_Banks.mp3" length="1741241" type="audio/mpeg" />
    </item>
    <item>
      <title>Will New Consumer Finance Protection Bureau Aid Debt Relief?</title>
      <link>http://www.totaldebtrelief.net/total-debt-relief-blog/will-new-consumer-finance-protection-bureau-aid-debt-relief/</link>
      <comments>http://www.totaldebtrelief.net/total-debt-relief-blog/will-new-consumer-finance-protection-bureau-aid-debt-relief/#comments</comments>
      <pubDate>Thu, 03 May 2012 19:37:14 +0000</pubDate>
      <dc:creator>channel</dc:creator>
      <category><![CDATA[Uncategorized]]></category>
      <guid isPermaLink="false">http://www.totaldebtrelief.net/total-debt-relief-blog/?p=1013</guid>
      <description>After a seemingly endless period of gestation, the long awaited Consumer Financial Protection Bureau has finally opened its doors with Richard Cordray, the former Attorney General of Ohio, at the helm.  Boasting eight hundred civil servants at his disposal, Cordray &amp;#8230; &lt;a href="http://www.totaldebtrelief.net/total-debt-relief-blog/will-new-consumer-finance-protection-bureau-aid-debt-relief/"&gt;Continue reading &lt;span class="meta-nav"&gt;&amp;#8594;&lt;/span&gt;&lt;/a&gt;&lt;br&gt;&lt;a type="audio/mpeg" href="http://podcasts.odiogo.com/get_mp3.mp3?f=/total-debt-relief-blog/Total_Debt_Relief_Blog-Will_New_Consumer_Finance_Protection_Bureau_Aid_Debt_Relief.mp3"&gt;Click here to play&lt;/a&gt;&lt;br&gt;</description>
      <content:encoded><![CDATA[<p>After a seemingly endless period of gestation, the long awaited Consumer Financial Protection Bureau has finally opened its doors with Richard Cordray, the former Attorney General of Ohio, at the helm.  Boasting eight hundred civil servants at his disposal, Cordray will be expected to oversee an increasingly important segment of the economy that has thus far largely gone either unregulated or, in the opinion of some pundits, over regulated, with genuinely useful restrictions upon lender misdeeds hidden behind contradictory or meaningless guidelines.  At this moment, though, the Bureau&#8217;s leadership has only formally outlined plans for promoting the spread of information to consumers about the various means of compensating student loans and residential mortgages.</p>
<p>&nbsp;</p>
<p>These twin implacable gremlins at the heart of our current fiscal unease have wholly resisted all governmental actions to smooth over ongoing difficulties hindering repayment, and printing more <a title="debt relief" href="http://www.totaldebtrelief.net/">debt relief</a> booklets reminding borrowers that they should have monitored liabilities beforehand shan&#8217;t correct the situation.  Still, even if there&#8217;s only negligible value to the dissemination of additional data, the heightened communication won&#8217;t do any harm.  Moreover, the program hardly comes as a surprise, especially in comparison to the all too vivid questions encircling the unsecured burdens.  Given the tentative nature of the United States economy at present, commentators have openly wondered just how much leeway the new bureau will be given to rein in credit card debt accounts or if, in fact, Cordray will instead be advised by administration higher ups to concentrate regulatory efforts on the credit card debt relief firms that have pushed the envelope negotiating debt settlement reductions.</p>
<p>&nbsp;</p>
<p>For their part, journalists studying the Director&#8217;s impeccably measured statements and hammering his muted staff for some clue regarding the overall debt relief thrust of the inaugural Consumer Finance Protection endeavors have been thoroughly frustrated to this date by the Bureau&#8217;s tight lipped reluctance to share the merest detail about future policy directions.  Considering the roiling electoral landscape, though, minimizing any data that could be potentially twisted for Republican talking points shouldn&#8217;t require elaboration, especially given the circumstances surrounding Cordray&#8217;s own appointment.  Snuck on board the ship of state by President Obama during a Congressional hiatus absent the traditional process of Senate confirmation, the legitimacy of the Directorship remains a political football certain to be revisited by a bitterly partisan legislature.</p>
<p>&nbsp;</p>
<p>This atmosphere of mistrust and combativeness for its own sake has seeped into so many tendrils of the national government, and consumer advocates are quite reasonably concerned that the Bureau&#8217;s directives will be consequentially compromised and switch targets from the lending community to the debt relief providers.  Lawmakers have been circling the debt settlement industry for years, and, fairly or not, there&#8217;s bound to be elevated scrutiny over any financial counseling maneuver that manipulates the promise of Chapter 7 protection by enlisting proxy agents to suggest the borrowers would be unable to avoid bankruptcy unless the lenders agreed to dissolve a significant portion of their otherwise undisputed claims for reclamation of monetary resources.  Prior inequities of the approach exploited by less than legitimate settlement enterprises have been already mollified by existing statutes, and the Federal Trade Commission has done an effective job separating out the suspicious firms.  The powers granted Consumer Finance Protection bureau were made for greater things.</p>
]]></content:encoded>
      <wfw:commentRss>http://www.totaldebtrelief.net/total-debt-relief-blog/will-new-consumer-finance-protection-bureau-aid-debt-relief/feed/</wfw:commentRss>
      <slash:comments>0</slash:comments>
      <enclosure url="http://podcasts.odiogo.com/get_mp3.mp3?f=/total-debt-relief-blog/Total_Debt_Relief_Blog-Will_New_Consumer_Finance_Protection_Bureau_Aid_Debt_Relief.mp3" length="1802852" type="audio/mpeg" />
    </item>
    <item>
      <title>Negotiation Skills Aid More Than Just Debt Settlement</title>
      <link>http://www.totaldebtrelief.net/total-debt-relief-blog/negotiation-skills-aid-more-than-just-debt-settlement/</link>
      <comments>http://www.totaldebtrelief.net/total-debt-relief-blog/negotiation-skills-aid-more-than-just-debt-settlement/#comments</comments>
      <pubDate>Wed, 02 May 2012 16:42:42 +0000</pubDate>
      <dc:creator>channel</dc:creator>
      <category><![CDATA[Uncategorized]]></category>
      <guid isPermaLink="false">http://www.totaldebtrelief.net/total-debt-relief-blog/?p=1008</guid>
      <description>A hotly contested “miracle” debt solution to credit card debt relief that boasts as many critics as devotees, debt settlement negotiation has been the financial management topic of choice throughout the United States ever since the industry was all but &amp;#8230; &lt;a href="http://www.totaldebtrelief.net/total-debt-relief-blog/negotiation-skills-aid-more-than-just-debt-settlement/"&gt;Continue reading &lt;span class="meta-nav"&gt;&amp;#8594;&lt;/span&gt;&lt;/a&gt;&lt;br&gt;&lt;a type="audio/mpeg" href="http://podcasts.odiogo.com/get_mp3.mp3?f=/total-debt-relief-blog/Total_Debt_Relief_Blog-Negotiation_Skills_Aid_More_Than_Just_Debt_Settlement.mp3"&gt;Click here to play&lt;/a&gt;&lt;br&gt;</description>
      <content:encoded><![CDATA[<p>A hotly contested “miracle” <a title="debt solution" href="http://www.totaldebtrelief.net/debt-solutions/">debt solution</a> to credit card debt relief that boasts as many critics as devotees, debt settlement negotiation has been the financial management topic of choice throughout the United States ever since the industry was all but outlawed four years ago.  A statute added to the fine print of Congressional legislation supposedly meant to restrict telemarketing effectively prevented any debt relief agents specializing in settlement negotiators from billing any clients for services rendered prior to the successful culmination of the repayment process (typically three to five years) or else forgo advertising, telephone communication, and a number of other handy business practices that the federal government has somehow enjoined.  What with the raft of media stories detailing the tragedies of little old ladies who&#8217;d lost everything after giving con artists free rein to run their finances and supposedly handle their debt relief, there was a backlash building among the general public.</p>
<p>At the same time, popular opinion also indulged an essential distrust of the clandestine manner in which the legislators hid the signal regulatory passage amidst a bill targeting phone sales that no elected official in his right mind would ever go on record as opposing, and the corporate banks made no secret of which side they were rooting forward.  Contrary to the expectations of most pundits, though, the companies that had the appropriate cash reserves went into a holding pattern for a period of time and reconstructed under an operating budgetary plan that ably reflected the new statutory restrictions.   In seemingly no time at all, the industry had recovered and, freed from associations with criminal enterprises, emerged stronger than ever before.  Indeed, far from engendering social critiques, the revamped debt relief methodology had become a rallying cry for a host of different strategies.</p>
<p>“I know the whole thing started with the investment traders in New York, back during Black Friday,” said California Pro Finance&#8217;s Caitlyn Mills, a credit card debt relief officer specializing in settlement arrangements, “and those were all guys.  That was the culture on Wall Street, which is why they never really were able to get the same kind of concessions after the first few clients.  I think, honestly, negotiation&#8217;s more of a woman&#8217;s prerogative.  It&#8217;s all about the ability to bend while still asserting your own needs and explaining how best to resolve the conflict.  For people who understand, who really understand, the basics of debt settlement negotiation, there&#8217;s no telling where the technique may be able to help them in day to day life.”</p>
<p>According to Ms. Mills, the skills utilized in debt settlement negotiation could be called upon to argue for advancement in the workplace, more amenable terms in consumer transactions, and even a healthier basis for relationship positioning.  “It all has to do with the simple ability to admit what you really want,” she continued.  “The brilliance of credit card debt relief through negotiation starts out with a fairly simple admission &#8212; that everyone involved wants to avoid bankruptcy as an option &#8212; and, once you get through that part, everything else snaps into focus.  You might have to make some hard sacrifices along the way, but, compared to &#8216;the B word&#8217;, it&#8217;s going to seem like a walk in the park.  Sounds like a cliché, but successful negotiations really do help each side arrive at a positive outcome.”</p>
]]></content:encoded>
      <wfw:commentRss>http://www.totaldebtrelief.net/total-debt-relief-blog/negotiation-skills-aid-more-than-just-debt-settlement/feed/</wfw:commentRss>
      <slash:comments>0</slash:comments>
      <enclosure url="http://podcasts.odiogo.com/get_mp3.mp3?f=/total-debt-relief-blog/Total_Debt_Relief_Blog-Negotiation_Skills_Aid_More_Than_Just_Debt_Settlement.mp3" length="1736984" type="audio/mpeg" />
    </item>
    <item>
      <title>Debt Settlement Is Among Tax Pitfalls For Unwary</title>
      <link>http://www.totaldebtrelief.net/total-debt-relief-blog/debt-settlement-is-among-tax-pitfalls-for-unwary/</link>
      <comments>http://www.totaldebtrelief.net/total-debt-relief-blog/debt-settlement-is-among-tax-pitfalls-for-unwary/#comments</comments>
      <pubDate>Tue, 01 May 2012 15:59:41 +0000</pubDate>
      <dc:creator>channel</dc:creator>
      <category><![CDATA[Uncategorized]]></category>
      <guid isPermaLink="false">http://www.totaldebtrelief.net/total-debt-relief-blog/?p=1006</guid>
      <description>This is the time of year when tax accountants and tax preparers are magically transformed from tedious pencil pushers to riveting fonts of fascinating, useful information.  Everyone loves free advice, after all.   Just in case there’s no handy CPA at &amp;#8230; &lt;a href="http://www.totaldebtrelief.net/total-debt-relief-blog/debt-settlement-is-among-tax-pitfalls-for-unwary/"&gt;Continue reading &lt;span class="meta-nav"&gt;&amp;#8594;&lt;/span&gt;&lt;/a&gt;&lt;br&gt;&lt;a type="audio/mpeg" href="http://podcasts.odiogo.com/get_mp3.mp3?f=/total-debt-relief-blog/Total_Debt_Relief_Blog-Debt_Settlement_Is_Among_Tax_Pitfalls_For_Unwary.mp3"&gt;Click here to play&lt;/a&gt;&lt;br&gt;</description>
      <content:encoded><![CDATA[<p>This is the time of year when <a title="tax debt relief" href="http://www.totaldebtrelief.net/tax/">tax</a> accountants and tax preparers are magically transformed from tedious pencil pushers to riveting fonts of fascinating, useful information.  Everyone loves free advice, after all.   Just in case there’s no handy CPA at your health club or tax lawyer at your workplace, though, here are a couple of the tips these pros would be likely to share if only you could find one who wasn’t buried under a mountain of other free-advice-seeking scroungers.</p>
<p>The first of these tips is really more like a warning.  Here’s the scenario: let’s say a few years ago, you hit a rough patch financially.  Maybe you lost a job, or had a health problem, or got shellacked in the mortgage mess.  Whatever it was, you came out of it with too much credit card debt &#8212; more than you could reasonably be expected to pay.</p>
<p>What to do?  You could have walked away, but you wanted to avoid bankruptcy if at all possible.  You started looking into credit card debt relief programs.  Maybe you could <a title="debt negotiation" href="http://www.totaldebtrelief.net/debt-settlement/debt-negotiation/">negotiate debt</a> with the card issuer to reduce your outstanding principal.</p>
<p>Unbelievably, this worked: you got your debt relief, reducing your outstanding credit card debt from $50,000 to $20,000.  Wiping the sweat from your brow with an audible “Whew,” you prepared to go on with your life.</p>
<p>So far, so good.  Now, fast-forward to tax time.  Uh-oh &#8212; your tax preparer has some bad news.  Remember that $30,000 you convinced your card issuers to forgive?  Well, guess what?  That counts as income.  You’ve gotta pay taxes on it.</p>
<p>Whatever institution it was that structured your debt settlement &#8212; bank, card issuer, and so on &#8212; they should send you a form 1099-C, “Cancellation of Debt” form to let you know how much taxable income you’re on the hook for thanks to the credit card debt relief you managed to arrange.  You’ll have to list this amount on your form 1040.  So be careful!</p>
<p>Here’s a second tip: every year around tax time, you’ll start seeing lots of tax preparers offering “instant refunds.”  The idea is that they do your taxes, figure out how much you’re going to get back, and lend you that amount in exchange for your signing over the rights to your actual refund check &#8212; the one that’s not coming for two months &#8212; to the tax preparer.  It’s like a payday loan, only instead of borrowing against your future paycheck, you’re borrowing against your future tax refund.</p>
<p>Well, what’s wrong with that?  Get some money now, take a trip, do some repairs, pay down some of that credit card debt that’s still hanging around.  It all sounds good, right?</p>
<p>Once  again, though, let the buyer &#8212; or borrower &#8212; beware.  Remember the earlier bit about how these instant refunds are structured like a payday loan?  Well, they resemble payday loans in another way as well: they charge an astronomical rate of interest.</p>
<p>Unsurprisingly, the purveyors of instant refunds don’t advertise this, but most such loans work out to an interest rate of anywhere from fifty to five hundred percent annually.  Unless you really, really need the money right now to avoid bankruptcy or financial ruin, just bite the bullet and wait for your check from Uncle Sam like everybody else.</p>
<p>Hope these tips help your tax season &#8212; and future tax seasons &#8212; go more smoothly.  Knowledge is power!</p>
]]></content:encoded>
      <wfw:commentRss>http://www.totaldebtrelief.net/total-debt-relief-blog/debt-settlement-is-among-tax-pitfalls-for-unwary/feed/</wfw:commentRss>
      <slash:comments>0</slash:comments>
      <enclosure url="http://podcasts.odiogo.com/get_mp3.mp3?f=/total-debt-relief-blog/Total_Debt_Relief_Blog-Debt_Settlement_Is_Among_Tax_Pitfalls_For_Unwary.mp3" length="1772894" type="audio/mpeg" />
    </item>
    <item>
      <title>Concerns Over Debt Relief Lead Economic Worries</title>
      <link>http://www.totaldebtrelief.net/total-debt-relief-blog/concerns-over-debt-relief-lead-economic-worries/</link>
      <comments>http://www.totaldebtrelief.net/total-debt-relief-blog/concerns-over-debt-relief-lead-economic-worries/#comments</comments>
      <pubDate>Mon, 30 Apr 2012 15:59:32 +0000</pubDate>
      <dc:creator>channel</dc:creator>
      <category><![CDATA[Uncategorized]]></category>
      <guid isPermaLink="false">http://www.totaldebtrelief.net/total-debt-relief-blog/?p=1004</guid>
      <description>For the first time in more than four years, the United States economy seems to finally be on the right track, and, should the increases in business investment and gains in employment continue, we may finally be through the eye &amp;#8230; &lt;a href="http://www.totaldebtrelief.net/total-debt-relief-blog/concerns-over-debt-relief-lead-economic-worries/"&gt;Continue reading &lt;span class="meta-nav"&gt;&amp;#8594;&lt;/span&gt;&lt;/a&gt;&lt;br&gt;&lt;a type="audio/mpeg" href="http://podcasts.odiogo.com/get_mp3.mp3?f=/total-debt-relief-blog/Total_Debt_Relief_Blog-Concerns_Over_Debt_Relief_Lead_Economic_Worries.mp3"&gt;Click here to play&lt;/a&gt;&lt;br&gt;</description>
      <content:encoded><![CDATA[<p>For the first time in more than four years, the United States economy seems to finally be on the right track, and, should the increases in business investment and gains in employment continue, we may finally be through the eye of the storm.  Alas, many of the eventual forces which will play a part directing the future of American fiscal policy are not within our nation&#8217;s control.  The ongoing Greek debt relief crisis and subsequent dizzying uncertainties in Europe, to name arguably the most important question mark soon to dominate global finance for better or worse, could plunge international markets into a downward spiral of truly ominous proportions, and we&#8217;re to an unfortunate degree helpless to do more than strenuously suggest a swift and painless resolution</p>
<p>While our dependance upon foreign investment may technically be a trap of our devising, it&#8217;s a little too late at this stage of the game to suddenly cast off the momentum of decades.  Similarly, our political leadership may undoubtedly have done more to divert American industry away from fossil fuels by heightening efficiency standards and creating monetary incentives for businesses to invest in alternative energy sources, the imminent future of the country remains inextricably linked to the price of gasoline.  While this isn&#8217;t the immediate death knell of times past &#8212; a mix (a hybrid, if you will) of consumer trends and vastly improved domestic production has actually rendered the United States an oil exporter,  reversing the flow of more than half a century &#8212; the added revenue of some firms won&#8217;t help others avoid bankruptcy if the cost of a gallon at the pumps climbs above four dollars.</p>
<p>However, from the perspective of some fiscal authorities, one of the greatest threats to American economic health is purely homegrown.  Muddled debt relief &#8212; in particular the inability of a divided national legislature to make any headway whatsoever on a federal budgetary <a title="debt settlement" href="http://www.totaldebtrelief.net/debt-settlement/">debt settlement</a> &#8212; has directly led to the diminished foreign assessments of our financial stability, which has potentially far greater impact than merely our current embarrassments.  While the past summer&#8217;s (wholly unprecedented) downgrade of our Treasury bonds by the Standard &amp; Poor analysts has thus far thankfully not encouraged other arbitrators of equivalent repute to follow their devalued appraisals, we also haven&#8217;t come anywhere close to repairing the growing chasm, and, short of expecting our elected officials to suddenly withdraw their hard won ideological objections and come to a consensus for the good of the country at the probable expense of their political viability, we the people can do nothing but wait and pray that the governmental leadership comes to its senses.</p>
<p>Of course, technically, the American citizens could just decide to vote for less intractable candidates who appreciate the necessity of debt relief come the next turn at the polls, but, even besides the genuine differences of opinion among proud party members, there&#8217;s a real and definable purpose to maintaining delegates with seniority to aid specific local needs.  That doesn&#8217;t mean, however, that the electorate has absolutely no recourse.  Alerting members of Congress about the urgency of a workable debt settlement &#8212; or, at least, papering over the discord to ensure our creditors are paid promptly and without threat of default &#8212; truly does make a difference at the end of the day.  Furthermore, considering the hurdles placed on our monetary stability by the spiraling credit card debt loads owed by United States residents, how better to point the way for the politicians than by engaging in substantive credit card debt relief and putting our own accounts in order?</p>
]]></content:encoded>
      <wfw:commentRss>http://www.totaldebtrelief.net/total-debt-relief-blog/concerns-over-debt-relief-lead-economic-worries/feed/</wfw:commentRss>
      <slash:comments>0</slash:comments>
      <enclosure url="http://podcasts.odiogo.com/get_mp3.mp3?f=/total-debt-relief-blog/Total_Debt_Relief_Blog-Concerns_Over_Debt_Relief_Lead_Economic_Worries.mp3" length="1789854" type="audio/mpeg" />
    </item>
    <item>
      <title>The Rotisserie Baseball Guide To Credit Card Debt Relief</title>
      <link>http://www.totaldebtrelief.net/total-debt-relief-blog/the-rotisserie-baseball-guide-to-credit-card-debt-relief/</link>
      <comments>http://www.totaldebtrelief.net/total-debt-relief-blog/the-rotisserie-baseball-guide-to-credit-card-debt-relief/#comments</comments>
      <pubDate>Fri, 27 Apr 2012 18:37:14 +0000</pubDate>
      <dc:creator>channel</dc:creator>
      <category><![CDATA[Uncategorized]]></category>
      <guid isPermaLink="false">http://www.totaldebtrelief.net/total-debt-relief-blog/?p=1002</guid>
      <description>While anyone thoroughly immersed within the world of fantasy baseball knows full well that there&amp;#8217;s no real comparison to be made between ensuring household fiscal stability and cultivating the right statistical sampling of Major Leaguers to best the teams assembled &amp;#8230; &lt;a href="http://www.totaldebtrelief.net/total-debt-relief-blog/the-rotisserie-baseball-guide-to-credit-card-debt-relief/"&gt;Continue reading &lt;span class="meta-nav"&gt;&amp;#8594;&lt;/span&gt;&lt;/a&gt;&lt;br&gt;&lt;a type="audio/mpeg" href="http://podcasts.odiogo.com/get_mp3.mp3?f=/total-debt-relief-blog/Total_Debt_Relief_Blog-The_Rotisserie_Baseball_Guide_To_Credit_Card_Debt_Relief.mp3"&gt;Click here to play&lt;/a&gt;&lt;br&gt;</description>
      <content:encoded><![CDATA[<p>While anyone thoroughly immersed within the world of fantasy baseball knows full well that there&#8217;s no real comparison to be made between ensuring household fiscal stability and cultivating the right statistical sampling of Major Leaguers to best the teams assembled by likeminded competitors &#8212; managing a triumphant squad both far more important and exponentially more difficult &#8212; the hours spent peering over box scores midst the fantasy trenches may still serve you well when it comes to plotting a season (or five, as needs must) of <a title="debt relief" href="http://www.totaldebtrelief.net/">debt relief</a>.</p>
<p>&nbsp;</p>
<p>After all, the average bread winner won&#8217;t waste a Sunday afternoon sweating out budgetary minutiae or scrutinizing spread sheets for many reasons beyond the boys of summer or the bills of winter.  Equating the twin American obsessions might just make the rigors of credit card debt relief the slightest bit less painful, and, more to the point, any justification for the endless rain delay spent skimming the waiver wire and calculating cumulative earned run averages should come as a much needed reprieve for the long suffering skipper.</p>
<p>&nbsp;</p>
<p>Fantasy baseball, also known as rotisserie league or roto baseball (so named for the slow-cooked chicken joint where a gang of New York sportswriters originated the vague parameters of what&#8217;s become a national pastime nearly outstripping the game itself), depends upon two signal elements for eventual success, and both share more than a nodding acquaintance with the skills prized by debt relief counselors.</p>
<p>&nbsp;</p>
<p>First and foremost, the prospective team owner must select the ideal line up of position players, gamers blending speed and power with an enviable on base percentage, alongside an invulnerable rotation of strikeout machines equally proficient in shut out wins and late inning heroics.  Whether drafting the team or bidding midst auction format, the process requires a firm resolve, solid preparation, and the ability to prioritize need above want.</p>
<p>&nbsp;</p>
<p>In practice, this means cramming to learn a faintly ridiculous base of knowledge about the subject at hand &#8212; base stealing left fielders or summertime utility expenses &#8212; in order to estimate a realistic and reliable budget.  At the same point, once the available resources come into focus, the impossibility of affording all that you want shall tease what may seem like a never-ending succession of torturous choices.  A season of Konerko or a few months of Howard?  A family vacation or a hot water heater?  If you want to avoid bankruptcy or, worse, last place, you&#8217;ll have to learn restraint.</p>
<p>&nbsp;</p>
<p>Alas, despite the most elegantly designed plans seemingly accounting for every potential occurrence, we&#8217;re none of us perfect, and an untimely injury could suddenly leave your roster or revenue stream dangerously weakened.  Here, too, the careful manager knows when to walk off foolish pride and cowboy up under encroaching despair.  There comes a moment when it&#8217;ll simply make good ball sense to fix a gaping hole by negotiating a trade (or, say, debt settlement), however unappetizing the exchange may initially appear.</p>
<p>&nbsp;</p>
<p>Does this mean sacrificing your RBI spitting catcher &#8212; namesake of your team and icon of your desktop &#8212; to short up saves?  Will you need to temporarily cut up your credit cards for a formal reduction in the sums owed?  If it&#8217;s in the best interest of your team and family, you should accept what has to be done and head to the bargaining table before your deficits appear any more evident.  In relief pitching as in debt relief pleading, you always want to deal from strength.</p>
]]></content:encoded>
      <wfw:commentRss>http://www.totaldebtrelief.net/total-debt-relief-blog/the-rotisserie-baseball-guide-to-credit-card-debt-relief/feed/</wfw:commentRss>
      <slash:comments>0</slash:comments>
      <enclosure url="http://podcasts.odiogo.com/get_mp3.mp3?f=/total-debt-relief-blog/Total_Debt_Relief_Blog-The_Rotisserie_Baseball_Guide_To_Credit_Card_Debt_Relief.mp3" length="1776532" type="audio/mpeg" />
    </item>
    <item>
      <title>Spare The Credit Card Debt, Spoil The Child?</title>
      <link>http://www.totaldebtrelief.net/total-debt-relief-blog/spare-the-credit-card-debt-spoil-the-child/</link>
      <comments>http://www.totaldebtrelief.net/total-debt-relief-blog/spare-the-credit-card-debt-spoil-the-child/#comments</comments>
      <pubDate>Thu, 26 Apr 2012 18:29:42 +0000</pubDate>
      <dc:creator>channel</dc:creator>
      <category><![CDATA[Uncategorized]]></category>
      <guid isPermaLink="false">http://www.totaldebtrelief.net/total-debt-relief-blog/?p=999</guid>
      <description>While the very idea of trusting teenagers with credit card debt may sound absurd to many American parents hesitant about allowing their pride and joy outside the house without a muffler and galoshes, financial counselors and debt relief agents have &amp;#8230; &lt;a href="http://www.totaldebtrelief.net/total-debt-relief-blog/spare-the-credit-card-debt-spoil-the-child/"&gt;Continue reading &lt;span class="meta-nav"&gt;&amp;#8594;&lt;/span&gt;&lt;/a&gt;&lt;br&gt;&lt;a type="audio/mpeg" href="http://podcasts.odiogo.com/get_mp3.mp3?f=/total-debt-relief-blog/Total_Debt_Relief_Blog-Spare_The_Credit_Card_Debt_Spoil_The_Child.mp3"&gt;Click here to play&lt;/a&gt;&lt;br&gt;</description>
      <content:encoded><![CDATA[<p>While the very idea of trusting teenagers with credit card debt may sound absurd to many American parents hesitant about allowing their pride and joy outside the house without a muffler and galoshes, financial counselors and debt relief agents have recently begun advising their clients about the potential benefits of allowing our youngest consumers to, so to speak, get their feet wet with unsecured lines of credit under controlled conditions.  After all, twenty first century existence necessarily requires a charge card for a wide range of endeavors, and, though this so often justifies poor spending habits, an early incidence of responsible credit card debt activity will be instrumental to eventually achieving top credit ratings (which could impact everything from the proto consumer&#8217;s residence to employment).</p>
<p>&nbsp;</p>
<p>Of course, the theoretical rewards of co-signing a teen&#8217;s credit card debt rather presumes that the children learn the correct lessons, and many consumer advocates, pointing out the average American head of household&#8217;s nine thousand dollars unsecured debt holdings, argue that we&#8217;ve little reason to presume parental role models would offer anything beyond negative guidance.  For better or (generally) worse, modern American culture has grown to rely upon Visa as a convenience that even now still carries alongside a certain cachet, and children who&#8217;ve watched their parents blithely pull out the plastic countless times throughout the course of maturation are far more apt to remember that reflex than whatever lip service the family figurehead may suddenly pay to conscientious usage.</p>
<p>&nbsp;</p>
<p>“Frankly, most parents, left to their own devices, haven&#8217;t any real idea how to properly explain credit card debt,” said debt relief case manager Nathaniel McRae.  “If you suddenly broach the issue, the most common fall back response would be that the cards should only be used in case of emergency.  That&#8217;s a very mom and dad sort of answer, and we know that they want to make sure the kids aren&#8217;t left stranded.  However, any credit card debt relief analyst would tell you that intertwining charge cards and emergency provisions is a slippery slope toward disaster.  Not only does the context lend itself to easy rationalizations &#8212; you&#8217;d be surprised how quickly a mousy haircut or smudged sneaker can approach crisis proportions &#8212; but, honestly, that runs contrary to proper budgeting.  Credit card debt should only be taken out as previously planned for purpose of credit score maintenance.  <em>Savings</em> are supposed to paper over those bumps in the road.”</p>
<p>&nbsp;</p>
<p>Making matters worse, the one aspect through which the adult perspective might truly provide a unique opportunity &#8212; an open and honest dialogue about the parents&#8217; own credit card debt struggles &#8212; likely does a disservice as the heads of household, understandably embarrassed, dissemble when asked if they&#8217;ve ever run into trouble.  “It&#8217;s the perfect time to terrify the kids,” said McRae, “just throw out a few stories about giving up the car to <a title="avoid bankruptcy" href="http://www.totaldebtrelief.net/bankruptcy/">avoid bankruptcy</a> or braving a lawsuit midst debt settlement, and it&#8217;s absolutely wasted, nine times out of ten.”  McRae, like so many other debt relief professionals, strictly admonishes his own customers to have nothing to do with bringing their children into the world of credit card debt.  “If you&#8217;re worried about their credit, just urge them to save up a grand and put that into a secured card from their bank.  It has exactly the same effect upon credit bureau ratings and actually promotes favorable attitudes toward money management.”  When pressed, however, the debt relief officer admits that he did help his daughter take out her own credit card before she left for college.  “And I told her to just use it for emergencies.  What can I say?  I&#8217;m a dad.”</p>
]]></content:encoded>
      <wfw:commentRss>http://www.totaldebtrelief.net/total-debt-relief-blog/spare-the-credit-card-debt-spoil-the-child/feed/</wfw:commentRss>
      <slash:comments>0</slash:comments>
      <enclosure url="http://podcasts.odiogo.com/get_mp3.mp3?f=/total-debt-relief-blog/Total_Debt_Relief_Blog-Spare_The_Credit_Card_Debt_Spoil_The_Child.mp3" length="1900876" type="audio/mpeg" />
    </item>
    <item>
      <title>Prevalent Rumors About Credit Card Debt pt 1</title>
      <link>http://www.totaldebtrelief.net/total-debt-relief-blog/prevalent-rumors-about-credit-card-debt-pt-1/</link>
      <comments>http://www.totaldebtrelief.net/total-debt-relief-blog/prevalent-rumors-about-credit-card-debt-pt-1/#comments</comments>
      <pubDate>Wed, 25 Apr 2012 18:29:17 +0000</pubDate>
      <dc:creator>channel</dc:creator>
      <category><![CDATA[Uncategorized]]></category>
      <guid isPermaLink="false">http://www.totaldebtrelief.net/total-debt-relief-blog/?p=997</guid>
      <description>1)      Life After Debt  After a triumphant voyage of credit card debt relief, the natural inclination of any former borrower should be to cast aside all implements of unsecured obligations in fear of accumulating further burdens, but, despite the (thoroughly &amp;#8230; &lt;a href="http://www.totaldebtrelief.net/total-debt-relief-blog/prevalent-rumors-about-credit-card-debt-pt-1/"&gt;Continue reading &lt;span class="meta-nav"&gt;&amp;#8594;&lt;/span&gt;&lt;/a&gt;&lt;br&gt;&lt;a type="audio/mpeg" href="http://podcasts.odiogo.com/get_mp3.mp3?f=/total-debt-relief-blog/Total_Debt_Relief_Blog-Prevalent_Rumors_About_Credit_Card_Debt_pt_1.mp3"&gt;Click here to play&lt;/a&gt;&lt;br&gt;</description>
      <content:encoded><![CDATA[<p><strong>1)      </strong><strong>Life After Debt</strong></p>
<p><strong> </strong>After a triumphant voyage of <a title="credit card debt" href="http://www.totaldebtrelief.net/credit-card-debt/">credit card debt relief</a>, the natural inclination of any former borrower should be to cast aside all implements of unsecured obligations in fear of accumulating further burdens, but, despite the (thoroughly understandable) reflex, consumers with a fairly confident grasp upon their newly strengthened budgetary discipline should think twice before cutting up the plastic.  Even if you truly never again plan to depend upon charge cards &#8212; and, regardless of the wish to dispel temptation, emergencies befall the best of families &#8212; that doesn&#8217;t mean there&#8217;s no point whatsoever toward maintaining decent credit ratings.  If there&#8217;s the slightest chance that you may one day wish to purchase another house with aid of financing or help your children qualify for school loans, why not keep scores near the upper register if at all possible?</p>
<p>&nbsp;</p>
<p>Certainly, paying down the credit card debt balances will help tremendously, but debt relief veterans who immediately cancel their existing accounts won&#8217;t possibly qualify for the same scores as those borrowers maintaining cordial relations with lenders.  In a bit of tragic irony, owing a noticeable sum helps matters as well.  It&#8217;s all neither fair nor unfair, the scoring matrix was devised after analysts perused the statistical predilections of countless consumers.  If the potential loan applicants who repaid their obligations in full and canceled their accounts proved less likely to afford compensation the second time around, there&#8217;s no use arguing the point.  Bite the bullet and borrow the slightest bit each year to keep your scores flying high: just make sure you don&#8217;t work too hard demonstrating account activity.</p>
<p><strong> </strong></p>
<p><strong>2)      </strong><strong>Cross Checking</strong></p>
<p><strong> </strong></p>
<p>As most Americans know by now, the powers that be determining the Fair Isaacs credit scoring logarithms place a negative value upon successive attempts at financing.  Each time a new lender runs a formal credit check through the reporting bureaus, the prospective borrower&#8217;s numerical ratings will diminish by fifteen points for a period of ninety days.  This is one instance in which popular rumors may be thought to have had a beneficial influence.  Certainly, potential home owners who refrain from simultaneously sampling a dozen mortgage loan officers in search of the best deal &#8212; and, by doing so, guaranteeing themselves a sudden plunge in credit ratings that would invalidate any possible offer &#8212; have the word on the street to thank for the responsible care and tending of their scores.</p>
<p>&nbsp;</p>
<p>&#8212;- Consumers hoping to drive their scores downward in order to achieve a proper debt settlement, on the other hand, should still talk with a debt relief professional prior to any attempts at &#8216;helping&#8217; their situation.  Recent entreaties to borrowing would effectively avoid bankruptcy protection for the next calendar year, and this has a decidedly chilling effect upon settlement negotiations.</p>
<p>&nbsp;</p>
<p>While all of the above may be true, though, this does not intrinsically mean that each stab at a new credit card debt account would automatically lower the applicant&#8217;s overall scores.  The fifteen points will be subtracted, absent the most extraordinary circumstances.  However, if the credit check results in a lender&#8217;s approval of a new and unoccupied account balance that pushes the debt ratio (existing obligations divided by available spending limits) into a more aspirational percentage, the resultant change could well be a net improvement.  Obviously, in the long run, you&#8217;ll still be better off eliminating credit card debt altogether, but, under specific scenarios, there might be a reasonable excuse for raising the ratings by any means necessary.</p>
]]></content:encoded>
      <wfw:commentRss>http://www.totaldebtrelief.net/total-debt-relief-blog/prevalent-rumors-about-credit-card-debt-pt-1/feed/</wfw:commentRss>
      <slash:comments>0</slash:comments>
      <enclosure url="http://podcasts.odiogo.com/get_mp3.mp3?f=/total-debt-relief-blog/Total_Debt_Relief_Blog-Prevalent_Rumors_About_Credit_Card_Debt_pt_1.mp3" length="1833493" type="audio/mpeg" />
    </item>
    <item>
      <title>The Generation Gap Complicating Credit Card Debt Relief</title>
      <link>http://www.totaldebtrelief.net/total-debt-relief-blog/the-generation-gap-complicating-credit-card-debt-relief/</link>
      <comments>http://www.totaldebtrelief.net/total-debt-relief-blog/the-generation-gap-complicating-credit-card-debt-relief/#comments</comments>
      <pubDate>Tue, 17 Apr 2012 20:50:19 +0000</pubDate>
      <dc:creator>channel</dc:creator>
      <category><![CDATA[Uncategorized]]></category>
      <guid isPermaLink="false">http://www.totaldebtrelief.net/total-debt-relief-blog/?p=994</guid>
      <description>To a certain extent, over confidence and a reckless disregard of others&amp;#8217; experiences should be expected as a natural consequence of youth &amp;#8212; as well as an integral component of capitalism &amp;#8212; and economic crises always shock the children of &amp;#8230; &lt;a href="http://www.totaldebtrelief.net/total-debt-relief-blog/the-generation-gap-complicating-credit-card-debt-relief/"&gt;Continue reading &lt;span class="meta-nav"&gt;&amp;#8594;&lt;/span&gt;&lt;/a&gt;&lt;br&gt;&lt;a type="audio/mpeg" href="http://podcasts.odiogo.com/get_mp3.mp3?f=/total-debt-relief-blog/Total_Debt_Relief_Blog-The_Generation_Gap_Complicating_Credit_Card_Debt_Relief.mp3"&gt;Click here to play&lt;/a&gt;&lt;br&gt;</description>
      <content:encoded><![CDATA[<p>To a certain extent, over confidence and a reckless disregard of others&#8217; experiences should be expected as a natural consequence of youth &#8212; as well as an integral component of capitalism &#8212; and economic crises always shock the children of privilege upon some level.  It&#8217;s one thing to know that what goes up most come down, in theoretical terms, but even the most learned student of history&#8217;s still a creature of experience.  Once the world&#8217;s largest corporations began offering successively greater amounts of revolving credit card debt lines to college kids without assets or prior employment (and after the federal government implicitly promoted the practice through <a title="tax debt relief" href="http://www.totaldebtrelief.net/tax/">tax</a> breaks gifted heavy borrowers), consumers stopped worrying about their accumulated burdens, and they never saw how ill prepared they&#8217;d be in the event of a recession.</p>
<p>“That&#8217;s what made these last few years so devastating for so many people,” said Debra Wailing, “it just really underlined how close most of us were to the edge, regardless of our tax brackets.”  An account supervisor at a Seattle area <a title="debt settlement" href="http://www.totaldebtrelief.net/debt-settlement/">debt settlement</a> firm and former mortgage loan officer who herself spent almost nine months on unemployment following the industry downturn,Wailing couldn&#8217;t help but take notice of the coming storm well in advance of most twenty something professionals, but forewarned isn&#8217;t always forearmed, at least where foreclosure is concerned.  Arriving at her office each morning to face a new round of increasingly desperate messages from past clients, she soon came to realize the bubble aiding her industry&#8217;s steady rise was just about to burst, but her own personal debt holdings were so numerous and interlinked that she couldn&#8217;t do much more than sit back and watch the carnage erupt.</p>
<p>“Once you get used to lugging around student loans and credit card debt, you just start thinking about the minimums like any other monthly utility payment and forget about trying full on debt relief altogether.  Maybe 2007 wasn&#8217;t nearly so bad as what people had to go through in the 70s and 80s, but, talking with my parents and their friends, they didn&#8217;t have these massive burdens to worry about once times got tight.  They only had credit cards to use in case of a real household emergency, like keeping the lights on and making sure the kids got fed even if they were laid off all of a sudden and ran through their savings account before landing another job.  They had savings!”</p>
<p>Wailing admits she was part of the larger problem throughout her six year tenure at one of the Pacific Northwest&#8217;s largest residential mortgage lenders, though not by her own volition.  “It wasn&#8217;t like I was trying to scam anyone out of their properties.  Starting out, most of the home owners that I worked with were friends from school.  They were all drowning in credit card debt, which seemed totally normal, and, at the time, it did make mathematical sense to work out some kind of credit card debt relief consolidation program rather than just let the equity sit there gathering dust.  It wasn&#8217;t anything I didn&#8217;t do myself, you know?  I guess, in retrospect, the adjustable rates &#8212; all hooked around a balloon kicker that jumped up the interest two points after seven years &#8212; were a little dangerous, but I just thought that&#8217;d force my butt into gear when the time to pay everything off got close.  Worst case, I&#8217;d just eat the bill for another refinance.  The idea that I couldn&#8217;t get more debt to avoid bankruptcy,” she sighed, “never even entered my mind.”</p>
]]></content:encoded>
      <wfw:commentRss>http://www.totaldebtrelief.net/total-debt-relief-blog/the-generation-gap-complicating-credit-card-debt-relief/feed/</wfw:commentRss>
      <slash:comments>0</slash:comments>
      <enclosure url="http://podcasts.odiogo.com/get_mp3.mp3?f=/total-debt-relief-blog/Total_Debt_Relief_Blog-The_Generation_Gap_Complicating_Credit_Card_Debt_Relief.mp3" length="1730939" type="audio/mpeg" />
    </item>
  </channel>
</rss>
<!-- 584963 -->
<!-- Generated by Odiogobot V5.309 / http://www.odiogo.com -->
