<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de">
<head>
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
<meta http-equiv="content-script-type" content="text/javascript" />
<meta http-equiv="content-style-type" content="text/css" />
<meta name="Language" content="de" />
<meta name="Keywords" content="WDR 2, wdr2, startseite, home, homepage, start"/>
<meta name="Description" content="wdr2.de ist das programmbegleitende Internetangebot der WDR-Radiowelle WDR 2. Es bietet die aktuellen Nachrichten des Tages und zusätzliche Informationen in Text,Bild und Audio sowie umfassende Berichte und Hintergründe zu aktuellen Themen."/>
<meta name="Author" content="Akinci"/>
<meta name="DC.Rights" content="Nur WDR"/>
<meta name="Publisher" content="Westdeutscher Rundfunk" />
<meta http-equiv="expires" content="900" />
<meta name="DC.Date" content="2012-06-07T00:00+02:00" />
<meta name="robots" content="index,follow,noarchive" />
<link rel="start" href="http://www1.wdr.de/themen/" title="Startseite WDR.de" />
<link rel="bookmark" href="http://www.wdr.de/tv/" title="WDR Fernsehen" />
<link rel="bookmark" href="http://www.wdr.de/radio/" title="WDR Radioprogramme" />
<link rel="bookmark" href="http://www.wdr.de/themen/homepages/epg.jhtml" title="WDR Programmvorschau" />
<link rel="bookmark" href="http://www.wdr.de/unternehmen/" title="Informationen über das Unternehmen WDR" />
<link rel="bookmark" href="#wrapper" title="Zum Seitenanfang" />
<link rel="bookmark" href="#content" title="Zum Seiteninhalt" />
<link rel="bookmark" href="http://www1.wdr.de/themen/global/impressum/" title="Impressum" />
<link rel="search" href="http://www1.wdr.de/themen/suche/" title="Suche im WDR Online Angebot" />
<link rel="help" href="http://www1.wdr.de/themen/hilfe/" title="Hilfe zur Bedienung und Orientierung" />
<link rel="copyright" href="http://www1.wdr.de/themen/hilfe/urheberrecht102.html" title="Copyright" />
<link rel="icon" href="/resources/img/logos/favicon.ico" type="image/ico" />
<link rel="shortcut icon" href="/resources/img/logos/favicon.ico" type="image/ico" />
<link rel="alternate" type="application/rss+xml" title="RSS" href="/startseite100.feed" />
<link rel="stylesheet" href="/resources/css/basic.min.css" type="text/css" />
<!--[if gt IE 6 & lt IE 9]>
<link rel="stylesheet" href="/resources/css/global.min.css" type="text/css" />
<link rel="stylesheet" href="/resources/css/ie.min.css" type="text/css" />
<![endif]-->
<!--[if gte IE 9]>
<link rel="stylesheet" href="/resources/css/global.min.css" type="text/css" />
<![endif]-->
<!--[if !IE]> <-->
<link rel="stylesheet" media="all" href="/resources/css/global.min.css" type="text/css" id="cssGlobal" />
<link rel="stylesheet" href="/resources/css/map.css" type="text/css"/>
<!--> <![endif]-->
<script type="text/javascript">
<!-- <![CDATA[
var galleryObjArr = [];
document.writeln('<style type="text/css">@import "/resources/css/js.min.css";<\/style>');
// ]]> -->
</script>
<title>WDR 2 Der Sender</title>
</head>
<body>
<!--googleoff: index-->
<div id="wrapper">
<div id="bgImageCont">
<ul id="skipLinks">
<li><a href="#content">zum Inhalt</a></li>
<li><a href="#navigation">zur Navigation</a></li>
<li><a href="#search">zur Suche</a></li>
</ul>
<!--[if lt IE 7]>
<p id="ieAlert">
Lieber Nutzer,<br />
leider nutzen Sie eine veraltete Version Ihres Browsers. Deshalb können die an dieser Stelle vorgesehenen Inhalte nicht korrekt dargestellt werden. Bitte aktualisieren Sie auf eine aktuelle Version.
Unter <a href="http://www.browserchoice.eu/">http://www.browserchoice.eu/</a> stehen alternative Browser zur Verfügung.
Für eine Installation benötigen Sie gegebenenfalls Administrator-Rechte.</p>
</p>
<![endif]-->   <hr />
<div id="banner">
<img src="/resources/img/logos/wdr2.gif" alt="WDR 2" title="" id="wdr2Logo" />
<img src="/resources/img/logos/wdr2_banner.jpg" alt="WDR 2 Banner" title="" width="1000" height="80" id="wdr2Banner" />
</div>
<div class="printLocation" title="URL: http://www.wdr2.de/startseite100.html">&nbsp;</div>
<hr/>
<p class="hidden">Sie befinden sich hier:</p>
<ul id="breadCrumb" class="">
<li><a href="http://www.wdr.de/radio">Radio</a></li>
<li>WDR 2</li>
</ul>
<!--googleon: index-->
<div id="content" class="isCollection">
<!-- wdr3.de -->
<hr/>
<div id="contentRow">
<h1 class="hidden">Startseite: WDR 2 Der Sender</h1>
<div class="teaserContOuter">
<div class="topTeaserCont std">
<div class="teaser">
<dl class="illustrationCont">
<dt><img src="/politik/strampler100_v-TeaserAufmacher.jpg"    title="Bildrechte: pa / dpa" alt="Strampler auf der Wäscheleine: Das Betreuungsgeld sorgt weiter für Streit" height="288" width='512' />
</dt>
</dl>
<div class="teaserText">
<h2>
<span>Kabinett beschließt Betreuungsgeld<span class="hidden">:</span></span>
Streit geht weiter
</h2>
<p>
Monatelang hat die Koalition über das Betreuungsgeld gestritten. Jetzt soll das Gesetz binnen drei Wochen vom Bundestag verabschiedet werden. Die SPD will das Vorhaben im Bundesrat stoppen.
<a href="/politik/betreuungsgeld170.html" >
<span class="invisible">Kabinett beschließt Betreuungsgeld: Streit geht weiter</span>
<span>[mehr]</span>
</a>
</p>
</div>
</div>

<ul class="linkList"><li class="audioLink">
<a href="/musik/audionrwfdpcheflindnerrechtfertigtebeiwdrdiezustimmungzumbetreuungsgeldmitvertragstreue100-audioplayer.html" >
<span class="hidden">Audio: </span>
NRW-FDP-Chef Lindner rechtfertigte bei WDR 2 die Zustimmung zum Betreuungsgeld mit "Vertragstreue" (06.06.2012)
</a>
<span class="audioMeta">Christian Lindner (NRW-FDP-Chef) / Helmut Rehmsen, WDR 2 Morgenmagazin</span>
</li>
<li class="audioLink">
<a href="/musik/audiokabinettbeschliesstbetreuungsgeld100-audioplayer.html" >
<span class="hidden">Audio: </span>
Kabinett beschließt Betreuungsgeld (06.06.2012)
</a>
<span class="audioMeta">Lioba Werrelmann, WDR 2 Morgenmagazin</span>
</li>
<li class="neutral">
<a href="/politik/klartext/betreuungsgeld174.html" >
WDR 2 Klartext zum Betreuungsgeld
</a>
</li></ul>

</div>
<div class="teaserCont radioBox">
<ul class="boxSwitch">
<li id="a1-1" class="opened">
<h2>Jetzt im Programm</h2>
<div class="currentSongCont">
<!-- ajaxURL: /musik/playlist_neu100-akkordeon-playlist.html -->
<p>
<span class="colored">Jetzt läuft</span> <strong>Bruno Mars:</strong> Just The Way You Are
</p>
<p>
<a href="http://www.wdr2.de/musik/playlist116.html">Ausführliche Playlist und Titelsuche</a>
</p>
</div>
<div class="scrollContainer">
<!-- ajaxURL: /vorlagen/jetztimprogramm102-akkordeon-jetztimprogramm_wn-2.html -->
<table class="program" summary="Tabelle mit dem WDR 2 Programm von heute nach Uhrzeit">
<caption>WDR 2 Programm von heute</caption>
<thead>
<tr>
<th scope="col" id="jip-2-a1-1TimeId">Uhrzeit</th>
<th scope="col" id="jip-2-a1-1BroadcastId">Sendung</th>
</tr>
</thead>
<tbody>
<tr>
<th scope="row" headers="jip-2-a1-1TimeId">
00.03
<span class="hidden"> Uhr</span>
</th>
<td headers="jip-2-a1-1BroadcastId" >
<a href="http://www.wdr2.de/sendungen/ndr2undwdr2dienacht/index.html"><strong>NDR 2 und WDR 2: Die Nacht</strong></a>
</td>
</tr>
<tr>
<th scope="row" headers="jip-2-a1-1TimeId">
06.00
<span class="hidden"> Uhr</span>
</th>
<td headers="jip-2-a1-1BroadcastId" >
<a href="http://www.wdr.de/radio/home/nachrichten/index.phtml"><strong>Nachrichten, Wetter</strong></a>
</td>
</tr>
<tr>
<th scope="row" headers="jip-2-a1-1TimeId">
06.05
<span class="hidden"> Uhr</span>
</th>
<td headers="jip-2-a1-1BroadcastId" >
<a href="http://www.wdr2.de/sendungen/wdr2derfeiertag/derfeiertag100.html"><strong>WDR 2 Der Feiertag</strong></a>
<span class="subText">
mit
<a href="http://www.wdr2.de/moderatoren/simon100.html">Johannes Simon</a>
</span>
<img src="/musik/bildjohannessimon100_v-TeaserKlein.jpg"    title="Bildrechte: WDR" alt="Johannes Simon" height="82" width='146' />
</td>
</tr>
<tr>
<th scope="row" headers="jip-2-a1-1TimeId">
09.00
<span class="hidden"> Uhr</span>
</th>
<td headers="jip-2-a1-1BroadcastId" >
<a href="http://www.wdr.de/radio/home/nachrichten/index.phtml"><strong>Nachrichten, Wetter</strong></a>
</td>
</tr>
<tr>
<th scope="row" headers="jip-2-a1-1TimeId">
09.05
<span class="hidden"> Uhr</span>
</th>
<td headers="jip-2-a1-1BroadcastId" >
<a href="http://www.wdr2.de/sendungen/wdr2derfeiertag/derfeiertag100.html"><strong>WDR 2 Der Feiertag</strong></a>
<span class="subText">
mit
<a href="http://www.wdr2.de/moderatoren/hoepker100.html">Gudrun Höpker</a>
</span>
<img src="/musik/bildgudrunhoepker100_v-TeaserKlein.jpg"    title="Bildrechte: WDR" alt="Gudrun Höpker" height="82" width='146' />
</td>
</tr>
<tr>
<th scope="row" headers="jip-2-a1-1TimeId">
13.00
<span class="hidden"> Uhr</span>
</th>
<td headers="jip-2-a1-1BroadcastId" >
<a href="http://www.wdr.de/radio/home/nachrichten/index.phtml"><strong>Nachrichten, Wetter</strong></a>
</td>
</tr>
<tr>
<th scope="row" headers="jip-2-a1-1TimeId">
13.04
<span class="hidden"> Uhr</span>
</th>
<td headers="jip-2-a1-1BroadcastId" >
<a href="http://www.wdr2.de/sendungen/wdr2derfeiertag/derfeiertag100.html"><strong>WDR 2 Der Feiertag</strong></a>
<span class="subText">
mit
<a href="http://www.wdr2.de/moderatoren/brackmann100.html">Cathrin Brackmann</a>
</span>
<img src="/moderatoren/bildcathrinbrackmann100_v-TeaserKlein.jpg"    title="Bildrechte: WDR" alt="Cathrin Brackmann" height="82" width='146' />
</td>
</tr>
<tr>
<th scope="row" headers="jip-2-a1-1TimeId">
17.00
<span class="hidden"> Uhr</span>
</th>
<td headers="jip-2-a1-1BroadcastId" >
<a href="http://www.wdr.de/radio/home/nachrichten/index.phtml"><strong>Nachrichten, Wetter</strong></a>
</td>
</tr>
<tr>
<th scope="row" headers="jip-2-a1-1TimeId">
17.05
<span class="hidden"> Uhr</span>
</th>
<td headers="jip-2-a1-1BroadcastId" >
<a href="http://www.wdr2.de/sendungen/wdr2dertag/index.html"><strong>WDR 2 Der Tag</strong></a>
<span class="subText">
mit
<a href="http://www.wdr2.de/moderatoren/vogt100.html">Stefan Vogt</a>
</span>
<img src="/musik/bildstefanvogt100_v-TeaserKlein.jpg"    title="Bildrechte: WDR" alt="Stefan Vogt" height="82" width='146' />
</td>
</tr>
<tr>
<th scope="row" headers="jip-2-a1-1TimeId">
18.00
<span class="hidden"> Uhr</span>
</th>
<td headers="jip-2-a1-1BroadcastId" >
<a href="http://www.wdr.de/radio/home/nachrichten/index.phtml"><strong>Nachrichten, Wetter</strong></a>
</td>
</tr>
<tr>
<th scope="row" headers="jip-2-a1-1TimeId">
18.05
<span class="hidden"> Uhr</span>
</th>
<td headers="jip-2-a1-1BroadcastId" >
<a href="http://www.wdr2.de/sendungen/wdr2musikclub/index.html"><strong>WDR 2 Musikclub</strong></a>
<span class="subText">
mit
<a href="http://www.wdr2.de/moderatoren/vieth100.html">Udo Vieth</a>
</span>
<img src="/musik/bildudovieth100_v-TeaserKlein.jpg"    title="Bildrechte: WDR" alt="Udo Vieth" height="82" width='146' />
</td>
</tr>
<tr>
<th scope="row" headers="jip-2-a1-1TimeId">
00.00
<span class="hidden"> Uhr</span>
</th>
<td headers="jip-2-a1-1BroadcastId" >
<a href="http://www.wdr.de/radio/home/nachrichten/index.phtml"><strong>Nachrichten, Wetter</strong></a>
</td>
</tr>
</tbody>
</table>
</div>
<ul><li><a class="studioMail" href="/kontakt/mail-ins-studio100.html">Mail ins Studio</a></li></ul>
</li>
<li id="a1-2">
<!-- ajaxURL: /streams100-akkordeonLinkliste_akk-a1-2.html,/regionalstreams100-akkordeonLinkliste_akk-a1-2.html -->
<a href="/startseite100_akk-a1-2.html#a1-2">Jetzt WDR 2 hören</a></li>
<li id="a1-3">
<!-- ajaxURL: /podcast102-akkordeonLinkliste_akk-a1-3.html,/podcast144-akkordeonLinkliste_akk-a1-3.html,/podcast146-akkordeonLinkliste_akk-a1-3.html,/podcast148-akkordeonLinkliste_akk-a1-3.html,/podcast150-akkordeonLinkliste_akk-a1-3.html,/podcast152-akkordeonLinkliste_akk-a1-3.html,/podcast154-akkordeonLinkliste_akk-a1-3.html,/podcast156-akkordeonLinkliste_akk-a1-3.html -->
<a href="/startseite100_akk-a1-3.html#a1-3">Podcast</a></li>
<li id="a1-4"class="last">
<!-- ajaxURL: /frequenzen118-akkordeonLinkliste_akk-a1-4.html,/frequenzen100-akkordeonLinkliste_akk-a1-4.html,/frequenzen102-akkordeonLinkliste_akk-a1-4.html,/frequenzen104-akkordeonLinkliste_akk-a1-4.html,/frequenzen106-akkordeonLinkliste_akk-a1-4.html,/frequenzen108-akkordeonLinkliste_akk-a1-4.html,/frequenzen110-akkordeonLinkliste_akk-a1-4.html,/frequenzen112-akkordeonLinkliste_akk-a1-4.html,/frequenzen114-akkordeonLinkliste_akk-a1-4.html,/frequenzen116-akkordeonLinkliste_akk-a1-4.html -->
<a href="/startseite100_akk-a1-4.html#a1-4">Frequenzen</a></li>
</ul>
</div>
</div>
<hr/>
<div class="teaserContOuter">
<div class="teaserCont std">
<div class="teaser">
<img src="/musik/oceana100_v-TeaserNormal.jpg"    title="Bildrechte: dpa" alt="Die Sängerin Oceana mit dem EM-Maskottchen auf der Bühne" height="174" width='310' />
<div class="teaserText">
<h2>
<span>Fußballhymnen<span class="hidden">:</span></span>
Kicken, singen, swingen
</h2>
<p>
So eine Fußball-Europameisterschaft hat auch musikalisch Einiges zu bieten. Fußball und Musik gehörten ja schon immer zusammen - auch wenn sich das früher noch etwas anders anhörte als heute.
<a href="/musik/fussball_musik100.html" >
<span class="invisible">Fußballhymnen: Kicken, singen, swingen</span>
<span>[mehr]</span>
</a>
</p>
</div>
</div>
<ul class="linkList"><li class="neutral">
<a href="/sport/fussball_europameisterschaft100.html" >
Schwerpunkt: UEFA EURO 2012
</a>
</li></ul>

</div>
<div class="teaserCont">
<div class="teaser">
<img src="/sport/uefa_euro_2012/ukraine116_v-TeaserNormal.jpg"    title="Bildrechte: dpa" alt="Unabhängigkeitsplatz in Kiew/Ukraine" height="174" width='310' />
<div class="teaserText">
<h2>
<span>Reiseknigge Ukraine<span class="hidden">:</span></span>
Schnaps und schwere Speisen
</h2>
<p>
Die Fußballfans strömen in die Ukraine. Moskau-Korrespondent Stephan Laack hat einen Reiseknigge zusammengestellt, wie man auch außerhalb der Stadien von Donezk oder Kiew nicht ins Abseits gerät.
<a href="/sport/uefa_euro_2012/verhaltenstipps100.html" >
<span class="invisible">Reiseknigge Ukraine: Schnaps und schwere Speisen</span>
<span>[mehr]</span>
</a>
</p>
</div>
</div>

</div>
<div class="teaserCont std noBorder last">
<div class="regionalTeaser" id="news">
<h2>
<a href="http://www.wdr.de/radio/home/nachrichten/index.phtml" >WDR 2 Nachrichten</a>
</h2>
<ul class="linkList">
<li class="audioLink">
<a href="/admin/wdrzweinachrichten100-audioplayer.html" >
<span class="hidden">Audio: </span>WDR 2 Nachrichten</a>
</li>
<li>
<a href="http://www.tagesschau.de" >
Weitere Informationen auf tagesschau.de
</a>
</li>
</ul>
</div>
<div class="regionalTeaser" id="weather">
<h2>
<a href="http://www.wdr.de/themen/wetter/nrw/heute.jhtml" >Wetter</a>
</h2>
<ul class="linkList">
<li class="staticWeatherLink">
<a href="http://www.wdr.de/themen/wetter/nrw/heute.jhtml" >
Vorhersage für <acronym title="Nordrhein-Westfalen">NRW</acronym>, 07.06.2012
</a>
</li>
</ul>
</div>
<div class="regionalTeaser last" id="traffic">
<h2>
<a href="http://www.wdr.de/verkehrslage/" >Verkehrslage</a>
</h2>
<p>Kein Stau gemeldet in <acronym title="Nordrhein-Westfalen">NRW</acronym></p>
<p>
WDR 2 Staunummer:
<strong>0221 1680 3050</strong>
</p>
</div>
</div>
</div>
<hr/>
<div class="teaserContOuter">
<div class="teaserCont">
<div class="teaser">
<img src="/unterhaltung/comedy/wdr2popolski100_v-TeaserNormal.jpg"    title="Bildrechte: wdr" alt="Die Popolskis mit WDr 2 Logo" height="174" width='310' />
<div class="teaserText">
<h2>
<span>Live aus der Plattenbau in Zabrze!<span class="hidden">:</span></span>
Der Popolski EM Studio
</h2>
<p>
Die Berichterstattung über die "UEFA EURO 2012" (Sprich: EM) ist gefährdet! Aufgrund von Schwächen in unserer Hackerabwehr drohen tägliche abrupte Eingriffe "Der Familie Popolski" in das laufende Programm.
<a href="/unterhaltung/comedy/popolski104.html" >
<span class="invisible">Live aus der Plattenbau in Zabrze!: Der Popolski EM Studio</span>
<span>[mehr]</span>
</a>
</p>
</div>
</div>

</div>
<div class="teaserCont std">
<div class="teaser">
<img src="/kultur/kino/kochenistchefsache106_v-TeaserNormal.jpg"    title="Bildrechte: dpa / Senator Filmverleih" alt="Filmszene aus &#034;Kochen ist Chefsache&#034;" height="174" width='310' />
<div class="teaserText">
<h2>
<span>Der WDR 2 Kinotipp<span class="hidden">:</span></span>
Aktuelle Filme im Überblick
</h2>
<p>
Neu im Kino: Die Komödie "Kochen ist Chefsache" mit Jean Reno, der Abenteuerfilm "Wolfsbrüder" und die Dokumentation "Knistern der Zeit - Christoph Schlingensief und sein Operndorf in Burkina Faso".
<a href="http://www.wdr2.de/kultur/kino/kino100.html" >
<span class="invisible">Der WDR 2 Kinotipp: Aktuelle Filme im Überblick</span>
<span>[mehr]</span>
</a>
</p>
</div>
</div>
<ul class="linkList"><li class="wdr">
<a href="http://www.wdr.de/radio/home/podcasts/channelausspielung.phtml?channel=wdr2_kino" >
WDR 2 Kino als Podcast: Aktuelle Filmkritiken zum Mitnehmen
</a>
</li>
<li class="audioLink">
<a href="/musik/audioneuimkinokochenistchefsachewolfsbruederknisternderzeit100-audioplayer.html" >
<span class="hidden">Audio: </span>
Neu im Kino: "Kochen ist Chefsache", "Wolfsbrüder", "Knistern der Zeit" (06.06.2012)
</a>
<span class="audioMeta">Andrea Burtz, WDR 2 Morgenmagazin</span>
</li></ul>

</div>
<div class="teaserCont std last">
<div class="teaser">
<img src="/home/nrw_panorama100_v-TeaserNormal.jpg"    title="Bildrechte: Montage: dpa, WDR" alt="NRW Panorama mit Sehenswürdigkeiten des Landes" height="174" width='310' />
<div class="teaserText">
<h2>
<span>Nachrichten aus Ihrer Region<span class="hidden">:</span></span>
WDR 2 NRW Infos
</h2>
<p>
Täglich aktuelle und kompakte Informationen aus allen Teilen Nordrhein Westfalens.
<a href="/nrw/studios104.html" >
<span class="invisible">Nachrichten aus Ihrer Region: WDR 2 NRW Infos</span>
<span>[mehr]</span>
</a>
</p>
</div>
</div>
<ul class="linkList"><li class="neutral">
<a href="http://www1.wdr.de/themen/infokompakt/nachrichten/nrwkompakt/nrwkompakt6956.html" >
Teutoburger Wald: Tauziehen um zweiten Nationalpark geht weiter
[WDR]
</a>
</li>
<li class="neutral">
<a href="http://www1.wdr.de/themen/infokompakt/nachrichten/nrwkompakt/nrwkompakt6954.html" >
Prozessauftakt: 87-Jähriger soll Nachbarin erschossen haben
[WDR]
</a>
</li>
<li class="neutral">
<a href="http://www1.wdr.de/themen/infokompakt/nachrichten/nrwkompakt/nrwkompakt6964.html" >
Nach Explosion: Bielefelder Unglückshaus bekommt Holzkorsett
[WDR]
</a>
</li></ul>

</div>
</div>
<hr/>
<div class="stripTeaserSix" id="teaserSix1">
<ul class="teaserContOuter">
<li class="teaserCont firstImgTeaser">
<img src="http://www1.wdr.de/themen/archiv/stichtag/stichtagjunizwoelf130_v-TeaserKlein.jpg"    title="Bildrechte: dpa" alt="Jean Harlow" height="82" width='146' />
<a href="http://www1.wdr.de/themen/archiv/stichtag/stichtag6676.html" class="textPageLink">
Stichtag: 1937 - Jean Harlow stirbt in Los Angeles
</a>
</li>
<li class="teaserCont ">
<img src="/sendungen/wdr2montalk/schaefer108_v-TeaserKlein.jpg"    title="Bildrechte: WDR/Fehlauer" alt="Bärbel Schäfer im WDR 2-Studio" height="82" width='146' />
<a href="http://www.wdr.de/Fotostrecken/wdr2/montalk/schaefer.jsp" class="galleryPageLink">
<span class="hidden">Galerie: </span>
Bärbel Schäfer im WDR 2 MonTalk
[Fotostrecke]
</a>
</li>
<li class="teaserCont ">
<img src="/panorama/venustransit110_v-TeaserKlein.jpg"    title="Bildrechte: picture alliance/Georg Hochmuth/APA/picturedesk.com" alt="Venustransit am frühen Mittwochmorgen, 06.06.2012" height="82" width='146' />
<a href="http://www.wdr.de/Fotostrecken/wdr2/venustransit.jsp" class="galleryPageLink">
<span class="hidden">Galerie: </span>
Venustransit: Seltenes Himmelsspektakel
[Fotostrecke]
</a>
</li>
<li class="teaserCont ">
<img src="/panorama/diskriminierung116_v-TeaserKlein.jpg"    title="Bildrechte: dpa" alt="Demonstration anlässlich des Internationalen Tages gegen Rassismus (21.03.2012)" height="82" width='146' />
<a href="/diskriminierung100.html" class="textPageLink">
WDR 2 Serie - Diskriminierung im Alltag
</a>
</li>
<li class="teaserCont ">
<img src="/unterhaltung/paternoster/jonflemingolsen102_v-TeaserKlein.jpg"    title="Bildrechte: wdr" alt="Heike Knispel und Jon Fleming Olsen im WDR 2 Paternoster" height="82" width='146' />
<a href="/unterhaltung/paternoster/jonflemmingolsen100.html" class="textPageLink">
WDR 2 Paternoster - Jon Flemming Olsen
</a>
</li>
<li class="teaserCont last">
<img src="/panorama/queen116_v-TeaserKlein.jpg"    title="Bildrechte: dpa / Facundo Arrizabalaga" alt="Queen Elizabeth II. beim Derby in Epsom" height="82" width='146' />
<a href="http://www.wdr.de/Fotostrecken/wdr2/thronjubilaeum.jsp" class="galleryPageLink">
<span class="hidden">Galerie: </span>
60 Jahre Queen
[Fotostrecke]
</a>
</li>
<li class="nextTeaserSix">
<!-- ajaxURL: /startseite100-teaserleisteKomponente_ai-1_ft-7_ki-1_tl-1.html -->
<a href="/startseite100_ai-1_ft-7_ki-1_tl-1.html#teaserSix1">Programm-Highlights: vorblättern</a>
</li>
</ul>
</div>
<hr/>
<div class="teaserContOuter">
<div class="teaserCont">
<div class="teaserCompactList">
<h2 class="Theme"><a href="http://www.tagesschau.de/" >tagesschau.de</a></h2>
<img height="174" width="310" alt="Deutschlandtrend" title="Deutschlandtrend - " src="http://www.tagesschau.de/multimedia/bilder/deutschlandtrend858~_v-gross16x9.jpg"/>
<ul>
<li>
<a href="http://www.tagesschau.de/inland/deutschlandtrend1534.html">
DeutschlandTrend: SPD legt zu, Piraten klar im Minus
</a>
<p>Nach den Erfolgen bei den Landtagswahlen hat die SPD im aktuellen ARD-DeutschlandTrend zwei Prozentpunkte zugelegt. Trotzdem kann Rot-Grün nicht auf eine eigene Mehrheit hoffen. Daran ändern auch Dauer-Koalitionsstreit und eine breite Ablehnung des Betreuungsgeldes nichts. Für die Piraten geht es indes deutlich bergab.</p>
</li>
<li>
<a href="http://www.tagesschau.de/ausland/hama120.html">
Offenbar neues Massaker in Syrien
</a>
<p>In der syrischen Region?Hama? hat es offenbar ein neues Massaker mit vielen Toten gegeben. Das berichten Nachrichtenagenturen unter Berufung auf?Regimegegner. Unter den Opfern sollen auch Kinder sein. Ein Oppositionssprecher machte syrische Regierungstruppen verantwortlich.</p>
</li>
<li>
<a href="http://www.tagesschau.de/wirtschaft/spanien464.html">
Kauder verlangt von Spanien Antrag auf Rettungsschirm-Hilfe
</a>
<p>Spanien stemmt sich noch gegen einen Hilfsantrag des Euro-Rettungsschirms. Doch Unionsfraktionschef Kauder machte nun als erster führender Koalitionspolitiker öffentlich klar, dass er das für zwingend erforderlich hält. Den Vorschlag direkter Zahlungen an Spaniens Bankenrettungsfonds lehnte er ab.</p>
</li>
<li>
<a href="http://www.tagesschau.de/wirtschaft/bankenrettung112.html">
EU fordert Bankenrettung ohne Steuergelder
</a>
<p>Die Kosten der Rettung von Banken soll künftig die Finanzbranche selbst tragen. Die EU-Kommission legte einen Gesetzesvorschlag vor, der einen Krisenfonds vorsieht, den die Institute finanzieren. Zugleich sollen die Aufsichtsbehörden früher eingreifen und Banken auch schließen dürfen.</p>
</li>
</ul>
</div>
</div>
<div class="teaserCont">
<div class="teaserAudioList">
<h2 class="audioTheme" ><a href="http://www.wdr2.de/sendungen/audios104.html" >Aktuelle WDR 2 Audios</a></h2>
<ul>
<li class="audioLink">
<a href="/musik/audiovielestreitpunkteinnrwkoalitionsverhandlungennochoffen100-audioplayer.html" >
<span class="hidden">Audio: </span>
Viele Streitpunkte in NRW-Koalitionsverhandlungen noch offen (06.06.2012)
</a>
<span class="audioMeta">Leo Flamm / Michael Brocker, WDR 2 Der Tag</span>
</li>
<li class="audioLink">
<a href="/musik/audioeukommissionwillbankenpleitenbeherrschbarmachen100-audioplayer.html" >
<span class="hidden">Audio: </span>
EU-Kommission will Bankenpleiten beherrschbar machen (06.06.2012)
</a>
<span class="audioMeta">Wolfgang Landmesser, WDR 2 Der Tag</span>
</li>
<li class="audioLink">
<a href="/musik/audioangstvorderspanischengrippeberlinunddiebankenkrise100-audioplayer.html" >
<span class="hidden">Audio: </span>
Angst vor der spanischen Grippe: Berlin und die Bankenkrise (06.06.2012)
</a>
<span class="audioMeta">Georg Schwarte, WDR 2 Der Tag</span>
</li>
<li class="audioLink">
<a href="/musik/audioeuenergiekommissarguentheroettingerwillmarktanteilerneuerbarerenergienehoehen100-audioplayer.html" >
<span class="hidden">Audio: </span>
EU-Energiekommissar Günther Oettinger will Marktanteil erneuerbarer Energien ehöhen (06.06.2012)
</a>
<span class="audioMeta">Christoph Prössl, WDR 2 Der Tag</span>
</li>
<li class="audioLink">
<a href="/musik/audionetzbetreibersiegenvorgerichtstromundgaspreisekoenntensteigen100-audioplayer.html" >
<span class="hidden">Audio: </span>
Netzbetreiber siegen vor Gericht: Strom- und Gaspreise könnten steigen (06.06.2012)
</a>
<span class="audioMeta">Jörg Marksteiner, WDR 2 Der Tag</span>
</li>
<li class="audioLink">
<a href="/musik/audiokabinettbeschliesstbetreuungsgeldundfoerderungprivaterpflegeversicherung100-audioplayer.html" >
<span class="hidden">Audio: </span>
Kabinett beschließt Betreuungsgeld und Förderung privater Pflegeversicherung (06.06.2012)
</a>
<span class="audioMeta">Lioba Werrelmann, WDR 2 Der Tag</span>
</li>
</ul>
</div>
</div>
<div class="teaserCont last">
<div class="teaserList">
<h2 class="eventTheme" ><a href="http://www.wdr2.de/musik/veranstaltungen100.html" >WDR 2 Veranstaltungen</a></h2>
<ul>
<li>
<a href="/veranstaltungen/jamesmorrison110.html">James Morrison</a>
<span>Köln, 08.06.2012</span>
</li>
<li>
<span>WDR 2 Lachen Live - Mehr!
Nachholtermin vom 21.04.</span>
<span>Brilon, 12.06.2012</span>
</li>
<li>
<a href="/sport/leichtathletik_dm102.html">Leichtathletik - Deutsche Meisterschaften</a>
<span>Bochum, 16.06.2012</span>
</li>
<li>
<a href="/sport/leichtathletik_dm102.html">Leichtathletik - Deutsche Meisterschaften</a>
<span>Bochum, 17.06.2012</span>
</li>
<li>
<a href="/veranstaltungen/katzenjammer168.html">Katzenjammer</a>
<span>Köln, 22.06.2012</span>
</li>
<li>
<a href="/veranstaltungen/tom_petty104.html">Tom Petty</a>
<span>Köln, 25.06.2012</span>
</li>
</ul>
</div>
</div>
</div>
<hr/>
<div class="teaserContOuter">
<div class="teaserCont bannerTeaserCont">
<div class="bannerTeaserListCont">
<ul class="bannerTeaserList">
<li>
<img src="/sport/fussball_em122_v-WDRBannerteaser.jpg"    title="Bildrechte: picture alliance/ dpa" alt="Nachbildung des EM-Spielballs auf dem Unabhängigkeitsplatz in Kiew, Urkaine" height="100" width='310' />
<a href="/sport/fussball_europameisterschaft100.html" >
<strong>UEFA EURO 2012<span class="hidden">:</span></strong> Alles Infos zur Fußball-Europameisterschaft
<span>[mehr]</span>
</a>
</li>
<li>
<img src="/musik/bildwdrfacebook100_v-WDRBannerteaser.jpg"    title="Bildrechte: WDR/dpa[M]" alt="WDR 2 bei Facebook" height="100" width='310' />
<a href="/panorama/soziale_netzwerke130.html" >
<strong>WDR 2 bei <span lang="en">Facebook</span> und <span lang="en">Twitter</span><span class="hidden">:</span></strong> Gut vernetzt, gut informiert
<span>[mehr]</span>
</a>
</li>
</ul>
</div>
</div>
<div class="teaserCont bannerTeaserCont">
<div class="bannerTeaserListCont">
<ul class="bannerTeaserList">
<li>
<img src="/musik/young_neil100_v-WDRBannerteaser.jpg"    title="Bildrechte: dpa" alt="Der Musiker Neil Young bei einem Auftritt 1982" height="100" width='310' />
<a href="http://www.wdr2.de/quizze100.html" >
<strong>WDR 2 Quizze<span class="hidden">:</span></strong> Rätseln, raten, schlauer werden
<span>[Quiz]</span>
</a>
</li>
<li>
<img src="/service/gote/pierogi_teigtaschen100_v-WDRBannerteaser.jpg"    title="Bildrechte: dpa" alt="Gefüllte Teigtaschen, in Butter und Zwiebeln angebraten" height="100" width='310' />
<a href="/service/gote/polnische_kueche100.html" >
<strong>WDR 2 Einfach Gote - Buchweizen Pierogi<span class="hidden">:</span></strong> Polnische Küche
<span>[mehr]</span>
</a>
</li>
</ul>
</div>
</div>
<div class="teaserCont bannerTeaserCont">
<div class="bannerTeaserListCont">
<ul class="bannerTeaserList">
<li>
<img src="/aktionen/hausparty/hp_witten100_v-WDRBannerteaser.jpg"    title="Bildrechte: WDR/Brill" alt="WDR 2 StrandHausparty Witten" height="100" width='310' />
<a href="/aktionen/hausparty/hp_next128.html" >
<strong>WDR 2 StrandHausparty in Witten<span class="hidden">:</span></strong> Mit Steffi Neu und Jürgen Mayer am Strand
<span>[mehr]</span>
</a>
</li>
<li>
<img src="/podcast104_v-WDRBannerteaser.jpg"    title="Bildrechte: WDR/Mauritius[M]bhm" alt="Podcast" height="100" width='310' />
<a href="http://www.wdr.de/radio/home/podcasts/wdr2_podcast.phtml" >
<strong>Radio zum Mitnehmen<span class="hidden">:</span></strong> Das Podcast-Angebot von WDR 2
<span>[mehr]</span>
</a>
</li>
</ul>
</div>
</div>
</div>
<hr/>
<div class="teaserContOuter">
<div class="teaserCont">
<div class="teaserChangeList">
<h2><a href="http://www.wdr2.de/musik/musik100.html" >Musik</a></h2>
<ul>
<li>
<img src="/musik/nrw_publikum100_v-TeaserKlein.jpg"    title="Bildrechte: mauritius_images" alt="Ein junger Mann spielt E-Gitarre" height="82" width='146' />
<a href="/musik/szenenrw262.html" >
WDR 2 Musikclub - Szene NRW (06.06.2012): Das Voting
</a>
</li>
<li>
<img src="/musik/mick_hucknall102_v-TeaserKlein.jpg"    title="Bildrechte: dpa" alt="Mick Hucknall bei einem Konzert in Wien am 23.11.2010" height="82" width='146' />
<a href="/musik/simply_red104.html" >
WDR 2 in Concert - Simply Red: Abschied zum Anhören
</a>
</li>
<li>
<img src="/musik/traurige_musik100_v-TeaserKlein.jpg"    title="Bildrechte: dpa" alt="Junges Mädchen hört Musik und schaut traurig drein" height="82" width='146' />
<a href="/musik/traurige_musik102.html" >
Wissenschaftlich bewiesen: Pop-Musik klingt immer trauriger
</a>
</li>
</ul>
</div>
</div>
<div class="teaserCont">
<div class="teaserChangeList">
<h2><a href="http://www.wdr2.de/service/service100.html" >Service</a></h2>
<ul>
<li>
<img src="/service/quintessenz/quintessenz_gut_grillen100_v-TeaserKlein.jpg"    title="Bildrechte: dpa" alt="Grillzange nimmt Fleisch und Gemuese vom Grill" height="82" width='146' />
<a href="/service/quintessenz/gut_grillen100.html" >
WDR 2 Servicezeit - Gut grillen für Fortgeschrittene: Leckerer Sommerspaß
</a>
</li>
<li>
<img src="http://www.sportschau.de/uefaeuro2012/empokal100_v-TeaserKlein.jpg"    title="Bildrechte: dpa" alt="EM-Pokal" height="82" width='146' />
<a href="/sport/em_tippen100.html" >
Tippspiele zur EM: Verbotenes Glückspiel?
</a>
</li>
<li>
<img src="/service/quintessenz/quintessenz_wadenkrampf100_v-TeaserKlein.jpg"    title="Bildrechte: dpa" alt="Fußballspieler mit Wadenkrampf" height="82" width='146' />
<a href="/service/quintessenz/wadenkraempfe100.html" >
WDR 2 Quintessenz - Die Wade zwickt: Wundermittel Magnesium
</a>
</li>
</ul>
</div>
</div>
<div class="teaserCont last">
<div class="teaserChangeList">
<h2><a href="http://www.wdr2.de/sport/sport100.html" >Sport</a></h2>
<ul>
<li>
<img src="http://www.sportschau.de/fussball/bundesliga/saisondortmund104_v-TeaserKlein.jpg"    title="Bildrechte: imago" alt="Shinji Kagawa" height="82" width='146' />
<a href="http://www.sportschau.de/fussball/bundesliga/kagawa112.html" >
Dortmund verliert Top-Spieler: Kagawa-Wechsel zu Manchester United perfekt
</a>
</li>
<li>
<img src="/sport/citta104_v-TeaserKlein.jpg"    title="Bildrechte: pa / dpa" alt="Die Elefantenkuh Citta im Zoo von Krakau mit einem Fußball " height="82" width='146' />
<a href="/panorama/citta100.html" >
Elefantenkuh tippt Spiel-Ergebnisse: EM-Orakel Citta
</a>
</li>
<li>
<img src="http://www.sportschau.de/kurznachrichten/fussballkompakt/kobiashwilisperre104_v-TeaserKlein.jpg"    title="Bildrechte: dpa" alt="Lewan Kobiashwili" height="82" width='146' />
<a href="http://www.sportschau.de/fussball/bundesliga/lewankobiaschwilli104.html" >
Lange Sperre für Hertha-Spieler: Hertha akzeptiert Rekordstrafe für Kobiaschwili
</a>
</li>
</ul>
</div>
</div>
</div>
<hr/>
<div class="teaserContOuter">
<div class="teaserCont">
<div class="teaserChangeList">
<h2><a href="http://www.wdr2.de/unterhaltung/unterhaltung100.html" >Unterhaltung</a></h2>
<ul>
<li>
<img src="/unterhaltung/lachenlive/reuter_matthias102_v-TeaserKlein.jpg"    title="Bildrechte: Sebastian Mölleken" alt="Kabarettist Matthias Reuter; Rechte: Sebastian Mölleken" height="82" width='146' />
<a href="/unterhaltung/lachenlive/lachen_live242.html" >
WDR 2 Lachen Live!: Wir empfehlen außerdem
</a>
</li>
<li>
<img src="/vonderleyens104_v-TeaserKlein.jpg"    title="Bildrechte: WDR" alt="CD cover Von der Leyens" height="82" width='146' />
<a href="/unterhaltung/comedy/vonderleyens102.html" >
Die von der Leyens: EM
</a>
</li>
<li>
<img src="/unterhaltung/zugabe104_v-TeaserKlein.jpg"    title="Bildrechte: wdr" alt="Die Nachteule schmunzelt und kniept mit dem Auge - die WDR 2 Zugabe" height="82" width='146' />
<a href="/sendungen/wdr2zugabe/zugabe_nachhoeren244.html" >
WDR 2 Zugabe - Samstag, 02.06.2012: Alle Beiträge zum Nachhören
</a>
</li>
</ul>
</div>
</div>
<div class="teaserCont">
<div class="teaserChangeList">
<h2><a href="http://www.wdr2.de/kultur/kultur100.html" >Kultur</a></h2>
<ul>
<li>
<img src="/kultur/macbeth100_v-TeaserKlein.jpg"    title="Bildrechte: Mayou Trikerioti / Icarus Theatre London" alt="Szene aus der &#034;Macbeth&#034;-Inszenierung des Icarus Theatre London" height="82" width='146' />
<a href="/kultur/kritiker/shakespeare100.html" >
WDR 2 Die Kritiker - Shakespeare-Festival: Blutiges Spektakel
</a>
</li>
<li>
<img src="/kultur/schnitt100_v-TeaserKlein.jpg"    title="Bildrechte: Ullstein Taschenbuch Verlag " alt="Ausschnitt aus dem Cover des Krimis &#034;Schnitt&#034; von Marc Raabe" height="82" width='146' />
<a href="/kultur/tatortnrw/raabe100.html" >
WDR 2 Tatort NRW - Marc Raabe: Schnitt
</a>
</li>
<li>
<img src="/kultur/buecher/toedlichegeschenke100_v-TeaserKlein.jpg"    title="Bildrechte: btb Verlag" alt="Ausschnitt des Buchcovers &#034;Tödliche Geschenke&#034; von Carol O&#039;Connell" height="82" width='146' />
<a href="/kultur/buecher/toedliche_geschenke100.html" >
WDR 2 Bücher - Carol O'Connell: Tödliche Geschenke
</a>
</li>
</ul>
</div>
</div>
<div class="teaserCont last">
<div class="teaserChangeList">
<h2><a href="http://www.wdr2.de/aktionen/aktionen100.html" >Aktionen</a></h2>
<ul>
<li>
<img src="/aktionen/wdr2_fuer_eine_stadt/2012/collage_boot100_v-TeaserKlein.jpg"    title="Bildrechte: dpa, Universal, Imago, WDR (Montage)" alt="Ein Boot mit den Künstlern Rea Garvey, Stefanie Heinzmann und Katzenjammer vor einem künstlichen NRW-Panorama" height="82" width='146' />
<a href="/aktionen/wdr2_fuer_eine_stadt/2012/portal100.html" >
WDR 2 für eine Stadt: Ein ganzer Tag mit WDR 2
</a>
</li>
<li>
<img src="/aktionen/lehrstellenaktion/titelmotiv100_v-TeaserKlein.jpg"    title="Bildrechte: WDR" alt="WDR Lehrstellenaktion" height="82" width='146' />
<a href="http://www.wdr-lehrstellenaktion.de" >
WDR Lehrstellenaktion: Der WDR hilft bei der Lehrstellensuche
</a>
</li>
<li>
<img src="/sendungen/wdr2montalk/daniel_glattauer106_v-TeaserKlein.jpg"    title="Bildrechte: wdr" alt="Daniel Glattauer mit  Christine Westermann im WDR 2 MonTalk " height="82" width='146' />
<a href="/sendungen/wdr2montalk/glattauer_livemontalk100.html" >
WDR 2 MonTalk live auf der lit.COLOGNE: Christine Westermann trifft Daniel Glattauer
</a>
</li>
</ul>
</div>
</div>
</div>
<hr/>
<div class="teaserContOuter">
<div class="teaserCont">
<div class="teaserChangeList">
<h2><a href="http://www.wdr2.de/panorama/panorama100.html" >Panorama</a></h2>
<ul>
<li>
<img src="http://www1.wdr.de/themen/digital/bildblog100_v-TeaserKlein.jpg"    title="Bildrechte: Picture Alliance" alt="Verwaltung von Netzwerkadressen: Die IP-Adressen werden knapp" height="82" width='146' />
<a href="http://wdrblog.de/joergschieb/archives/2012/06/ipv6.html" >
Jörg-Schieb-Blog: IPv6 macht das Internet zukunftstauglich
</a>
</li>
<li>
<img src="/wirtschaft/visacard100_v-TeaserKlein.jpg"    title="Bildrechte: Pa/Empics" alt="Geldkarten mit Visa- und MasterCard-Zeichen liegen auf einer Tastatur" height="82" width='146' />
<a href="/panorama/datenklau122.html" >
Lauschangriff auf neue Kreditkarten: Datenklau per Funk
</a>
</li>
<li>
<img src="/panorama/vatikan114_v-TeaserKlein.jpg"    title="Bildrechte: dpa" alt="Italienische Polizisten stehen auf dem Petersplatz in Rom" height="82" width='146' />
<a href="/panorama/vatikan110.html" >
Diebstahl im Vatikan: "Nicht einschüchtern lassen"
</a>
</li>
</ul>
</div>
</div>
<div class="teaserCont">
<div class="teaserChangeList">
<h2><a href="http://www.wdr2.de/politik/politik100.html" >Politik</a></h2>
<ul>
<li>
<img src="/politik/klartext/fachkraeftemangel118_v-TeaserKlein.jpg"    title="Bildrechte: dpa" alt="In einem Reinraum werden am Donnerstag (01.09.2011) im Bosch Werk Feuerbach in Stuttgart Hochdruckpumpen für Commonrail Systeme gebaut." height="82" width='146' />
<a href="/politik/fachkraeftemangel122.html" >
Mangel von Fachkräften: Europäischer Arbeitsmarkt soll helfen
</a>
</li>
<li>
<img src="/politik/stimmzettel110_v-TeaserKlein.jpg"    title="Bildrechte: pa / dpa" alt="Im niederbayerischen Mallersdorf (Landkreis Straubing-Bogen) wird am 18.09.2005 ein Stimmzettel in einem Wahllokal vor den Wahlkabinen hochgehalten." height="82" width='146' />
<a href="/politik/wahlrecht108.html" >
Neues Wahlrecht vor Verfassungsgericht: Mehr Wähler, weniger Mandate
</a>
</li>
<li>
<img src="/politik/roesler124_v-TeaserKlein.jpg"    title="Bildrechte: dpa / Maurizio Gambarini" alt="Bundeskanzlerin Angela Merkel (CDU, Mitte), der bayerische Ministerpräsident Horst Seehofer (CSU, rrechts) und Wirtschaftsminister und FDP-Chef Philipp Rösler" height="82" width='146' />
<a href="/politik/klartext/koalition116.html" >
WDR 2 Klartext zum Koalitionsgipfel: Keinen Schritt weiter
</a>
</li>
</ul>
</div>
</div>
<div class="teaserCont last">
<div class="teaserChangeList">
<h2><a href="http://www.wdr2.de/wirtschaft/wirtschaft100.html" >Wirtschaft</a></h2>
<ul>
<li>
<img src="http://www1.wdr.de/themen/wirtschaft/stromundgas100_v-TeaserKlein.jpg"    title="Bildrechte: dpa,ddp,wdr(m)schweda" alt="Steckdosen und Gasflamme" height="82" width='146' />
<a href="http://www1.wdr.de/themen/wirtschaft/stromgas100.html" >
Oberlandesgericht gibt Netzbetreibern recht: Strom und Gas könnten teurer werden  [WDR]
</a>
</li>
<li>
<img src="/wirtschaft/paketbote100_v-TeaserKlein.jpg"    title="Bildrechte: mauritius images" alt="Viele Paketboten arbeiten unter harten Bedingungen" height="82" width='146' />
<a href="/wirtschaft/paketzusteller100.html" >
Arbeit bei Paketdiensten: Knallharte Bedingungen
</a>
</li>
<li>
<img src="/wirtschaft/schlecker350_v-TeaserKlein.jpg"    title="Bildrechte: Dapd/ Lohnes" alt="Ein Schild &#034;Kasse geschlossen&#034; steht vor der Kasse in einer Filiale der Drogeriemarkt-Kette Schlecker" height="82" width='146' />
<a href="/wirtschaft/schlecker130.html" >
Arbeitsminister trifft Schlecker-Betriebsrätinnen: Schlechte Aussichten
</a>
</li>
</ul>
</div>
</div>
</div>
<hr/>
<div class="stripTeaserSix" id="teaserSix2">
<h2><a href="http://www.wdr2.de/unterhaltung/unterhaltung100.html" class="colored">Satire</a></h2>
<ul class="teaserContOuter">
<li class="teaserCont firstImgTeaser">
<img src="/unterhaltung/kabarett/eckenga108_v-TeaserKlein.jpg"    title="Bildrechte: WDR" alt="Fritz Eckenga" height="82" width='146' />
<a href="/unterhaltung/kabarett/fritz_eckenga100.html" class="textPageLink">
Fritz Eckenga
</a>
</li>
<li class="teaserCont ">
<img src="/unterhaltung/comedy/sarko106_v-TeaserKlein.jpg"    title="Bildrechte: wdr" alt="Nicolas Sarkozy" height="82" width='146' />
<a href="/unterhaltung/comedy/sarkodefunes100.html" class="videoPageLink">
<span class="hidden">Video: </span>
Sarko de Funes
</a>
</li>
<li class="teaserCont ">
<img src="/musik/bildschlosskoalitionssteinmitbundesadler100_v-TeaserKlein.jpg"    title="Bildrechte: WDR, Birgit Heinzelmann" alt="Burg mit Bundesadler im Gewitter" height="82" width='146' />
<a href="/unterhaltung/comedy/schloss_koalitionsstein100.html" class="textPageLink">
Willkomen im Reich des Grauens!
</a>
</li>
<li class="teaserCont ">
<img src="/unterhaltung/comedy/bildgaertnermeisterplueschke100_v-TeaserKlein.jpg"    title="Bildrechte: dpa" alt="Richard Berkowski als Gärtner Plüschke" height="82" width='146' />
<a href="/unterhaltung/comedy/plueschkegartentipp100.html" class="textPageLink">
Pflanzentipps mit Gärtner Plüschke
</a>
</li>
<li class="teaserCont ">
<img src="/unterhaltung/comedy/astroradio112_v-TeaserKlein.jpg"    title="Bildrechte: WDR, Deiter Bey" alt="Maria Grund-Scholer als Seherin Donata" height="82" width='146' />
<a href="/unterhaltung/comedy/astroradio100.html" class="textPageLink">
Astroradio
</a>
</li>
<li class="teaserCont last">
<img src="/unterhaltung/comedy/wdr2comedy_alexissorgas102_v-TeaserKlein.jpg"    title="Bildrechte: onkel fisch " alt="Sirtaki Tänzer" height="82" width='146' />
<a href="/unterhaltung/comedy/alexissorgas100.html" class="videoPageLink">
<span class="hidden">Video: </span>
Wer's glaubt, wird selig!
</a>
</li>
<li class="nextTeaserSix">
<!-- ajaxURL: /startseite100-teaserleisteKomponente_ai-2_ft-6_ki-17_tl-2.html -->
<a href="/startseite100_ai-2_ft-6_ki-17_tl-2.html#teaserSix2">Satire: vorblättern</a>
</li>
</ul>
</div>
<hr/>
</div>
</div>
<div id="pageFunctions">
<ul>
<li>
<a href="#wrapper">Seitenanfang</a>
</li>
</ul>
</div>
<!--googleoff: index-->
<div id="footer">
<h2 class="hidden">Service-Navigation</h2>
<ul>
<li id="newsletter"><a href="http://www.wdr.de/themen/global/newsletter/">Newsletter
+ RSS</a></li>
<li id="impressum"><a href="/impressum/impressum100.html">Impressum</a></li>
<li id="copyright"><a href="http://www.wdr.de/themen/global/urheber/">&copy; WDR 2012</a></li>
</ul>
</div>
<!-- footer -->
<hr />
<form method="post"
action="/suche/suche104.jsp"
id="search" accept-charset="UTF-8">
<h2 class="hidden">Suche</h2>
<fieldset>
<legend class="hidden">Suche im gesamten Angebot von WDR&nbsp;2</legend>
<label for="words" class="hidden">Suchbegriff:</label>
<input name="Q" value="" type="text" id="words" />
<input type="submit" value="suchen" />
</fieldset>
</form>
<hr/>
<div id="navigation">
<h2 class="hidden">Navigation</h2>
<h3 class="hidden">WDR 2-Navigation</h3>
<ul id="radioSubNavi">
<li class="active">
<span>WDR 2</span>
</li>
<li>
<a href="/nrw/index.html">NRW</a>
</li>
<li>
<a href="/politik/index.html">Politik</a>
<div class="hoverCont">
<ul>
<li><a href="/politik/klartext/index.html">WDR 2 Klartext</a></li>
<li><a href="/politik/wdr2arena/index.html">WDR 2 Arena</a></li>
<li><a href="/politik/wahlen/index.html">NRW-Landtagswahl 2012</a></li>
</ul>
</div>
</li>
<li>
<a href="/wirtschaft/index.html">Wirtschaft</a>
</li>
<li>
<a href="/panorama/index.html">Panorama</a>
<div class="hoverCont">
<ul>
<li><a href="/panorama/stichtag/index.html">Der Stichtag bei WDR.de</a></li>
<li><a href="/panorama/sonntagsfragen/index.html">WDR 2 Sonntagsfragen</a></li>
<li><a href="/panorama/fotostrecken/index.html">WDR 2 Fotostrecken</a></li>
<li><a href="/panorama/fruehling/index.html">Frühling 2012</a></li>
</ul>
</div>
</li>
<li>
<a href="/musik/index.html">Musik</a>
<div class="hoverCont">
<ul>
<li><a href="/musik/musiktipp/index.html">WDR 2 Musiktipp</a></li>
<li><a href="/musik/jukebox/index.html">Jukebox-Voting</a></li>
<li><a href="/musik/konzertbuebersichtslink/index.html">Konzerttermine</a></li>
<li><a href="/musik/konzertberichte/index.html">WDR 2 präsentierte</a></li>
<li><a href="/musik/neubeiwdr2/index.html">Neu bei WDR 2</a></li>
<li><a href="/musik/szenenrw/index.html">Szene NRW: Die Wahl</a></li>
<li><a href="/musik/musikquiz/index.html">WDR 2 Musikquiz</a></li>
<li><a href="/musik/musikclub/index.html">WDR 2 Musikclub</a></li>
<li><a href="/musik/classics/index.html">WDR 2 Musikclub - Classics</a></li>
<li><a href="/musik/yesterday/index.html">WDR 2 Yesterday</a></li>
<li><a href="/musik/playlist/index.html">Playlist</a></li>
</ul>
</div>
</li>
<li>
<a href="/unterhaltung/index.html">Unterhaltung</a>
<div class="hoverCont">
<ul>
<li><a href="/unterhaltung/comedy/index.html">WDR 2 Comedy</a></li>
<li><a href="/unterhaltung/paternoster/index.html">WDR 2 Paternoster</a></li>
<li><a href="/unterhaltung/lachenlive/index.html">WDR 2 Lachen Live</a></li>
<li><a href="/unterhaltung/kabarett/index.html">WDR 2 Kabarett</a></li>
<li><a href="/unterhaltung/wdr2montalk/index.html">WDR 2 MonTalk</a></li>
<li><a href="/unterhaltung/quizze/index.html">WDR 2 Quizze</a></li>
</ul>
</div>
</li>
<li>
<a href="/kultur/index.html">Kultur</a>
<div class="hoverCont">
<ul>
<li><a href="/kultur/tatortnrw/index.html">WDR 2 Tatort NRW</a></li>
<li><a href="/kultur/buecher/index.html">WDR 2 Bücher</a></li>
<li><a href="/kultur/kritiker/index.html">WDR 2 Die Kritiker</a></li>
<li><a href="/kultur/kino/index.html">WDR 2 Kinotipp</a></li>
</ul>
</div>
</li>
<li>
<a href="/service/index.html">Service</a>
<div class="hoverCont">
<ul>
<li><a href="/service/quintessenz/index.html">WDR 2 Quintessenz</a></li>
<li><a href="/service/gote/index.html">WDR 2 Einfach Gote</a></li>
<li><a href="/service/multimedia/index.html">WDR 2 Multimedia</a></li>
<li><a href="/service/servicezeit/index.html">WDR 2 Servicezeit</a></li>
</ul>
</div>
</li>
<li>
<a href="/sport/index.html">Sport</a>
<div class="hoverCont">
<ul>
<li><a href="/sport/pistor/index.html">Alle gegen Pistor</a></li>
<li><a href="/sport/torjaeger/index.html">WDR 2 Torjäger</a></li>
<li><a href="/sport/ligalive/index.html">Liga Live</a></li>
<li><a href="/sport/uefa_euro_2012/index.html">UEFA EURO 2012</a></li>
</ul>
</div>
</li>
<li>
<a href="/aktionen/index.html">Aktionen</a>
<div class="hoverCont">
<ul>
<li><a href="/aktionen/wdr2_fuer_eine_stadt/index.html">WDR 2 für eine Stadt</a></li>
<li><a href="/aktionen/hausparty/index.html">WDR 2 Hausparty</a></li>
<li><a href="/aktionen/lehrstellenaktion/index.html">WDR Lehrstellenaktion</a></li>
<li><a href="/aktionen/veranstaltungstermine/index.html">Veranstaltungstermine</a></li>
</ul>
</div>
</li>
<li>
<a href="/sendungen/index.html">Sendungen</a>
<div class="hoverCont">
<ul>
<li><a href="/sendungen/wdr2arena/index.html">WDR 2 Arena</a></li>
<li><a href="/sendungen/wdr2berichtevonheute/index.html">WDR 2 Berichte von heute</a></li>
<li><a href="/sendungen/wdr2amsamstag/index.html">WDR 2 am Samstag</a></li>
<li><a href="/sendungen/wdr2amsonntag/index.html">WDR 2 am Sonntag</a></li>
<li><a href="/sendungen/wdr2dertag/index.html">WDR 2 Der Tag</a></li>
<li><a href="/sendungen/wdr2ligalive/index.html">WDR 2 Liga Live/Sportzeit</a></li>
<li><a href="/sendungen/wdr2mittagsmagazin/index.html">WDR 2 Mittagsmagazin</a></li>
<li><a href="/sendungen/wdr2montalk/index.html">WDR 2 MonTalk</a></li>
<li><a href="/sendungen/wdr2morgenmagazin/index.html">WDR 2 Morgenmagazin</a></li>
<li><a href="/sendungen/wdr2musikclub/index.html">WDR 2 Musikclub</a></li>
<li><a href="/sendungen/wdr2musikclubclassics/index.html">WDR 2 Musikclub-Classics</a></li>
<li><a href="/sendungen/wdr2musikclubjukebox/index.html">WDR 2 Musikclub-Jukebox</a></li>
<li><a href="/sendungen/wdr2servicezeit/index.html">WDR 2 Servicezeit</a></li>
<li><a href="/sendungen/wdr2sonntagsfragen/index.html">WDR 2 Sonntagsfragen</a></li>
<li><a href="/sendungen/wdr2weltzeit/index.html">WDR 2 Weltzeit</a></li>
<li><a href="/sendungen/wdr2westzeit/index.html">WDR 2 Westzeit</a></li>
<li><a href="/sendungen/wdr2yesterday/index.html">WDR 2 Yesterday</a></li>
<li><a href="/sendungen/wdr2zugabe/index.html">WDR 2 Zugabe</a></li>
<li><a href="/sendungen/wdr2zwischenrheinundweser/index.html">WDR 2 Zwischen Rhein und Weser</a></li>
<li><a href="/sendungen/ndr2undwdr2dienacht/index.html">NDR 2 und WDR 2: Die Nacht</a></li>
</ul>
</div>
</li>
<li class="last">
<a href="/moderatoren/index.html">Moderation</a>
</li>
</ul>
<h3 class="hidden">Radio-Navigation</h3>
<ul id="radioNavi">
<li><a href="http://www.einslive.de">1LIVE</a></li>
<li class="active">
<span>WDR 2</span>
</li>
<li><a href="http://www.wdr3.de">WDR 3</a></li>
<li><a href="http://www.wdr.de/radio/wdr4">WDR 4</a></li>
<li><a href="http://www.wdr5.de">WDR 5</a></li>
<li><a href="http://www.funkhauseuropa.de/">Funkhaus Europa</a></li>
<li><a href="http://www.wdr.de/radio/orchester/index.html">Orchester + Chor</a></li>
</ul>
<img src="/resources/img/logos/wdr.gif" alt="WDR.de" title="" width="120" height="50" id="wdrLogo" />
<h3 class="hidden">WDR-Hauptnavigation</h3>
<ul id="wdrNavi">
<li><a href="http://www.wdr.de/">WDR.de</a></li>
<li><a href="http://www.wdr.de/tv/home/">Fernsehen</a></li>
<li class="active"><a href="http://www.wdr.de/radio/home/index.phtml">Radio</a></li>
<li><a href="http://www.wdr.de/mediathek/html/regional/index.xml">Mediathek</a></li>
<li><a href="http://www.wdr.de/programmvorschau/">Programmvorschau</a></li>
</ul>
<h3 class="hidden">Metanavigation</h3>
<ul id="wdrSubNavi">
<li id="weatherLink"><a href="http://www1.wdr.de/themen/infokompakt/wetter/wetter_nrw_ea100.html"><acronym title="Nordrhein-Westfalen">NRW</acronym>-Wetter</a></li>
<li id="trafficLink"><a href="http://www.wdr.de/verkehrslage/">Verkehrslage</a></li>
<li id="textLink"><a href="http://www1.wdr.de/themen/infokompakt/videotext_ea/index.html">WDR Text</a></li>
<li id="contactLink"><a href="/kontakt/kontakt102.html">Kontakt</a></li>
<li id="azLink"><a href="http://www.wdr.de/themen/global/a_z/index.jhtml">A - Z</a></li>
<li id="helpLink"><a href="http://www.wdr.de/themen/homepages/hilfe.jhtml">Hilfe</a></li>
<li id="companyLink"><a href="http://www.wdr.de/unternehmen/">Unternehmen</a></li>
</ul>
</div>
</div>
</div>
<div id="ivwPix">
<script type="text/javascript"><!-- <![CDATA[
var IVW='http://wdr.ivwbox.de/cgi-bin/ivw/CP/;www.wdr2.de/startseite100.html';
document.write("<img src=\""+IVW+"?r="+escape(document.referrer)+"\" width=\"1\" height=\"1\" alt=\"\" />");
// ]]> --></script><noscript>
<div><img src="http://wdr.ivwbox.de/cgi-bin/ivw/CP/;www.wdr2.de/startseite100.html" width="1" height="1" alt="" /></div>
</noscript>
</div>
<script type="text/javascript" charset="utf-8" src="/resources/js/jquery-1.6.2.min.js"></script>
<script type="text/javascript" charset="utf-8" src="/resources/js/jquery-ui-1.8.10.custom.min.js"></script>
<script type="text/javascript" charset="utf-8" src="/resources/js/plugins/jquery.requireScript-1.2.1.min.js"></script>
<script type="text/javascript">
<!--<![CDATA[
var $jsPath = '/resources/js/';
jQuery.noConflict();
// ]]>  -->
</script>
<script type="text/javascript" charset="utf-8" src="/resources/js/basic.min.js"></script>
<!--googleon: index-->
</body>
</html>