<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="de" xmlns:fb="http://ogp.me/ns/fb#">
<head>
	<title>Fehlerseite 404 - ANTENNE BAYERN</title>
	<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
	<meta name="keywords" lang="de" content="Antenne Bayern, Antenne, Radio, LIVE RADIO, webradio, Musik, Download, mp3, Music, internetradio, Online-Radio, onlineshop, antenne club, Community, Comedy, programm, aktion, high life, servus bayern, guten morgen bayern, extra, sendungen, moderatoren" />
	<meta name="description" lang="de" content="Fehlerseite 404 - Sie sind nicht dort, wo Sie eigentlich hin wollten, denn dies ist die Fehler-Seite von antenne.de!  Die Startseite von ANTENNE BAYERN erreichen" />
	<meta name="language" content="Deutsch" />
	<meta name="robots" content="index, follow" />
	<meta name="author" content="ANTENNE BAYERN ressort100" />
	<meta name="publisher" content="ANTENNE BAYERN" />
	<meta name="copyright" content="ANTENNE BAYERN 2012" />
		<!--FACEBOOK-->
		<meta property="og:title" content=""/>
  
    <meta property="og:url" content=""/>
    <meta property="og:image" content=""/>
    <meta property="og:site_name" content="antenne.de"/>
    <meta property="og:description" content=""/>
		<meta property="fb:app_id" content="138646096154672"/>
		<!--FACEBOOK ENDE-->
		
	<link rel="stylesheet" href="/antenne/incl/css_new/style_header_20091102_23.css" type="text/css" />
	<link rel="stylesheet" href="/antenne/incl/css_new/style_main_20111214_1.css" type="text/css" />
	<link rel="stylesheet" href="/antenne/incl/css_new/style_banner.css" type="text/css" />
	<link rel="stylesheet" href="/antenne/incl/css_new/style_footer.css" type="text/css" />
	<script type="text/javascript" src="/antenne/incl/js_new/prototype.js"></script>
	<script type="text/javascript" src="/antenne/incl/js_new/scriptaculous.js?load=effects"></script>
	<script type="text/javascript" src="/antenne/incl/js/AJAX.js"></script>
		<script type="text/javascript" src="/antenne/incl/js/tt.js"></script>
	<script type="text/javascript" src="/antenne/incl/js/dd.js"></script>
	<script type="text/javascript" src="/antenne/incl/js/PopUpWindow.js"></script>
	<script type="text/javascript" src="/antenne/incl/js/ivw_reload.js"></script>
	<script type="text/javascript" src="/antenne/incl/js/main2012011801.js"></script>
	<script type="text/javascript" src="/antenne/incl/js_new/rating.js"></script>
	<!-- Generated by OpenX 2.8.1 -->
<script type='text/javascript' src='http://media.antenne-bayern.de/openx/www/delivery/spcjs.php?id=1'></script>

<style>

#adl_sb_table{

position:relative;

width:821px;

left:0px;

}

</style>
<script>

                adlWallPaperLeft=821;

</script>

	<script type="text/javascript">
		var ivw_seite = "1";

		var layoutstyle = "ws_layout";
		var adsc_google;
	</script>

</head>
<body >


<div id="containerhome">
	<div id="left">

		<div id="header">
			<div id="topNew"><a id='logo' style='background:url(/antenne/incl/images/site_layout_weiss/head_logo.png) no-repeat 0 0;' href='http://www.antenne.de'>http://www.antenne.de</a><div id="worker">
	<ul>
		<li><a href='/mail_ins_studio/Ihr-Draht-ins-Studio__studiomails_428627_radio.html' class='message' title='Mail ins Studio'><span>Message</span>&nbsp;</a></li>
		<li><a href='/webcams/Webcam-der-Blick-hinter-die-Kulissen__studiocam_417745_radio.html' class='webcam' title='Webcams'><span>Studiocam</span>&nbsp;</a></li>
		<li><a href='/antenne/musik/stars/album.php?product_id=11930443_2' class='songdownload' title='Song-Download'><span>Download</span>&nbsp;</a></li>
	</ul>
	<a href='/antenne/radio/mailinsstudio/index.php'><img src='/antenne/incl/images/site_layout_weiss/header/moderator_default1.jpg' alt='' class='worker' /></a>
</div>

				<div id="v_sep"></div>

				<div id="on_air">
	<div id='titel'>Aktueller Titel</div>
	<div id='song_titel'><marquee scrollamount='3' onclick="webradio_popup('antenne');" style='cursor:pointer;'><b>So wie du warst</b> - Unheilig</marquee></div>

	<div id='eq'></div>
	<a href="javascript:webradio_popup('antenne');" ></a>
</div>
	<div id='login'>

		<form method='post' action='/antenne/club/login.php'>
			<div id='loginContent'>
				<div>
					<span>Login:</span><input type='text' id='login_username' name='login_username' value='Spitzname' class='inputbox' onfocus='del_form_text_value(this.id);' onchange="del_form_text_value('login_password', 1);" onkeydown="del_form_text_value('login_password', 1);" onblur='set_form_text_value(this.id);' /> <input type='password' id='login_password' name='login_password' value='Passwort' class='inputbox' onfocus='del_form_text_value(this.id);' onblur='set_form_text_value(this.id);' /> <input type='submit' name='login' value='login' class='lbutton' />
				</div>
				<div class='jetzt'>
					<div class='sep'></div>
					<a href='/club/register/start/'>Jetzt kostenlos anmelden</a>
					<div class='sep'></div>
					<a href='/antenne/club/profile/password_forgotten.php'>Passwort vergessen</a>
					<div class='sep'></div>
				</div>
			</div>
		</form>
	
	</div>
<div id="search">
					<form action="/antenne/home/search/index.php" method="get">
						<p>
							<input type="hidden" name="cx" value="partner-pub-5794249757241625:dywmm5v1pyv" />
							<input type="hidden" name="cof" value="FORID:10" />
							<input type="hidden" name="ie" value="ISO-8859-1" />
							<input type="text" name="q" class="inputbox" id="site_search_weiss" value="Suchbegriff eingeben" onfocus="del_form_text_value(this.id);" onblur="set_form_text_value(this.id);" />
							<input type="submit" class="submit" name="sa" value="" />
						</p>
					</form>
				</div>
			</div>
			<script type="text/javascript" src="http://www.google.de/coop/cse/brand?form=cse-search-box&amp;lang=de"></script><div id="m1New">
	<div class="ms"></div>
	<a href="/antenne/home/home/index.php" id="menu1">&nbsp;</a>
	<div class="ms"></div>
	<a href="/antenne/radio/home/index.php" id="menu8">&nbsp;</a>
	<div class="ms"></div>
	<a href="/antenne/musik/stars/index.php" id="menu9">&nbsp;</a>
	<div class="ms"></div>
	<a href="/antenne/news/nachrichten/index.php" id="menu4">&nbsp;</a>
	<div class="ms"></div>
	<a href="/eventkalender/" id="menu10">&nbsp;</a>
	<div class="ms"></div>
	<a href="/antenne/mediathek/all/index.php" id="menu11">&nbsp;</a>
	<div class="ms"></div>
	<a href="/antenne/spiele/spiele/index.php" id="menu6">&nbsp;</a>
	<div class="ms"></div>
	<a href="/club/" id="menu7">&nbsp;</a>
	<div class="ms"></div>
</div>

<!-- Status -->	</div>	</div>
   		<div class="newcontent">
			<div class="newcontentBody">
				<div class="newcontentBodyL">		
					<script type="text/javascript">
					// <![CDATA[
					function slide(className, id) {
						var dds = document.getElementById('mnBox').getElementsByTagName('div');

						for (var d = 0; d < dds.length; d++) {
							if (dds[d].className == className && dds[d].id != className + id) {
								dds[d].style.display = 'none';
							}
						}

						if ($(className+id).style.display == 'none') // open
							new Effect.SlideDown(className + id);
						else // close if it's open
							new Effect.SlideUp(className + id);
					}
					// ]]>
					</script>

					
					<!--LAST MODUL--><div class="lightBox">
	<div class="lightBoxBody">
		<div class="lightBoxTitle">
			<h1>Verzeihung! Dies ist die Fehlerseite!</h1>
		</div>
		
		<div class="lightBoxText">
			
			Sie sind nicht dort, wo Sie eigentlich hin wollten, denn dies ist die Fehler-Seite von antenne.de!<div style='height:5px;'></div>Die Startseite von ANTENNE BAYERN erreichen Sie mit einem Mausklick <a href='/antenne/home/home/index.php' class='arrow'>hier</a><div style='height:5px;'></div><b>Was ist passiert?</b><div style='height:5px;'></div>Kommen Sie möglicherweise von einer anderen Website, die einen veralteten Link auf eine Unterseite von antenne.de gesetzt hat?<br>Dann wäre es nett, wenn Sie den Betreiber der Seite darauf aufmerksam machen würden.<div style='height:5px;'></div>Haben Sie sich vielleicht einfach nur bei der Eingabe der URL vertippt?<br>Hey, das passiert uns auch öfters mal! ;-) <div style='height:5px;'></div>Stimmt ein Link innerhalb des antenne.de-Angebotes nicht?<br>Mist, da haben wir wohl was falsch gemacht! Damit wir den Fehler möglichst rasch beheben können, würden wir uns über einen Hinweis per E-Mail freuen: <br><a href='mailto:support@antenne.de' class='arrow'>support@antenne.de</a><div style='height:5px;'></div>In jedem Fall: Sorry - und vielen Dank für Ihr Verständnis.<div style='height:5px;'></div>Dennoch viel Spass beim Weitersurfen wünscht Ihnen<br>Das ANTENNE BAYERN Online-Team !<div style='height:5px;'></div>
			
			<div style='height:9px;'></div>
			
			<a href="/antenne/home/home/index.php" class="button"><span class="bl"> zurück zu antenne.de</span><span class="br">&nbsp;</span></a><umbruch />
		</div>
	</div>
	<div class="lightBoxBottom"></div>
</div><!--LAST MODUL--><div class="hr"></div>
			<div style="position:relative;left:-3px">
				  <div class="boxBlueLarge">
            <div class="top"></div>
            <div class="body">
            <h3>Empfehlungen von ANTENNE BAYERN</h3>
            
           <div style="float:left;width:220px">
	           &raquo; <a href="/antenne/news/versicherungsvergleich/jetztvergleichen_2011.php">Sparen und Vergleichen</a><br>
	           &raquo; <a href="/antenne/musik/stars/index.php">Musik Downloads</a><br>
	           &raquo; <a href="/eventkalender/">Eventkalender</a><br>
	           &raquo; <a href="http://www.shirtcity.de/shop/antenne-bayern" target="_blank">Fan-Shop</a><br>
	           &raquo; <a href="/antenne/radio/aktionen/abyhilft_home.php">Soziales Engagement</a><br>
	           &raquo; <a href="/antenne/news/service/jobs_bei_antenne.php">Jobs bei ANTENNE BAYERN</a><br>
           </div>
           <div style="float:left;width:230px">              
                &raquo; <a href="/antenne/news/wetter/index.php">Wetter in Bayern</a><br>
                &raquo; <a href="/antenne/news/verkehr/meldungen_bayern.php">Verkehr in Bayern</a><br>
                &raquo; <a href="/comedy/Mittwoch-ist-Mittermeier-Tag__mittermeiertag_468229_radio.html">Mittwoch ist Mittermeier-Tag</a><br>
                &raquo; <a href="/antenne/news/horoskop/index.php">Tageshoroskop kostenlos</a><br>
              	&raquo; <a href="/antenne/news/horoskope/liebeshoroskop.php">Liebeshoroskop kostenlos</a><br>
              	&raquo; <a href="/jahreshoroskop_2012_uebersicht/Das-bringen-Ihnen-die-Sterne-2012__horoskope2012_454967_news.html">Jahreshoroskop 2012 kostenlos</a><br>
              	&raquo; <a href="/langemann_late_night/Neu-auf-ANTENNE-BAYERN-Langemann-Late-Night-__aktionen_380937_radio.html">Langemann Late Night</a><br>
              	
           </div>
            </div>
            <div class="bottom"></div>
          </div>
        </div>
        </div>
<div class="newcontentBodyR">
					
					
					
					
					
					
					
	
					
					
					
					
					
					
					
					<div style="clear:left;"></div>
									
						<div style="clear:left;"></div>
									
	<div name="msie_bug" style="position:relative;top:0px;left:2px;margin-top:5px;margin-bottom:25px;text-align:center;height:250px;width:300px">
		<iframe src="http://www.antenne.de/cf/scripts/contentadd_box.php" scrolling="no"  width="300" height="260" frameborder="0"></iframe>

</div>
				</div>			</div>
<div class="newcontentBottom"></div>		</div>
		<div id="adsdf_810_250_95_f" style="width:810px; height:1px;display:none; margin-top: 12px;"></div>
<div id="footer">
	<ul>
		<li class="first">&copy;2012 ANTENNE BAYERN</li>
		<li><a href="/antenne/radio/kontakt/index.php">Kontakt</a></li>
		<li><a href="/antenne/radio/impressum/index.php">Impressum</a></li>
		<li><a href="/antenne/kontakt/agb/rechtliche_hinweise.php">Rechtliche Hinweise</a></li>

		
		<li class="last"><a href="http://www.spotcom.de/" target="_blank">Werben auf ANTENNE BAYERN</a></li>
	</ul>
	<a href="http://www.space.net/" target="_blank" class="hostedby"><img src="/antenne/incl/css/hosted_by.png" alt="hosted by SpaceNet AG" /></a>
</div>


	</div>
</div>








<script language="Javascript">
if(typeof oms_site=='undefined'){oms_site='pn.antennebayern.de';};
if(typeof btcode=='undefined'){btcode=''};
if(typeof oms_zone=='undefined'){oms_zone='entertainment';};
if(typeof WLRCMD=='undefined'){WLRCMD=''};
var wsite=oms_site;
var ccat=btcode;
var oms_random=Math.floor(Math.random()*10000000000);

document.write('<scr'+'ipt src="http://oms.nuggad.net/rc?nuggn=1615459509&nuggtg='+encodeURIComponent(oms_zone)+'" type="text/javascript"></scr'+'ipt>');
</script>
<div style="position:absolute;top:0px;left:0px;"><div style="position:absolute;left:0px;top:0px;width:795px;">
<!------- Start of OMSV - Javascript Format , size : 728x90 ------>
<table cellspacing="0" cellpadding="0" border="0" width="728" height="90"><tr>
<td valign="top" border="0" width="728" height="90">
<script language="JavaScript">
   if(typeof(WLRCMD)=="undefined"){var WLRCMD="";}
   if(typeof(rmsi_random)=="undefined"){var rmsi_random=Math.floor(Math.random()*10000000000)}
   document.write('<scr'+'ipt language="JavaScript" src="http://ad.de.doubleclick.net/adj/pn.antennebayern.de/entertainment;rmsi=entertainment;nielsen=4;dcopt=ist;'+WLRCMD+';sz=728x90;tile=1;ord='+rmsi_random+'?"><\/scr'+'ipt>');
</script><noscript>
<a href="http://ad.de.doubleclick.net/jump/pn.antennebayern.de/entertainment;rmsi=entertainment;nielsen=4;sz=728x90;tile=1;ord=933474005996?" target="_blank">
<img src="http://ad.de.doubleclick.net/ad/pn.antennebayern.de/entertainment;rmsi=entertainment;nielsen=4;sz=728x90;tile=1;ord=933474005996?" border="0" width="728" height="90">
</a></noscript></td></tr></table>
<!------- End of OMSV Tag - Javascript Format, size : 728x90 ------>
</div>


<!-- ADTAG: SKYSCRAPER Start-->
<div style="position:absolute; top:125px; left:830px; z-index:998;">
	<!------- Start of OMSV - Javascript Format , size : 120x600 ------>
<table cellspacing="0" cellpadding="0" border="0" width="120" height="600"><tr>
<td valign="top" border="0" width="120" height="600">
<script language="JavaScript">
   if(typeof(WLRCMD)=="undefined"){var WLRCMD="";}
   if(typeof(rmsi_random)=="undefined"){var rmsi_random=Math.floor(Math.random()*10000000000)}
   document.write('<scr'+'ipt language="JavaScript" src="http://ad.de.doubleclick.net/adj/pn.antennebayern.de/entertainment;rmsi=entertainment;nielsen=4;'+WLRCMD+';sz=120x600;tile=2;ord='+rmsi_random+'?"><\/scr'+'ipt>');
</script><noscript>
<a href="http://ad.de.doubleclick.net/jump/pn.antennebayern.de/entertainment;rmsi=entertainment;nielsen=4;sz=120x600;tile=2;ord=933474005996?" target="_blank">
<img src="http://ad.de.doubleclick.net/ad/pn.antennebayern.de/entertainment;rmsi=entertainment;nielsen=4;sz=120x600;tile=2;ord=933474005996?" border="0" width="120" height="600">
</a></noscript></td></tr></table>
<!------- End of OMSV Tag - Javascript Format, size : 120x600 ------>
</div>
<!-- ADTAG: SKYSCRAPER Ende-->
</div>




<!-- SZM VERSION="1.5" -->
<script type="text/javascript">
<!--
var IVW="http://antenne.ivwbox.de/cgi-bin/ivw/CP/1";
document.write("<img src=\""+IVW+"?r="+escape(document.referrer)+"&d="+(Math.random()*100000)+"\" width=\"1\" height=\"1\" alt=\"szmtag\" name=\"szmimages\" id=\"szmimages\"/>");
//-->
</script>
<noscript>
<img src="http://antenne.ivwbox.de/cgi-bin/ivw/CP/1" width="1" height="1" alt="szmtag" name="szmimages" id="szmimages" />
</noscript>
<!-- /SZM -->

<!-- SZMFRABO VERSION="1.1" -->
<script type="text/javascript">
	var szmvars="antenne//CP//"+ivw_seite;
</script>
<script type="text/javascript" src="http://antenne.ivwbox.de/2004/01/survey.js"></script>
<!-- /SZMFRABO -->
<!-- KAM VERSION="0.3" -->
<script type="text/javascript"><!--
function AGOF_keepAlive(x) {
document.getElementById('SZMDIV').innerHTML='<img src=\"' + x.replace('/ivw/CP','/ivw/VP') + '&d='+Math.random().toString(36)+ '\" width=\"1\" height=\"1\">';
}
document.write('<div id="SZMDIV"></div>');
setInterval("AGOF_keepAlive(IVW)", 60000);
// --></script>
<!-- /KAM -->
<!-- Facebook Stuff -->
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-25742830-1']);
  _gaq.push(['_setDomainName', 'antenne.de']);
  _gaq.push (['_gat._anonymizeIp']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<div id="fb-root"></div>
<script type="text/javascript">
window.fbAsyncInit = function(){
    FB.init({ appId:'236351849788068', status:true, cookie:true, xfbml:true }); 
    FB.getLoginStatus(function(response) {
        _gaq.push(['_trackEvent', 'FB', 'status', response.status, 1, true]);
    });
};
 
(function(d){
   var js, id = 'facebook-jssdk'; if (d.getElementById(id)) {return;}
   js = d.createElement('script'); js.id = id; js.async = true;
   js.src = "//connect.facebook.net/de_DE/all.js";
   d.getElementsByTagName('head')[0].appendChild(js);
 }(document));
</script>
</body>
</html>