<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de">
 
 
 
    
 
 

 
 
  
 <head><title>Die gesuchte Seite gibt&#39;s nicht mehr... - 1LIVE</title>
<!-- Metainformationen -->
<meta http-equiv="content-type" content="text/html; charset=ISO-8859-1" />
<meta http-equiv="content-script-type" content="text/javascript" />
<meta http-equiv="content-style-type" content="text/css" />

<meta name="Language" content="de" />
<meta name="Keywords" content="Radio, Eins Live, einslive, 1LIVE, WDR" />
<meta name="Description" content="Radio 1LIVE - Das junge Radio des WDR." />


<meta name="Author" content="Eins Live" />
<meta name="Publisher" content="Westdeutscher Rundfunk" />
<meta name="DC.Date" content="2011-11-06T14:25:32Z" />
<meta name="googlebot" content="noarchive" />
<meta name="robots" content="index,follow,noarchive" />

<link rel="start" href="http://www.einslive.de" title="Startseite 1LIVE" />



<link rel="bookmark" href="http://www.wdr.de/themen/homepages/homepage.jhtml" title="WDR.de" />
<link rel="bookmark" href="http://www.wdr.de/tv/" title="WDR Fernsehen" />
<link rel="bookmark" href="http://www.wdr.de/radio/" title="WDR Radioprogramme" />
<link rel="bookmark" href="http://www.wdr.de/themen/homepages/epg.jhtml" title="WDR Programmvorschau" />

<link rel="bookmark" href="http://www.wdr.de/unternehmen/" title="Informationen über das Unternehmen WDR" />

<link rel="bookmark" href="#top" title="Zum Seitenanfang" />
<link rel="bookmark" href="#inhalt" title="Zum Seiteninhalt" />

<link rel="contents" href="http://www.wdr.de/themen/global/inhalt/" title="Inhaltsverzeichnis" />
<link rel="bookmark" href="/impressum/" title="Impressum" />

<link rel="apple-touch-icon" href="http://www.einslive.de/img/1live_iphone.png" />

<link rel="search" href="http://suchen.wdr.de" title="Suche im WDR Online Angebot" />
<link rel="help" href="http://www.wdr.de/themen/global/hilfe/start.jhtml" title="Hilfe zur Bedienung und Orientierung" />
<link rel="copyright" href="http://www.wdr.de/themen/global/urheber/" title="Copyright" />

<link rel="icon" href="/codebase/nav/favicon.ico" type="image/ico" />
<link rel="shortcut icon" href="/codebase/nav/favicon.ico" />

        <!--[if gt IE 6 & lt IE 9]>
            <link rel="stylesheet" type="text/css" href="/codebase/css/2011/wrapper/live_ie.css" />
        <![endif]-->
        <!--[if gte IE 9]>
            <link rel="stylesheet" type="text/css" href="/codebase/css/2011/wrapper/live.css" />
        <![endif]-->
        <!--[if !IE]> <-->

            <link rel="stylesheet" type="text/css" href="/codebase/css/2011/wrapper/live.css" />
        <!--> <![endif]-->
        <link rel="stylesheet" type="text/css" href="/codebase/js/lib/jQuery/themes/base/jquery.ui.all.css" />

        <!-- Attach CSS Feature -->
        <link rel="stylesheet" type="text/css" href="/codebase/js/lib/Orbit_Kit/orbit_1.1.css" />

        <!-- Lightbox CSS -->

        <link rel="stylesheet" type="text/css" href="/codebase/js/lib/lightbox/css/style.css" />

        <!--[if IE]>
          <style type="text/css">
            .mask { display: none !important; }
          </style>
        <![endif]-->

        <!-- jQuery -->
        <script type="text/javascript" src="/codebase/js/lib/jQuery/jquery-1.4.4.min.js"></script>
        <script type="text/javascript" src="/codebase/js/lib/jQuery/ui/jquery.ui.core.js"></script>
        <script type="text/javascript" src="/codebase/js/lib/jQuery/ui/jquery.ui.widget.js"></script>
        <script type="text/javascript" src="/codebase/js/lib/jQuery/ui/jquery.ui.tabs.js"></script>
        <!-- jScroll -->
        <script type="text/javascript" src="/codebase/js/lib/jScroll/jquery.scrollTo-1.4.2-min.js"></script>


        <!-- Lightbox -->
        <script type="text/javascript" src="/codebase/js/lib/lightbox/ui.ariaLightbox_min.js"></script>

        <!-- Require Script-->
        <script type="text/javascript" charset="utf-8" src="/codebase/js/plugins/jquery.requireScript-1.2.1.min.js"></script>
        <!-- Browsercheck + Player -->
        <script type="text/javascript" src="/codebase/js/module/basic.js"></script>
        <!-- DOM -->
        <script type="text/javascript" src="/codebase/js/module/dom.js"></script>
        <!-- Ticker -->
        <script type="text/javascript" src="/codebase/js/module/ticker.js"></script>
        <!-- Feature Voodoo -->
        <script type="text/javascript" src="/codebase/js/lib/Orbit_Kit/jquery.orbit.min.js"></script>
				<!-- Moving Boxes -->
  			<link type="text/css" href="/codebase/js/lib/moving_boxes/movingboxes.css" media="screen" rel="stylesheet"  />
  			<script type="text/javascript" src="/codebase/js/lib/moving_boxes/jquery.movingboxes.min.js"></script>

        <script type="text/javascript">
        <!-- <![CDATA[

           $(document).ready(function() {

                // Swap DOM-Elements
                if (jQuery.isFunction($.fn.swapWith)) {
                    // Swap H3-H4 in Teaser
                    var wsTeaserCont = $('#wsContentArea .wsTeaserCont');
                    $.each(wsTeaserCont, function(index, value) {
                    var a = $(wsTeaserCont[index]).find('h3');
                    var b = $(wsTeaserCont[index]).find('h4');
                    if (a.length > 0 && b.length > 0){
                    $(a).swapWith($(b));
                    }
                    });
                    // Swap H3-H4 in TeaserL
                    var wsTeaserContL = $('.wsTeaserContL');
                    $.each(wsTeaserContL, function(index, value) {
                    var a = $(wsTeaserContL[index]).find('h3');
                    var b = $(wsTeaserContL[index]).find('h4');
                    if (a.length > 0 && b.length > 0){
                    $(a).swapWith($(b));
                    }
                    });
                    // Swap H3-H4 in TeaserR
                    var wsTeaserContR = $('.wsTeaserContR');
                    $.each(wsTeaserContR, function(index, value) {
                    var a = $(wsTeaserContR[index]).find('h3');
                    var b = $(wsTeaserContR[index]).find('h4');
                    if (a.length > 0 && b.length > 0){
                    $(a).swapWith($(b));
                    }
                    });
                    // Swap H1-H2 auf Beitragsseiten
                    if ($('#wsProlog h2').length) {
                     $('#wsProlog h1').swapWith('#wsProlog h2');
                    }

                }

                // Tablescroller für Sendeschema
                if(jQuery.isFunction($.fn.scrollTo)) {

                       	//Scrollbalken verstecken
                        $('#wsSendeschemaFussInner').css( {overflow:'hidden'});

                       	//Scroller Init
                        $('#wsSendeschemaFuss table').scrollTo(0);

                       		//Buttons
                        $('#wsSendeschemaFuss').append('<div id="wsSchemazurueck"><\/div>');
                        $('#wsSendeschemaFuss').append('<div id="wsSchemavor"><\/div> ');

                        var offsetLeft = $('#wsSendeschemaFuss table').width() / 3;

                        function scroll(direction){
                        if (direction == 'wsSchemavor') {
                                $('#wsSendeschemaFussInner').scrollTo({
                                        top: '0',
                                        left: '+=' + offsetLeft
                                }, 800);
                        }

                        if (direction == 'wsSchemazurueck') {
                                $('#wsSendeschemaFussInner').scrollTo({
                                        top: '0',
                                        left: '-=' + offsetLeft
                                }, 800);
                        }
                }
                // Click Handler
                $("#wsSchemazurueck,#wsSchemavor").live('click', function(){
                        return scroll($(this).attr('id'));
                });

                // Zusatzinfos Voodoo
                $('#wsSendeschemaFussInner .wsSchemaInfos').addClass('js');
                $('#wsSendeschemaFussInner .wsSchemaInfos strong').after($('<span class="wsELPink">[<a class="showMoreInfos" title="mehr zur Sendung" href="#">mehr<\/a>]<\/span>'));
                $('.showMoreInfos').live('click', function() {

                        // Alte Infos entfernen
                        $('#wsSchemaMehrID').remove();

                        var offset = $(this).offset();
                        var position = $(this).position();
                        var bubble = "wsBubble";

                        //Klick < 300px
                        if (offset.left<"300") {
                                var offsetLeft = offset.left-110;
                                var bubble = "wsBubble_L";
                        }
                        //Klick > 1000px
                        else if (offset.left>"1000") {
                                var offsetLeft = offset.left-420;
                                var bubble = "wsBubble_R";
                        }
                        else {
                                var offsetLeft = offset.left-190;
                        }

                        var clone = $(this).parent().next().next().clone(); //.wsSchemaMehr
                        var positionBottom = 30;

                        $('#wsSendeschemaFussInner').after('<div class="wsSchemaMehr" id="wsSchemaMehrID"><div class="wsSchemaMehrCont"><div class="wsSchemaClose"><span class="hidden">Zusatzinfos schließen: <\/span>X<\/div>'+$(clone).text()+'<\/div><\/div>');
                        $('#wsSchemaMehrID').css({'left' : offsetLeft, 'bottom' : positionBottom});
                        $('#wsSchemaMehrID').append('<div class="'+bubble+'">&nbsp;<\/div>');

                        $('#wsSchemaMehrID').show();

                        $('.wsSchemaClose').live('click', function(){
                                $('#wsSchemaMehrID').remove();
                        });

                        return false;
                });
                }


                // Current Time for Sendeschema
                function checktime(){
                        var now = new Date();
                        var hours = now.getHours();
                        var minutes = now.getMinutes();

                        clock_slide(hours, minutes);

                        function clock_slide(hours, minutes){
                                jQuery('#wsSendeschemaTimer').css("left", (hours*92)+(minutes*1.52)); // ->60 Minuten im bg_schema
                        };

                        setTimeout(function(){checktime();},250);
                };

                if($('#heute').length){
												var now = new Date();
                        var hours = now.getHours();
                        var minutes = now.getMinutes();
                        jQuery('#wsSendeschemaFussInner').append("<img alt='Aktuelle Zeit' id='wsSendeschemaTimer' src='/codebase/img/icons/timer.png' />");
												$('#wsSendeschemaFussInner').scrollTo({top: '0', left: hours*50}, 800);
                        checktime();
                }

                // Initialise feature via orbit
                if(jQuery.isFunction($.fn.orbit)) {

                    var feature_count=$('#featured .orbit-caption').length;
                    //show functions
                    if (feature_count > "1") {
                                $('#featured').orbit({
                                        'bullets': true,
                                        'timer': true,
                                        'animation': 'fade'
                                });
                    }
                    else {
                                $('#featured').orbit({
                                        'bullets': true,
                                        'timer': false,
                                        'animation': 'fade'
                                });
                          }
                }

              // Initialise ticker
              if(checkAjax()) {
					addJSTicker();
					ticker = document.getElementById("wsTicker").style;
					ticker2 = document.getElementById("wsTicker2").style;
					//ticker.marginLeft = 275 + 'px';
					getTickerText(txtFile);
					moveIt();
					$('#wsTickerSteuerung').click(function() {
						$(this).toggleClass('pause');
						if ( $('#wsTickerSteuerung').hasClass('pause') ) {stopTicker();}
						else {startTicker();}
					});
					$('#wsTickerSteuerung2').click(function() {
						$(this).toggleClass('pause');
						if ($('#wsTickerSteuerung2').hasClass('pause')) {stopTicker();}
						else {startTicker();}
					});
               }

              // Insert Print-Link
              if(window.print) {
                $('#wsFunction ul:first li:first').after('<li id="wsPrint"><a href="javascript: window.print();">Seite drucken<\/a><\/li>');
              }
              // Change Header
              //if(jQuery.isFunction(changeHeaderPosition)) {
              //  changeHeaderPosition();
              //}
              // Fill Forms
              if(jQuery.isFunction(setNaviSearchForm)) {
                setNaviSearchForm();
              }
              // Set Link Attributes
              if(jQuery.isFunction(setLinkAttributes)) {
                setLinkAttributes();
              }

            //show hide Bewertungsschema
            $('.wsBewertungsSchemaEL ul').hide();
            $('.wsBewertungsSchemaEL p').css('cursor', 'pointer');
            $('.wsBewertungsSchemaEL p').click(function(){
                    $(this).toggleClass('aktiv').parent().find('ul').slideToggle('slow');
            });

            // Lightbox Init
            $("#wsContentArea").ariaLightbox({
                    imageArray: "a.seriesLightbox",
                    useDimmer: true,
                    background: "#000000",
                    zIndex: 1000,
                    background: "black",
                    opacity: 0.8,
                    prevText: "zurück",
                    nextText: "vor",
                    em: 0.0758
            });
            // Activate Lightbox via Lupe
            $('.triggerLightbox').click(function() {
                    $(this).prev(".seriesLightbox").trigger("click");
                    return false;
            });


            $.requireScript('/codebase/js/plugins/detect_flash.min.js',function() {
                    //Flashfallback für Promoteaser
                    if($hasRequiredFlashVersion==false) {
                            if(jQuery.isFunction($.fn.movingBoxes)) {
                                $('#slider-one').movingBoxes({
                                    startPanel   : 4,      // start with this panel
                                    width        : 920,    // overall width of movingBoxes (not including navigation arrows)
                                    panelWidth   : .4,     // current panel width adjusted to 70% of overall width
                                    reducedSize  : 0.6,       // non-current panel size: 80% of panel size
                                    imageRatio   : 16/9,      // Image ration set to 1:1 (square image)
                                    wrap         : true,   // if true, the panel will "wrap" (it really rewinds/fast forwards) at the ends
                                    buildNav     : false,   // if true, navigation links will be added
                                    panelType    : '> li', // selector to find the immediate ">" children "li" of "#slider-one" in this case
                                    //navFormatter : function(){ return "&#9679;"; } // function which returns the navigation text for each panel
                                    completed : function(e, slider, tar) {
                                                    //$("#slider-one img").reflect();
                                    }
                                            });
                                    }
                    }
            });

            });
        // ]]> -->
        </script>







</head><body>
<!--[if lt IE 7]>
        <p id="ieAlert">
        Lieber Nutzer,<br />
        leider nutzen Sie eine veraltete Version Ihres Browsers. Deshalb können die an dieser Stelle vorgesehenen Inhalte nicht korrekt dargestellt werden. Bitte aktualisieren Sie auf eine aktuelle Version.
        Unter <a href="http://www.browserchoice.eu/">http://www.browserchoice.eu/</a> stehen alternative Browser zur Verfügung.
        Für eine Installation benötigen Sie gegebenenfalls Administrator-Rechte.</p>
        </p>
    <![endif]--><!--googleoff: index-->
<div class="inv">
<script type="text/javascript">
var IVW="http://wdr.ivwbox.de/cgi-bin/ivw/CP/;www.einslive.de/sitemap/fehler.jsp";
<!-- <![CDATA[
document.write("<img src=\""+IVW+"?r="+escape(document.referrer)+"\" width=\"1\" height=\"1\" alt=\"\" />");
//]]> -->
 </script><noscript><div><img src="http://wdr.ivwbox.de/cgi-bin/ivw/CP/;www.einslive.de/sitemap/fehler.jsp" width="1" height="1" alt="" /></div></noscript>

</div><p><a name="top" id="top"></a></p>
<p class="inv"><strong>Skiplinks / Sprungmarken</strong></p>
<ul class="inv">
<li><a href="#inhalt">Zum Inhalt</a></li>
<li><a href="#themen">Zur Themennavigation</a></li>
<li><a href="#mm">Multimedianavigation</a></li>
<li><a href="#service">Servicenavigation</a></li>
<li><a href="#re">Programmhinweise, weitere Themen und Fotos</a></li>
<li><a href="#elcom">Zum Community Login</a></li>
<li><a href="#elsuche">Zur 1LIVE Suche</a></li>
</ul>
<hr class="inv" />

<div id="wsContentBGOuter">

        <div id="wsQuerNaviU" class="wsQuerNavi">
          <a name="mm" id="mm"></a>
          <ul>
            <li class="webradio">
              <a href="/sendungen/player/EinsLivePlayer.html" rel="www" onclick="window.open(this.href,'radio','width=545,height=365,xsize=450,screenX=150,screenY=150,top=150,left=150,menubar=1,scrollbars=0,resizable=1,statusbar=1,locationbar=1'); return false;"><span lang="en">Webradio</span></a>
            </li>
            <li class="playlists">
              <a href="/musik/playlists/"><span lang="en">Playlist</span></a>
            </li>
            <li class="webcam">
              <a href="/sendungen/webcam/"><span lang="en">Webcam</span></a>
            </li>
          </ul>
        </div>
        <hr class="inv" />
        <div class="clearMe">
        </div>

        <div id="wsContentBGInner">
          <div id="wsKopf">
            <div id="wsBanner">
              <img src="/codebase/nav/2006/logo_print.gif" id="wsLogoPrint" alt="Drucker" />

                  

              

                <img src="/bilder/mediendb/1live/keyvisuals/1LIVE_image_banner.jpg" class="wsIMG968b" alt="Lautsprecher vor blauem Himmel, aufgenommen in einem Freibad in Köln, WDR/Knoff" />
                <a href="/" title="Link zur Startseite von 1LIVE">
                   <img id="wsLogoNoPrint" src="/codebase/nav/2006/logo_inv.png" class="wsIMG240b" alt="1Live-Logo; Rechte: WDR" />
                </a>


              
            </div>
          </div>

<hr class="inv" />
<!-- NAVI START -->

<div id="wsNavi">
  <ul class="wsSpezial extra">
    <li>
      <span class="aktiv"><span class="inv">1</span>Live</span>
    </li>
    <li>
      <a href="/medien/html/1live/index.xml"><span class="inv">1</span>Live Fernseher</a>
    </li>
    <li>
      <a href="http://freundeskreis.einslive.de/" rel="www"><span class="inv">1</span>Live Freundeskreis</a>
    </li>
     <li>
      <a href="http://tippspiel.einslive.de/" rel="www"><span class="inv">1</span>Live EM-Tipp</a>
    </li>
  </ul>
  <a name="elsuche" id="elsuche"></a>
  <form action="/suche.jsp" method="get">
      <fieldset id="wsSuchen">
          <legend>
              <strong>Eins Live Suche</strong>
          </legend>
          <label for="suche" class="inv">
              Suchbegriff:
          </label>

          <input type="text" id="suche" name="q"/>
          <!-- <input type="submit" value="suchen" class="wsFormBut" id="wsSuchenSubmit" />-->
          <input type="image" id="wsSuchenSubmit" class="wsFormBut" alt="Suchen" src="/codebase/img/icons/suche_lupe.gif" />
          <label for="wsSuchenSubmit">
              Suchen
          </label>
      </fieldset>
      <div class="clearMe">
      </div>

      <hr class="inv" />
  </form>
  
  <hr class="inv" />
  <p class="inv">
      <a name="themen" id="themen"></a>
  </p>
  <p class="inv">
      <strong>Themennavigation</strong>
  </p>


  <ul class="wsHauptnavi">
      <li><a href="/index.jsp">Startseite</a></li><li><a href="/magazin/">Magazin</a><ul>
<li><a href="/magazin/nachrichten/">Nachrichten</a></li><li><a href="/magazin/pop/">Pop</a></li><li><a href="/magazin/sport/2012/em/index.jsp">EM 2012</a></li><li><a href="/magazin/kino/">Kino</a></li><li><a href="/magazin/dvd/">DVD</a></li><li><a href="/magazin/literatur/">Literatur</a></li><li><a href="/magazin/interviews/">Interviews</a></li><li><a href="/magazin/spiele/">Spiele</a></li><li><a href="/magazin/sport/">Sport</a></li><li><a href="/magazin/mitwisser/">Endlich Mitwisser</a></li><li><a href="/magazin/netzthemen/">Netz-Themen</a></li><li><a href="/magazin/kolumne/index.jsp" class="wsLast">Kolumne Herr Nieswandt</a></li></ul>
</li>
<li><a href="/musik/">Musik</a><ul>
<li><a href="/musik/playlists/">Playlists</a></li><li><a href="/musik/platten/">Plattencheck</a></li><li><a href="/musik/interviews/">Interviews</a></li><li><a href="/musik/charts/">Charts</a></li><li><a href="/musik/neu_fuer_den_sektor/">Neu für den Sektor</a></li><li><a href="/musik/konzert_galerien/">Konzert-Galerien</a></li><li><a href="/musik/heimatkult/">Heimatkult</a></li><li><a href="http://www.einslivekrone.de/" class="wsLast">1LIVE Krone</a></li></ul>
</li>
<li><a href="/comedy/">Comedy</a><ul>
<li><a href="/comedy/o_ton_charts/">O-Ton-Charts</a></li><li><a href="/comedy/noob_und_nerd/">Noob und Nerd</a></li><li><a href="/comedy/tony_mono/">Tony Mono</a></li><li><a href="/comedy/em_fan_radio/index.jsp">Das EM-Fan-Radio</a></li><li><a href="/comedy/kraftklub/index.jsp">Kraftklub</a></li><li><a href="/comedy/kebekus/index.jsp">Die Kebekus</a></li><li><a href="http://www.einslive.de/comedy/werkerpedia/index.jsp">Werkerpedia</a></li><li><a href="http://www.einslive.de/comedy/sektormaehn/120120_sektormaehn.jsp">Sektormähn</a></li><li><a href="/comedy/die_bundesliga_in_90_sekunden/index.jsp">Die Bundesliga in 90 Sekunden</a></li><li><a href="/comedy/dennis/dennis_comedy_index.jsp">Dennis ruft an</a></li><li><a href="http://www.einslive.de/comedy/schroeders_netzwerk/index.jsp">Schroeders Netzwerk</a></li><li><a href="http://www.einslive.de/comedy/1live_freak/index.jsp" class="wsLast">1LIVE Freak</a></li></ul>
</li>
<li><a href="/aktionen/">Aktionen</a><ul>
<li><a href="/aktionen/termine/">Termine</a></li><li><a href="/aktionen/termine/sektor_events/">Sektor-Events</a></li><li><a href="/aktionen/termine/events/">1LIVE-Veranstaltungen</a></li><li><a href="/aktionen/termine/1live_partys/1live_partys.jsp">1LIVE-Partys</a></li><li><a href="/aktionen/2012/nacht_in/">Eine Nacht in Dortmund</a></li><li><a href="/aktionen/2012/04/1live_autokino/index.jsp">1LIVE Autokino</a></li><li><a href="/aktionen/schulduell/2012/finale/index.jsp" class="wsLast">Schulduell</a></li></ul>
</li>
<li><a href="/sendungen/">Sendungen</a><ul>
<li><a href="/sendungen/studiogaeste/index.jsp">Studiogäste </a></li><li><a href="/sendungen/diggi/">Diggi</a></li><li><a href="/sendungen/plan_b/talk/">Plan B Talk</a></li><li><a href="/sendungen/plan_b/reportage/">Plan B Reportage</a></li><li><a href="/sendungen/plan_b/krimi/index.jsp">Plan B Krimi</a></li><li><a href="/sendungen/plan_b/shortstory/">Plan B Shortstory</a></li><li><a href="/sendungen/plan_b/soundstories/">Plan B Soundstories</a></li><li><a href="/sendungen/musiksendungen/index.jsp">Musiksendungen</a></li><li><a href="/sendungen/1live_elfer/index.jsp">1LIVE Elfer</a></li><li><a href="/sendungen/klubbing/">Klubbing</a></li><li><a href="/sendungen/domian/">Domian</a></li><li><a href="/sendungen/podcasts/">Podcasts</a></li><li><a href="/sendungen/webcam/">Webcam</a></li><li><a href="/sendungen/sendeschema/">Sendeschema</a></li><li><a href="/sendungen/frequenzen/" class="wsLast">Frequenzen</a></li></ul>
</li>
<li><a href="/team/">Team</a><ul>
<li><a href="/team/kontakt/">Kontakt</a></li><li><a href="/team/moderatoren/">Moderatoren</a></li><li><a href="/team/jobs/" class="wsLast">Jobs</a></li></ul>
</li>

  </ul>
</div>
<hr class="wsTrenner" />
<!-- tN: 0 -->


<!-- kg_seiteurl  -->


<hr class="inv" />
<!-- NAVI ENDE -->
<!-- tH: 2 -->
 
 
 

<!--googleon: index-->
<!-- CONTENT START -->
<div id="wsContentArea" class="  wsFormulare">

<!--art :null-->


<p><a name="inhalt" id="inhalt"></a></p>
<p class="wsTrenner"><strong>FEHLERSEITE</strong></p>
<div id="wsProlog"><h1>Die gesuchte Seite gibt&#39;s nicht mehr...</h1>
</div>
  <p>Liebe Nutzer,</p>
<p>leider können wir euch die gewünschten Seite nicht mehr anbieten.  Der neue Rundfunkstaatsvertrag (1.6. 2009) untersagt uns als öffentlich-rechtlicher Anbieter eine Reihe von Inhalten in Videotext und Internet. In einer so genannten Negativliste als Anlage zum Rundfunkstaatsvertrag sind konkrete Verbote festgelegt. Im Gesetzestext werden weitere Einschränkungen gemacht, die bestimmte Inhalte problematisieren.  Bitte habt Verständnis dafür, dass wir im Rahmen einer Fehlerseite nicht konkret auf den jeweils zutreffenden Grund für die Löschung des von euch gesuchten Inhaltes eingehen können. Wenn ihr es genauer wissen wollt, schreibt uns bitte eine Mail an "<a href="mailto:warumweg@wdr.de">warumweg@wdr.de</a>".</p>
<div class="clearMe"></div>
<div class="wsMZT">
<ul class="wsLinkliste wsLiteColor"><li class="wsFirst"><img class="wsIcon" alt="WDR" src="/codebase/nav/2006/ffe5f5_f09/wdrext.gif"><span class="wsInner"><a rel="www" href="http://www.wdr.de/themen/kultur/rundfunk02/staatsvertrag_zwoelfter/index.jhtml" title="Link öffnet in neuem Fenster" target="_blank">Weitere Informationen zum 12. Rundfunkänderungsstaatsvertrag
findet ihr bei WDR.de</a></span></li><li><img class="wsIcon" alt="WDR" src="/codebase/nav/2006/ffe5f5_f09/wdrext.gif"><span class="wsInner"><a rel="www" href="http://www.stk.rlp.de/rlp/nav/c9a/binarywriterservlet?imgUid=980fb462-916e-1153-a16e-5c3899d11eb3&amp;uBasVariant=33333333-3333-3333-3333-333333333333" title="Link öffnet in neuem Fenster" target="_blank">Den Gesetzestext und die Begründung des 12.
Rundfunkänderungsstaatsvertrags könnt ihr hier nachlesen
(die Negativliste findet ihr am Ende des Gesetzestextes ab S. 58.)</a></span></li></ul></div>
<p>Wir bedauern es sehr, euch die gewünschten Inhalte nicht mehr zur Verfügung stellen zu dürfen. Für euer Interesse an unserem Internet-Angebot bedanken wir uns herzlich und hoffen, dass ihr uns als Nutzer weiterhin treu bleibt.</p>
<div class="clearMe"></div>
<p class="wsStand">Stand: 30.05.2010</p>  
</div>
<!-- CONTENT ENDE -->
<!--googleoff: index-->
<!-- tC: 1 -->
 
 
 




<!--RECHTE SPALTE ANFANG -->
<a id="re" name="re"></a>
<div id="wsReSpContD" class="wsReSpCont">
</div>

 
<!--RECHTE SPALTE ENDE -->
<div class="clearMe"></div>
<!-- tR: 0 -->

<!--googleon: index-->

<!-- FOOT START -->
</div>
<!--googleoff: index-->
<div id="wsFunction">
  <a name="service" id="service"></a>
  <ul>
    <li id="wsTop">
      <a href="#top"><span class="wsInner">Seitenanfang</span></a>
    </li>

    <li id="wsWdr">
      <a rel="www" href="http://www.wdr.de"><img alt="Logo Westdeutscher Rundfunk" src="/codebase/img/seitenfuss/wdr_logo_grau.gif" /></a>
    </li>
  </ul>
  <div class="clearMe"></div>
</div>
</div>
<div class="clearMe"></div>





















<!-- sendeschema.jsp -->
<div id="wsSendeschemaFuss">
<a name="sendeschema"></a>
  <div id="wsQuerNaviFuss" class="wsQuerNavi">
    <ul>
        <li class="webradio">
            <a onclick="window.open(this.href,'radio','width=545,height=365,xsize=450,screenX=150,screenY=150,top=150,left=150,menubar=1,scrollbars=0,resizable=1,statusbar=1,locationbar=1'); return false;" rel="www" href="/sendungen/player/EinsLivePlayer.html"><span lang="en">Webradio</span></a>
        </li>
        <li class="playlists">

            <a href="/musik/playlists/"><span lang="en">Playlist</span></a>
        </li>
        <li class="webcam">
            <a href="/sendungen/webcam/"><span lang="en">Webcam</span></a>
        </li>
    </ul>
  </div>

  <div id="wsSendeschemaHead">
    <h4>Das 1LIVE Sendeschema</h4>
    <ul>
      <li>
          <a href="?epgDatum=2012-06-06#sendeschema" title="06.06.2012">zurück</a>
      </li>
      <li>
          <span id="heute" class="aktiv">Donnerstag</span>
      </li>
      <li>
          <a href="?epgDatum=2012-06-08#sendeschema" title="08.06.2012">vor</a>
      </li>
    </ul>
  </div>

  <div id="wsSendeschemaFussInner">

    <table summary="Das 1LIVE Sendeschema vom 07.06.2012">
      <caption class="inv">TAGESÜBERSICHT</caption>
      <tbody>
        <tr class="wsSchemaBg">
          <th scope="col" id="wsUhr0">00.00 <span class="inv">Uhr</span></th>
          <th scope="col" id="wsUhr1">01.00 <span class="inv">Uhr</span></th>
          <th scope="col" id="wsUhr2">02.00 <span class="inv">Uhr</span></th>

          <th scope="col" id="wsUhr3">03.00 <span class="inv">Uhr</span></th>
          <th scope="col" id="wsUhr4">04.00 <span class="inv">Uhr</span></th>
          <th scope="col" id="wsUhr5">05.00 <span class="inv">Uhr</span></th>
          <th scope="col" id="wsUhr6">06.00 <span class="inv">Uhr</span></th>
          <th scope="col" id="wsUhr7">07.00 <span class="inv">Uhr</span></th>

          <th scope="col" id="wsUhr8">08.00 <span class="inv">Uhr</span></th>
          <th scope="col" id="wsUhr9">09.00 <span class="inv">Uhr</span></th>
          <th scope="col" id="wsUhr10">10.00 <span class="inv">Uhr</span></th>
          <th scope="col" id="wsUhr11">11.00 <span class="inv">Uhr</span></th>
          <th scope="col" id="wsUhr12">12.00 <span class="inv">Uhr</span></th>

          <th scope="col" id="wsUhr13">13.00 <span class="inv">Uhr</span></th>
          <th scope="col" id="wsUhr14">14.00 <span class="inv">Uhr</span></th>
          <th scope="col" id="wsUhr15">15.00 <span class="inv">Uhr</span></th>
          <th scope="col" id="wsUhr16">16.00 <span class="inv">Uhr</span></th>
          <th scope="col" id="wsUhr17">17.00 <span class="inv">Uhr</span></th>

          <th scope="col" id="wsUhr18">18.00 <span class="inv">Uhr</span></th>
          <th scope="col" id="wsUhr19">19.00 <span class="inv">Uhr</span></th>
          <th scope="col" id="wsUhr20">20.00 <span class="inv">Uhr</span></th>
          <th scope="col" id="wsUhr21">21.00 <span class="inv">Uhr</span></th>
          <th scope="col" id="wsUhr22">22.00 <span class="inv">Uhr</span></th>

          <th scope="col" id="wsUhr23">23.00 <span class="inv">Uhr</span></th>
        </tr>
        <tr>

          
            <td class="wsOdd" headers="wsUhr0" colspan="1">
             
                 
                    <div class="wsSchemaInfos">
                 
             
              <strong>
              
                <a href="http://www.einslive.de/sendungen/nieswandt/index.jsp">
              
              <span class="wsELBlack">1LIVE</span> Plan B mit Hans Nieswandt
              
                </a>
              
              </strong>
              <br />
              
                  
                      <!-- 0 - 1 -->
                      
                          
                          
                            <div class="wsSchemaMehr"><span class="wsELBlack">1LIVE</span> Plan B mit Hans Nieswandt: Elektronische Melodien aus Deutschland und dem Rest der Welt</div>
                          
                      
                  
              
             
                 
                    </div>
                 
             
            </td>
          
            <td class="wsEven" headers="wsUhr1" colspan="1">
             
                 
                    <div class="wsSchemaInfos">
                 
             
              <strong>
              
                <a href="http://www.einslive.de/sendungen/domian/">
              
              <span class="wsELBlack">1LIVE</span> Domian
              
                </a>
              
              </strong>
              <br />
              
                  
                      <!-- 1 - 2 -->
                      
                          
                          
                            <div class="wsSchemaMehr"><span class="wsELBlack">1LIVE</span> Domian: Die Telefon-Talkshow auf 1LIVE und im WDR Fernsehen Mit J&#252;rgen Domian Thema: Jung und zwischen den Kulturen Hotline: freecall 0800/2205050 / Fax: 0800/2205051</div>
                          
                      
                  
              
             
                 
                    </div>
                 
             
            </td>
          
            <td class="wsOdd" headers="wsUhr2 wsUhr3 wsUhr4 wsUhr5" colspan="4">
             
                 
             
              <strong>
              
              <span class="wsELBlack">1LIVE</span> Nacht
              
              </strong>
              <br />
              
                  
                      <!-- 2 - 6 -->
                      
                          
                            Musik und Comedy f&#252;r den Sektor bei Nacht Darin: 03.00, 04.00, 05.00 Nachrichten, Wetter
                          
                          
                      
                  
              
             
                 
             
            </td>
          
            <td class="wsEven" headers="wsUhr6 wsUhr7 wsUhr8" colspan="3">
             
                 
             
              <strong>
              
              <span class="wsELBlack">1LIVE</span> mit Vanessa Nolte
              
              </strong>
              <br />
              
                  
                      <!-- 6 - 9 -->
                      
                          
                          
                            <div class="wsSchemaMehr"><span class="wsELBlack">1LIVE</span> mit Vanessa Nolte: Die t&#228;gliche, aktuelle Morgen-Show in 1LIVE</div>
                          
                      
                  
              
             
                 
             
            </td>
          
            <td class="wsOdd" headers="wsUhr9 wsUhr10 wsUhr11 wsUhr12 wsUhr13" colspan="5">
             
                 
             
              <strong>
              
              <span class="wsELBlack">1LIVE</span> mit Tina Middendorf
              
              </strong>
              <br />
              
                  
                      <!-- 9 - 14 -->
                      
                          
                            Der Vormittag in 1LIVE
                          
                          
                      
                  
              
             
                 
             
            </td>
          
            <td class="wsEven" headers="wsUhr14 wsUhr15 wsUhr16 wsUhr17" colspan="4">
             
                 
             
              <strong>
              
              <span class="wsELBlack">1LIVE</span> Beeck und Schlegl
              
              </strong>
              <br />
              
                  
                      <!-- 14 - 18 -->
                      
                          
                            Der Nachmittag in 1LIVE
                          
                          
                      
                  
              
             
                 
             
            </td>
          
            <td class="wsOdd" headers="wsUhr18 wsUhr19" colspan="2">
             
                 
                    <div class="wsSchemaInfos">
                 
             
              <strong>
              
              <span class="wsELBlack">1LIVE</span> Sektor
              
              </strong>
              <br />
              
                  
                      <!-- 18 - 20 -->
                      
                          
                          
                            <div class="wsSchemaMehr"><span class="wsELBlack">1LIVE</span> Sektor: Mit Johannes Sassenroth Die Themen des Tages im Sektor</div>
                          
                      
                  
              
             
                 
                    </div>
                 
             
            </td>
          
            <td class="wsEven" headers="wsUhr20 wsUhr21 wsUhr22" colspan="3">
             
                 
             
              <strong>
              
              <span class="wsELBlack">1LIVE</span> Plan B
              
              </strong>
              <br />
              
                  
                      <!-- 20 - 23 -->
                      
                          
                          
                            <div class="wsSchemaMehr"><span class="wsELBlack">1LIVE</span> Plan B: Mit Ingo Schmoll Der Abend in 1LIVE - im Zeichen der Popkultur</div>
                          
                      
                  
              
             
                 
             
            </td>
          
            <td class="wsOdd" headers="wsUhr23" colspan="1">
             
                 
                    <div class="wsSchemaInfos">
                 
             
              <strong>
              
                <a href="http://www.einslive.de/sendungen/plan_b/krimi/index.jsp">
              
              <span class="wsELBlack">1LIVE</span> Plan B Krimi
              
                </a>
              
              </strong>
              <br />
              
                  
                      <!-- 23 - 24 -->
                      
                          
                          
                            <div class="wsSchemaMehr"><span class="wsELBlack">1LIVE</span> Plan B Krimi: Der Thrill vor Mitternacht</div>
                          
                      
                  
              
             
                 
                    </div>
                 
             
            </td>
          

        </tr>
      </tbody>
    </table>

    <script type="text/javascript">
      document.getElementById('wsUhr3').scrollIntoView(true);
      document.getElementById('top').scrollIntoView(true);
    </script>

  </div>
</div>


<div id="wsBannerFuss"></div>

<div id="wsFooterOuterBG">

        <div id="wsSitemapFooter">
            <!-- To be done -->
            <ul class="wsSpezial extra">
  <li><span class="aktiv"><span class="inv">1</span>Live</span></li>

  <li><a href="http://www.einslivekrone.de"><span class="inv">1</span>Live
  Krone</a></li>

  <li><a href="/medien/html/1live/index.xml"><span class="inv">1</span>Live
  Fernseher</a></li>
  <li><a rel="www" href="http://freundeskreis.einslive.de/"><span
    class="inv">1</span>Live Freundeskreis</a></li>
  <li><a rel="www" href="http://vereinsmeisterschaft.einslive.de/"><span
    class="inv">1</span>Live Vereinsmeisterschaft</a></li>
</ul>
<form id="wsSuchen2" method="get" action="/suche.jsp">
  <fieldset ><legend> <strong>Eins Live Suche</strong> </legend>
  <label class="inv" for="suche2"> Suchbegriff: </label>
  <input type="text" name="q" id="suche2" />
  <input type="image" src="/codebase/img/icons/suche_lupe.gif" alt="Suchen" class="wsFormBut" id="wsSuchenSubmit2" />
  <label for="wsSuchenSubmit2"> Suchen </label>
  </fieldset>
  <div class="clearMe"></div>
  <hr class="inv" />
</form>
<div class="clearMe"></div>
<ul class="wsHauptnavi">

  <li><a href="/index.jsp">Startseite</a>

    <ul>
        
      <li id="sitemap_rss"><a href="/index.jsp?rdf=1">RSS Feed</a></li>
    </ul>
  </li>

    <li><a href="/magazin/">Magazin</a><ul>
<li><a href="/magazin/nachrichten/">Nachrichten</a></li><li><a href="/magazin/pop/">Pop</a></li><li><a href="/magazin/sport/2012/em/index.jsp">EM 2012</a></li><li><a href="/magazin/kino/">Kino</a></li><li><a href="/magazin/dvd/">DVD</a></li><li><a href="/magazin/literatur/">Literatur</a></li><li><a href="/magazin/interviews/">Interviews</a></li><li><a href="/magazin/spiele/">Spiele</a></li><li><a href="/magazin/sport/">Sport</a></li><li><a href="/magazin/mitwisser/">Endlich Mitwisser</a></li><li><a href="/magazin/netzthemen/">Netz-Themen</a></li><li><a href="/magazin/kolumne/index.jsp" class="wsLast">Kolumne Herr Nieswandt</a></li></ul>
</li>
<li><a href="/musik/">Musik</a><ul>
<li><a href="/musik/playlists/">Playlists</a></li><li><a href="/musik/platten/">Plattencheck</a></li><li><a href="/musik/interviews/">Interviews</a></li><li><a href="/musik/charts/">Charts</a></li><li><a href="/musik/neu_fuer_den_sektor/">Neu für den Sektor</a></li><li><a href="/musik/konzert_galerien/">Konzert-Galerien</a></li><li><a href="/musik/heimatkult/">Heimatkult</a></li><li><a href="http://www.einslivekrone.de/" class="wsLast">1LIVE Krone</a></li></ul>
</li>
<li><a href="/comedy/">Comedy</a><ul>
<li><a href="/comedy/o_ton_charts/">O-Ton-Charts</a></li><li><a href="/comedy/noob_und_nerd/">Noob und Nerd</a></li><li><a href="/comedy/tony_mono/">Tony Mono</a></li><li><a href="/comedy/em_fan_radio/index.jsp">Das EM-Fan-Radio</a></li><li><a href="/comedy/kraftklub/index.jsp">Kraftklub</a></li><li><a href="/comedy/kebekus/index.jsp">Die Kebekus</a></li><li><a href="http://www.einslive.de/comedy/werkerpedia/index.jsp">Werkerpedia</a></li><li><a href="http://www.einslive.de/comedy/sektormaehn/120120_sektormaehn.jsp">Sektormähn</a></li><li><a href="/comedy/die_bundesliga_in_90_sekunden/index.jsp">Die Bundesliga in 90 Sekunden</a></li><li><a href="/comedy/dennis/dennis_comedy_index.jsp">Dennis ruft an</a></li><li><a href="http://www.einslive.de/comedy/schroeders_netzwerk/index.jsp">Schroeders Netzwerk</a></li><li><a href="http://www.einslive.de/comedy/1live_freak/index.jsp" class="wsLast">1LIVE Freak</a></li></ul>
</li>
<li><a href="/aktionen/">Aktionen</a><ul>
<li><a href="/aktionen/termine/">Termine</a></li><li><a href="/aktionen/termine/sektor_events/">Sektor-Events</a></li><li><a href="/aktionen/termine/events/">1LIVE-Veranstaltungen</a></li><li><a href="/aktionen/termine/1live_partys/1live_partys.jsp">1LIVE-Partys</a></li><li><a href="/aktionen/2012/nacht_in/">Eine Nacht in Dortmund</a></li><li><a href="/aktionen/2012/04/1live_autokino/index.jsp">1LIVE Autokino</a></li><li><a href="/aktionen/schulduell/2012/finale/index.jsp" class="wsLast">Schulduell</a></li></ul>
</li>
<li><a href="/sendungen/">Sendungen</a><ul>
<li><a href="/sendungen/studiogaeste/index.jsp">Studiogäste </a></li><li><a href="/sendungen/diggi/">Diggi</a></li><li><a href="/sendungen/plan_b/talk/">Plan B Talk</a></li><li><a href="/sendungen/plan_b/reportage/">Plan B Reportage</a></li><li><a href="/sendungen/plan_b/krimi/index.jsp">Plan B Krimi</a></li><li><a href="/sendungen/plan_b/shortstory/">Plan B Shortstory</a></li><li><a href="/sendungen/plan_b/soundstories/">Plan B Soundstories</a></li><li><a href="/sendungen/musiksendungen/index.jsp">Musiksendungen</a></li><li><a href="/sendungen/1live_elfer/index.jsp">1LIVE Elfer</a></li><li><a href="/sendungen/klubbing/">Klubbing</a></li><li><a href="/sendungen/domian/">Domian</a></li><li><a href="/sendungen/podcasts/">Podcasts</a></li><li><a href="/sendungen/webcam/">Webcam</a></li><li><a href="/sendungen/sendeschema/">Sendeschema</a></li><li><a href="/sendungen/frequenzen/" class="wsLast">Frequenzen</a></li></ul>
</li>
<li><a href="/team/">Team</a><ul>
<li><a href="/team/kontakt/">Kontakt</a></li><li><a href="/team/moderatoren/">Moderatoren</a></li><li><a href="/team/jobs/" class="wsLast">Jobs</a></li></ul>
</li>


</ul>
        </div>
        <div id="wsFooterInnerBG">
            <hr class="inv" />
            <div id="wsDisclaimer">
                <a href="http://www.wdr.de" title="Startseite WDR.de"><img src="/codebase/nav/2006/wdr.gif" alt="Startseite WDR.de" /></a>
                <p id="wsDisclaimerText">
                    1LIVE/
                    <acronym title="Westdeutscher Rundfunk">

                        WDR
                    </acronym>
                    ist nicht für die Inhalte fremder Seiten verantwortlich,
                    die über einen Link erreicht werden.
                </p>
                <p id="wsCopy">
                    <a href="http://www.wdr.de/themen/global/urheber/">&copy;&nbsp;WDR&nbsp;2012</a>
                </p>
                <p id="wsImp">
                    <a href="/impressum/">Impressum&nbsp;</a>
                </p>
            </div>
        </div>

    </div>
<!--

Umsetzung: WDR mediagroup digital GmbH, Köln

-->
<!-- tF: 102 --><!--googleon: index-->
</body>
</html>

