<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" media="screen" href="/~d/styles/rss2full.xsl"?>
<?xml-stylesheet type="text/css" media="screen" href="http://feeds.feedburner.com/~d/styles/itemcontent.css"?>
<rss xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:wfw="http://wellformedweb.org/CommentAPI/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:sy="http://purl.org/rss/1.0/modules/syndication/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:feedburner="http://rssnamespace.org/feedburner/ext/1.0" version="2.0">
  <channel>
    <title>Weight Loss Blog (Lose That Tyre) - Podcasts powered by Odiogo</title>
    <link>http://www.losethattyre.co.uk</link>
    <description>weight loss diet and more</description>
    <lastBuildDate>Thu, 10 May 2012 15:11:12 +0000</lastBuildDate>
    <language>en</language>
    <sy:updatePeriod>hourly</sy:updatePeriod>
    <sy:updateFrequency>1</sy:updateFrequency>
    <generator>http://wordpress.org/?v=</generator>
    <atom10:link xmlns:atom10="http://www.w3.org/2005/Atom" rel="self" type="application/rss+xml" href="http://feeds.feedburner.com/co/PDCB" />
    <feedburner:info uri="co/pdcb" />
    <atom10:link xmlns:atom10="http://www.w3.org/2005/Atom" rel="hub" href="http://pubsubhubbub.appspot.com/" />
    <image>
      <url>http://www.feedburner.com/fb/images/pub/fb_pwrd.gif</url>
    </image>
    <feedburner:emailServiceId>co/PDCB</feedburner:emailServiceId>
    <feedburner:feedburnerHostname>http://feedburner.google.com</feedburner:feedburnerHostname>
    <item>
      <title>Study Finds Eat Slowly to Prevent Diabetes</title>
      <link>http://feedproxy.google.com/~r/co/PDCB/~3/AXHrFy1Z5Dg/</link>
      <comments>http://www.losethattyre.co.uk/study-finds-eat-slowly-to-prevent-diabetes/#comments</comments>
      <pubDate>Thu, 10 May 2012 15:11:12 +0000</pubDate>
      <dc:creator>Mark</dc:creator>
      <category><![CDATA[Featured]]></category>
      <guid isPermaLink="false">http://www.losethattyre.co.uk/?p=4765</guid>
      <description>Image by mamchenkov
One of the things that we can do in order to help with weight gain is to eat our food slowly. This has been common knowledge now for some years, although some people might not know this. The reason behind it is simple. It can take up to 20 minutes before your brain receives [...]&lt;p&gt;Post from: &lt;a href="http://www.losethattyre.co.uk"&gt;Weight Loss Blog (Lose That Tyre)&lt;/a&gt;&lt;br/&gt;&lt;br/&gt;&lt;/p&gt;&lt;br&gt;&lt;a type="audio/mpeg" href="http://podcasts.odiogo.com/get_mp3.mp3?f=/weight-loss-blog/Weight_Loss_Blog-Study_Finds_Eat_Slowly_to_Prevent_Diabetes.mp3"&gt;Click here to play&lt;/a&gt;&lt;br&gt;</description>
      <content:encoded><![CDATA[<iframe src="http://www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.losethattyre.co.uk%2Fstudy-finds-eat-slowly-to-prevent-diabetes%2F&amp;layout=standard&amp;show_faces=true&amp;width=450&amp;action=like&amp;colorscheme=light&amp;height=80" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:450px; height:80px;" allowTransparency="true"></iframe><p>Image by <a href="http://www.flickr.com/photos/mamchenkov/368970804/sizes/s/in/photostream/">mamchenkov</a></p>
<p><img class="alignleft size-full wp-image-4767" style="margin: 20px;" title="368970804_40ede8f33c_m" src="http://www.losethattyre.co.uk/wp-content/uploads/2012/05/368970804_40ede8f33c_m.jpg" alt="" width="240" height="217" />One of the things that we can do in order to help with weight gain is to eat our food slowly. This has been common knowledge now for some years, although some people might not know this. The reason behind it is simple. It can take up to 20 minutes before your brain receives the full signal telling you to stop eating.</p>
<p>So if you eat your food  your brain automatically assumes that you&#8217;re still hungry, when, in fact, this might not be the case if you&#8217;re eating your food to fast, some recent research has come to light that says if you eat your food to quickly, this may cause you to get type II diabetes.</p>
<p>It would seem that if you eat really quickly, then you are two and half times more likely to contract the disease compared to somebody who takes their time to eat food. This is the first time that there has been links between how fast you eat and becoming a diabetic.</p>
<p>The researchers compared 234 people who had recently contracted it with 468 people whom have never had it. Participants in the study were asked a few things such as whether or not they thought they had a risk of contracting it. Their weights were taken, as well as measurements, after the researchers had added other factors such as a genetic history of the disease. How much exercise they did and whether they smoked or not.</p>
<p>After accumulating all the data, the researchers were quite surprised to find that those people that ate quickly were far more likely to become diabetics compared to those whom ate their food more slowly. On a slightly unrelated note, the team which conducted this research found previously that if you drink four or more cups of coffee a day. This can help to prevent it as well. As well as this, they found that smoking and eating more than five eggs a week was a contributory factor.</p>
<p>Experts say that as well as what has been mentioned above, the contributing factor to keeping it at bay is weight loss. They say that if people have type II diabetes and lose 10% of their weight more than half the cases may return to being normal. Some research that was publicised last year found that when you eat quickly you pile on the pounds, compared to if you eat slowly. The amount that you consume is far less. Two consecutive studies found that men eat faster than women. If you&#8217;re heavier, you are far more likely to eat faster compared to somebody who is slimmer, they found refined grains are eaten quicker than whole grains.</p>
<p><strong>Some tips to help with slow eating</strong></p>
<p>Have selected mealtimes. If you&#8217;re able to and have a table eat your food on this and try not to be doing other things at the same time, such as using your mobile phone, watching television or any other activity. The reason for this is because you want to become consciously aware of how you are eating. If you are doing other things, and you may not realise how fast you are eating.</p>
<p>Get some smaller plates. This has been proven to work for a lot of people. This way, you will only eat what is on the plate chew your food about a minimum of about 20 times. Forming a new habit can be hard, so make sure that you keep it up for at least 30 days or more. Anything less than that and you may be struggling.</p>
<p>Take time to enjoy the taste of your food instead of just shovelling it in. It&#8217;s not a race you eating food. The great thing about this research is, it goes to show and prove that they can be more than one contributing factor in any kind of disease, especially diabetes. It would now seem that there is more to it than we first thought.</p>
<p>If you have any thoughts or opinions about this research or diabetes, please leave your comments and thoughts in the section below.</p>
<div style="float: left;"><a href="http://bufferapp.com/add" class="buffer-add-button" data-text="Study Finds Eat Slowly to Prevent Diabetes" data-url="http://www.losethattyre.co.uk/study-finds-eat-slowly-to-prevent-diabetes/" data-via="bufferapp" data-count="horizontal">Buffer</a><script type="text/javascript" src="http://static.bufferapp.com/js/button.js"></script></div><p>Post from: <a href="http://www.losethattyre.co.uk">Weight Loss Blog (Lose That Tyre)</a><br/><br/></p>
<div class="feedflare">
<a href="http://feeds.feedburner.com/~ff/co/PDCB?a=AXHrFy1Z5Dg:Pqaq-eGl-Cw:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/co/PDCB?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/co/PDCB?a=AXHrFy1Z5Dg:Pqaq-eGl-Cw:-BTjWOF_DHI"><img src="http://feeds.feedburner.com/~ff/co/PDCB?i=AXHrFy1Z5Dg:Pqaq-eGl-Cw:-BTjWOF_DHI" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/co/PDCB?a=AXHrFy1Z5Dg:Pqaq-eGl-Cw:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/co/PDCB?d=qj6IDK7rITs" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/co/PDCB?a=AXHrFy1Z5Dg:Pqaq-eGl-Cw:I9og5sOYxJI"><img src="http://feeds.feedburner.com/~ff/co/PDCB?d=I9og5sOYxJI" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/co/PDCB?a=AXHrFy1Z5Dg:Pqaq-eGl-Cw:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/co/PDCB?i=AXHrFy1Z5Dg:Pqaq-eGl-Cw:gIN9vFwOqvQ" border="0"></img></a>
</div><img src="http://feeds.feedburner.com/~r/co/PDCB/~4/AXHrFy1Z5Dg" height="1" width="1"/>]]></content:encoded>
      <wfw:commentRss>http://www.losethattyre.co.uk/study-finds-eat-slowly-to-prevent-diabetes/feed/</wfw:commentRss>
      <slash:comments>1</slash:comments>
      <feedburner:origLink>http://www.losethattyre.co.uk/study-finds-eat-slowly-to-prevent-diabetes/?utm_source=rss&amp;utm_medium=rss&amp;utm_campaign=study-finds-eat-slowly-to-prevent-diabetes</feedburner:origLink>
      <enclosure url="http://podcasts.odiogo.com/get_mp3.mp3?f=/weight-loss-blog/Weight_Loss_Blog-Study_Finds_Eat_Slowly_to_Prevent_Diabetes.mp3" length="1898655" type="audio/mpeg" />
    </item>
    <item>
      <title>Why Google Why Me ?</title>
      <link>http://feedproxy.google.com/~r/co/PDCB/~3/Qz60U4xLawU/</link>
      <comments>http://www.losethattyre.co.uk/why-google-why-me/#comments</comments>
      <pubDate>Mon, 30 Apr 2012 10:43:55 +0000</pubDate>
      <dc:creator>Mark</dc:creator>
      <category><![CDATA[Featured]]></category>
      <guid isPermaLink="false">http://www.losethattyre.co.uk/?p=4761</guid>
      <description>This post may seem quite a digression from what I normally write about. However, there is a very good reason for it. I can assure you during last week I noticed something rather odd had happened concerning my stats of my blog traffic they had taken quite a nose dive and as the week progressed, [...]&lt;p&gt;Post from: &lt;a href="http://www.losethattyre.co.uk"&gt;Weight Loss Blog (Lose That Tyre)&lt;/a&gt;&lt;br/&gt;&lt;br/&gt;&lt;/p&gt;&lt;br&gt;&lt;a type="audio/mpeg" href="http://podcasts.odiogo.com/get_mp3.mp3?f=/weight-loss-blog/Weight_Loss_Blog-Why_Google_Why_Me_.mp3"&gt;Click here to play&lt;/a&gt;&lt;br&gt;</description>
      <content:encoded><![CDATA[<iframe src="http://www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.losethattyre.co.uk%2Fwhy-google-why-me%2F&amp;layout=standard&amp;show_faces=true&amp;width=450&amp;action=like&amp;colorscheme=light&amp;height=80" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:450px; height:80px;" allowTransparency="true"></iframe><p><img class="alignleft size-full wp-image-4762" style="margin: 20px;" title="google_logo" src="http://www.losethattyre.co.uk/wp-content/uploads/2012/04/google_logo.jpg" alt="" width="256" height="256" />This post may seem quite a digression from what I normally write about. However, there is a very good reason for it. I can assure you during last week I noticed something rather odd had happened concerning my stats of my blog traffic they had taken quite a nose dive and as the week progressed, they got worse and worse.</p>
<p>At first I thought there was something else wrong. But then when I started checking other sources of my blog traffic they seem to be saying all the same thing during the course of last week. From what I understand, there were two updates to Google&#8217;s algorithm.</p>
<p>And for whatever reason unbeknown to me, I seem to have got caught up in the recent penguin Google update which in essence more or less seems that Google seems to think that my blog is <strong>web spam</strong> or words to that effect. It would seem that if you&#8217;re site is over SEO’D back link wise as well as <strong>poor content</strong> and <strong>keyword stuffed pages</strong>, then you would be affected by this update.</p>
<p>I always thought that my blog was a good source of relevant content. Even though I do rely on some sources for my content. I do write it all myself, as well as research. It and edit it, and proof read it. Sometimes it can take me a while to write a piece of content, because I am so particular about how I want it to be seen from a reader&#8217;s perspective.</p>
<p>This year is my fifth year of doing this blog and I have thoroughly enjoyed it. For me it has been the thing that has kept me going for such a long time now, although some people may not know, or realise this. And I had quite a few things planned in order to make it even better for people such as a free course to be delivered by e-mail. As well as other things.</p>
<p>I actually saw for once in a long time, a very bright future from doing this, but now I&#8217;m not so sure without traffic. This blog will not survive in the long term. I do have one advertiser on board at present, but after what has happened. I&#8217;m not sure whether they will hang around after this. There are many things I would like to have done off the back of this blog, such as consulting work, maybe some social media and other things.</p>
<p>The thing is, if these updates keep happening and my blog is getting caught up in them each time the traffic levels are going to plummet to almost nothing, and really it will be a waste of time writing new posts because no one will see them apart from what traffic. I get from social media, which is nowhere near enough at the moment, like what I&#8217;ve been getting from Google.</p>
<p>So you can get some idea of how devastating it has been. I have lost approximately 15,000 visitors this month that is quite a large amount. I&#8217;m sure you&#8217;ll agree it&#8217;s not small change by any degree, and yet people still continue to subscribe to my blog, whether by e-mail, or merely by sharing it on Facebook or Twitter and Pinterest, as well as linking from their sites such as forums, and so forth.</p>
<p>Not only that PR agencies have been in contact with me throughout all of this year, asking me to try their products in return for my thoughts and opinions in a review, as well as people asking for guest post opportunities so on a positive note, there is still interest.</p>
<p>And surely if my blog was that bad. I wouldn&#8217;t have this amount of interest, having spent four years or more. Getting it to where it is now and to have this happen after all this time it&#8217;s to me personally devastating.  So, from this point forward. I&#8217;m not exactly sure what to do or where to go. I do want to keep writing posts and keep the blog going. The only thing is, I&#8217;m not very certain about its future.</p>
<p>I was hoping to in the near future and get more advertisers on board and it would start to pay for itself over time. It would seem that I&#8217;m not the only one who&#8217;s been affected by this update. Any thoughts or comments you may care to add, please do so in the following section, or you can contact me through my contact form on my blog. And in closing the question I still have in my mind is  <strong>Why Google Why Me ?</strong></p>
<p>Thanks Mark, owner of Lose That Tyre</p>
<div style="float: left;"><a href="http://bufferapp.com/add" class="buffer-add-button" data-text="Why Google Why Me ?" data-url="http://www.losethattyre.co.uk/why-google-why-me/" data-via="bufferapp" data-count="horizontal">Buffer</a><script type="text/javascript" src="http://static.bufferapp.com/js/button.js"></script></div><p>Post from: <a href="http://www.losethattyre.co.uk">Weight Loss Blog (Lose That Tyre)</a><br/><br/></p>
<div class="feedflare">
<a href="http://feeds.feedburner.com/~ff/co/PDCB?a=Qz60U4xLawU:duiLXIZWf2I:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/co/PDCB?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/co/PDCB?a=Qz60U4xLawU:duiLXIZWf2I:-BTjWOF_DHI"><img src="http://feeds.feedburner.com/~ff/co/PDCB?i=Qz60U4xLawU:duiLXIZWf2I:-BTjWOF_DHI" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/co/PDCB?a=Qz60U4xLawU:duiLXIZWf2I:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/co/PDCB?d=qj6IDK7rITs" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/co/PDCB?a=Qz60U4xLawU:duiLXIZWf2I:I9og5sOYxJI"><img src="http://feeds.feedburner.com/~ff/co/PDCB?d=I9og5sOYxJI" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/co/PDCB?a=Qz60U4xLawU:duiLXIZWf2I:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/co/PDCB?i=Qz60U4xLawU:duiLXIZWf2I:gIN9vFwOqvQ" border="0"></img></a>
</div><img src="http://feeds.feedburner.com/~r/co/PDCB/~4/Qz60U4xLawU" height="1" width="1"/>]]></content:encoded>
      <wfw:commentRss>http://www.losethattyre.co.uk/why-google-why-me/feed/</wfw:commentRss>
      <slash:comments>7</slash:comments>
      <feedburner:origLink>http://www.losethattyre.co.uk/why-google-why-me/?utm_source=rss&amp;utm_medium=rss&amp;utm_campaign=why-google-why-me</feedburner:origLink>
      <enclosure url="http://podcasts.odiogo.com/get_mp3.mp3?f=/weight-loss-blog/Weight_Loss_Blog-Why_Google_Why_Me_.mp3" length="2091048" type="audio/mpeg" />
    </item>
    <item>
      <title>Does Exercise Makes You Eat More or Less</title>
      <link>http://feedproxy.google.com/~r/co/PDCB/~3/Nm0iYXMCTzk/</link>
      <comments>http://www.losethattyre.co.uk/does-exercise-makes-you-eat-more-or-less/#comments</comments>
      <pubDate>Tue, 24 Apr 2012 09:33:46 +0000</pubDate>
      <dc:creator>Mark</dc:creator>
      <category><![CDATA[Featured]]></category>
      <guid isPermaLink="false">http://www.losethattyre.co.uk/?p=4754</guid>
      <description>Image by yourdon
Scientists have often wondered about what happens when we exercise when it comes to eating some people eat more. Others eat less. It would seem, for quite sometime now; scientists thought that certain hormones were turned on and off when people exercised, but now that train of thought has been changed  as other evidence [...]&lt;p&gt;Post from: &lt;a href="http://www.losethattyre.co.uk"&gt;Weight Loss Blog (Lose That Tyre)&lt;/a&gt;&lt;br/&gt;&lt;br/&gt;&lt;/p&gt;&lt;br&gt;&lt;a type="audio/mpeg" href="http://podcasts.odiogo.com/get_mp3.mp3?f=/weight-loss-blog/Weight_Loss_Blog-Does_Exercise_Makes_You_Eat_More_or_Less.mp3"&gt;Click here to play&lt;/a&gt;&lt;br&gt;</description>
      <content:encoded><![CDATA[<iframe src="http://www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.losethattyre.co.uk%2Fdoes-exercise-makes-you-eat-more-or-less%2F&amp;layout=standard&amp;show_faces=true&amp;width=450&amp;action=like&amp;colorscheme=light&amp;height=80" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:450px; height:80px;" allowTransparency="true"></iframe><p>Image by <a href="http://www.flickr.com/photos/yourdon/2819557294/sizes/s/in/photostream/">yourdon</a></p>
<p><img class="alignleft size-full wp-image-4756" style="margin: 20px;" title="2819557294_681d6d162f_m" src="http://www.losethattyre.co.uk/wp-content/uploads/2012/04/2819557294_681d6d162f_m.jpg" alt="" width="240" height="159" />Scientists have often wondered about what happens when we exercise when it comes to eating some people eat more. Others eat less. It would seem, for quite sometime now; scientists thought that certain hormones were turned on and off when people exercised, but now that train of thought has been changed  as other evidence suggests otherwise. It seems that exercise may affect your desire to eat.</p>
<p>This is due to how certain parts of your brain work when they see food, the culmination of this research has come from two studies which we will look at now.</p>
<p>In the first study, researchers had 30 active men, and women attend to a laboratory session at California Polytechnic State University. They examined their brains using functional MRI coils, the scientists wanted to track the areas in the brain which workaround the food and reward structure in the parts of the brain that deal with this. They control whether we want food or not, the more cells in that part of the brain, the more we want to eat food.</p>
<p>However, it&#8217;s not been made clear how exercise influences the food and reward system. So in order to see what was going on. The scientists asked the participants to do one of two tests either ride a stationary bike or sit still for an hour after this, they would have their brains scanned using the MRI scanner again.</p>
<p>Straight after they looked at photos on a computer screen. These were images of low fat fruit, vegetables and grains. Other images were cheeseburgers, cookies and ice cream sundae’s interspersed with this were non-food images. Here is where it starts to get interesting in the volunteers who were sitting still for an hour. The reward system, lit up when they saw images of high fat, high-sugar  foods.</p>
<p>However, if the participants had been exercising for an hour instead, their brain scans showed very little activity, even when shown pictures of the ice cream, it would seem that the stimulus in the brain was so much quieter when people had been exercising vigorously.</p>
<p>However, we must stress that these results may not be necessarily typical as participants were in their 20s, of normal weight and physically fit enough to ride a bike for an hour vigorously. In the second study, they had different results. The researchers in this particular study, had overweight, sedentary people in it found that they responded to food, after exercise rather than dampening their appetite. This study, which was published in the Journal of Obesity  had people exercising for five days a week, on a program that was designed to burn 500 calories per workout. They were also allowed to eat when they wanted.</p>
<p>Even after three months had passed their brains were more enthusiastic, compared to when they were first measured at the beginning of the study. If you compare this to the people who responded positively after exercising their hardly lit up at all.</p>
<p>One of the researchers said that what this goes to show, and proves is that exercise can affect your brain&#8217;s food reward system, but this depends on who you are and what kind of exercise you do. He says that in order to maintain weight loss, you need to exercise and do it often, which makes sense in order to dampen your desire for food after exercise. You may need to do it for an hour at least. So you are sweating as a result of it.</p>
<p>Sources and references : <a href="http://well.blogs.nytimes.com/2012/04/16/does-exercise-make-you-overeat/">http://well.blogs.nytimes.com</a></p>
<div style="float: left;"><a href="http://bufferapp.com/add" class="buffer-add-button" data-text="Does Exercise Makes You Eat More or Less" data-url="http://www.losethattyre.co.uk/does-exercise-makes-you-eat-more-or-less/" data-via="bufferapp" data-count="horizontal">Buffer</a><script type="text/javascript" src="http://static.bufferapp.com/js/button.js"></script></div><p>Post from: <a href="http://www.losethattyre.co.uk">Weight Loss Blog (Lose That Tyre)</a><br/><br/></p>
<div class="feedflare">
<a href="http://feeds.feedburner.com/~ff/co/PDCB?a=Nm0iYXMCTzk:JVr35qjHTJ0:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/co/PDCB?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/co/PDCB?a=Nm0iYXMCTzk:JVr35qjHTJ0:-BTjWOF_DHI"><img src="http://feeds.feedburner.com/~ff/co/PDCB?i=Nm0iYXMCTzk:JVr35qjHTJ0:-BTjWOF_DHI" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/co/PDCB?a=Nm0iYXMCTzk:JVr35qjHTJ0:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/co/PDCB?d=qj6IDK7rITs" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/co/PDCB?a=Nm0iYXMCTzk:JVr35qjHTJ0:I9og5sOYxJI"><img src="http://feeds.feedburner.com/~ff/co/PDCB?d=I9og5sOYxJI" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/co/PDCB?a=Nm0iYXMCTzk:JVr35qjHTJ0:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/co/PDCB?i=Nm0iYXMCTzk:JVr35qjHTJ0:gIN9vFwOqvQ" border="0"></img></a>
</div><img src="http://feeds.feedburner.com/~r/co/PDCB/~4/Nm0iYXMCTzk" height="1" width="1"/>]]></content:encoded>
      <wfw:commentRss>http://www.losethattyre.co.uk/does-exercise-makes-you-eat-more-or-less/feed/</wfw:commentRss>
      <slash:comments>0</slash:comments>
      <feedburner:origLink>http://www.losethattyre.co.uk/does-exercise-makes-you-eat-more-or-less/?utm_source=rss&amp;utm_medium=rss&amp;utm_campaign=does-exercise-makes-you-eat-more-or-less</feedburner:origLink>
      <enclosure url="http://podcasts.odiogo.com/get_mp3.mp3?f=/weight-loss-blog/Weight_Loss_Blog-Does_Exercise_Makes_You_Eat_More_or_Less.mp3" length="1789080" type="audio/mpeg" />
    </item>
    <item>
      <title>How to Get Yourself a Running Habit</title>
      <link>http://feedproxy.google.com/~r/co/PDCB/~3/WHRg7n9fie0/</link>
      <comments>http://www.losethattyre.co.uk/how-to-get-yourself-a-running-habit/#comments</comments>
      <pubDate>Mon, 23 Apr 2012 09:38:14 +0000</pubDate>
      <dc:creator>Guest Poster</dc:creator>
      <category><![CDATA[Featured]]></category>
      <guid isPermaLink="false">http://www.losethattyre.co.uk/?p=4745</guid>
      <description>Image by lululemonathletica
This is a Guest Post By Julian on behalf of JTX Fitness
The health benefits of running are well known and documented across literature and the web. Running regularly makes us slimmer, healthier and fitter and even better, it helps us to balance our stressful lives, relax our minds and makes us overall happier as well. [...]&lt;p&gt;Post from: &lt;a href="http://www.losethattyre.co.uk"&gt;Weight Loss Blog (Lose That Tyre)&lt;/a&gt;&lt;br/&gt;&lt;br/&gt;&lt;/p&gt;&lt;br&gt;&lt;a type="audio/mpeg" href="http://podcasts.odiogo.com/get_mp3.mp3?f=/weight-loss-blog/Weight_Loss_Blog-How_to_Get_Yourself_a_Running_Habit.mp3"&gt;Click here to play&lt;/a&gt;&lt;br&gt;</description>
      <content:encoded><![CDATA[<iframe src="http://www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.losethattyre.co.uk%2Fhow-to-get-yourself-a-running-habit%2F&amp;layout=standard&amp;show_faces=true&amp;width=450&amp;action=like&amp;colorscheme=light&amp;height=80" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:450px; height:80px;" allowTransparency="true"></iframe><p>Image by <a href="http://www.flickr.com/photos/lululemonathletica/3908348636/sizes/s/in/photostream/">lululemonathletica</a></p>
<p>This is a Guest Post By Julian on behalf of <a href="http://www.jtxfitness.com/treadmills">JTX Fitness</a></p>
<p><img class="alignleft size-full wp-image-4746" style="margin: 20px;" title="3908348636_ca616088e5_m" src="http://www.losethattyre.co.uk/wp-content/uploads/2012/04/3908348636_ca616088e5_m.jpg" alt="" width="240" height="160" />The health benefits of running are well known and documented across literature and the web. Running regularly makes us slimmer, healthier and fitter and even better, it helps us to balance our stressful lives, relax our minds and makes us overall happier as well. All we need to do is to start running, right?</p>
<p>Well, as I am sure many will agree with me it’s just not quite that simple. Running, and especially running regularly requires a vast amount of mental strength particularly during the first few months before it becomes part of our weekly routine and we start feeling weird if we don’t go. An that is precisely the state of mind and body we are aiming for, the sensation of craving to go for a run which is followed by a sense of relaxation and relieve after the run rather than total and utter exhaustion and physical pain.</p>
<p>It is hard work to get to that point and once you are enjoying your running, you still need to put some effort into keeping the momentum up as it is quite easy to lose it all again after a week away on business or a family holiday spent eating well and putting your feet up. For some people, running is part of everyday life – even a way of life and they will not travel without their running gear. Running can be quite addictive to some people but most normal people find it a lot more difficult mentally to get into that routine.</p>
<p>Every person’s body and mind work differently so there is no hard and fast rule of how long it will take to get to that magic point. From personal experience I would say it takes between 4-6 weeks before I am where I want to be. Personally, I am not what one would describe as an enthusiastic runner.</p>
<p>I do not own a running outfit or several pairs of running shoes. I do not wear skin-tight running shorts or even worse, those super short ones that always seem to threaten to reveal a little bit too much. I try to run regularly because exercise makes me a happier person. Every time I decide to get into running again I go through the same mental process. At first I am very motivated and do ok for a week, sometimes two. Then I will use any excuse to not go for a few days, forget about the whole thing and a month later I have to start over again.</p>
<p>So here is a guide of how to get yourself a running habit which is working for me, the average lazy guy:</p>
<p>1. Sit down, work out what you are trying to achieve and write it on a piece of paper. Writing down why you want to run will help you to remind yourself and to get motivated. Then turn that paper around and write in big letters ‘I love running’ on it before you stick it up on the wall in your room. Remember that the overall objective should be to enjoy running regularly, everything else will fall in place from there.</p>
<p>2. Set yourself targets. Short term and a long term targets on how often you want to run are a great start. Making sure they are achievable yet challenging in both frequency and distance. Don’t be too tough on yourself especially in the beginning as the objective is to enjoy it. Making it too difficult for yourself in the beginning increases the risk of you dropping out of your regime.</p>
<p>3. Keep a record of your runs. A little notebook will do but if you are a little bit more technical and enjoy your Apps and gadgets, there are some amazing and mostly free running apps out there allowing you to track your progress on the computer, manage your targets and challenge you to improve your personal best time. Apps I have used in the past and would recommend are the Nike+ app as well as the free version of Runkeeper.</p>
<p>4. Try to be methodical and build the running into your weekly routine. Try to fit the running into your life rather than attempting to re-arrange your life around your new favourite hobby, an approach that is not likely to stand the test of time. For example find something you do twice or three times a week and attach the running to that. Instead of putting your feet up and wasting your time ‘unwinding’ in from of the TV after work, get your running shoes on. If your live is not very structured and every week is different, choose something you still do every day like getting out of bed.</p>
<p>The thought of exercising early is daunting to some but there is no better way to inject some energy into your day than an early morning run. Other alternatives are during your lunch break at work (provided the office has changing facilities and a shower) or last thing in the evening. That latter version is probably the most difficult one if you have an active social or family life. As a woman you should also think about your safety &#8211; running through the city late at night, probably even along the same route on the same days every week may be a concern.</p>
<p>5. Do daydream! – Letting your mind run free will take the focus off the running and help you to get into an almost meditative state making the run feel a lot shorter and less exhausting. Instead of checking your watch or the miles you have done every 5 minutes try to distract your mind from the exercise. A decent running soundtrack or recorded podcasts on a subject you are really interested in work wonders. This kind of meditation and mind-relaxation works particulary well on a treadmill where every step is the same and there are no distractions around at all.</p>
<p>6. Reward yourself for achieving milestones and for keeping it up but choose the kind of reward wisely. Some new runnign shoes or maybe a healthy meal out, don’t be tempted to reward yourself with a week off running as that completely defies the objective. You can start doing that once your routine has stuck and you have proven to yourself that you can keep it up. The temptation of thinking ‘oh I will just take this week off and start again on Monday’ may put you back to square one faster than you think.</p>
<p>7. Religiously stick to it. Now this is probably the most difficult one as most people have the tendency to subconsciously avoid doing something difficult. Try to catch yourself when you are procrastinating and snap out of it as quickly as you can. There are no excuses for not running, it does not require much time or a lot of kit and there is always room for your running shoes when you go on a business trip or a long weekend away with friends. Bad weather is not an acceptable excuse and neither is a hangover.</p>
<p>Not everybody lives in an area where the weather or the environment allow running all year round and at any time of the day. If you find that external factors seem to be keeping you from running more often than not, it may be worth looking into getting your hands on a half-decent treadmill which will allow you to run in the comfort of your home any time you like. You can watch the TV to distract yourself and over the duration of a year it will certainly work out cheaper than a gym membership.</p>
<p>Good treadmills can be a bit pricey but cheap treadmills are a waste of money and you will end up not using them. There are various specialist online retailers like <a href="http://www.jtxfitness.com/treadmills">JTX Fitness</a> selling home fitness equipment, if you are unsure about how frequently you will use it or just do not want to spend that kind of money it is always worth checking the classified section in your local paper or website for a treadmill bargain. There are always people who buy a treadmill in order to get running regularly, fail miserably and then sell a practically un-used treadmill for little money because it is cluttering their garage up. No, you won’t be one of them!</p>
<div style="float: left;"><a href="http://bufferapp.com/add" class="buffer-add-button" data-text="How to Get Yourself a Running Habit" data-url="http://www.losethattyre.co.uk/how-to-get-yourself-a-running-habit/" data-via="bufferapp" data-count="horizontal">Buffer</a><script type="text/javascript" src="http://static.bufferapp.com/js/button.js"></script></div><p>Post from: <a href="http://www.losethattyre.co.uk">Weight Loss Blog (Lose That Tyre)</a><br/><br/></p>
<div class="feedflare">
<a href="http://feeds.feedburner.com/~ff/co/PDCB?a=WHRg7n9fie0:A-6dahp3tjs:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/co/PDCB?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/co/PDCB?a=WHRg7n9fie0:A-6dahp3tjs:-BTjWOF_DHI"><img src="http://feeds.feedburner.com/~ff/co/PDCB?i=WHRg7n9fie0:A-6dahp3tjs:-BTjWOF_DHI" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/co/PDCB?a=WHRg7n9fie0:A-6dahp3tjs:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/co/PDCB?d=qj6IDK7rITs" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/co/PDCB?a=WHRg7n9fie0:A-6dahp3tjs:I9og5sOYxJI"><img src="http://feeds.feedburner.com/~ff/co/PDCB?d=I9og5sOYxJI" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/co/PDCB?a=WHRg7n9fie0:A-6dahp3tjs:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/co/PDCB?i=WHRg7n9fie0:A-6dahp3tjs:gIN9vFwOqvQ" border="0"></img></a>
</div><img src="http://feeds.feedburner.com/~r/co/PDCB/~4/WHRg7n9fie0" height="1" width="1"/>]]></content:encoded>
      <wfw:commentRss>http://www.losethattyre.co.uk/how-to-get-yourself-a-running-habit/feed/</wfw:commentRss>
      <slash:comments>1</slash:comments>
      <feedburner:origLink>http://www.losethattyre.co.uk/how-to-get-yourself-a-running-habit/?utm_source=rss&amp;utm_medium=rss&amp;utm_campaign=how-to-get-yourself-a-running-habit</feedburner:origLink>
      <enclosure url="http://podcasts.odiogo.com/get_mp3.mp3?f=/weight-loss-blog/Weight_Loss_Blog-How_to_Get_Yourself_a_Running_Habit.mp3" length="3696415" type="audio/mpeg" />
    </item>
    <item>
      <title>The 4 Reasons Why (and How) You Should Incorporate Fat into Your Diet</title>
      <link>http://feedproxy.google.com/~r/co/PDCB/~3/UCsEqx5IhPM/</link>
      <comments>http://www.losethattyre.co.uk/the-4-reasons-why-and-how-you-should-incorporate-fat-into-your-diet/#comments</comments>
      <pubDate>Fri, 09 Mar 2012 11:37:12 +0000</pubDate>
      <dc:creator>Mark</dc:creator>
      <category><![CDATA[Featured]]></category>
      <category><![CDATA[Healthy Eating]]></category>
      <guid isPermaLink="false">http://www.losethattyre.co.uk/?p=4727</guid>
      <description>Image by greatlettuce

This is a guest post by This post was written by Ella Davidson of Coupons.org.
In modern times, our society is often overly focused on physical appearance so much so that many people forget about staying healthy. However, the truth is that even if you are trying to lose weight it is important to incorporate fat [...]&lt;p&gt;Post from: &lt;a href="http://www.losethattyre.co.uk"&gt;Weight Loss Blog (Lose That Tyre)&lt;/a&gt;&lt;br/&gt;&lt;br/&gt;&lt;/p&gt;&lt;br&gt;&lt;a type="audio/mpeg" href="http://podcasts.odiogo.com/get_mp3.mp3?f=/weight-loss-blog/Weight_Loss_Blog-The_4_Reasons_Why_and_How_You_Should_Incorporate_Fat_into_Your_Diet.mp3"&gt;Click here to play&lt;/a&gt;&lt;br&gt;</description>
      <content:encoded><![CDATA[<iframe src="http://www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.losethattyre.co.uk%2Fthe-4-reasons-why-and-how-you-should-incorporate-fat-into-your-diet%2F&amp;layout=standard&amp;show_faces=true&amp;width=450&amp;action=like&amp;colorscheme=light&amp;height=80" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:450px; height:80px;" allowTransparency="true"></iframe><p>Image by <a href="http://www.flickr.com/photos/greatlettuce/533939554/sizes/s/in/photostream/">greatlettuce</a></p>
<p><img class="alignleft size-full wp-image-4728" style="margin: 20px;" title="533939554_6479e55846_m" src="http://www.losethattyre.co.uk/wp-content/uploads/2012/03/533939554_6479e55846_m.jpg" alt="" width="240" height="180" /></p>
<p>This is a guest post by This post was written by Ella Davidson of <a href="http://www.coupons.org.">Coupons.org.</a></p>
<p>In modern times, our society is often overly focused on physical appearance so much so that many people forget about staying healthy. However, the truth is that even if you are trying to lose weight it is important to incorporate fat into your diet.</p>
<p>Despite popular belief, deciding to remove all fat from your diet is actually a move that is bad for your health, rather than good for it. It is not the total amount of fat in your diet that affects your weight or susceptibility to disease; rather it is the types of fat. Here are four reasons why and how you should incorporate fat into your diet.</p>
<p><strong>1. Fat plays an important role in your body</strong></p>
<p>Fat is a biological tool that has many functions throughout the body. It is involved in cell membranes and is the chemical starting point for many compounds, including the hormones estrogen and testosterone as well as vitamins, such as Vitamin D.</p>
<p>Removing all fat from your diet prevents these processes from occurring and can result in your body lacking in essential vitamins and under-producing important hormones.The key is to focus on the kind of fat you put into your body. More important is to focus on consuming a proportionately greater amount of unsaturated fats than saturated ones.</p>
<p><strong>2. Unsaturated fats can reduce the risk of heart disease</strong></p>
<p>Fats can be broken down into two groups, unsaturated and saturated fats. Saturated fats are the type of fat that you find in foods such as bacon, cheese, butter and steak. Scientific evidence links this type of fat to an increased risk of heart disease and other negative health effects. However, research suggests that the most effective way to avoid these problems is not to cut fat out of your diet, but to replace saturated fat with unsaturated fat.</p>
<p><strong>3. Unsaturated fats have a number of positive health benefits</strong></p>
<p>Unsaturated fat is often referred to as the ‘good’ fat and has many positive benefits to the body, including reducing inflammation and improving cholesterol levels. There are two forms of unsaturated fats and both are required in the diet. Monounsaturated fats can be found in peanut, canola and olive oils, as well as foods such as avocados, nuts, and seeds, such as pumpkin seeds, almonds and hazelnuts. Polyunsaturated fats are in other oils, such as corn, flaxseed, as well as in flax seeds themselves, walnuts, and fish.</p>
<p>One very good way of incorporating unsaturated fat into your diet is to eat fish at least two times each week and to eat seeds and nuts such as those listed above, both of which are high in these fats. You can take some in a snack bag, or throw them on top of oatmeal or a fruit salad for something a little different.</p>
<p>4. <strong>Saturated fat has health benefits, too</strong></p>
<p>Saturated fats are often promoted as something that should be entirely cut from the diet and that anything containing saturated fats should be avoided whenever humanly possible. However, this is not necessarily true. Saturated fats do play a beneficial role in the body when in small quantities. Saturated fat in the diet reduces the amount of lipoprotein(a). This compound has been associated with heart disease and cannot be lowered by any other known dietary means.</p>
<p>Saturated fat has been reported to increase the strength of bones, which is especially important in older men and women. Other benefits include increased lung health, brain health, and nerve signaling. Accessing saturated fat in the diet isn’t that difficult because most of the foods that people love to eat already contain high amounts of it.</p>
<p>Fat intake, like for most compounds, is all about maintaining a balance. While conventional wisdom tells us that we should remove all sources of fat from our diets, the truth is significantly different. The presence of a substantial amount of unsaturated fat, along with some saturated fat helps our bodies to work much better and to be healthier. It can also decrease our risk of getting diseases, such as heart disease, as well as increase the health of some organs.</p>
<p>This post was written by Ella Davidson of Coupons.org. <a href="http://coupons.org">Coupons</a> provides authoritative couponing information along with top-retailer savings options. Changing your diet can be expensive, consider their directory coupons and deals to help you on your way.</p>
<p>References</p>
<p>- <a href="http://www.hsph.harvard.edu/nutritionsource/what-should-you-eat/fats-full-story/">http://www.hsph.harvard.edu/nutritionsource/what-should-you-eat/fats-full-story/</a></p>
<p>- <a href="http://bodyshapeshiftersonline.com/2011/04/30/why-you-should-eat-more-saturated-fat-in-your-diet/">http://bodyshapeshiftersonline.com/2011/04/30/why-you-should-eat-more-saturated-fat-in-your-diet/</a></p>
<div style="float: left;"><a href="http://bufferapp.com/add" class="buffer-add-button" data-text="The 4 Reasons Why (and How) You Should Incorporate Fat into Your Diet" data-url="http://www.losethattyre.co.uk/the-4-reasons-why-and-how-you-should-incorporate-fat-into-your-diet/" data-via="bufferapp" data-count="horizontal">Buffer</a><script type="text/javascript" src="http://static.bufferapp.com/js/button.js"></script></div><p>Post from: <a href="http://www.losethattyre.co.uk">Weight Loss Blog (Lose That Tyre)</a><br/><br/></p>
<div class="feedflare">
<a href="http://feeds.feedburner.com/~ff/co/PDCB?a=UCsEqx5IhPM:MSplo5FHx4I:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/co/PDCB?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/co/PDCB?a=UCsEqx5IhPM:MSplo5FHx4I:-BTjWOF_DHI"><img src="http://feeds.feedburner.com/~ff/co/PDCB?i=UCsEqx5IhPM:MSplo5FHx4I:-BTjWOF_DHI" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/co/PDCB?a=UCsEqx5IhPM:MSplo5FHx4I:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/co/PDCB?d=qj6IDK7rITs" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/co/PDCB?a=UCsEqx5IhPM:MSplo5FHx4I:I9og5sOYxJI"><img src="http://feeds.feedburner.com/~ff/co/PDCB?d=I9og5sOYxJI" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/co/PDCB?a=UCsEqx5IhPM:MSplo5FHx4I:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/co/PDCB?i=UCsEqx5IhPM:MSplo5FHx4I:gIN9vFwOqvQ" border="0"></img></a>
</div><img src="http://feeds.feedburner.com/~r/co/PDCB/~4/UCsEqx5IhPM" height="1" width="1"/>]]></content:encoded>
      <wfw:commentRss>http://www.losethattyre.co.uk/the-4-reasons-why-and-how-you-should-incorporate-fat-into-your-diet/feed/</wfw:commentRss>
      <slash:comments>4</slash:comments>
      <feedburner:origLink>http://www.losethattyre.co.uk/the-4-reasons-why-and-how-you-should-incorporate-fat-into-your-diet/?utm_source=rss&amp;utm_medium=rss&amp;utm_campaign=the-4-reasons-why-and-how-you-should-incorporate-fat-into-your-diet</feedburner:origLink>
      <enclosure url="http://podcasts.odiogo.com/get_mp3.mp3?f=/weight-loss-blog/Weight_Loss_Blog-The_4_Reasons_Why_and_How_You_Should_Incorporate_Fat_into_Your_Diet.mp3" length="2593157" type="audio/mpeg" />
    </item>
  </channel>
</rss>
<!-- 91934 -->
<!-- Generated by Odiogobot V5.309 / http://www.odiogo.com -->
