<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:wfw="http://wellformedweb.org/CommentAPI/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:sy="http://purl.org/rss/1.0/modules/syndication/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd">
  <channel>
    <title>MIND POWER: Discover the Subconscious Mind Power Secrets » Blog - Podcasts powered by Odiogo</title>
    <atom:link href="http://www.mindpowerspecialreport.com/category/blog/feed/" rel="self" type="application/rss+xml" />
    <link>http://www.mindpowerspecialreport.com</link>
    <description>Mind Power. Unlock the secrets to tapping the power of the subconscious mind for health, wealth, success and happiness. The psychology of brain and mind success at your fingertips</description>
    <lastBuildDate>Tue, 29 Sep 2009 00:48:07 +0000</lastBuildDate>
    <generator>http://wordpress.org/?v=2.9.1</generator>
    <language>en</language>
    <sy:updatePeriod>hourly</sy:updatePeriod>
    <sy:updateFrequency>1</sy:updateFrequency>
    <copyright>admin</copyright>
    <itunes:author>admin</itunes:author>
    <itunes:summary>Mind Power. Unlock the secrets to tapping the power of the subconscious mind for health, wealth, success and happiness. The psychology of brain and mind success at your fingertips</itunes:summary>
    <itunes:explicit>No</itunes:explicit>
    <itunes:block>No</itunes:block>
    <item>
      <title>Success Beliefs: The True Key to Wealth</title>
      <link>http://www.mindpowerspecialreport.com/success-beliefs-the-true-key-to-wealth/</link>
      <comments>http://www.mindpowerspecialreport.com/success-beliefs-the-true-key-to-wealth/#comments</comments>
      <pubDate>Tue, 29 Sep 2009 00:48:07 +0000</pubDate>
      <dc:creator>admin</dc:creator>
      <category><![CDATA[Blog]]></category>
      <category><![CDATA[mind power]]></category>
      <category><![CDATA[Success Beliefs]]></category>
      <guid isPermaLink="false">http://www.mindpowerspecialreport.com/?p=178</guid>
      <description>&lt;p&gt;&lt;a href="http://www.mindpowerspecialreport.com/go/morpheus.php"&gt;&lt;img src="http://www.mindpowerspecialreport.com/wp-content/uploads/2009/09/nicholas.gif" alt="nicholas" title="nicholas" width="105" height="128" class="alignleft size-full wp-image-159" /&gt;&lt;/a&gt;by &lt;b&gt;Nicholaus R. Taylor&lt;/b&gt;&lt;br /&gt;
Best-selling author of&lt;br /&gt;
&lt;a href="http://www.mindpowerspecialreport.com/go/morpheus.php"&gt;The Morpheus Protocol&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;Belief&amp;#8230; the true source of all our accomplishments, unattained goals, happiness or frustration. Beliefs are subconscious. They are the unseen guiding force in our lives that bring us everything we want and desire or that which we fear the most. Once you begin to understand that beliefs are the underlying foundation of who you are and why you do what you do, you will quickly begin to understand how powerful the subconscious mind really is. &lt;/p&gt;
&lt;p&gt;&lt;a href="http://www.mindpowerspecialreport.com/success-beliefs-the-true-key-to-wealth/#more-178" class="more-link"&gt;More on Success Beliefs: The True Key to Wealth&lt;/a&gt;&lt;/p&gt;&lt;br&gt;&lt;a type="audio/mpeg" href="http://podcasts.odiogo.com/get_mp3.mp3?f=/mind-powerunlock-the-subconscious-mind-power-secr/Mind_Power-Unlock_The_Subconscious_Mind_Power_Secr-Success_Beliefs-_The_True_Key_to_Wealth.mp3"&gt;Click here to play&lt;/a&gt;&lt;br&gt;</description>
      <content:encoded><![CDATA[<p><a href="http://www.mindpowerspecialreport.com/go/morpheus.php"><img src="http://www.mindpowerspecialreport.com/wp-content/uploads/2009/09/nicholas.gif" alt="nicholas" title="nicholas" width="105" height="128" class="alignleft size-full wp-image-159" /></a>by <b>Nicholaus R. Taylor</b><br />
Best-selling author of<br />
<a href="http://www.mindpowerspecialreport.com/go/morpheus.php">The Morpheus Protocol</a></p>
<p>Belief&#8230; the true source of all our accomplishments, unattained goals, happiness or frustration. Beliefs are subconscious. They are the unseen guiding force in our lives that bring us everything we want and desire or that which we fear the most. Once you begin to understand that beliefs are the underlying foundation of who you are and why you do what you do, you will quickly begin to understand how powerful the subconscious mind really is. </p>
<p>Beliefs are taken on at an early age and usually from our parents, other family members, peers, teachers, television and so on. Once you accept something as truth, it becomes a belief running on auto pilot within your subconscious mind guiding your everyday affairs according to that program in the most subtle but yet almost uncontrollable way.</p>
<p>The average person has no idea of how many subconscious programs are running their lives on auto-pilot. You can notice these auto-pilot programs very clearly next time you are out and about. Notice the person in line with a nervous twitch, biting finger nails, starring at a magazine ad for food and so on. It may seem as if these people are completely conscious of what they are doing but when you take another look you will notice many other things going on and that these things are completely unconscious! </p>
<blockquote><p><a href="http://www.mindpowerspecialreport.com/go/morpheus.php"><img src="http://www.mindpowerspecialreport.com/wp-content/uploads/2009/09/morpheus-100x150.jpg" alt="morpheus" title="morpheus" width="100" height="150" class="alignleft size-thumbnail wp-image-163" /></a><a href="http://www.mindpowerspecialreport.com/go/morpheus.php">The Morpheus Protocol</a> is creating massive positive changes in peoples lives! Developed over the last decade through diligent research in the areas of subconscious science, psychological studies and NLP, this carefully crafted technique is fast acting, effective and creates lasting changes where the root of the problems reside, deep within the subconscious mind.<br />
<a href="http://www.mindpowerspecialreport.com/go/morpheus.php"><i>Click here to learn more about the Morpheus Protocol!</i></a></p></blockquote>
<p>How many people have you seen sabotage their own efforts when trying to accomplish a goal? How many people have you seen ruin good relationships or stay in ones that were completely out of control? How many stories do you hear about people winning the lottery only to end up broke shortly after?</p>
<p>All of these situations are guided by an unseen force that exists within everyone of us and what ever habits and beliefs we picked up from some one we looked up to, those habits become programs in the subconscious mind that can run on auto-pilot for ever unless they are properly eliminated. </p>
<p>The <a href="http://www.mindpowerspecialreport.com/go/morpheus.php">The Morpheus Protocol</a> is the most powerful and quickest way to eliminate negative subconscious beliefs “programs” with out meditation or hypnosis. This technique speaks the language of the nervous system allowing you to quickly access the subconscious mind and start erasing old limiting beliefs that have turned into habits. Once these old limiting beliefs have stopped running and have been erased from your subconscious, new energy is released and a new you emerges. </p>
<p><font size="4">Success has to be more than just a mind state, it has to be a belief.</font> Most people believe they can be successful, but its the limiting belief “that pessimistic voice” that counter acts your desire to live a better life that is the negative subconscious program blocking you from attaining your goals. Once again, that little voice was put there by some one else. Most of the time, we think its just us being hard on ourselves when in reality, that little voice is a subconscious program or what I call an “Archetype” simply trying to run its program. </p>
<p>The <a href="http://www.mindpowerspecialreport.com/go/morpheus.php">The Morpheus Protocol</a> eliminates that opposing little voice and the emotional frustration that comes from listening to it! We all want a better life, more money, more joy and freedom to think and grow. Getting rid of those limiting belief programs and discovering the powerful positive ones you already have is now at your fingertips. </p>
<p>The <a href="http://www.mindpowerspecialreport.com/go/morpheus.php">The Morhpeus Protocol</a> will teach you how to quickly access your subconscious with out meditation or hypnosis, find those limiting beliefs and get rid of them so you can live the life you want and experience how much more life has to offer. You will become a different person. Other people will notice they new you. They will feel it emanating from your core. Not only that but others will act differently around you as well. </p>
<p>As this moment right now, its about simply making a decision. A decision to keep running the mill or change your circumstances and take charge of your life. Something inside you wants to improve, it wants you to have, be and do more. It is this very same part of you that has brought you to this article&#8230; and not by chance. Here is your opportunity to get rid of old limiting programs and discover your success beliefs, the true key to wealth.</p>
<p><a href="http://www.mindpowerspecialreport.com/go/morpheus.php"><img src="http://www.mindpowerspecialreport.com/wp-content/uploads/2009/09/morpheus-100x150.jpg" alt="morpheus" title="morpheus" width="100" height="150" class="alignleft size-thumbnail wp-image-163" /></a>Nicholaus R. Taylor is an author, entrepreneur, researcher, film/television producer and personal break through expert. Through the discovery that beliefs control every aspect of our lives, and beliefs become subconscious programs that are literally installed into the nervous system to run on autopilot, Nicholaus has created <a href="http://www.mindpowerspecialreport.com/go/morpheus.php">The Morpheus Protocol technique</a> that allows you to access the subconscious very quickly without hypnosis, repetition or meditation and eliminate useless subconscious programs within a matter of seconds to minutes.</p>
]]></content:encoded>
      <wfw:commentRss>http://www.mindpowerspecialreport.com/success-beliefs-the-true-key-to-wealth/feed/</wfw:commentRss>
      <slash:comments>1</slash:comments>
      <enclosure url="http://podcasts.odiogo.com/get_mp3.mp3?f=/mind-powerunlock-the-subconscious-mind-power-secr/Mind_Power-Unlock_The_Subconscious_Mind_Power_Secr-Success_Beliefs-_The_True_Key_to_Wealth.mp3" length="2559557" type="audio/mpeg" />
    </item>
    <item>
      <title>Why Do Some Succeed While Others Struggle?</title>
      <link>http://www.mindpowerspecialreport.com/why-do-some-succeed-while-others-struggle/</link>
      <comments>http://www.mindpowerspecialreport.com/why-do-some-succeed-while-others-struggle/#comments</comments>
      <pubDate>Wed, 23 Sep 2009 00:59:24 +0000</pubDate>
      <dc:creator>admin</dc:creator>
      <category><![CDATA[Blog]]></category>
      <guid isPermaLink="false">http://www.mindpowerspecialreport.com/?p=157</guid>
      <description>&lt;p&gt;&lt;a href="http://www.mindpowerspecialreport.com/go/morpheus.php"&gt;&lt;img src="http://www.mindpowerspecialreport.com/wp-content/uploads/2009/09/nicholas.gif" alt="nicholas" title="nicholas" width="105" height="128" class="alignleft size-full wp-image-159" /&gt;&lt;/a&gt;by &lt;b&gt;Nicholaus R. Taylor&lt;/b&gt;&lt;br /&gt;
Best-selling author of&lt;br /&gt;
&lt;a href="http://www.mindpowerspecialreport.com/go/morpheus.php"&gt;The Morhpeus Protocol&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;There are several answers to this question and to begin, it is important to understand that timing is a major factor that plays a role in a person&amp;#039;s success. &lt;/p&gt;
&lt;p&gt;&lt;a href="http://www.mindpowerspecialreport.com/why-do-some-succeed-while-others-struggle/#more-157" class="more-link"&gt;More on Why Do Some Succeed While Others Struggle?&lt;/a&gt;&lt;/p&gt;&lt;br&gt;&lt;a type="audio/mpeg" href="http://podcasts.odiogo.com/get_mp3.mp3?f=/mind-powerunlock-the-subconscious-mind-power-secr/Mind_Power-Unlock_The_Subconscious_Mind_Power_Secr-Why_Do_Some_Succeed_While_Others_Struggle.mp3"&gt;Click here to play&lt;/a&gt;&lt;br&gt;</description>
      <content:encoded><![CDATA[<p><a href="http://www.mindpowerspecialreport.com/go/morpheus.php"><img src="http://www.mindpowerspecialreport.com/wp-content/uploads/2009/09/nicholas.gif" alt="nicholas" title="nicholas" width="105" height="128" class="alignleft size-full wp-image-159" /></a>by <b>Nicholaus R. Taylor</b><br />
Best-selling author of<br />
<a href="http://www.mindpowerspecialreport.com/go/morpheus.php">The Morhpeus Protocol</a></p>
<p>There are several answers to this question and to begin, it is important to understand that timing is a major factor that plays a role in a person&#039;s success. </p>
<p>Always keep in mind that life is not all about the end result goal; it is about the journey that helps get you there and all the knowledge and experiences you pick up along the way. Having a goal is okay but worrying about getting there can create blocks.</p>
<p>Understanding that a part of life&#039;s meaning is about &#034;conscious experience&#034; will help you grasp the fact that no matter what happens to you in life, just be grateful you are alive, kicking and experiencing the greatness we call life!</p>
<p>Now let&#039;s look at the meaning of the two words &#034;success &#034;and &#034;struggle&#034; according to Mariam-Websters dictionary.</p>
<p><font size="4">Success</font> &#8211;<br />
<i>A. Degree or measure of succeeding.<br />
B. Favorable or desired outcome, also the attainment of wealth, favor or eminence.</i></p>
<p><font size="4">Struggle</font> &#8211;<br />
<i>A. To make strenuous or violent efforts in the face of difficulties or opposition <struggling with the problem><br />
B. To proceed with difficulty or with great effort > <struggling to make a living> </i></p>
<p>What you will notice between these two words is a great difference, not only in their meaning, but also in terms of timing. Success is thought of as a future tense word and event. Struggle is a present tense word and event. In a later chapter you will get a clear understanding of what role our minds play within struggle and success. For now let us focus on the effects each word has on our body and mind.</p>
<p>When you mention the word &#034;struggle&#034; you will probably get an uncomfortable feeling within. Some people love struggle and thrive on it. It makes them feel alive.  Others may cringe at the mere sight or sound of the word.</p>
<p>When you are wondering why people are doing what they are doing, remember, EVERYONE IS DIFFERENT. </p>
<p>Keeping this in mind will help a person stop being judgmental about others when they appear to screw something up. It is a part of everyone&#039;s learning process to mess something up and those who are a part of the process need to understand that there is great wisdom in what they have experienced during a turn of events that may not have played out in their favor. </p>
<p>Also, remember that just because something may not turn out in your favor does not mean it&#039;s the end of the world. There may just be a subconscious block that needed to be eliminated before you took on the Endeavour.</p>
<p>As the great saying goes, &#034;As above so below; As within, so without,&#034; meaning that what is going on outside of you reflects what is going on inside of you. If you are having many struggles in your daily life, there are struggles going on within yourself that you may or may not be aware of. </p>
<p>By taking a look at the situations you have put yourself in, you will get a good look at what is going on within you that needs to be addressed and cleared out so that you can move above and beyond what you are struggling with. </p>
<p>For those of you who like to struggle, don&#039;t worry.  Even as you move beyond your internal resistance blocks, there will still be plenty of challenges to face and overcome as you move onward and upward. </p>
<p><b><i>There is great personal power to be had in overcoming obstacles.</b></i></p>
<p>Even for those who seem to have it all together, there are still decisions and challenges they are faced with at times. It all depends on how you handle those challenges that determines the outcomes.</p>
<p><u><i>Success as mentioned above is an end result goal.</u></i> But our personal definition of a successful person may seem to be different. If you think about a person that you would say is successful do you see them retired and just relaxing? Most likely not. When I think of a successful person I picture in my mind a person who is on the go, handling his or her business and feeling happy because he or she is living their passion. </p>
<blockquote><p><a href="http://www.mindpowerspecialreport.com/go/morpheus.php"><img src="http://www.mindpowerspecialreport.com/wp-content/uploads/2009/09/morpheus-100x150.jpg" alt="morpheus" title="morpheus" width="100" height="150" class="alignleft size-thumbnail wp-image-163" /></a><a href="http://www.mindpowerspecialreport.com/go/morpheus.php">The Morpheus Protocol</a> is creating massive positive changes in peoples lives! Developed over the last decade through diligent research in the areas of subconscious science, psychological studies and NLP, this carefully crafted technique is fast acting, effective and creates lasting changes where the root of the problems reside, deep within the subconscious mind.<br />
<a href="http://www.mindpowerspecialreport.com/go/morpheus.php"><i>Click here to learn more about the Morpheus Protocol!</i></a></p></blockquote>
<p>Keep in mind that everyone&#039;s definition of success will be different because everyone is different and each expects different things from themselves. </p>
<p><b>It is important to understand what your own definition of success is and try not to make it just an end result expectation.</b> Even though success describes an end result, it is actually more of an in-the-now action word.</p>
<p>If you find yourself struggling with a situation or with life in general, here is an excellent way to move beyond the struggle and into a mode of flow, because success is a flow, and to struggle is to move against the flow of success.</p>
<p>The first thing to do is assess that which is causing the struggle, which would be &#034;You.&#034;  Next, relax and take a deep breath and then look outward to the situation at hand. The importance here is to relax. When you relax it allows your mind to work more efficiently.  If your muscles are tense, it uses up vital energy that the brain needs to bring forth viable solutions from the right brain hemisphere where our creative faculties reside. </p>
<p><b>Here is a story</b> that will help you understand what helps spark the flow of success and remove the resistance of struggle. </p>
<p>John was struggling with trying to figure out what type of business to start. He struggled day and night trying to think of ideas. He asked himself, &#034;What kind of business could make me a lot of money?&#034; While searching for an answer he began to get more and more frustrated. He was caught in the struggle of moving against the flow of success. After meeting with a business consultant, it became clear that if he was to start a business, it would need to be doing something he absolutely loved doing. Within a minute or so he began coming up with ideas of what type of business to start. After he sparked his natural passion by thinking of what he loves doing, he moved into the flow of success which opened his creative mind &#034;right brain hemisphere,&#034; bringing in a flood of ideas that he could capture, organize, put to paper, and begin to act on. </p>
<p>When John focused on what he was passionate about his body relaxed and his creative mind and motivation kicked in with ease. This demonstrates the power of inner resourcefulness when we align with our deeper purpose and natural talents.  </p>
<p><font size="4">Remember, success is a flow.</font> Struggle is when you are working against the flow. It is actually easier to be successful and move with the flow. It takes up to ten times more energy to struggle against something, especially when it is yourself, because what you are struggling with externally reflects what you are struggling with internally.</p>
<p>This step for John was a good one to help him come up with ideas but there is another step John needs to take before taking action on his business plan.  He has to make sure that his internal resistance factors have been eliminated.  Otherwise, those resistant forces will work against his every effort like they did me for so long before discovering the block removal technique you are about to learn.</p>
<p>So you may be asking yourself, &#034;Why don&#039;t people just stop struggling and go with the flow?&#034; You would think it is an easy task but there are some main factors involved with change that must be addressed before the change can happen.</p>
<p><a href="http://www.mindpowerspecialreport.com/go/morpheus.php"><img src="http://www.mindpowerspecialreport.com/wp-content/uploads/2009/09/morpheus-100x150.jpg" alt="morpheus" title="morpheus" width="100" height="150" class="alignleft size-thumbnail wp-image-163" /></a>Nicholaus R. Taylor is an author, entrepreneur, researcher, film/television producer and personal break through expert. Through the discovery that beliefs control every aspect of our lives, and beliefs become subconscious programs that are literally installed into the nervous system to run on autopilot, Nicholaus has created <a href="http://www.mindpowerspecialreport.com/go/morpheus.php">The Morpheus Protocol technique</a> that allows you to access the subconscious very quickly without hypnosis, repetition or meditation and eliminate useless subconscious programs within a matter of seconds to minutes.</p>
]]></content:encoded>
      <wfw:commentRss>http://www.mindpowerspecialreport.com/why-do-some-succeed-while-others-struggle/feed/</wfw:commentRss>
      <slash:comments>2</slash:comments>
      <enclosure url="http://podcasts.odiogo.com/get_mp3.mp3?f=/mind-powerunlock-the-subconscious-mind-power-secr/Mind_Power-Unlock_The_Subconscious_Mind_Power_Secr-Why_Do_Some_Succeed_While_Others_Struggle.mp3" length="3902815" type="audio/mpeg" />
    </item>
    <item>
      <title>What We Focus On Affects Our Results In Life</title>
      <link>http://www.mindpowerspecialreport.com/what-we-focus-on-affects-our-results-in-life/</link>
      <comments>http://www.mindpowerspecialreport.com/what-we-focus-on-affects-our-results-in-life/#comments</comments>
      <pubDate>Fri, 11 Sep 2009 14:25:40 +0000</pubDate>
      <dc:creator>admin</dc:creator>
      <category><![CDATA[Blog]]></category>
      <guid isPermaLink="false">http://www.mindpowerspecialreport.com/?p=152</guid>
      <description>&lt;p&gt;&lt;img src="http://www.mindpowerspecialreport.com/wp-content/uploads/2009/09/Adam-Khoo_114863-150x150.jpg" alt="Adam-Khoo_114863" title="Adam-Khoo_114863" width="150" height="150" class="alignleft size-thumbnail wp-image-134" /&gt;by &lt;b&gt;Adam Khoo&lt;/b&gt;&lt;br /&gt;
Motivation Speaker &amp;#124; Asia&amp;#039;s #1 Success Coach&lt;br /&gt;
Best-selling author of&lt;br /&gt;
&lt;a href="http://cywei99.successnlp.hop.clickbank.net"&gt;Master Your Mind, Design Your Destiny&lt;/a&gt;&lt;br /&gt;
&lt;a href="http://www.adamkhoo.net/go.php?offer=cywei99&amp;#038;pid=12"&gt;Secrets of Self-Made Millionaires&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;At any given second, there are two million bits of information bombarding us. While it is impossible to consciously be aware of everything, our mind tends to filter all this stimuli and focus on a few chunks of information at a time.&lt;/p&gt;
&lt;p&gt;&lt;a href="http://www.mindpowerspecialreport.com/what-we-focus-on-affects-our-results-in-life/#more-152" class="more-link"&gt;More on What We Focus On Affects Our Results In Life&lt;/a&gt;&lt;/p&gt;&lt;br&gt;&lt;a type="audio/mpeg" href="http://podcasts.odiogo.com/get_mp3.mp3?f=/mind-powerunlock-the-subconscious-mind-power-secr/Mind_Power-Unlock_The_Subconscious_Mind_Power_Secr-What_We_Focus_On_Affects_Our_Results_In_Life.mp3"&gt;Click here to play&lt;/a&gt;&lt;br&gt;</description>
      <content:encoded><![CDATA[<p><img src="http://www.mindpowerspecialreport.com/wp-content/uploads/2009/09/Adam-Khoo_114863-150x150.jpg" alt="Adam-Khoo_114863" title="Adam-Khoo_114863" width="150" height="150" class="alignleft size-thumbnail wp-image-134" />by <b>Adam Khoo</b><br />
Motivation Speaker | Asia&#039;s #1 Success Coach<br />
Best-selling author of<br />
<a href="http://cywei99.successnlp.hop.clickbank.net">Master Your Mind, Design Your Destiny</a><br />
<a href="http://www.adamkhoo.net/go.php?offer=cywei99&#038;pid=12">Secrets of Self-Made Millionaires</a></p>
<p>At any given second, there are two million bits of information bombarding us. While it is impossible to consciously be aware of everything, our mind tends to filter all this stimuli and focus on a few chunks of information at a time.</p>
<p>Similarly, when we think of something in the past or something in the future, we tend to focus on certain aspects of the experience. And to us what we choose to focus on becomes most real in our minds. Some people have a pattern of focusing on pictures, sounds and feelings that put them into un-resourceful states while others generate pictures, sounds and feelings them put them into resourceful states.</p>
<p>How about you? What do you do when you meet with failure? Some people keep playing mind pictures of themselves screwing up. Some people even play it like a bad movie, over and over again in their heads.</p>
<p>They keep seeing themselves making the bad decisions, experiencing the consequences and they re-play all the negative voices around them. They may play the sound of their boss shouting at them. Then they run an internal dialogue that goes like this: &#039;How could I have been so stupid!&#039; &#039;Why do I always screw things up?&#039;</p>
<p>What kind of pictures and sounds should one play to produce a resourceful state?</p>
<p><a href="http://cywei99.successnlp.hop.clickbank.net"><img alt="" src="http://www.successwithnlp.com/images/book-small.jpg" class="alignleft" width="150" height="214" /></a>Well, this is what positive people do when they encounter failure. They choose to re-present the failure as feedback that will lead them into finding a solution. Instead of re-playing scenes of the event or project that flopped, they focus on what they can learn from it, and how they will do it the next time&#8230;to get good results.<br />
They may even imagine themselves succeeding, using what they have learnt from the past experience, and their success would be accompanied by the sounds of people cheering or the boss congratulating them.</p>
<p>Our minds are never still or idle&#8230;throughout our waking hours we play mental programs continuously. Now, start becoming aware of the kind of mental program you usually run, when you are about to take on a challenging task?</p>
<p>For example, just before making an important presentation or writing a difficult report, what goes on in your mind?</p>
<p>Are you one of those who habitually focus on how difficult it is going to be? Do you see yourself being overwhelmed and stressed out? Do you mutter under your breath, &#039;Oh no! How am I ever going to do this?&#039; &#039;What if I screw up?&#039; &#039;It&#039;s just too difficult!&#039; You may even picture yourself screwing up or giving up. As a result you get into a state of nervous anxiety.</p>
<p>But can you choose to represent the challenge very differently in your mind? Of course! You could choose to focus on how easy, fun and rewarding the challenge will be. Confident people will picture themselves dealing with the task or project effortlessly. They may even have an internal voice saying, &#039;I am finally getting this done! This is so rewarding!&#039; &#039;I knew I could do it.&#039;</p>
<p>Now, given the same challenge, why do some people rise to it while others feel apprehension? The interesting fact is that most of us do not consciously decide what pictures, sounds and feelings we are going to generate in our mind.</p>
<p>Our mind seems to be on auto-pilot and, within seconds of being faced with a challenge, it will subconsciously, create re-presentations. And the kinds of re-presentations created are dependent on past conditioning.</p>
<p>Isn&#039;t this scary? It appears that we do not have much control over our mind! This is why most people feel that their emotions control them.</p>
<p>Begin by paying full attention to the &#039;program&#039; that is running in your brain-mind. If you find that what you are thinking of is not putting you in a resourceful state, then change it! In short, consciously change WHAT you focus on! You may keep slipping back, and each time you do, pull yourself up and re-focus. If you want to have mastery over your mind and emotions, then you must begin right away to control what you focus on!</p>
<p><a href="http://www.adamkhoo.net/go.php?offer=cywei99&#038;pid=8"><img alt="" src="http://www.patterns-of-excellence.com/images/group-final-small.jpg" class="alignleft" width="200" height="162" /></a>Adam Khoo is an entrepreneur, best-selling author and a self-made millionaire by the age of 26. Over the last 15 years, he has trained over 245,000 professionals, executives and business owners to tap their personal power and achieve excellence in their various fields of endeavor. Discover his supercharged success secrets and claim your FREE bonus report Ultimate Success Formula at <b><a href="http://www.adamkhoo.net/go.php?offer=cywei99&#038;pid=8">http://www.Patterns-Of-Excellence.com</a></b></p>
]]></content:encoded>
      <wfw:commentRss>http://www.mindpowerspecialreport.com/what-we-focus-on-affects-our-results-in-life/feed/</wfw:commentRss>
      <slash:comments>3</slash:comments>
      <enclosure url="http://podcasts.odiogo.com/get_mp3.mp3?f=/mind-powerunlock-the-subconscious-mind-power-secr/Mind_Power-Unlock_The_Subconscious_Mind_Power_Secr-What_We_Focus_On_Affects_Our_Results_In_Life.mp3" length="2381870" type="audio/mpeg" />
    </item>
    <item>
      <title>It Ain't How Hard You Hit – It's How Hard You Can Get Hit and Keep Moving Forward!</title>
      <link>http://www.mindpowerspecialreport.com/it-aint-how-hard-you-hit-its-how-hard-you-can-get-hit-and-keep-moving-forward/</link>
      <comments>http://www.mindpowerspecialreport.com/it-aint-how-hard-you-hit-its-how-hard-you-can-get-hit-and-keep-moving-forward/#comments</comments>
      <pubDate>Sat, 05 Sep 2009 03:06:07 +0000</pubDate>
      <dc:creator>admin</dc:creator>
      <category><![CDATA[Blog]]></category>
      <category><![CDATA[adam khoo]]></category>
      <guid isPermaLink="false">http://www.mindpowerspecialreport.com/?p=128</guid>
      <description>&lt;p&gt;&lt;img src="http://www.mindpowerspecialreport.com/wp-content/uploads/2009/09/Adam-Khoo_114863-150x150.jpg" alt="Adam-Khoo_114863" title="Adam-Khoo_114863" width="150" height="150" class="alignleft size-thumbnail wp-image-134" /&gt;by &lt;b&gt;Adam Khoo&lt;/b&gt;&lt;br /&gt;
Motivation Speaker &amp;#124; Asia&amp;#039;s #1 Success Coach&lt;br /&gt;
Best-selling author of&lt;br /&gt;
&lt;a href="http://cywei99.successnlp.hop.clickbank.net"&gt;Master Your Mind, Design Your Destiny&lt;/a&gt;&lt;br /&gt;
&lt;a href="http://www.adamkhoo.net/go.php?offer=cywei99&amp;#038;pid=12"&gt;Secrets of Self-Made Millionaires&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;It was about 22 years ago when I watched my first ROCKY movie (Rocky III) and it really inspired me to get up from defeat (after failing my exams) and to train hard to become a winner in life.&lt;/p&gt;
&lt;p&gt;&lt;a href="http://www.mindpowerspecialreport.com/it-aint-how-hard-you-hit-its-how-hard-you-can-get-hit-and-keep-moving-forward/#more-128" class="more-link"&gt;More on It Ain&amp;#039;t How Hard You Hit &amp;#8211; It&amp;#039;s How Hard You Can Get Hit and Keep Moving Forward!&lt;/a&gt;&lt;/p&gt;&lt;br&gt;&lt;a type="audio/mpeg" href="http://podcasts.odiogo.com/get_mp3.mp3?f=/mind-powerunlock-the-subconscious-mind-power-secr/Mind_Power-Unlock_The_Subconscious_Mind_Power_Secr-It_Aint_How_Hard_You_Hit__Its_How_Hard_You_Can_Get_Hit_and_Keep_Moving_Forward.mp3"&gt;Click here to play&lt;/a&gt;&lt;br&gt;</description>
      <content:encoded><![CDATA[<p><img src="http://www.mindpowerspecialreport.com/wp-content/uploads/2009/09/Adam-Khoo_114863-150x150.jpg" alt="Adam-Khoo_114863" title="Adam-Khoo_114863" width="150" height="150" class="alignleft size-thumbnail wp-image-134" />by <b>Adam Khoo</b><br />
Motivation Speaker | Asia&#039;s #1 Success Coach<br />
Best-selling author of<br />
<a href="http://cywei99.successnlp.hop.clickbank.net">Master Your Mind, Design Your Destiny</a><br />
<a href="http://www.adamkhoo.net/go.php?offer=cywei99&#038;pid=12">Secrets of Self-Made Millionaires</a></p>
<p>It was about 22 years ago when I watched my first ROCKY movie (Rocky III) and it really inspired me to get up from defeat (after failing my exams) and to train hard to become a winner in life.</p>
<p>Today, 22 years later, I find myself being inspired once again by Sylvestor Stallone&#039;s latest Rocky Movie (Rocky Balboa- part 6). In this latest movie, Rocky is aged 60+ and retired from boxing. One day, Rocky decides to come out of retirement and to get back into the ring. He feels the need to fight because of emotional issues that he needs to resolve within himself. Naturally, he is criticized and made fun of because he is fighting opponents half his age.</p>
<p>His son (a corporate executive in his 30s) is totally against the idea. His career is going nowhere and he blames his father for casting a big shadow over him. His friends make fun of him because of who his father is.</p>
<p>This is where the 60-year old Rocky gives his son a heart-to-heart reprimand about how he needs to stop blaming and take charge of his life. A saddened Rocky says he remembers when his son could fit in the palm of his hand.</p>
<p>He says that he saw great potential in him and when he first started off in life, he did great. However,at some point, he changed. He lost his way and started blaming other things and people for his own misfortune. Telling him:</p>
<blockquote><p>&#034;Let me tell you something you already know. The world ain&#039;t all sunshine and rainbows. It is a very mean and nasty place and I don&#039;t care how tough you are, it will beat you to your knees and keep you there permanently if you let it. You, me, or nobody is gonna hit as hard as life.</p>
<p><b>But it ain&#039;t about how hard you hit; it&#039;s about how hard you can get hit, and keep moving forward.</b> It&#039;s How much you can take, and keep moving forward. That&#039;s how winning is done.</p></blockquote>
<p>Now, if you know what you&#039;re worth, then go out and get what you&#039;re worth. But you gotta be willing to take the hits, and not point fingers and blame other people. Cowards do that and that ain&#039;t you. You&#039;re better than that!&#034;</p>
<p>This movie had a huge impact on me just like the first few Rocky movies did because what was said was so true in my own life. &#034; Its not how hard you hit, but how hard you can get hit and keep moving forward.&#034;</p>
<p>I have found that in my life, I have met so many people who were much smarter, talented and luckier than me. What made me more successful at the end of the day was my ability to get hit again and again and to keep moving forward. I never gave up. However, I know of many friends who got hit hard by life and could never find the courage to get up again. Instead, they quit dreaming and accepted a mediocre life.</p>
<p><i>There were many times in my life when I did get hit hard and felt that I had problems I could never solve.</i> There were times when I felt that life was unfair and too painful to live. What kept me going forward was that I knew that no matter how bad, every problem will not last forever. Every recession will end. Dawn always breaks after the darkest hour. It was this belief that allowed me to keep getting up.</p>
<p>• When I got expelled from school at age 9, I kept moving forward<br />
• When my parents split up when I was aged 13, I kept moving forward<br />
• When my first girlfriend dumped me just before my major exams (and I was subsequently dumped by 2 other girls), I kept moving forward<br />
• When everyone looked down on me because I got poor grades in school, I kept moving forward<br />
• When my interior design business went bankrupt (Losing me $250,000), I kept moving forward<br />
• When I lost over $300,000 in the stock market as an early amateur investor, I kept moving forward<br />
• When my first book, &#039;I Am Gifted, So Are You!&#039; was rejected by over 9 publishers, I kept moving forward<br />
• When only 1 person signed up for my first Patterns of Excellence program 7.5 years ago, and everyone thought that my company would never make it, I kept moving forward<br />
• When I lost all the money I made from my mobile disco business because I was cheated by a supplier I trusted, I kept moving forward</p>
<p>Whenever we see people achieve great things, it is easy to think that they had less problems and less obstacles than we have. That their brilliance, luck or talent gave them super human abilities to sail through life easily. That everything always goes according to plan.</p>
<p><b>I can tell you from experience that things NEVER EVER always go according to plan. 80% of the goals you set and plans you make will never go the way you want. Things will screw up and obstacles will appear that will knock you down. Its all part of the game of life.</b></p>
<p>Have you heard of George Lucas, the creator of Star Wars? On the surface, it seems this guy could do not wrong. He had the genius to create one of the most successful franchises in the world, Star Wars that made hundreds of millions of dollars.</p>
<p>Did you know of all the things that went wrong? When George Lucas had the vision of creating the special effects for the battle scenes, the technology did not exist at the time. That didn&#039;t stop Lucas. He set up a company, Industrial Light &#038; Magic to invent and create the special effects needed to make Star Wars.</p>
<p><a href="http://cywei99.successnlp.hop.clickbank.net"><img alt="" src="http://www.successwithnlp.com/images/book-small.jpg" class="alignleft" width="150" height="214" /></a>Did it work? Not at first. During production, everything that could have possibly gone wrong went wrong! At the end of sixteen weeks of filming, everyone had every reason to believe it would fail.</p>
<p>The equipment kept breaking down, the actors could not get along and everything that was filmed turned out lousy and had to be discarded. The movie had grossly exceeded the initial budget, it had overrun the filming schedule, the special effects unit could not create the desired special effects and everyone had the opinion that the movie was too childish.</p>
<p>As a result, 20th Century Fox studios (the producers) wanted to cancel the movie and fire Lucas. After Lucas begged for a chance to save the movie, they gave him three days to finish two weeks of work that was lost. It seemed like an impossible task.</p>
<p>What made things worse was that Lucas suffered severe chest pains in the middle of all this and was rushed to hospital for severe stress and exhaustion. Everyone thought that the movie would fail (even some of the actors didn&#039;t dare to go for the premier).</p>
<p>But Lucas just wouldn&#039;t quit. Lucas hired a triple filming crew, divided the film stage into three sets and directed three scenes concurrently! Within 3 days, he filmed weeks worth of scenes and finished the movie only moments before the movie premier. The rest was history!</p>
<p>I am sure you have heard of Honda Motor Corporation, one of the most successful automakers from Japan. Again what made Honda a success was that its founder, Soichiro Honda was able to take the hardest hits and still get up and move forward.</p>
<p>In 1938, while Soichiro was still in school, when he started a workshop to develop the piston ring that he hoped he could sell to Toyota. He worked 7 days a week, even sleeping in his workshop at times. When money ran out with no success, he pawned his wife&#039;s jewelry for working capital.</p>
<p>Finally, came the day he completed his piston ring and was able to sell it to Toyota. However, he was told that the rings did not meet their standards! Soichiro went back to school for 2 years to improve his invention only to suffer ridicule when the engineers saw his design.</p>
<p><a href="http://www.adamkhoo.net/go.php?offer=cywei99&#038;pid=8"><img alt="" src="http://www.patterns-of-excellence.com/images/group-final-small.jpg" class="alignleft" width="200" height="162" /></a><b>He refused to quit.</b> After two more years of struggle and improvement, he successful won the contract with Toyota. He needed to build a factory to supply Toyota. Unfortunately, his timing was bad. At this time, the Japanese government was gearing up for war and needed all the concrete for the war effort, so he could not get the concrete necessary to build his factory.</p>
<p>Instead of giving up, he invented a new concrete-making process that enabled him to build the factory. With the factory now built, he was ready for production, but again, his luck was bad. His factory was bombed twice by American war planes and steel became unavailable, too.</p>
<p>Instead of giving up, he started collecting surplus gasoline cans discarded by US fighters &#8211; &#034;Gifts from President Truman,&#034; he called them, which became the new raw materials for his rebuilt manufacturing process. Again, his timing was bad. An earthquake hit and his factory was destroyed the third time.</p>
<p>After the war, an extreme gasoline shortage forced people to walk or use bicycles. Soichiro saw this opportunity and built a tiny engine and attached it to his bicycle. His neighbors wanted one, and although he tried, materials could not be found and he was unable to supply the demand. He also didn&#039;t have the money to build another factory to make these &#039;motorbikes&#039;.</p>
<p>He still didn&#039;t quit. he wrote letters to 18,000 bicycles shop owners and asked them to pay him in advanced so he could build his factory to sell them his newly invented motorbikes. Unfortunately, the first models were too bulky to work well, so he continued to develop and adapt, until finally, &#039;The Super Cub&#039; became a success and took Japan by storm. With success in Japan, Honda began exporting his bicycle engines to Europe and America.</p>
<p>This was how the Honda Motor Corporation was formed. Was that the end of his problems? Nope! As he ran Honda, it went into lots of financial problems. Honda also went near to bankruptcy five times, only to be turned around just in time. Everytime he took a hit, Soichiro would just get up, learn from his mistakes and keep moving forward.</p>
<p>Today, Honda Corporation employs over 100,000 people in the USA and Japan, and is one of the world&#039;s largest automobile companies. Honda&#039;s excellent engineering and clever marketing even resulted in Honda motorcycles out-selling Triumph and Harley-Davidson in their respective home markets.</p>
<p>So, the greater the success you want in life, the bigger the hits you got to be willing to take. There is a price for everything. A Suzuki costs $30,000 and a Ferrari costs $1m (at least in Singapore).</p>
<p><b>Success too has a price. The price is massive rejection, frustration, and hardwork, People never succeed either because they thought that success comes easy or because they are not willing to pay the price!</b></p>
<p><a href="http://www.adamkhoo.net/go.php?offer=cywei99&#038;pid=8"><img alt="" src="http://www.patterns-of-excellence.com/images/group-final-small.jpg" class="alignleft" width="200" height="162" /></a>Adam Khoo is an entrepreneur, best-selling author and a self-made millionaire by the age of 26. Over the last 15 years, he has trained over 245,000 professionals, executives and business owners to tap their personal power and achieve excellence in their various fields of endeavor. Discover his supercharged success secrets and claim your FREE bonus report Ultimate Success Formula at <b><a href="http://www.adamkhoo.net/go.php?offer=cywei99&#038;pid=8">http://www.Patterns-Of-Excellence.com</a></b></p>
]]></content:encoded>
      <wfw:commentRss>http://www.mindpowerspecialreport.com/it-aint-how-hard-you-hit-its-how-hard-you-can-get-hit-and-keep-moving-forward/feed/</wfw:commentRss>
      <slash:comments>1</slash:comments>
      <enclosure url="http://podcasts.odiogo.com/get_mp3.mp3?f=/mind-powerunlock-the-subconscious-mind-power-secr/Mind_Power-Unlock_The_Subconscious_Mind_Power_Secr-It_Aint_How_Hard_You_Hit__Its_How_Hard_You_Can_Get_Hit_and_Keep_Moving_Forward.mp3" length="5560213" type="audio/mpeg" />
    </item>
    <item>
      <title>How To Mediatate</title>
      <link>http://www.mindpowerspecialreport.com/112/</link>
      <comments>http://www.mindpowerspecialreport.com/112/#comments</comments>
      <pubDate>Tue, 18 Aug 2009 16:43:18 +0000</pubDate>
      <dc:creator>admin</dc:creator>
      <category><![CDATA[Blog]]></category>
      <category><![CDATA[how to meditate]]></category>
      <guid isPermaLink="false">http://www.mindpowerspecialreport.com/?p=112</guid>
      <description>&lt;p&gt;&lt;b&gt;Step 1:&lt;/b&gt; &lt;u&gt;Make time to meditate.&lt;/u&gt; Set aside enough time in your daily routine for meditating. The effects of meditation are most noticeable when you do it regularly and consistently rather than sporadically.&lt;/p&gt;
&lt;p&gt;&lt;a href="http://www.mindpowerspecialreport.com/112/#more-112" class="more-link"&gt;More on How To Mediatate&lt;/a&gt;&lt;/p&gt;&lt;br&gt;&lt;a type="audio/mpeg" href="http://podcasts.odiogo.com/get_mp3.mp3?f=/mind-powerunlock-the-subconscious-mind-power-secr/Mind_Power-Unlock_The_Subconscious_Mind_Power_Secr-How_To_Mediatate.mp3"&gt;Click here to play&lt;/a&gt;&lt;br&gt;</description>
      <content:encoded><![CDATA[<p><b>Step 1:</b> <u>Make time to meditate.</u> Set aside enough time in your daily routine for meditating. The effects of meditation are most noticeable when you do it regularly and consistently rather than sporadically.</p>
<p>* Some people will find a five minute meditation worthwhile, for others, the benefits of longer meditation are well worth the time.</p>
<p>* You can meditate at any time of day; some people like to start their day off with meditation, others like to end the day by clearing their mind, and some prefer to find refuge in meditation in the middle of a busy day. Generally, however, the easiest time to meditate is in the morning, before the day&#039;s events tire your body out and give your mind more to think about.</p>
<p>* Don&#039;t meditate immediately following a meal, or when you are likely to be hungry. The body&#039;s digestive system can be very distracting.</p>
<p><b>Step 2: </b><u>Find or create a quiet, relaxing environment.</u> It&#039;s especially important, when you&#039;re starting out, to avoid any obstacles to attention. Turn off any TV sets, phone(s) or other noisy appliances. If you play music, make sure it&#039;s calm, repetitive and gentle, so as not to break your concentration. Meditating outside can be conducive, as long as you don&#039;t sit near a busy roadway or another source of loud noise.</p>
<p><b>Step 3:</b><u> Sit on level ground.</u> Sit on a cushion if the ground is uncomfortable. You don&#039;t have to twist your limbs into the lotus position or adopt any unusual postures. The important thing is to keep your back straight, as this will help with breathing later on.</p>
<p>* You can also meditate on a chair. Make sure your back is straight (whether you lean against the chair or sit free does not matter). Your feet should rest solidly on the ground.</p>
<p>* Any position in which you&#039;re relaxed but your back is straight is permissible, even lying down &#8211; but be careful that you&#039;re not so relaxed that you fall asleep. In warm weather, consider watching the clouds.</p>
<blockquote><p>“Dive Into A Deep, Relaxed State In 5 Minutes FLAT, Eliminate Stress, Increase Your Energy, And Wipe Out All Of Your Problems &#8211; As If They Never Existed” &#8211; <a href="http://www.deep-zen.com/index-m.html?apid=B100203">Click here to learn more about Holothink</a></p></blockquote>
<p><b>Step 4:</b> <u>Keep your eyes half-open without focusing on anything.</u> If this is too distracting or difficult, close them or find something steady to focus on such as a small candle flame.</p>
<p><b>Step 5:</b> <u>Breathe deeply and slowly from your abdomen rather than your chest.</u> You should feel your stomach rise and fall while your chest stays relatively still. Healthy, stress relieving breathing may be done by inhaling for count of 3, exhaling for count of 6, repeat over and over for 15 to 20 minutes. This expels the used air and more completely oxygenates your blood, lowering heart rate and blood pressure. Many high blood pressure patients have dropped their blood pressure as much as 50 points, allowing them to decrease or eliminate the need for medication. This breathing exercise should be done on a regular basis.</p>
<p><b>Step 6:</b> <u>Relax every muscle in your body.</u> Don&#039;t rush this, as it takes time to fully relax. Do it bit by bit, starting at your toes, and working up to your head, until the tension melts away.</p>
<p><b>Step 7:</b> <u>Focus your attention. </u>You may notice that your mind wants to wander, bouncing from thought to thought, making observations about other things. Gently bring your attention back to a single point until it rests there naturally. The goal is to allow the &#034;chattering&#034; in your mind to gradually fade away. Find an &#034;anchor&#034; to settle your mind.</p>
<p>* Let your attention rest on the flow of your breath. Listen to it, follow it, but make no judgments on it (such as &#034;It sounds a little raspy&#8230;maybe I&#039;m getting a cold?&#034;).</p>
<p>* To overcome verbal chatter, recite a mantra (repetition of a sacred word). A single word like &#034;aum&#034; uttered at a steady rhythm is best. You can recite it verbally or just with the voice in your mind. Beginners may find it easier to count their breaths. Try counting your breath from 1 to 10, then simply start again at 1.</p>
<p>* To circumvent images that keep intruding on your thoughts, visualize a place that calms you. It can be real or imaginary. Imagine you are at the top of a staircase leading to a peaceful place. Count your way down the steps until you are peaceful and relaxed.</p>
<p>* For some people, focusing attention on a point or object does exactly the opposite of what meditation is all about. It takes you back to the life of &#039;focus&#039;, &#039;concentration&#039;, &#039;strain&#039;. In this case, as an alternative to the above techniques, some meditators recommend un-focusing your attention. Instead of focusing attention on a point or an object, this type of meditation is achieved by attaining a state of zero. Take your attention above all thoughts till a point you lose all attention and all thoughts.</p>
<p><b>Step 8: </b><u>Silence your mind.</u> Once you&#039;ve trained your mind to focus on just one thing at a time, the next step is focus on nothing at all, essentially &#034;clearing&#034; your mind. This requires tremendous discipline but is the pinnacle of meditation. After focusing on a single point as described in the previous step, you can either cast it away, or observe it impartially and let it come and then go, without labeling it as &#034;good&#034; or &#034;bad&#034;. Take the same approach to any thoughts which return to your mind until silence perseveres. <img src="http://589d40bki3mw4rd73fwglfo6id.hop.clickbank.net/" alt=" "></p>
<p>Learn how you transit into a meditative state with ease and as quick as 5 minutes with Holothink. Holothink is a carefully researched program that brings listeners to deep levels of Zen meditation by tuning your brainwaves to the right frequency. <a href="http://www.deep-zen.com/index-m.html?apid=B100203">You can find more information about Holothink here.</a></p>
]]></content:encoded>
      <wfw:commentRss>http://www.mindpowerspecialreport.com/112/feed/</wfw:commentRss>
      <slash:comments>0</slash:comments>
      <enclosure url="http://podcasts.odiogo.com/get_mp3.mp3?f=/mind-powerunlock-the-subconscious-mind-power-secr/Mind_Power-Unlock_The_Subconscious_Mind_Power_Secr-How_To_Mediatate.mp3" length="2909727" type="audio/mpeg" />
    </item>
    <item>
      <title>The Secret of The Most Successful People on The Planet</title>
      <link>http://www.mindpowerspecialreport.com/the-secret-of-the-most-successful-people-on-the-planet/</link>
      <comments>http://www.mindpowerspecialreport.com/the-secret-of-the-most-successful-people-on-the-planet/#comments</comments>
      <pubDate>Fri, 14 Aug 2009 08:24:22 +0000</pubDate>
      <dc:creator>admin</dc:creator>
      <category><![CDATA[Blog]]></category>
      <category><![CDATA[mind power]]></category>
      <guid isPermaLink="false">http://www.mindpowerspecialreport.com/?p=101</guid>
      <description>&lt;p&gt;by Enoch Tan&lt;br /&gt;
Author of Bestseller &amp;#8211; &lt;a href="&lt;br /&gt;
http://53d01z5urfnuemdat9qet6ztf3.hop.clickbank.net/"&gt;Reality Creation Secrets&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;All conditions in life are created by consciousness. You manifest exactly what you perceive. If you try to express abundance towards another while seeing lack in them, you will perpetuate conditions of lack in your experience with them. In order to experience abundance, you have to perceive abundance. If your world really was abundant, then you&amp;#039;d expect that others have more than enough to give to you for what you give to them, and you&amp;#039;d receive joyfully knowing that they&amp;#039;ll keep having more themselves&amp;#8230;&lt;/p&gt;
&lt;p&gt;&lt;a href="http://www.mindpowerspecialreport.com/the-secret-of-the-most-successful-people-on-the-planet/#more-101" class="more-link"&gt;More on The Secret of The Most Successful People on The Planet&lt;/a&gt;&lt;/p&gt;&lt;br&gt;&lt;a type="audio/mpeg" href="http://podcasts.odiogo.com/get_mp3.mp3?f=/mind-powerunlock-the-subconscious-mind-power-secr/Mind_Power-Unlock_The_Subconscious_Mind_Power_Secr-The_Secret_of_The_Most_Successful_People_on_The_Planet.mp3"&gt;Click here to play&lt;/a&gt;&lt;br&gt;</description>
      <content:encoded><![CDATA[<p>by Enoch Tan<br />
Author of Bestseller &#8211; <a href="<br />
http://53d01z5urfnuemdat9qet6ztf3.hop.clickbank.net/">Reality Creation Secrets</a></p>
<p>All conditions in life are created by consciousness. You manifest exactly what you perceive. If you try to express abundance towards another while seeing lack in them, you will perpetuate conditions of lack in your experience with them. In order to experience abundance, you have to perceive abundance. If your world really was abundant, then you&#039;d expect that others have more than enough to give to you for what you give to them, and you&#039;d receive joyfully knowing that they&#039;ll keep having more themselves&#8230;</p>
<p><a href="http://53d01z5urfnuemdat9qet6ztf3.hop.clickbank.net/"><img src="http://www.mindpowerspecialreport.com/wp-content/uploads/2009/08/reality-creation-secrets.jpg" alt="reality-creation-secrets" title="reality-creation-secrets" width="250" height="340" class="alignleft size-full wp-image-102" /></a>That is why people who have wealth consciousness keep getting wealthier compared to the rest of the world. They have the freedom to charge for whatever they do according to the amount they believe it is worth, even when it is to people who try to tell them they are charging too much, or should not be charging at all. It is because wealth conscious people perceive their reality as abundant and do not allow themselves to be affected be the perceptions of those that come from a limited consciousness&#8230;</p>
<p>If everyone in these world was wealth conscious and freely gave money to others and freely received it when it is appropriate, then everyone would be as wealthy as they could be. This is because energy would flow freely and hence everyone would be able to experience what they desire without holding back from paying for it, and others would not hold back from paying them for what they contribute. The economy would be much smoother and the progress of the entire world would advance extremely fast&#8230;</p>
<p>Enoch Tan is an established Mind Power Expert and is best known for his private membership site &#8211; <a href="<br />
http://53d01z5urfnuemdat9qet6ztf3.hop.clickbank.net/">Mind Reality</a> which provides weekly cutting-edge content on secrets related to the mind, law of attraction and quantum physics. His newsletter is read by more than 40,000 subscribers and growing! <a href="<br />
http://53d01z5urfnuemdat9qet6ztf3.hop.clickbank.net/"><b>Click here to find out more about Mind Reality!</b></a></p>
]]></content:encoded>
      <wfw:commentRss>http://www.mindpowerspecialreport.com/the-secret-of-the-most-successful-people-on-the-planet/feed/</wfw:commentRss>
      <slash:comments>1</slash:comments>
      <enclosure url="http://podcasts.odiogo.com/get_mp3.mp3?f=/mind-powerunlock-the-subconscious-mind-power-secr/Mind_Power-Unlock_The_Subconscious_Mind_Power_Secr-The_Secret_of_The_Most_Successful_People_on_The_Planet.mp3" length="981481" type="audio/mpeg" />
    </item>
    <item>
      <title>Why I Won't Bring My "A" Game</title>
      <link>http://www.mindpowerspecialreport.com/why-i-wont-bring-my-a-game/</link>
      <comments>http://www.mindpowerspecialreport.com/why-i-wont-bring-my-a-game/#comments</comments>
      <pubDate>Fri, 14 Aug 2009 08:17:55 +0000</pubDate>
      <dc:creator>admin</dc:creator>
      <category><![CDATA[Blog]]></category>
      <guid isPermaLink="false">http://www.mindpowerspecialreport.com/?p=105</guid>
      <description>&lt;p&gt;&lt;a href="http://760d186lq9fxdtbyl0kcsbvv3n.hop.clickbank.net/"&gt;&lt;img src="http://www.mindpowerspecialreport.com/wp-content/uploads/2009/08/stevejonesface.jpg" alt="stevejonesface" title="stevejonesface" width="150" height="127" class="alignleft size-full wp-image-106" /&gt;&lt;/a&gt;by Steve G. Jones, M.Ed&lt;br /&gt;
Clinical Hypnotherapist&lt;br /&gt;
Author of &lt;a href="http://760d186lq9fxdtbyl0kcsbvv3n.hop.clickbank.net/"&gt;Confidence Beyond Belief&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;I refuse to &amp;#034;bring my A game.&amp;#034; When I hear someone say, &amp;#034;Bring your A game,&amp;#034; I cringe. This is an expression in the United States which is supposed to mean &amp;#034;Do your best.&amp;#034; An &amp;#034;A&amp;#034; in academics means that you have achieved the top mark, grade, or score in a subject.&lt;/p&gt;
&lt;p&gt;&lt;a href="http://www.mindpowerspecialreport.com/why-i-wont-bring-my-a-game/#more-105" class="more-link"&gt;More on Why I Won&amp;#039;t Bring My &amp;#034;A&amp;#034; Game&lt;/a&gt;&lt;/p&gt;&lt;br&gt;&lt;a type="audio/mpeg" href="http://podcasts.odiogo.com/get_mp3.mp3?f=/mind-powerunlock-the-subconscious-mind-power-secr/Mind_Power-Unlock_The_Subconscious_Mind_Power_Secr-Why_I_Wont_Bring_My_A_Game.mp3"&gt;Click here to play&lt;/a&gt;&lt;br&gt;</description>
      <content:encoded><![CDATA[<p><a href="http://760d186lq9fxdtbyl0kcsbvv3n.hop.clickbank.net/"><img src="http://www.mindpowerspecialreport.com/wp-content/uploads/2009/08/stevejonesface.jpg" alt="stevejonesface" title="stevejonesface" width="150" height="127" class="alignleft size-full wp-image-106" /></a>by Steve G. Jones, M.Ed<br />
Clinical Hypnotherapist<br />
Author of <a href="http://760d186lq9fxdtbyl0kcsbvv3n.hop.clickbank.net/">Confidence Beyond Belief</a></p>
<p>I refuse to &#034;bring my A game.&#034; When I hear someone say, &#034;Bring your A game,&#034; I cringe. This is an expression in the United States which is supposed to mean &#034;Do your best.&#034; An &#034;A&#034; in academics means that you have achieved the top mark, grade, or score in a subject.</p>
<p>The problem with the saying, however, is that it implies that there is a B game, C game, etc. You don&#039;t have an A without a B. Just like you don&#039;t have a One without a Two.</p>
<p>If there weren&#039;t other letters or numbers, you could simply say, &#034;Bring it!&#034; or &#034;Bring it on!&#034; And this is exactly what YOU should bring. It. Your best. Every time.</p>
<p>Why would anyone have different levels of achievement? Is it that in some situations they don&#039;t want to try as hard or do their best? Are there any situations in which you would want to &#034;bring your F game&#034;? Well, there must be if you have an &#034;A game.&#034;</p>
<p>Why would that be the case? Why would anyone be involved in anything in which they used less than their total capability? The way I see it, you either do your best or you don&#039;t do anything. You either go all the way, or you go home. You either shoot for the stars, or you don&#039;t shoot at all.</p>
<p>Sure, there will be times when sickness, weather conditions, other people, etc. cause your best in that moment to be less than your best in another moment. This does not in any way excuse you from doing things to the best of your capability in that moment.</p>
<p>Additionally, this is not a contest against others. The only contestant is YOU. Your best time running a marathon may be a lot slower than that of an Olympic athlete. That&#039;s fine. Your best singing voice may not be as pleasing to as many people as that of a professional singer. That&#039;s fine. The point is that you are doing YOUR personal best.</p>
<p>What often happens, and this is a true crime, is that we tend to do as well as the worst examples around us. We do this so that we won&#039;t &#034;stand out&#034; or &#034;rock the boat&#034; or disturb &#034;the way things are done around here.&#034;</p>
<p>This is all nonsense. These are feeble fear-based excuses for settling for less than what we really are.</p>
<p>Worse than this, maybe you are the best in your class or field of expertise or office. Maybe you out-sell, out-shine, and out-perform everyone around you. Yet, you know in your heart that you are capable of so much more. You are operating at half-speed while the rest are at their top speed. What a crime! All that wasted, unused potential! Why aren&#039;t you doing YOUR best? So what if it puts you way out in front. Guess what &#8211; there are more people up ahead in the distance who you don&#039;t even know about because you are simply trying to keep ahead of your group.</p>
<p><a href="http://760d186lq9fxdtbyl0kcsbvv3n.hop.clickbank.net/"><img src="http://www.mindpowerspecialreport.com/wp-content/uploads/2009/08/ConfidenceBeyondBeliefcom_clip_image002.jpg" alt="ConfidenceBeyondBeliefcom_clip_image002" title="ConfidenceBeyondBeliefcom_clip_image002" width="222" height="222" class="alignleft size-full wp-image-107" /></a>Get moving! Run at YOUR top speed! Be YOUR best! Reach YOUR potential! We don&#039;t want to see what you can do &#034;without even studying&#034; or what you &#034;could do with one hand tied behind your back.&#034;</p>
<p>We want to see what you can do when you shine like the Sun, run like the wind, and fight like your life depended on it!</p>
<p>Think about it. Do you really want to reach the end of your life and say, &#034;Wow, I could have been and done so much more.&#034;? NO! Nobody wants that.</p>
<p>So put down the alcohol, cigarettes, worthless friends, or whatever it is that you have added to your life to slow you down. Start believing in yourself! Get up! Stand up tall! Get moving! And keep moving! Bring it all, bring it on! Every time!</p>
<p>Steve G. Jones, M.Ed is a certified clinical hypnotherapist, has devoted his life to making sure you achieve this goal easily. He has focused his genius on developing a powerful line of hypnosis products to launch you powerfully in the direction of ultimate success. New opportunities await you, so start your journey NOW. <a href="http://760d186lq9fxdtbyl0kcsbvv3n.hop.clickbank.net/">Learn more&#8230; </a></p>
]]></content:encoded>
      <wfw:commentRss>http://www.mindpowerspecialreport.com/why-i-wont-bring-my-a-game/feed/</wfw:commentRss>
      <slash:comments>0</slash:comments>
      <enclosure url="http://podcasts.odiogo.com/get_mp3.mp3?f=/mind-powerunlock-the-subconscious-mind-power-secr/Mind_Power-Unlock_The_Subconscious_Mind_Power_Secr-Why_I_Wont_Bring_My_A_Game.mp3" length="2085631" type="audio/mpeg" />
    </item>
    <item>
      <title>PANIC: 3 Ways You Can Turn Panic Into Happiness</title>
      <link>http://www.mindpowerspecialreport.com/panic-3-ways-you-can-turn-panic-into-happiness/</link>
      <comments>http://www.mindpowerspecialreport.com/panic-3-ways-you-can-turn-panic-into-happiness/#comments</comments>
      <pubDate>Fri, 14 Aug 2009 07:58:44 +0000</pubDate>
      <dc:creator>admin</dc:creator>
      <category><![CDATA[Blog]]></category>
      <category><![CDATA[Panic Into Happiness]]></category>
      <guid isPermaLink="false">http://www.mindpowerspecialreport.com/?p=89</guid>
      <description>&lt;p&gt;&lt;img src="http://www.mindpowerspecialreport.com/wp-content/uploads/2009/08/edanddebheadshot.jpg" alt="edanddebheadshot" title="edanddebheadshot" width="45" height="90" class="alignleft size-full wp-image-90" /&gt;by &lt;b&gt;Ed and Deb Shapiro&lt;/b&gt;&lt;br /&gt;
Authors:BE THE CHANGE- How Meditation Can Transform You and the World. EdandDebShapiro.com&lt;br /&gt;
Posted: August 13, 2009&lt;/p&gt;
&lt;p&gt;We are witnessing an outbreak of panic and fear as people in the US respond with misunderstanding and ignorance to falsely perceived threats to their welfare. There is a tremendous fear of and resistance to change, which cause further suffering.&lt;/p&gt;
&lt;p&gt;&lt;a href="http://www.mindpowerspecialreport.com/panic-3-ways-you-can-turn-panic-into-happiness/#more-89" class="more-link"&gt;More on PANIC: 3 Ways You Can Turn Panic Into Happiness&lt;/a&gt;&lt;/p&gt;&lt;br&gt;&lt;a type="audio/mpeg" href="http://podcasts.odiogo.com/get_mp3.mp3?f=/mind-powerunlock-the-subconscious-mind-power-secr/Mind_Power-Unlock_The_Subconscious_Mind_Power_Secr-PANIC-_3_Ways_You_Can_Turn_Panic_Into_Happiness.mp3"&gt;Click here to play&lt;/a&gt;&lt;br&gt;</description>
      <content:encoded><![CDATA[<p><img src="http://www.mindpowerspecialreport.com/wp-content/uploads/2009/08/edanddebheadshot.jpg" alt="edanddebheadshot" title="edanddebheadshot" width="45" height="90" class="alignleft size-full wp-image-90" />by <b>Ed and Deb Shapiro</b><br />
Authors:BE THE CHANGE- How Meditation Can Transform You and the World. EdandDebShapiro.com<br />
Posted: August 13, 2009</p>
<p>We are witnessing an outbreak of panic and fear as people in the US respond with misunderstanding and ignorance to falsely perceived threats to their welfare. There is a tremendous fear of and resistance to change, which cause further suffering.</p>
<p>Panic affects us all at different times, but for some it dominates their day-to-day life. &#034;I had panic all through my childhood until I was 13. I grew up at the base of the Himalaya Mountains and I was afraid of snowstorms, earthquakes, fire, and sometimes for no reason &#8211; I was just fearful, I did not sleep well, I panicked very easily.&#034;</p>
<p>We were talking with Mingyur Rinpoche, a Tibetan Buddhist teacher, about his new book, Joyful Wisdom. He is openly honest about what he has been through. However, Mingyur did something with his panic that few of us are able to: where most of us feel overcome by panic or try to suppress it, he made friends with it &#8212; he turned his enemy into his ally.</p>
<p>&#034;There are two ways we actually make panic worse: we say Yes Sir to it, or Get Out. If we say Yes Sir then we do anything that the panic wants us to do, we let it rule us. But if we fear panic or try to get rid of it, and we say Get Out, then this just makes panic into the enemy. Either way, panic gets bigger and we become less able to cope.&#034;</p>
<p>So how can you turn panic into your friend? The answer is surprisingly simple: by becoming aware of it. &#034;Awareness means seeing it, feeling it, and then panic becomes many different pieces: physical sensations, emotions, frightened images, words, thoughts. So awareness is of all the pieces. If you are not aware of the panic then you are a victim of it; awareness is saying hello and inviting it in.&#034;</p>
<p><b>Turning your panic into happiness:</b></p>
<p><b>1. Become aware of the panic.</b> Seeing it for what it is without judgment, that it is neither good or bad.</p>
<p><b>2. Shift your focus away from Yes Sir or Get Out.</b> Normally, when we are panicked, our breathing is shallow and rapid. To help you shift the focus you can bring your<br />
breathing down to the belly, away from the panic. Soft belly breathing: breathing deeply all the way in and out, then relaxing and breathing in again slowly, with a soft and relaxed belly.</p>
<p><b>3. Develop love and compassion by becoming a friend to yourself.</b> Then you can understand that others panic, that every person in every moment, every breath, every thought, every movement, is looking for happiness &#8211; we are no different, we all want the same, we are all part of the big family.</p>
<p>Amazingly, Mingyur was just 13 years old when he discovered the transformative power of meditation. The more he practiced, the more he was able to be with the panic and not let it run his life. &#034;Meditation enabled me to witness my panic. Normally my busy monkey mind ran the show by telling me to be panicked or to hide. Meditation gave me greater freedom of the mind as it gave a job to the monkey mind and I become the boss.&#034;</p>
<p>&#034;Who makes problems? We humans. And who is the controller of the human? The mind. And how to control the human mind? Through meditation. If you can control the pilot, then the pilot can control the plane,&#034; says Mingyur in our new book, <a href="http://www.amazon.com/gp/product/1402760019?ie=UTF8&#038;tag=hdrera-20&#038;linkCode=as2&#038;camp=1789&#038;creative=390957&#038;creativeASIN=1402760019">Be the Change: How Meditation Can Transform You and the World</a><img src="http://www.assoc-amazon.com/e/ir?t=hdrera-20&#038;l=as2&#038;o=1&#038;a=1402760019" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" /></p>
<p>In this way, panic can become our friend and teacher, something we can learn so much from about ourselves. &#034;Panic pushed me into understanding myself more deeply, it opened my heart so that I have greater understanding that others are suffering too.&#034;</p>
<p>Sitting quietly in meditation, can silently repeat: May I have happiness and causes of happiness. May I be well, may I be peaceful, may others be well, may others be peaceful.</p>
<p>Do you have stories of when you were able to transform panic? Do comment below. You can receive notice of our blogs every Thursday by checking Become a Fan at the top.<br />
<img src="http://www.mindpowerspecialreport.com/wp-content/uploads/2009/08/bethechange.jpg" alt="bethechange" title="bethechange" width="200" height="295" class="alignleft size-full wp-image-98" /></p>
<p>You can pre-order a copy of our book at: <a href="http://www.amazon.com/gp/product/1402760019?ie=UTF8&#038;tag=hdrera-20&#038;linkCode=as2&#038;camp=1789&#038;creative=390957&#038;creativeASIN=1402760019">Be the Change: How Meditation Can Transform You and the World</a><img src="http://www.assoc-amazon.com/e/ir?t=hdrera-20&#038;l=as2&#038;o=1&#038;a=1402760019" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" /> It will be published Nov 3. </p>
<p>Ed and Deb Shapiro&#039;s new book, BE THE CHANGE, How Meditation Can Transform You And The World, forewords by the Dalai Lama and Robert Thurman, with contributors such as Marianne Williamson, astronaut Edgar Mitchell, Ellen Burstyn, Michael Beckwith, Jon Kabat-Zinn, Jane Fonda, Jack Kornfield, Byron Katie, Dean Ornish, Ed Begley, Gangaji, Dan Millman, Russell Bishop, and others, will be published Nov 3 2009 by Sterling Ethos.</p>
<p>Deb is the author of the award-winning book YOUR BODY SPEAKS YOUR MIND. Ed and Deb are the authors of over 15 books, and lead meditation retreats and workshops. They are corporate consultants, and the creators of Chillout daily inspirational text messages on Sprint cell phones. See: www.EdandDebShapiro.com</p>
]]></content:encoded>
      <wfw:commentRss>http://www.mindpowerspecialreport.com/panic-3-ways-you-can-turn-panic-into-happiness/feed/</wfw:commentRss>
      <slash:comments>2</slash:comments>
      <enclosure url="http://podcasts.odiogo.com/get_mp3.mp3?f=/mind-powerunlock-the-subconscious-mind-power-secr/Mind_Power-Unlock_The_Subconscious_Mind_Power_Secr-PANIC-_3_Ways_You_Can_Turn_Panic_Into_Happiness.mp3" length="2666627" type="audio/mpeg" />
    </item>
    <item>
      <title>Have An Ever Increasing Mindset for Prosperity!</title>
      <link>http://www.mindpowerspecialreport.com/have-an-ever-increasing-mindset-for-prosperity/</link>
      <comments>http://www.mindpowerspecialreport.com/have-an-ever-increasing-mindset-for-prosperity/#comments</comments>
      <pubDate>Mon, 10 Aug 2009 12:52:28 +0000</pubDate>
      <dc:creator>admin</dc:creator>
      <category><![CDATA[Blog]]></category>
      <category><![CDATA[mind power]]></category>
      <guid isPermaLink="false">http://www.mindpowerspecialreport.com/?p=71</guid>
      <description>&lt;p&gt;by Enoch Tan&lt;br /&gt;
Author of bestselling, &lt;a href="http://mindreality.com/cb/?a=2ILtTww&amp;#038;p=3"&gt;Mind Power Secrets Package&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;&lt;b&gt;The principle to increase in prosperity is to always be gathering.&lt;/b&gt; There is no reason why a person should ever stop. This does not mean that we should be miserly, trying to accumulate more and more to hold, but that our thought should so enlarge that it can not help gathering more and more, even though with the other hand, we are ever distributing that which we gather. Indeed, the only reason for having is that we may give out of that which we have. We’re here to be a conduit of abundance in expression.&lt;/p&gt;
&lt;p&gt;&lt;a href="http://www.mindpowerspecialreport.com/have-an-ever-increasing-mindset-for-prosperity/#more-71" class="more-link"&gt;More on Have An Ever Increasing Mindset for Prosperity!&lt;/a&gt;&lt;/p&gt;&lt;br&gt;&lt;a type="audio/mpeg" href="http://podcasts.odiogo.com/get_mp3.mp3?f=/mind-powerunlock-the-subconscious-mind-power-secr/Mind_Power-Unlock_The_Subconscious_Mind_Power_Secr-Have_An_Ever_Increasing_Mindset_for_Prosperity.mp3"&gt;Click here to play&lt;/a&gt;&lt;br&gt;</description>
      <content:encoded><![CDATA[<p>by Enoch Tan<br />
Author of bestselling, <a href="http://mindreality.com/cb/?a=2ILtTww&#038;p=3">Mind Power Secrets Package</a></p>
<p><b>The principle to increase in prosperity is to always be gathering.</b> There is no reason why a person should ever stop. This does not mean that we should be miserly, trying to accumulate more and more to hold, but that our thought should so enlarge that it can not help gathering more and more, even though with the other hand, we are ever distributing that which we gather. Indeed, the only reason for having is that we may give out of that which we have. We’re here to be a conduit of abundance in expression.</p>
<p>No matter what big thing happens to us we should still be expecting more and more. Even when we think that we have at last arrived, right here let it be but a beginning for still greater things. No matter how large the picture that you hold in mind, make it larger. The reason why so many people come to the point where they stop is that they come to a point where they stop growing in their own minds. They come to a point where they can see no more, thinking that because they have done enough to continue.</p>
<p><u>We must watch our thought for signs of inactivity.</u> Nothing in the universe ever stops. Everything is built on a boundless basis, drawn from a limitless source, come forth from an Infinite sea of unmanifest life. We speak forth into this life and draw back from it all that we first think into it. Life is always limitless, and the only thing that limits us is our inability to conceive mentally, and we should draw more and more from that limitless source. Keep on creating and progressing. Life is always in constant action.</p>
<p><b><u>The key to meaningful life is in enlarging our thought.</b></u> We can never stand still in our thought. Either we will be growing or else we will be going back. As we can attract to ourselves only what we first have a mental likeness of, it follows that if we wish to attract larger things we must provide larger thoughts. This enlarging of consciousness is so necessary that too much cannot be said about it. Expansion or enlarging of consciousness is for the purpose of becoming and of course having and experiencing more.</p>
<p>Most people get only a short way and then stop: they cannot seem to get beyond a certain point; they can do so much and no more. Why is it that a person in business does just about so much each year? We see people in all walks of life, getting so far, never going beyond a certain point. There must be a reason for everything; nothing happens, if all is governed by law, and we can come to no other conclusion. Knowing the reason why people stop increasing, is the secret by which we can have no limits.</p>
<p>When we look into the mental reason for things we find out why things happen. The man who gets so far and never seems to go beyond that point is still governed by law; when he allows his thoughts to take him out into larger fields of action, his conditions come up to his thought; when he stops enlarging his thought he stops growing. If he would still keep on in thought, realizing more and still more, he would find that in the outer form of things he would be doing greater things. Think bigger to achieve greater.</p>
<p>There are many reasons why a man stops thinking larger things. One of them is a lack of imagination. He cannot conceive of anything more to follow than that which has already happened. Another thought works like this: &#034;This is as far as any one can go in my business.&#034; Right here he signs his own death warrant. Often a person will say, &#034;I am too old to do bigger things.&#034; There he stops. Some one else will say, &#034;Competition is too great&#034;; and here is where he stops. You go no further than your thought will.</p>
<p><i><b>All this is unnecessary when we realize that life is first of all Consciousness, and then conditions follow.</i></b> We see no reason why a man should not go on and on and never stop growing. No matter what age or what circumstance, if life is thought, we can keep on thinking bigger things. There is no reason why a man who is already doing well should not be able mentally to conceive of a still better condition. There is always a greater activity possible. We must keep on with seeing beyond what has come before.</p>
<p>If we always practice this, we will find that every year we shall be growing, every month we shall be advancing; and as time goes on we shall become really great. As there is no limit in that power which is Infinite, so should we keep on trying to see more and greater possibilities in life. We should definitely work every day for the expansion of thought. If we have ten customers a day we should intend to believe that we have fifteen, when fifteen see thirty. This should never stop; there’s no stopping place in mind.</p>
<p><img src="http://www.mindpowerspecialreport.com/wp-content/uploads/2009/08/goldpower.jpg" alt="goldpower" title="goldpower" width="200" height="229" class="alignleft size-full wp-image-78" />Let go of everything else, drop everything else from your thought, and mentally see more coming to you than has ever come before; believe that Mind is establishing this unto you, and then go about your business in the regular way. Never see the limitation; never dwell upon it, and above all things else never talk limitation to any one; this is the only way, and there is no other way to grow a larger thought. The man with the big thought is always the man who does big things in life. Prove that life is with no limit.</p>
<p><b>Enjoy what you have, but that doesn’t mean you’ve got to stick with it because you said you liked it. You like it, and love it, but there’s other stuff to do. You’re here in this reality, this reality of yours, to experience as much as you can.</b> That’s why you’re here, because every experience is an opportunity. What kind of an opportunity? It is an opportunity for growth. Those who express their true divine nature are ever increasing in their lives. Prosperity is the path of becoming and having more than you did before.</p>
<p>Enoch Tan is the author of Mind Power Secrets Package. You can find more information about Enoch&#039;s bestseller, Mind Power Secrets Package at <a href="http://mindreality.com/cb/?a=2ILtTww&#038;p=3">Mind Reality</a></p>
]]></content:encoded>
      <wfw:commentRss>http://www.mindpowerspecialreport.com/have-an-ever-increasing-mindset-for-prosperity/feed/</wfw:commentRss>
      <slash:comments>1</slash:comments>
      <enclosure url="http://podcasts.odiogo.com/get_mp3.mp3?f=/mind-powerunlock-the-subconscious-mind-power-secr/Mind_Power-Unlock_The_Subconscious_Mind_Power_Secr-Have_An_Ever_Increasing_Mindset_for_Prosperity.mp3" length="3058934" type="audio/mpeg" />
    </item>
    <item>
      <title>Your MIND POWER Controls Everything In Reality</title>
      <link>http://www.mindpowerspecialreport.com/your-mind-power-controls-everything-in-reality/</link>
      <comments>http://www.mindpowerspecialreport.com/your-mind-power-controls-everything-in-reality/#comments</comments>
      <pubDate>Mon, 10 Aug 2009 12:49:14 +0000</pubDate>
      <dc:creator>admin</dc:creator>
      <category><![CDATA[Blog]]></category>
      <category><![CDATA[mind power]]></category>
      <guid isPermaLink="false">http://www.mindpowerspecialreport.com/?p=68</guid>
      <description>&lt;p&gt;Lack of control is an illusion. If you are the creator, all things are under your control. Some people say that control is an illusion but the opposite is the real truth. How can you not be in control when all things are under your control? Realize the aspect of yourself that is divine, your Godhood. God is in control of all things, and God is the Self of all, which is your Higher Self. You are the Higher Self. You create all of your reality. There is no aspect of your reality which you do not create. Therefore you control all.&lt;/p&gt;
&lt;p&gt;&lt;a href="http://www.mindpowerspecialreport.com/your-mind-power-controls-everything-in-reality/#more-68" class="more-link"&gt;More on Your MIND POWER Controls Everything In Reality&lt;/a&gt;&lt;/p&gt;&lt;br&gt;&lt;a type="audio/mpeg" href="http://podcasts.odiogo.com/get_mp3.mp3?f=/mind-powerunlock-the-subconscious-mind-power-secr/Mind_Power-Unlock_The_Subconscious_Mind_Power_Secr-Your_MIND_POWER_Controls_Everything_In_Reality.mp3"&gt;Click here to play&lt;/a&gt;&lt;br&gt;</description>
      <content:encoded><![CDATA[<p>Lack of control is an illusion. If you are the creator, all things are under your control. Some people say that control is an illusion but the opposite is the real truth. How can you not be in control when all things are under your control? Realize the aspect of yourself that is divine, your Godhood. God is in control of all things, and God is the Self of all, which is your Higher Self. You are the Higher Self. You create all of your reality. There is no aspect of your reality which you do not create. Therefore you control all.</p>
<p>You are not a victim. All power is within and is absolutely under your control. To say that things happen through another cause other than yourself is to say that you are a victim. Nothing happens outside of you. Everything is happening within you. You are Consciousness, and Consciousness encompasses All That Is. Whenever you feel not being in control, you are experiencing an illusion. You created the illusion of not being in control, of not being God. You are the director of the script and can control at will.</p>
<p>Intention controls results. Everything is created by your intention. Even when what you desire comes at a time or in a way that seems beyond your control, it is still your intent that brought it into manifesting. That is no God outside of you that makes things happen. Everything is within you and within God. Nothing happens to you outside of you. When you realize this truth, you know that you are the creator of everything that happens in your life. The idea that something else makes things happen is not truth.</p>
<p>When undesirable things happen, you are simply being moved mentally or physically towards somewhere else that is closer to what you want. It is you moving yourself. Those undesirable things are not created by something external of you to affect you. They are part of your intent. Your intent arranges and rearranges the universe to move you to closer to where you wan to be. The rearrangement of the universe may seem to be something that is happening on its own but it is you who control it with intention.</p>
<p>Mind Power creates and controls reality. Think of Desire-Force as the warm, ardent, fiery, forceful energy, underlying the manifestations of Mind-Power; and of the Will-Power as the cold, keen, strong, directing, controlling projector of the energy. By fixing these mental images in your mind, you will be better able to manifest the two phases as occasion arises. To create a thing you must want it with a burning desire that allows no denial, backed up by a will that knows no such word as &#034;can&#039;t&#034; or &#034;no.&#034;</p>
<p>Besides its role as the director of the energy, the will serves a very important office as the restrainer of Desire-Force. When under the control of the &#034;I&#034; of the person, and taking the suggestion of reason and judgment, it is able to prevent one from expressing undesirable or hurtful desires.  It refuses to project the Desire-Force, or to allow the desire to take effect in action. It also turns back the desire upon itself, and refuses to allow it to manifest. The will prevents negative manifestation upon the plane of action.</p>
<p>And the will has still another important function. It acts as a protector. The will repels the influence or vibrations of another mind, and renders its possessor immune to undesirable thought-waves. It creates a protective aura around the individual, which will turn aside the thought-waves or vibrations which may reach him, whether such be sent directly to him or whether they are the vibrations emanating from minds of others and unconsciously sent forth. A strong soul retains strong individuality and thinking.</p>
<p>Feeling is living thought. Everything that is worthwhile was produced by this feeling thought. Feeling—Desire— Emotion—Passion—Wanting— Willing—Demanding—these are the things that have creative power. So do not deceive yourself with this &#034;holding the thought,&#034; or any such nonsense of which you have heard so much until you get sick at the mention of the words. It is not simply &#034;holding the thought,&#034; it is &#034;holding the desire,&#034; and backing it up with the will that does the work. Desire-Will is intent.</p>
<p>Each one of these centers of energy seems to have two poles of activity, one of which acts in the direction of impelling, driving, pushing, forcing, urging, directing, etc., the action being always &#034;outward&#034;; and the other acting in the direction of drawing, pulling, attracting, coaxing, alluring, charming, leading, etc., the action always being &#034;inward.&#034; One seems to be a masculine force, the other a feminine force. One seems to act as Will-Power; the other as Desire-Force. The Desire aligns, and the will acts.</p>
<p>These two poles of Mind-Power possessed by each center are called the motive pole, and the emotive pole, respectively. As in all other things, a combination of the masculine and feminine qualities and characteristics produces the best results. Each has its strong and weak points, but together they are irresistible along all lines of work, physical, mental and spiritual. Desire is emotive force which is internal action. Will is motive force which is external action. Desire translated into Will is Magic work.</p>
<p>To live as a powerful creator, you have to banish the illusion once and for all that you are not in control. Because you will always arrive back at the core truth that you are the creator of your reality and that you create all of it. Not being in control makes you feel like a victim. When you focus on what you can do to create what you want, you take back the power. Your intent brings you the knowledge, the awareness and the energy to create what you want. Everything that happens can be traced back to intent.</p>
<p>Enoch Tan – Creator of Mind Reality and Administrator of the Mind Power Secrets Package: http://www.MindPowerSecretsPackage.com</p>
]]></content:encoded>
      <wfw:commentRss>http://www.mindpowerspecialreport.com/your-mind-power-controls-everything-in-reality/feed/</wfw:commentRss>
      <slash:comments>1</slash:comments>
      <enclosure url="http://podcasts.odiogo.com/get_mp3.mp3?f=/mind-powerunlock-the-subconscious-mind-power-secr/Mind_Power-Unlock_The_Subconscious_Mind_Power_Secr-Your_MIND_POWER_Controls_Everything_In_Reality.mp3" length="3081213" type="audio/mpeg" />
    </item>
  </channel>
</rss>
<!-- 54651 -->
<!-- Generated by Odiogobot V5.309 / http://www.odiogo.com -->
