<?xml version="1.0" encoding="utf-8" ?><rss xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>Daily Bible Radio</title><description>A short, daily verse-by-verse Bible study</description><link>http://www.dailybibleradio.com/AmenMe/Education/BibleStudy.aspx</link><language>en-us</language><copyright>&#xA9; 2011 Troy Taft</copyright><lastBuildDate>Wed, 6 Jun 2012 23:00:00 GMT</lastBuildDate><pubDate>Wed, 6 Jun 2012 23:00:00 GMT</pubDate><docs>http://www.dailybibleradio.com/AmenMe/Education/BibleStudy.aspx</docs><webMaster>biblestudy@valleyhighlands.com (Troy Taft)</webMaster><itunes:author>Troy Taft</itunes:author><itunes:subtitle></itunes:subtitle><itunes:summary>A short, daily verse-by-verse Bible study</itunes:summary><itunes:owner>  <itunes:name>Troy Taft</itunes:name>  <itunes:email>biblestudy@valleyhighlands.com</itunes:email></itunes:owner><itunes:explicit>No</itunes:explicit><itunes:image href="http://www.dailybibleradio.com/AmenMe/images/books/podcastimg.jpg"/><itunes:category text="Religion &amp; Spirituality">  <itunes:category text="Christianity"/></itunes:category><atom:link href="http://www.dailybibleradio.com/AmenMe/Education/BibleStudyRadio.aspx" rel="self" type="application/rss+xml" /><item><title>God Isn't the Problem</title><link>http://www.dailybibleradio.com/AmenMe/Education/BibleStudy.aspx</link><guid>http://www.dailybibleradio.com/AmenMe/Education/Lessons/Luke/audio/168.mp3</guid><description>
    When it comes to prayer, it isn't God who doesn't follow through.
  </description><enclosure url="http://www.dailybibleradio.com/AmenMe/Education/Lessons/Luke/audio/168.mp3" length="2020170" type="audio/mpeg"/><category>Bible Study</category><pubDate>Wed, 6 Jun 2012 23:00:00 GMT</pubDate><itunes:author>Troy Taft</itunes:author><itunes:explicit>No</itunes:explicit><itunes:subtitle>Luke 18:6-8</itunes:subtitle><itunes:summary>
    When it comes to prayer, it isn't God who doesn't follow through.
  </itunes:summary><itunes:duration>4:05</itunes:duration><itunes:keywords>Bible Study,Bible,Christianity,truth</itunes:keywords></item><item><title>How Persistence Works</title><link>http://www.dailybibleradio.com/AmenMe/Education/BibleStudy.aspx</link><guid>http://www.dailybibleradio.com/AmenMe/Education/Lessons/Luke/audio/167.mp3</guid><description>
    The question that I have, then, is why would God make us have to persist?
  </description><enclosure url="http://www.dailybibleradio.com/AmenMe/Education/Lessons/Luke/audio/167.mp3" length="3494682" type="audio/mpeg"/><category>Bible Study</category><pubDate>Tue, 5 Jun 2012 23:00:00 GMT</pubDate><itunes:author>Troy Taft</itunes:author><itunes:explicit>No</itunes:explicit><itunes:subtitle>Luke 18:1-5</itunes:subtitle><itunes:summary>
    The question that I have, then, is why would God make us have to persist?
  </itunes:summary><itunes:duration>7:09</itunes:duration><itunes:keywords>Bible Study,Bible,Christianity,truth</itunes:keywords></item><item><title>Where the Vultures Gather</title><link>http://www.dailybibleradio.com/AmenMe/Education/BibleStudy.aspx</link><guid>http://www.dailybibleradio.com/AmenMe/Education/Lessons/Luke/audio/166.mp3</guid><description>
    Jesus warns his Jewish listeners here that when the time finally comes for Jesus to rule the earth, it will be a terrible thing.
  </description><enclosure url="http://www.dailybibleradio.com/AmenMe/Education/Lessons/Luke/audio/166.mp3" length="2483178" type="audio/mpeg"/><category>Bible Study</category><pubDate>Mon, 4 Jun 2012 23:00:00 GMT</pubDate><itunes:author>Troy Taft</itunes:author><itunes:explicit>No</itunes:explicit><itunes:subtitle>Luke 17:31-37</itunes:subtitle><itunes:summary>
    Jesus warns his Jewish listeners here that when the time finally comes for Jesus to rule the earth, it will be a terrible thing.
  </itunes:summary><itunes:duration>5:03</itunes:duration><itunes:keywords>Bible Study,Bible,Christianity,truth</itunes:keywords></item><item><title>No One is Going to See This Coming</title><link>http://www.dailybibleradio.com/AmenMe/Education/BibleStudy.aspx</link><guid>http://www.dailybibleradio.com/AmenMe/Education/Lessons/Luke/audio/165.mp3</guid><description>
    It's not that people aren't adequately warned about bad things before they happen.
  </description><enclosure url="http://www.dailybibleradio.com/AmenMe/Education/Lessons/Luke/audio/165.mp3" length="2327178" type="audio/mpeg"/><category>Bible Study</category><pubDate>Sun, 3 Jun 2012 23:00:00 GMT</pubDate><itunes:author>Troy Taft</itunes:author><itunes:explicit>No</itunes:explicit><itunes:subtitle>Luke 17:26-30</itunes:subtitle><itunes:summary>
    It's not that people aren't adequately warned about bad things before they happen.
  </itunes:summary><itunes:duration>4:43</itunes:duration><itunes:keywords>Bible Study,Bible,Christianity,truth</itunes:keywords></item><item><title>How Does the "Day of the Lord" Come?</title><link>http://www.dailybibleradio.com/AmenMe/Education/BibleStudy.aspx</link><guid>http://www.dailybibleradio.com/AmenMe/Education/Lessons/Luke/audio/164.mp3</guid><description>
    It is very important that everyone understand that when the true Messiah comes, it will be very obvious.
  </description><enclosure url="http://www.dailybibleradio.com/AmenMe/Education/Lessons/Luke/audio/164.mp3" length="2250634" type="audio/mpeg"/><category>Bible Study</category><pubDate>Sat, 2 Jun 2012 23:00:00 GMT</pubDate><itunes:author>Troy Taft</itunes:author><itunes:explicit>No</itunes:explicit><itunes:subtitle>Luke 17:20-21</itunes:subtitle><itunes:summary>
    It is very important that everyone understand that when the true Messiah comes, it will be very obvious.
  </itunes:summary><itunes:duration>4:34</itunes:duration><itunes:keywords>Bible Study,Bible,Christianity,truth</itunes:keywords></item></channel></rss>