<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:wfw="http://wellformedweb.org/CommentAPI/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:sy="http://purl.org/rss/1.0/modules/syndication/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/">
  <channel>
    <title>GO Zone Investments Investing Mississippi Louisiana - Podcasts powered by Odiogo</title>
    <atom:link href="http://www.gozonegateway.com/feed/" rel="self" type="application/rss+xml" />
    <link>http://www.gozonegateway.com</link>
    <description>Your gateway to investing in the GO Zone</description>
    <lastBuildDate>Mon, 19 Jul 2010 19:38:27 +0000</lastBuildDate>
    <generator>http://wordpress.org/?v=2.9.2</generator>
    <language>en</language>
    <sy:updatePeriod>hourly</sy:updatePeriod>
    <sy:updateFrequency>1</sy:updateFrequency>
    <item>
      <title>Damage and destruction to houses in Biloxi, Mississippi. Hurricane Katrina caused extensive damage all along the Mississippi gulf</title>
      <link>http://www.gozonegateway.com/featured/damage-and-destruction-to-houses-in-biloxi-mississippi-hurricane-katrina-caused-extensive-damage-all-along-the-mississippi-gulf/</link>
      <comments>http://www.gozonegateway.com/featured/damage-and-destruction-to-houses-in-biloxi-mississippi-hurricane-katrina-caused-extensive-damage-all-along-the-mississippi-gulf/#comments</comments>
      <pubDate>Thu, 06 May 2010 07:40:34 +0000</pubDate>
      <dc:creator>admin</dc:creator>
      <category><![CDATA[Featured]]></category>
      <guid isPermaLink="false">http://www.gozonegateway.com/?p=242</guid>
      <description>Biloxi, Miss., September 3, 2005 &amp;#8212; Damage and  destruction to houses in Biloxi, Mississippi.  Hurricane Katrina caused  extensive damage all along the Mississippi gulf coast.  FEMA/Mark Wolfe&lt;br&gt;&lt;a type="audio/mpeg" href="http://podcasts.odiogo.com/get_mp3.mp3?f=/go-zone-gateway/GO_Zone_Gateway-Damage_and_destruction_to_houses_in_Biloxi_Mississippi_Hurricane_Katrina_caused_extensive_damage_all.mp3"&gt;Click here to play&lt;/a&gt;&lt;br&gt;</description>
      <content:encoded><![CDATA[<p><a href="http://www.gozonegateway.com/wp-content/uploads/2010/05/wreckhouse.jpg"><img class="alignleft size-full wp-image-243" style="border: 0pt none; margin: 10px;" title="wreckhouse" src="http://www.gozonegateway.com/wp-content/uploads/2010/05/wreckhouse.jpg" alt="" width="640" height="425" /></a></p>
<p>Biloxi, Miss., September 3, 2005 &#8212; Damage and  destruction to houses in Biloxi, Mississippi.  Hurricane Katrina caused  extensive damage all along the Mississippi gulf coast.  FEMA/Mark Wolfe</p>
]]></content:encoded>
      <wfw:commentRss>http://www.gozonegateway.com/featured/damage-and-destruction-to-houses-in-biloxi-mississippi-hurricane-katrina-caused-extensive-damage-all-along-the-mississippi-gulf/feed/</wfw:commentRss>
      <slash:comments>0</slash:comments>
      <enclosure url="http://podcasts.odiogo.com/get_mp3.mp3?f=/go-zone-gateway/GO_Zone_Gateway-Damage_and_destruction_to_houses_in_Biloxi_Mississippi_Hurricane_Katrina_caused_extensive_damage_all.mp3" length="255053" type="audio/mpeg" />
    </item>
    <item>
      <title>The heavily damaged Treasure Bay casino in Gulfport, Mississippi lay lifeless after Hurricane Katrina smashed her.</title>
      <link>http://www.gozonegateway.com/featured/the-heavily-damaged-treasure-bay-casino-in-gulfport-mississippi-lay-lifeless-after-hurricane-katrina-smashed-her/</link>
      <comments>http://www.gozonegateway.com/featured/the-heavily-damaged-treasure-bay-casino-in-gulfport-mississippi-lay-lifeless-after-hurricane-katrina-smashed-her/#comments</comments>
      <pubDate>Thu, 06 May 2010 07:22:44 +0000</pubDate>
      <dc:creator>admin</dc:creator>
      <category><![CDATA[Featured]]></category>
      <guid isPermaLink="false">http://www.gozonegateway.com/?p=232</guid>
      <description>Gulfport, Mississippi, September 6, 2005 -illinoisphoto.com enhanced fema image- The heavily damaged Treasure Bay casino in Gulfport, Miss. Hurricane Katrina caused extensive damage all along the Mississippi gulf coast&lt;br&gt;&lt;a type="audio/mpeg" href="http://podcasts.odiogo.com/get_mp3.mp3?f=/go-zone-gateway/GO_Zone_Gateway-The_heavily_damaged_Treasure_Bay_casino_in_Gulfport_Mississippi_lay_lifeless_after_Hurricane_Katrina.mp3"&gt;Click here to play&lt;/a&gt;&lt;br&gt;</description>
      <content:encoded><![CDATA[<p><a href="http://www.gozonegateway.com/wp-content/uploads/2010/05/TreauseCasino.jpg"><img class="alignnone size-full wp-image-233" style="border: 0pt none; margin: 10px;" title="TreauseCasino" src="http://www.gozonegateway.com/wp-content/uploads/2010/05/TreauseCasino.jpg" alt="" width="640" height="425" /></a>Gulfport, Mississippi, September 6, 2005 -illinoisphoto.com enhanced fema image- The heavily damaged Treasure Bay casino in Gulfport, Miss. Hurricane Katrina caused extensive damage all along the Mississippi gulf coast</p>
]]></content:encoded>
      <wfw:commentRss>http://www.gozonegateway.com/featured/the-heavily-damaged-treasure-bay-casino-in-gulfport-mississippi-lay-lifeless-after-hurricane-katrina-smashed-her/feed/</wfw:commentRss>
      <slash:comments>0</slash:comments>
      <enclosure url="http://podcasts.odiogo.com/get_mp3.mp3?f=/go-zone-gateway/GO_Zone_Gateway-The_heavily_damaged_Treasure_Bay_casino_in_Gulfport_Mississippi_lay_lifeless_after_Hurricane_Katrina.mp3" length="260901" type="audio/mpeg" />
    </item>
    <item>
      <title>Highway 90 bridge from Biloxi to Ocean Springs lies in a twisted mass as result of catastrophic wind.</title>
      <link>http://www.gozonegateway.com/featured/hurricane-katrina/</link>
      <comments>http://www.gozonegateway.com/featured/hurricane-katrina/#comments</comments>
      <pubDate>Thu, 06 May 2010 04:30:34 +0000</pubDate>
      <dc:creator>admin</dc:creator>
      <category><![CDATA[Featured]]></category>
      <guid isPermaLink="false">http://www.gozonegateway.com/?p=220</guid>
      <description>Biloxi, Miss., November 3, 2005  -fema/illinoisphoto.com- The Hwy 90 bridge from Biloxi to Ocean Springs  lies in a twisted mass as result of catastrophic wind and storm surge  from Hurricane Katrina.  Road closure along the coastal area has been  problematic in recovery efforts.&lt;br&gt;&lt;a type="audio/mpeg" href="http://podcasts.odiogo.com/get_mp3.mp3?f=/go-zone-gateway/GO_Zone_Gateway-Highway_90_bridge_from_Biloxi_to_Ocean_Springs_lies_in_a_twisted_mass_as_result_of_catastrophic_wind.mp3"&gt;Click here to play&lt;/a&gt;&lt;br&gt;</description>
      <content:encoded><![CDATA[<p><a href="http://www.gozonegateway.com/wp-content/uploads/2010/05/Highway-Bolixi.jpg"><img class="alignnone size-full wp-image-223" title="Highway-Bolixi" src="http://www.gozonegateway.com/wp-content/uploads/2010/05/Highway-Bolixi.jpg" alt="" width="640" height="425" /></a></p>
<p>Biloxi, Miss., November 3, 2005  -fema/illinoisphoto.com- The Hwy 90 bridge from Biloxi to Ocean Springs  lies in a twisted mass as result of catastrophic wind and storm surge  from Hurricane Katrina.  Road closure along the coastal area has been  problematic in recovery efforts.</p>
]]></content:encoded>
      <wfw:commentRss>http://www.gozonegateway.com/featured/hurricane-katrina/feed/</wfw:commentRss>
      <slash:comments>0</slash:comments>
      <enclosure url="http://podcasts.odiogo.com/get_mp3.mp3?f=/go-zone-gateway/GO_Zone_Gateway-Highway_90_bridge_from_Biloxi_to_Ocean_Springs_lies_in_a_twisted_mass_as_result_of_catastrophic_wind.mp3" length="288023" type="audio/mpeg" />
    </item>
    <item>
      <title>GO Zone Extension Sought By Senators of Mississippi</title>
      <link>http://www.gozonegateway.com/go-zone-news/go-zone-extension-sought-by-senators-of-mississippi/</link>
      <comments>http://www.gozonegateway.com/go-zone-news/go-zone-extension-sought-by-senators-of-mississippi/#comments</comments>
      <pubDate>Thu, 12 Nov 2009 16:23:24 +0000</pubDate>
      <dc:creator>admin</dc:creator>
      <category><![CDATA[GO Zone news]]></category>
      <guid isPermaLink="false">http://www.gozonegateway.com/?p=215</guid>
      <description>Mississippi State Republican senators Thad Cochran and Roger Wicker, in a bold effort to encourage building growth after hurricane Katrina, have introduced legislation towards that end.
This new bill would allow an extension of the soon to expire Gulf Opportunity Zone bonus depreciation tax by two years. The new expiration date would be December 31, 2011 [...]&lt;br&gt;&lt;a type="audio/mpeg" href="http://podcasts.odiogo.com/get_mp3.mp3?f=/go-zone-gateway/GO_Zone_Gateway-GO_Zone_Extension_Sought_By_Senators_of_Mississippi.mp3"&gt;Click here to play&lt;/a&gt;&lt;br&gt;</description>
      <content:encoded><![CDATA[<div>
<div>
<p>Mississippi State Republican senators Thad Cochran and Roger Wicker, in a bold effort to encourage building growth after hurricane Katrina, have introduced legislation towards that end.</p>
<p>This new bill would allow an extension of the soon to expire Gulf Opportunity Zone bonus depreciation tax by two years. The new expiration date would be December 31, 2011 instead of 2009, which is less than two months away as of this writing.</p>
<p>Senator Wicker, the author of the bill stated in a news release that Louisiana Democratic Senator Mary Landrieu and Republican Senator David Vitter had also signed on from the outset as cosponsors of the new measure.</p>
<p>In 2005 a tax incentive called the GO Zone Act was established that was the equivalent of 50% of the cost of property that qualified for the year it was put in service and was also taxable.</p>
<p>Areas that would benefit from the extended bonus depreciation incentive of the new bill are those in Mississippi and Louisiana, which suffered the most damage from Katrina; including the counties of Hancock, Jackson, Pearl River and Stone of Mississippi.</p>
<p>In Wicker’s news release he stated, “The bonus depreciation incentive has had a substantial impact on Gulf Coast rebuilding by helping fuel private investment in commercial and affordable housing construction.” He added, “Problems with flood maps and other infrastructure delays have prohibited many projects from being able to take advantage of the bonus depreciation incentive.”</p>
<p>Senator Cochran stated that in order for progress to continue to be made, the two-year extension was necessary. Another staunch supporter of the bill, Brian Sanderson, a member of the Gulf cost Business Council referred to the GO Zone as “one of the most important tools” develop by Congress after the destruction of Hurricane Katrina.</p>
<p>Investors and developers have taken advantage of the GO Zone’s depreciation deduction for rebuilding efforts spanning the Gulf Coast. A variety of building structures have been included in the Incentive. Everything from apartment complexes to hotels and factories to retail stores have been erected using this bonus incentive.</p>
<p>Senator Landrieu introduced two bills that are also being cosponsored by Senators Cocnran and Wicker. These would allow GO Zone tax credits to be extended for low-income housing projects and the restoration of historical buildings.</p></div>
</div>
]]></content:encoded>
      <wfw:commentRss>http://www.gozonegateway.com/go-zone-news/go-zone-extension-sought-by-senators-of-mississippi/feed/</wfw:commentRss>
      <slash:comments>0</slash:comments>
      <enclosure url="http://podcasts.odiogo.com/get_mp3.mp3?f=/go-zone-gateway/GO_Zone_Gateway-GO_Zone_Extension_Sought_By_Senators_of_Mississippi.mp3" length="1248895" type="audio/mpeg" />
    </item>
    <item>
      <title>Long Term Workforce Housing</title>
      <link>http://www.gozonegateway.com/articles/long-term-workforce-housing/</link>
      <comments>http://www.gozonegateway.com/articles/long-term-workforce-housing/#comments</comments>
      <pubDate>Wed, 09 Sep 2009 22:04:54 +0000</pubDate>
      <dc:creator>admin</dc:creator>
      <category><![CDATA[Articles]]></category>
      <guid isPermaLink="false">http://www.gozonegateway.com/?p=213</guid>
      <description>WARNING:  We have had numerous complaints about developers in Mississippi for not honoring and performing on contractual agreements with buyers, clients, contractors or vendors.  If you have questions about a developers reputation or have had issues with your developer please contact us to report or to see if class action suit participation may be available. [...]&lt;br&gt;&lt;a type="audio/mpeg" href="http://podcasts.odiogo.com/get_mp3.mp3?f=/go-zone-gateway/GO_Zone_Gateway-Long_Term_Workforce_Housing.mp3"&gt;Click here to play&lt;/a&gt;&lt;br&gt;</description>
      <content:encoded><![CDATA[<p><a href="http://www.gozonegateway.com/wp-content/uploads/2009/09/House-wiped.jpg"><img class="alignleft size-medium wp-image-246" style="border: 0pt none; margin: 10px;" title="House-wiped" src="http://www.gozonegateway.com/wp-content/uploads/2009/09/House-wiped-300x190.jpg" alt="" width="300" height="190" /></a></p>
<p><strong><span style="color: #ff0000;">WARNING:  We have had numerous complaints about developers in Mississippi for not honoring and performing on contractual agreements with buyers, clients, contractors or vendors.  If you have questions about a developers reputation or have had issues with your developer please contact us to report or to see if class action suit participation may be available. </span></strong></p>
<p>The following is from the State of Mississippi.</p>
<p>DATE:  February 5, 2009</p>
<p>SUBJECT:  HUD approved waivers for the State of Mississippi</p>
<p>I. Purpose:  The Department of Housing and Urban Development has published a waiver of section 105(a) that allows new housing construction and of section 105(a) (24) to allow homeownership assistance for families whose income is up to 120 percent of the area median income (AMI) and up to 100 percent of housing down payment.  The waiver can be found at http://www.federalregister.gov/inspection.aspx#reg_H.  The Long Term Workforce Housing (LTWH) program is providing the following clarification of the approved waiver and additional regulatory guidance to assist in serving households up to 120 percent.  The State is committed to serving low to moderate income households.  Therefore, all projects shall serve at least 51 percent low to moderate income households.</p>
<p>II. Discussion:</p>
<p>1. The LTWH program will provide direct assistance (homebuyer assistance) to eligible households up to 120 percent of AMI due to the recent waiver.  In addition, that waiver reconfirms the eligibility of new housing construction as an eligible CDBG activity as granted in the original waiver dated June 14, 2006.</p>
<p>2. The LTWH program, as stated in our original and modified action plan, will grant funds to Community Based Development Organizations (CBDO)/Neighborhood Based Development Organizations (NDO).  As a result, any revenue generated through these programs will not be considered program income.  Because the LTWH program is designed to provide affordable housing to the coastal workforce, it qualifies as a community economic development program.  As a result, the CB-grantees DO/NDOs sub are able to carry out their projects under this umbrella.  It is understood that some may carry out neighborhood revitalization or energy conservation projects as well, and these will be documented on a case-by-case basis. Furthermore, these organizations are not considered to be sub-recipients and should be expected to act independently in carrying out their projects.</p>
<p>3. To clarify and document the LTWH programs status as a community economic development program, MDA will provide HUD with a brief document detailing how the LTWH program is eligible for this designation.  This documentation will be sufficient to qualify the projects of all the CBDO/NDOs participating in t he LTWH program.</p>
<p>4. As it pertains to new construction and rehabilitation activities, LTWH is not bound to the low/mod national objective.  Instead, we may use the slum/blight and/or urgent need objectives if there is a clear demonstration of meeting these objectives.  Acquisition, clearance, relocation, historic preservation and building rehabilitation activities which eliminate specific conditions of blight or physical decay on a spot basis not located in a slum or blighted area will meet this same objective. The slum/blight and urgent need objectives are not income qualified.  Specifically, there are single and multi-family housing developments projects currently being funded through LTWH.  These units can be occupied by households up to 80% AMI under low/mod or up to 120% AMI under urgent needs or slum/blight.</p>
<p>5. The number of households in mixed-income developments serving over 120 percent of  AMI will be pro-rated based upon the amount of non-CDBG funds in the project.</p>
<p>6. All projects shall serve at least 51 percent low to moderate income households.  The remaining 49 percent of the households can be up to 120% AMI.</p>
<p>III. Action Needed:  Sub-recipients may request a change in their current contract scope to include households up to 120 percent of the AMI.  The request must be made in writing and forwarded to Lynn Seals, Bureau Manager, P.O. Box 849, Jackson, Mississippi  39205.</p>
<p>IV. Questions:  If you have questions concerning this memorandum, please contact Lynn Seals or Chuck Bearman at (601) 359-2905.</p>
]]></content:encoded>
      <wfw:commentRss>http://www.gozonegateway.com/articles/long-term-workforce-housing/feed/</wfw:commentRss>
      <slash:comments>0</slash:comments>
      <enclosure url="http://podcasts.odiogo.com/get_mp3.mp3?f=/go-zone-gateway/GO_Zone_Gateway-Long_Term_Workforce_Housing.mp3" length="2512585" type="audio/mpeg" />
    </item>
    <item>
      <title>Mississippi’s Disaster Recovery Falling Behind</title>
      <link>http://www.gozonegateway.com/rebuilding-efforts/mississippi-disaster-recovery-falling-behind/</link>
      <comments>http://www.gozonegateway.com/rebuilding-efforts/mississippi-disaster-recovery-falling-behind/#comments</comments>
      <pubDate>Wed, 09 Sep 2009 16:08:23 +0000</pubDate>
      <dc:creator>admin</dc:creator>
      <category><![CDATA[Rebuilding Efforts]]></category>
      <guid isPermaLink="false">http://www.gozonegateway.com/?p=116</guid>
      <description>Has Mississippi Fallen Further Behind?
At the fourth anniversary of Hurricane Katrina, the harmful consequences of Mississippi&amp;#8217;s misplaced priorities have become clear, and perhaps irreversible. The State has reduced its allocation for housing programs, lowered its forecasts for key affordable housing programs and abandoned plans for a full housing recovery. Between 2006 and 2008, the State [...]&lt;br&gt;&lt;a type="audio/mpeg" href="http://podcasts.odiogo.com/get_mp3.mp3?f=/go-zone-gateway/GO_Zone_Gateway-Mississippis_Disaster_Recovery_Falling_Behind.mp3"&gt;Click here to play&lt;/a&gt;&lt;br&gt;</description>
      <content:encoded><![CDATA[<p><strong>Has Mississippi Fallen Further Behind?</strong></p>
<p>At the fourth anniversary of Hurricane Katrina, the harmful consequences of Mississippi&#8217;s misplaced priorities have become clear, and perhaps irreversible. The State has reduced its allocation for housing programs, lowered its forecasts for key affordable housing programs and abandoned plans for a full housing recovery. Between 2006 and 2008, the State reallocated over $800 million away from housing towards other purposes. Governor Barbour claimed the diversion was justified because existing programs would fully address the housing crisis caused by Katrina.<span id="more-116"></span></p>
<p>In January, 2009, however, the State received a report that anticipates  over 15,000 fewer housing units from three key affordable housing programs than forecast by the State in May 2008. The report  excuses this shortage on the assumption that fewer people will return to the Gulf Coast. This diverts attention from uncounted and still-unserved people residing on the Coast today and diminishes the Coast&#8217;s ability to welcome future residents.  If we don&#8217;t build enough permanent housing now, all of our people will not remain, whether it is working families, retirees, or any other residents. Neither the State&#8217;s recent pursuit of 5,000 housing vouchers nor its program to permanently place cottages will bridge the gap.  Unless Mississippi changes direction, it will have lost a unique opportunity to both recover from our state&#8217;s greatest housing disaster and  close disparities in housing conditions in the poorest state in the nation.<br />
This report traces the problems to their source and offers recommendations to restore affordable housing to its proper place as the state&#8217;s first priority in disaster recovery.</p>
<p>Among other things, Mississippi</p>
<ul>
<li>lags Louisiana in its overall support for housing and rate of spending of disaster funds;</li>
</ul>
<ul>
<li>started later and spent down less funds more slowly on affordable housing programs than for wealthier residents; and</li>
</ul>
<ul>
<li>falls sharply below its own projections for production of affordable subsidized housing in small rental, long term workforce housing, tax-credit financed rentals and public housing.</li>
</ul>
<p>Failing to provide permanent, safe and affordable housing has profound human consequences. It means the absence of a fundamental human right that our nation expects other nations to observe with its internally displaced people. It means a deep uncertainty and insecurity in the most basic aspect of one&#8217;s daily life. Three stories of the human toll appear at the end of this report, just before the recommendations for future action.</p>
<p><strong>II. OVERVIEW OF FUNDING AND PROGRAMS<br />
A.Mississippi&#8217;s Housing Allocation Decreased But Louisiana&#8217;s Increased.</strong><br />
According to the GAO, between 2006 and 2008, Mississippi reallocated almost $800 million of its disaster Community Development Block Grant (CDBG) housing funds toward economic development, while Louisiana sought and received increased housing funding. Mississippi reduced its housing allocation from 65 to 52 percent, while Louisiana increased its housing allocation from 77 to 86 percent. The GAO rejected<br />
Mississippi&#8217;s attempt to pad its housing allocation with utility and insurance subsidy programs. Mississippi diverted $600 million in unused housing funds to a port</p>
<p style="text-align: center;"><a rel="nofollow" href="http://www.gozonegateway.com/wp-content/uploads/2009/09/page3-img011.jpg"><img class="size-full wp-image-135 aligncenter" title="page3-img011" src="http://www.gozonegateway.com/wp-content/uploads/2009/09/page3-img011.jpg" alt="" width="572" height="507" /></a></p>
<p><strong>B. Mississippi Lags in Spending Disaster Relief. </strong><br />
Mississippi spent almost 50 percent of its funds as of March 2009, compared to 33 percent at the end of 2007. Louisiana widened its lead over Mississippi by spending 68 percent of its funds as of March 2009, compared to 45 percent  as of 2007.</p>
<p style="text-align: center;"><a rel="nofollow" href="http://www.gozonegateway.com/wp-content/uploads/2009/09/page4-img01.jpg"><img class="size-full wp-image-162 aligncenter" title="page4-img01" src="http://www.gozonegateway.com/wp-content/uploads/2009/09/page4-img01.jpg" alt="" width="600" height="197" /></a></p>
<p><strong>C. State Took Longer to Spend Less, Later for Income-Targeted Programs. </strong><br />
Mississippi started in 2006 and accelerated swiftly with larger spending on income-exempt programs (Phase I and Utility/Insurance), reaching over $1.4 billion within 15 months. The State started in 2007 and spent less money more slowly on income-limited programs, reaching only  $661 million in 21 months. See Figures 3 and 4 for details.</p>
<p style="text-align: center;"><a rel="nofollow" href="http://www.gozonegateway.com/wp-content/uploads/2009/09/page4-img02.jpg"><img class="size-full wp-image-163 aligncenter" title="page4-img02" src="http://www.gozonegateway.com/wp-content/uploads/2009/09/page4-img02.jpg" alt="" width="629" height="344" /></a></p>
<p>2007 figures appear in Steps Coalition, &#8220;Is Mississippi Building Back Better Than Before?&#8221; August 2008,<br />
p. 4.</p>
<p><a rel="nofollow" href="http://www.gozonegateway.com/wp-content/uploads/2009/09/page5-img01.jpg"><img class="size-full wp-image-165 aligncenter" title="page5-img01" src="http://www.gozonegateway.com/wp-content/uploads/2009/09/page5-img01.jpg" alt="" width="589" height="719" /></a></p>
<p><strong>D.Lowered Expectations: State Reduces Program Forecasts by 15,000 units</strong><br />
In May, 2008, Mississippi&#8217;s Office of Recovery and Renewal testified in a Congressional oversight hearing that its housing programs would restore or exceed the 52,512 housing units with major and severe hurricane damage. Three programs were the key to the state&#8217;s assurance: long term workforce housing, small rental, and low income housing tax credit properties.</p>
<p>These three programs actually will fall over 15,000 units short of prior forecasts, according to figures in the Mississippi Housing Data Project, a report commissioned by Governor Barbour. A comparison of the data is set forth in Table 1. The Steps Coalition anticipates that the shortage will widen when an updated report is released, based on field reports.</p>
<p style="text-align: center;"><a rel="nofollow" href="http://www.gozonegateway.com/wp-content/uploads/2009/09/page6-img01.jpg"><img class="aligncenter size-full wp-image-170" title="page6-img01" src="http://www.gozonegateway.com/wp-content/uploads/2009/09/page6-img01.jpg" alt="" width="600" height="208" /></a></p>
<p>The Steps Coalition is troubled by news reports that  Mississippi intends to use lower population recovery forecasts to justify a slower and incomplete housing recovery. Planning based on a smaller population is a self-fulfilling prophecy: today and in the future, all residents cannot return to the Gulf Coast area unless adequate housing is restored.  Delaying a complete housing recovery will delay a population recovery, and<br />
the result will be the denial of a fundamental human right of internally displaced persons: the right to return.</p>
<p>Mississippi officials still forecast a full recovery of housing by 2011, but acknowledge it will not be a universal recovery. The Gulf region continues to face  shortages in the category of deepest need of affordability, according to state officials.  In Part III, the causes and solutions of this shortfall will be discussed.</p>
<p><strong>E. Lowering the Bar: HUD allows Mississippi to target only one-third of its primary appropriation to assist lower-income residents.</strong><br />
Over the past four years, the Steps Coalition has urged the U. S. Department of Housing and Urban Development (HUD) to hold Mississippi to the requirement that the Disaster CDBG funds be spent in ways that benefit persons of low and moderate income. In Congressional oversight hearings, advocates urged HUD and Congress to re-examine over $4 billion worth of program waivers previously granted to Mississippi&#8217;s disaster CDBG programs.</p>
<p>In December, 2008 the outgoing HUD administration used some Enron-style accounting  to conclude that Mississippi could meet the Congressional goal without waivers of the low-income benefit requirement for three non-housing programs.  In effect, HUD took off the books over $1.8 Billion in programs that did not benefit lower income persons. The Steps Coalition asserts that the only way to accurately assess overall benefit is to count all of the money, including the $1.8 billion HUD excluded from the equation. In the table below, the Steps Coalition demonstrates that an accurate overall calculation shows Mississippi achieved only a 34 percent benefit, substantially short of the 50 percent Congressional goal.</p>
<p style="text-align: center;"><a rel="nofollow" href="http://www.gozonegateway.com/wp-content/uploads/2009/09/page7-img01.jpg"><img class="aligncenter size-full wp-image-172" title="page7-img01" src="http://www.gozonegateway.com/wp-content/uploads/2009/09/page7-img01.jpg" alt="" width="600" height="283" /></a></p>
<p style="text-align: center;"><a rel="nofollow" href="http://www.gozonegateway.com/wp-content/uploads/2009/09/page8-img011.jpg"><img class="aligncenter size-full wp-image-176" title="page8-img011" src="http://www.gozonegateway.com/wp-content/uploads/2009/09/page8-img011.jpg" alt="" width="600" height="201" /></a></p>
<p style="text-align: left;">* Small Rental Assistance and Workforce Housing programs were paid in part with funds from Public Laws 109-148 and 109-234. Only the portion funded by 109-148 is included.</p>
<p style="text-align: left;">Moreover, all income-targeted programs are spending less later and more slowly than the income-exempt programs, as shown in Figure 3. In human terms, this nearly four year delay is for all intents and purposes a non-recovery for those least able to stretch their personal and temporary resources until relief arrives. The Steps Coalition urges the incoming administration to re-evaluate and reconsider the action of the prior<br />
administration on this vital policy decision.</p>
<p style="text-align: left;"><strong>II.  CURRENT CHALLENGES<br />
A. Rescuing Households &#8220;Outside of the System&#8221;</strong><br />
In August, 2008, the Steps Coalition warned that Mississippi&#8217;s disaster housing recovery programs would not generate a sufficient supply of affordable housing to absorb the more than 4,000 households then in the FEMA temporary housing programs. One year later,  this prediction tragically has come true, and there remain thousands of residents in this region who have unwillingly traded cramped FEMA trailers or hotel rooms for equally unacceptable housing Òoutside of the system,Ó such as unrepaired or overcrowded dwellings shared with others.  This unfortunate population joins thousands more wrongly denied or improperly removed from FEMA&#8217;s temporary housing programs.</p>
<p>In the Spring of 2009, Mississippi officials publicly acknowledged the need of the residents still outside the system and requested Congress to award 5,000 Section 8 housing vouchers.  In support of this request, the State cited unmet needs for 2,000 pre-Katrina lower-income homeowners who are post-Katrina renters, 2,322 households who cannot afford rent due to the post-Katrina spike in rental rates, and 1,750 who await the completion of public housing. The Steps Coalition welcomes Mississippi&#8217;s acknowledgement of unmet housing need. But it was no invisible hand that pushed these households out of FEMA&#8217;s temporary housing programs into an abyss. Mississippi officials excluded  thousands of wind-damaged homeowners and delayed programs to restore affordable and public housing.</p>
<p>HUD and Mississippi share responsibility for laws that have left thousands of households still without permanent housing four years after Katrina. With HUD&#8217;s approval, Mississippi has denied compensation to thousands of lower-income wind-damaged homeowners, who now live in unrepaired housing or have been forced to become renters. Four years after Katrina, HUD and Mississippi have failed to deliver a large enough supply of affordable housing under the state&#8217;s dramatically-underperforming small rental and long term workforce housing programs. Participants describe to the Steps Coalition deep frustration with complex, shifting, and excessively risk-averse requirements imposed by federal and state officials, their lawyers and accountants. Also, HUD has failed to heed Mississippi&#8217;s appeal to apply common sense instead of bureaucratic rigidity to the important issue of duplication of benefits, which limits the ability of ordinary citizens to use the full spectrum of resources to achieve permanent housing.</p>
<p>HUD and Mississippi share responsibility to change current policies if the voucher program is to even partially by self-created gaps in the housing recovery system. First, HUD awarded a grossly inadequate supply of vouchers to Gulf Coast housing authorities, less than 800 vouchers in response to a request for 5,000. Instead,  HUD directed up to 2,500 to other housing authorities away from coastal Mississippi, which will worsen the lagging efforts to restore the population to pre-Katrina levels.</p>
<p>Second, a housing voucher without a rental unit is a ticket without a train. Mississippi asserted that there existed a nearly 25 percent vacancy rate and over 2,000 units of market-rate rentals whose landlords would accept Section 8 vouchers, a claim that was ridiculed when repeated by a HUD offcial in a Congressional oversight hearing. Newly-released data show a 12 percent vacancy rate in market-rent apartments.</p>
<p>Raising further doubt on supply,  Steps Coalition allies, Mississippi Center for Justice and Lawyers&#8217; Committee for Civil Rights Under Law,  performed a held check of landlords accepting Section VIII vouchers and found fewer than 800 actual vacancies.</p>
<p>HUD and Mississippi must redouble their efforts to and innovative solutions to restore affordable housing. Extending compensation to households still struggling to repair their homes is a basic requirement. Mississippi added $10 million for housing resource centers to split among thousands of households that still face major gaps to recovery after exhausting all other resources. A substantially larger commitment is required.</p>
<p>HUD and Mississippi also must add to their commitments to income-targeted housing programs  and, just as importantly, must simplify and accelerate the approval and implementation process.   As two Congressional housing leaders reminded Governor Barbour, vouchers are &#8220;only one part of the housing equation; hard affordable housing units are also needed.&#8221; Moreover, vouchers matched with market rate rentals cannot take the place of long-term affordable housing units and do not represent a sustainable solution. Some housing advocates have called for the conversion of market rate rentals to long-term subsidized rentals. The evidence of an overbuild is shown by the higher-than-normal market-rate vacancy rates and the first, modest softening in rental rates since Katrina. Mississippi could step in at this point to assist public housing authorities and other investors in subsidized housing in rebalancing and extending the affordability horizon of the area&#8217;s rental market. To do so will require the State to return funds that were diverted away from housing to provide grants or loans to qualified buyers.</p>
<p>The Steps Coalition fully supports the call by Congressman Frank and Congresswoman Waters for Governor Barbour  to &#8220;match your commitment to vouchers with a commensurate commitment to the use of your existing CDBG funds for the redevelopment and expansion of hard units of affordable housing in Mississippi.&#8221;</p>
<p><a rel="nofollow" href="http://www.gozonegateway.com/wp-content/uploads/2009/09/page11-img01.jpg"><img class="alignright size-full wp-image-180" title="page11-img01" src="http://www.gozonegateway.com/wp-content/uploads/2009/09/page11-img01.jpg" alt="" width="349" height="406" /></a></p>
<p><strong>B. Public Housing: Too Little Too Late</strong><br />
The rate, speed and size of CDBG spending for the Gulf $1.2 B Coast&#8217;s wealthiest homeowners dwarfs spending for its poorest public housing residents. Until $900M early 2008, public housing spending was so close to zero that it was nearly invisible $600M (Figure 5A). Mississippi took 18 months to spend more on public housing grants than it did on $300M administration. (Figure 5B).  The delay cannot be justified merely on differences in the size, grant amount, or complexity of the programs. Mississippi officials, and ultimately HUD itself, simply Phase IPHA GrantsPH</p>
<p>A Admin placed a lower priority on the state&#8217;s most vulnerable residents</p>
<p style="text-align: center;"><a rel="nofollow" href="http://www.gozonegateway.com/wp-content/uploads/2009/09/page11-img02.jpg"><img class="aligncenter size-full wp-image-182" title="page11-img02" src="http://www.gozonegateway.com/wp-content/uploads/2009/09/page11-img02.jpg" alt="" width="600" height="327" /></a></p>
<p style="text-align: left;">State officials have routinely obscured the public housing picture by combining true public housing units with other forms of deep subsidy housing to artificially infate the progress on traditional public housing.  It is important to track conventional public housing separately because this category has the longest duration of affordability. The Gulf Coast area remains over 1,000 traditional public housing units below pre-Katrina levels, according to an independent rental market analysis. Only one unit out of 1,171public housing apartments was vacant as of May, 2009, a 0.1 percent vacancy rate.</p>
<p style="text-align: center;"><a rel="nofollow" href="http://www.gozonegateway.com/wp-content/uploads/2009/09/page12-img01.jpg"><img class="aligncenter size-full wp-image-185" title="page12-img01" src="http://www.gozonegateway.com/wp-content/uploads/2009/09/page12-img01.jpg" alt="" width="593" height="207" /></a></p>
<p style="text-align: left;">Demand for Section 8 vouchers through Public Housing Authorities continues to outstrip supply, as demonstrated by the Coastal Housing Lease Up Report, set forth in Table 5. Unforgivably, HUD has allocated coastal Mississippi housing authorities less than 800 vouchers of the 3,000 provided to the state. The Steps Coalition urges HUD to redirect all vouchers allocated to Mississippi into the Gulf Coast area for use by displaced residents.</p>
<p style="text-align: center;"><a rel="nofollow" href="http://www.gozonegateway.com/wp-content/uploads/2009/09/page12-img02.jpg"><img class="aligncenter size-full wp-image-186" title="page12-img02" src="http://www.gozonegateway.com/wp-content/uploads/2009/09/page12-img02.jpg" alt="" width="620" height="208" /></a></p>
<p style="text-align: left;">Mississippi still has a significant task ahead of itself in restoring traditional public housing capacity and meeting post-Katrina needs of this area&#8217;s residents who earn at or below 30 percent of area median income.  The obvious and basic immediate job ought to be to build at least 1,000 traditional public housing units affordable to the Coast&#8217;s most needy residents. The State¼s actual use of $105 million was not to restore public housing structures that have the longest affordability commitment, but to treat the fund as a bank to subsidize construction of shorter-horizon tax-credit properties. As tenants earning 30 percent of area median income are blended into properties with higher income eligibility requirements, the ability is lost to assure a one-for-one replacement of units permanently affordable to these tenants.</p>
<p style="text-align: left;"><strong>CI.LIHTC progress not enough to overcome losses elsewhere.</strong><br />
Mississippi has insisted from the outset that a surplus in apartment complexes financed by low income housing tax credits (LIHTC) will expand public housing supply and offset shortfalls in its other affordable housing programs, such as the Small Rental Assistance Program and Long Term Workforce Housing. Unfortunately this prediction also has failed to come true. According to one independent source, the Gulf Coast has produced 2,142 more LIHTC rental units than the Gulf Coast had before Katrina, and expects another 1,242, the total from these programs would be only about 12,500 units, over 11,000 fewer than the State originally predicted.</p>
<p style="text-align: center;"><a rel="nofollow" href="http://www.gozonegateway.com/wp-content/uploads/2009/09/page13-img01.jpg"><img class="aligncenter size-full wp-image-187" title="page13-img01" src="http://www.gozonegateway.com/wp-content/uploads/2009/09/page13-img01.jpg" alt="" width="615" height="306" /></a></p>
<p style="text-align: left;">There remains strong demand for the subsidized rental housing available at LIHTC-ennanced apartments. In 2008, an independent rental market analyst pointed out that the unusually high occupancy rates and rapid lease-up rates at LIHTC-financed properties were indications of deep demand for affordable rental housing on the Mississippi Gulf Coast. Over the next year, the Coast saw 1,450 LIHTC units added to the supply, and produced a temporarily inflated 11 percent vacancy rate while these units were being absorbed by the market.23 As occurred last year, this additional supply will be absorbed without exhausting remaining demand.</p>
<p style="text-align: left;">More aggressive enforcement of the federal Fair Housing Act would have accelerated the recovery of this important segment of the rental market. Through the Warm Welcome Gulf Coast campaign, a key Steps Coalition ally, Back Bay Mission undertook important educational work to dispel prejudice and educate the public about affordable housing. But education alone will not move some stubborn local governments.  Federal and state officials have been all too timid in deferring to local moratoria against multifamily rental projects, or tax-credit finance projects. As a result, a permanent recovery has been delayed or denied to thousands of lower-income members of protected classes, including racial minorities, persons with disabilities, and families with children.  As this report is released, at least two municipalities in hardest-hit Hancock County, have moratoria against construction of multifamily rental complexes, despite a clearly inadequate rate of housing recovery overall.</p>
<p style="text-align: left;"><a rel="nofollow" href="http://www.gozonegateway.com/wp-content/uploads/2009/09/page14-img011.jpg"><img class="alignleft size-full wp-image-190" title="page14-img011" src="http://www.gozonegateway.com/wp-content/uploads/2009/09/page14-img011.jpg" alt="" width="396" height="270" /></a><strong>D. Cottages &#8211; Permanent Placement is Elusive</strong><br />
In Mississippi, nearly 2,800 cottages were constructed and deployed under Mississippi&#8217;s share of a $400 million Alternative Housing Pilot Program pilot program funded by the Federal Emergency Management Agency (&#8220;FEMA&#8221;) and administered by the Mississippi Emergency Management Agency (&#8220;MEMA&#8221;).  The cottages are larger, stronger, and more livable than the FEMA trailers they replaced. While a few hundred cottages in extremely low-lying flood zones were surge-damaged by Hurricane Gustav, the majority of cottages weathered the winds well. Significantly, the cottages were designed to be converted to permanent use.</p>
<p>Despite the MEMA Cottage&#8217;s superior modular construction, Hancock Harrison Jackson vernacular architecture, and higher quality, many  municipalities have banned or severely restricted the permanent placement of  the MEMA cottage on the mistaken assumption that it is indistinguishable from a mobile home. Steps Coalition members currently pursue advocacy and litigation against local municipalities to ensure that the MEMA cottages are treated the same as any other modular unit, and to remove other restrictions.  Despite these efforts, the conversion of individual cottages to permanent use remains stymied by case management complications, a disunited resource pool for elevation and foundation costs, and local government opposition. As a result there is a troublingly low 42 percent  conversion rate to permanency, and an even worse percent rate in Hancock County, which faces the greatest challenge to recovery.</p>
<p style="text-align: center;"><a rel="nofollow" href="http://www.gozonegateway.com/wp-content/uploads/2009/09/page15-img01.jpg"><img class="aligncenter size-full wp-image-192" title="page15-img01" src="http://www.gozonegateway.com/wp-content/uploads/2009/09/page15-img01.jpg" alt="" width="586" height="231" /></a></p>
<p style="text-align: left;">The Steps Coalition supports MEMA¼s effort to convert the Mississippi cottages to permanent use, and supports Mississippi Development Authority¼s intention to provide elevation grants above the arbitrary benchmark established by FEMA. Several Steps Coalition allies have been promised allocations of cottages for owner-occupied and rental uses, including Enterprise Corporation of the Delta, Mercy Housing and Human Development, Habitat for Humanity, and the North Gulfport Community Land Trust. Some of these projects are going forward, but others face continued challenges from the tangled approval and compliance process imposed by federal and state officials.</p>
<p>The Steps Coalition opposes redistribution of cottages to other state agencies or a statewide public auction. Instead, MEMA should insure that each and every Mississippi cottage is placed on the Mississippi Coast to restore housing opportunity.</p>
<p><strong>E. Wind-Damaged Homeowners Get Zero CDBG Assistance</strong><br />
The Steps Coalition looks forward to the release of the next phase of the Mississippi Housing Data Project&#8217;s report on unrepaired damage. We anticipate confirmation that thousands of households still have unrepaired dwellings, both from storm surge and from hurricane wind damage.  For a sizable percentage of wind-damaged homeowners who have not repaired their dwellings, the Steps Coalition anticipates the explanation will be inability to pay either due to inadequate insurance payment or absence of a federal grant program covering wind-damage. A table of owner-occupied residences with major to severe wind damage for South Mississippi counties is set forth below.</p>
<p style="text-align: center;"><a rel="nofollow" href="http://www.gozonegateway.com/wp-content/uploads/2009/09/page16-img01.jpg"><img class="aligncenter size-full wp-image-194" title="page16-img01" src="http://www.gozonegateway.com/wp-content/uploads/2009/09/page16-img01.jpg" alt="" width="589" height="218" /></a></p>
<p style="text-align: left;">Rural households above the three coastal counties continue to deteriorate in obscurity because the State has defined out of existence this entire category of disaster victims. The Steps Coalition renews its call for Governor Barbour to put forward some grant or compensation program to help this class of Katrina-damaged citizens complete their recovery. From the standpoint of basic fairness it only makes sense for the State to extend similar concern to these citizens as it did to the utility companies whose repairs to wind damage to transmission and distribution lines in these same counties were promptly funded by hundreds of millions of dollars in  federal CDBG assistance, without disdainful lectures about personal responsibility to insure one¼s assets against disaster.</p>
<p style="text-align: left;">
<h1>Left in Distress- Three Stories</h1>
<h2>Federal and state housing recovery gaps have a human toll.</h2>
<p><a rel="nofollow" href="http://www.gozonegateway.com/wp-content/uploads/2009/09/page17-img011.jpg"><img class="alignleft size-full wp-image-198" style="border: 1px solid black; margin: 5px;" title="page17-img011" src="http://www.gozonegateway.com/wp-content/uploads/2009/09/page17-img011.jpg" alt="" width="205" height="173" /></a><strong>James Johnson</strong> sleeps on a bench cushion in a FEMA trailer that he moved onto his land after a tornado spawned by Hurricane Katrina destroyed the house he built from scrap lumber brought from the sawmill where he worked for 47 years.</p>
<p>Mr. Johnson, who quit elementary school to help his family earn the money to buy the land he now occupies, was excluded by Mississippi&#8217;s Homeowner Assistance program because his hurricane damage was not caused by storm surge. His family provides some assistance to him and he receives a small social security check. He is crippled by gout.</p>
<p>His trailer sits less than a five-minute ride from hundreds of unoccupied MEMA cottages stored on open land. He owns his own property, it has no zoning barriers, and it is above the flood plain. He is &#8220;exactly the type of individual&#8221; MEMA wants to sell a cottage to, according to the Director of MEMA. But no one can connect the dots for Mr. Johnson, despite unrelenting efforts by his daughter Cynthia Moore, case managers, or even Congressional Staff. He likely will wake up on the Fourth Anniversary of Katrina on the same bench cushion.</p>
<p><a rel="nofollow" href="http://www.gozonegateway.com/wp-content/uploads/2009/09/page17-img02.jpg"><img class="alignleft size-full wp-image-201" style="border: 1px solid black; margin: 5px;" title="page17-img02" src="http://www.gozonegateway.com/wp-content/uploads/2009/09/page17-img02.jpg" alt="" width="203" height="173" /></a><strong>Robert Guercio&#8217;s</strong> home in Waveland was completely destroyed by Hurricane Katrina. MEMA installed a cottage on his vacant lot in October of 2007. Now MEMA wants it back.</p>
<p>Guercio and dozens of other cottage recipients recieved eviction notices from MEMA earlier this spring. But Guercio who is retired and living on a fixed income, has no place to go. The contractor he hired to rebuild his home absconded with the money Guercio advanced and left the house<br />
uncompleted</p>
<p>MEMA served Guercio with a summons to court in June and obtained an order of eviction. The Mississippi Center for Justice filed an appeal on his behalf and the Circuit Court on Aug. 212009 found that the eviction did not conform to statutory requirements. Another victory for a Katrina survivor battling the unfeeling bureaucracy in charge of Mississippi&#8217;s recovery?</p>
<p>Not exactly. Last week MEMA served Guercio with another eviction notice. It states that he must be out of his cottage by Aug. 27 or face court proceedings to force his removal from the cottage<br />
<a rel="nofollow" href="http://www.gozonegateway.com/wp-content/uploads/2009/09/page17-img03.jpg"><img class="alignleft size-full wp-image-202" style="border: 1px solid black; margin: 5px;" title="page17-img03" src="http://www.gozonegateway.com/wp-content/uploads/2009/09/page17-img03.jpg" alt="" width="217" height="179" /></a>Martha Snelling&#8217;s home and rental units in Gulfport were damaged by Hurricane Katrina. Martha pursued and received small rental and historic preservation grants because both were needed to restore the structures to habitability. Standing alone, the Small Rental Assistance Program was not enough to enable her to complete the work.</p>
<p>While Martha appreciates the support that lets her do her part to restore housing in two historic African American communities,Soria City and Turkey Creek, she has experieced profound distress trying to get the state programs to work together.The stress from continuously changing rules, duplication of benefits and competing demand drove her to the brink of abandoning the effort. Unfortunately the challenges Martha has met have deterred too many other other small landlords from restoring damaged rentals in communities across the coast.</p>
<p><strong>Recommendations: </strong><br />
HUD should require Mississippi to restore disaster CDBG funds back to housing programs that were diverted for other purposes until a complete housing recovery is achieved.<br />
HUD should reevaluate Mississippi&#8217;s performance on the overall benefit percentage requirement and refuse to exempt over 36 percent of the funds from an overall benefit analysis.<br />
HUD should require Mississippi to spend existing disaster funds more quickly, but particularly those for affordable housing programs. HUD, in cooperation with other federal agencies, should streamline the approval, implementation and regulatory compliance process to accelerate this effort.<br />
HUD should reallocate all Mississippi&#8217;s housing vouchers in the 2009 appropriation to serve the unmet needs in coastal Mississippi, as originally intended.  Also, HUD should condition the reallocation upon Mississippi&#8217;s taking affirmative steps to finance the purchase of market rate rental units and convert them into hard, long-term affordable rental units.<br />
Mississippi should accelerate the expenditure of funds in affordable housing programs, including the Small Rental Assistance Program, the Long Term Workforce Housing Program, and the Cottage Permanency Program, and streamline or eliminate the state compliance requirements imposed by its lawyers and accountants.<br />
Mississippi should fund an income-targeted program to compensate or repair the thousands of still-unrepaired dwellings in the region, including those with severe wind damage, whether on or above the three coastal counties.<br />
Mississippi should ensure that all Mississippi Cottages are permanently placed for storm-damaged residents with priority to areas in greatest distress.</p>
<p>Together, HUD and Mississippi should more forcefully enforce the federal Fair Housing Act&#8217;s non-discrimination requirements against local jurisdictions that enact regulations whose effect is to exclude lower income members of racial minorities, persons with disabilities, and other protected classes.</p>
<p style="text-align: center;"><strong>For more information, visit the Steps Coalition at <a rel="nofollow" href="http://www.stepscoalition.org" target="_blank">www.stepscoalition.org</a> </strong><br />
<em>This report was authored for the Steps Coalition by the Mississippi Center for Justice with contributions from Back Bay Mission and the Gulf Coast Fair Housing Center.</em></p>
]]></content:encoded>
      <wfw:commentRss>http://www.gozonegateway.com/rebuilding-efforts/mississippi-disaster-recovery-falling-behind/feed/</wfw:commentRss>
      <slash:comments>0</slash:comments>
      <enclosure url="http://podcasts.odiogo.com/get_mp3.mp3?f=/go-zone-gateway/GO_Zone_Gateway-Mississippis_Disaster_Recovery_Falling_Behind.mp3" length="14053078" type="audio/mpeg" />
    </item>
    <item>
      <title>Mississippi Long Term Workforce Housing Program</title>
      <link>http://www.gozonegateway.com/mda/mississippi-long-term-workforce-housing-program/</link>
      <comments>http://www.gozonegateway.com/mda/mississippi-long-term-workforce-housing-program/#comments</comments>
      <pubDate>Thu, 03 Sep 2009 15:33:40 +0000</pubDate>
      <dc:creator>admin</dc:creator>
      <category><![CDATA[MDA]]></category>
      <guid isPermaLink="false">http://www.gozonegateway.com/?p=114</guid>
      <description>WARNING:   We have had numerous complaints about developers in Mississippi for not  honoring and performing on contractual agreements with buyers, clients,  contractors or vendors.  If you have questions about a developers  reputation or have had issues with your developer please contact us to  report or to see if class action [...]&lt;br&gt;&lt;a type="audio/mpeg" href="http://podcasts.odiogo.com/get_mp3.mp3?f=/go-zone-gateway/GO_Zone_Gateway-Mississippi_Long_Term_Workforce_Housing_Program.mp3"&gt;Click here to play&lt;/a&gt;&lt;br&gt;</description>
      <content:encoded><![CDATA[<p><span style="color: #ff0000;"><strong>WARNING:   We have had numerous complaints about developers in Mississippi for not  honoring and performing on contractual agreements with buyers, clients,  contractors or vendors.  If you have questions about a developers  reputation or have had issues with your developer please contact us to  report or to see if class action suit participation may be available.</strong></span></p>
<p>The Mississippi Development Authority&#8217;s Long Term Workforce Housing Program has been established to help create affordable workforce housing largely for the counties of Hancock, Harrison, and Jackson that were adversely affected by Hurricane Katrina.</p>
<p>The program is part of the Homeowner Assistance Grant Program, and its budget is $241 million, or $350 million when administrative cost is taken into consideration. The program works to help individuals with low or moderate income, destroy or prevent slums or blight, and assist communities with a need for fast help due to an immediate threat to the well being of the residents living there.</p>
<p>The action plan of the program outlines its most prominent goals and the methods that will be employed to reach them. It defines Long Term Workforce Housing as housing that helps households who make 120% of the Area Median Income or less.</p>
<p>Nearly 9,000 families as of 2008 were still living in trailers provided by the Federal Emergency Management Agency (FEMA) after being displaced by hurricane Katrina, three years after it occurred. Most of these people currently had incomes below the 120% mark of the Area Median Income. One of the main goals of the Long Term Workforce Housing Program was to help these people find permanent housing.</p>
<p>In order to decide which individuals, businesses, and charities should receive assistance, the Development Authority created a point system based on several factors.</p>
<p>One criteria is practicality of whether the amount requested was reasonable for the good done. Bonuses were the ability of the individuals or organization to receive additional financing from other sources or provide some of the funding.</p>
<p>Other criterion was based on the plans, environmental friendliness, varied incomes of individuals helped by the proposed project, and the location of the project.  For example, it is favorable to be close to such amenities as downtown districts, employment centers, schools, public transportation, hospitals, fire stations, and police stations, and unfavorable to be near power plants and heavy industrial areas.</p>
<p>Applicants should also focus on the need for the project, the efficiency of the proposed schedule, the experience of the workers (including resumes for all team members), and the support of the community.</p>
<p>The program also works to ensure that a fair number of the contracts go to minority and woman&#8217;s businesses.</p>
]]></content:encoded>
      <wfw:commentRss>http://www.gozonegateway.com/mda/mississippi-long-term-workforce-housing-program/feed/</wfw:commentRss>
      <slash:comments>0</slash:comments>
      <enclosure url="http://podcasts.odiogo.com/get_mp3.mp3?f=/go-zone-gateway/GO_Zone_Gateway-Mississippi_Long_Term_Workforce_Housing_Program.mp3" length="1466630" type="audio/mpeg" />
    </item>
    <item>
      <title>Attention: The GO Zone deductibility period will end 2009</title>
      <link>http://www.gozonegateway.com/go-zone-news/go-zone-deductibility-period-will-end-2009/</link>
      <comments>http://www.gozonegateway.com/go-zone-news/go-zone-deductibility-period-will-end-2009/#comments</comments>
      <pubDate>Mon, 09 Feb 2009 13:34:49 +0000</pubDate>
      <dc:creator>admin</dc:creator>
      <category><![CDATA[GO Zone news]]></category>
      <guid isPermaLink="false">http://www.gozonegateway.com/?p=92</guid>
      <description>Investors all across the United States have expressed interest in GO Zone property and the potential benefits it creates financially, but there is a lot of confusion about when the GO Zone deductibility period will end.  Most GO Zone material portrays that the GO Zone will allow for deductions to the end of 2010.  This [...]&lt;br&gt;&lt;a type="audio/mpeg" href="http://podcasts.odiogo.com/get_mp3.mp3?f=/go-zone-gateway/GO_Zone_Gateway-Attention-_The_GO_Zone_deductibility_period_will_end_2009.mp3"&gt;Click here to play&lt;/a&gt;&lt;br&gt;</description>
      <content:encoded><![CDATA[<p>Investors all across the United States have expressed interest in GO Zone property and the potential benefits it creates financially, but there is a lot of confusion about when the GO Zone deductibility period will end.  Most GO Zone material portrays that the GO Zone will allow for deductions to the end of 2010.  This is NOT true; actually, any expenditure on a GO Zone property made in 2010 will not qualify for the GO Zone 50% bonus depreciation deduction!  This means all expenditures must be paid for by 31 December 2009.  The legislation is pages and pages long, but has 1 line that expresses this approaching deadline.  <strong>This does not leave investors a lot of time to find a great property that qualifies for the GO Zone 50% bonus depreciation. </strong></p>
<p><strong>The end of 2009 date was confirmed by John (GO Zone Gateway tax adviser), via a direct conversation with the IRS.</strong></p>
<p>As an investor, you should be seeking a cash-flowing investment that is already built, or in construction.  We have spoken to over 50 GO Zone &#8216;developers&#8217; and very few of them actually have their act together, most are just trying to make a quick buck.  A great example of this are the significant amount of investors that tried to invest in property in Alabama, but didn&#8217;t close on their investment before the end of 2008 and thus will not qualify for the GO Zone benefits (AL benefits ended 2008).  We have also spoken to many investors who have been in contract waiting for their homes to close for well over a year, some up to almost 2 years.  If this has happened to you then you can be sure you aren&#8217;t investing with a team that has your best interest in mind.</p>
<p>The GO Zone Gateway team has taken the hard work out of finding a turn-key, cash- flowing GO Zone property.  We have conducted thousands of hours in due diligence and have laid the projects we recommend on a silver platter for investors to review.</p>
<p><strong>You don&#8217;t have much time, so make sure you invest wisely and in the right project!  Call us now for a free one-on-one consultation.  561-404-7375</strong></p>
]]></content:encoded>
      <wfw:commentRss>http://www.gozonegateway.com/go-zone-news/go-zone-deductibility-period-will-end-2009/feed/</wfw:commentRss>
      <slash:comments>0</slash:comments>
      <enclosure url="http://podcasts.odiogo.com/get_mp3.mp3?f=/go-zone-gateway/GO_Zone_Gateway-Attention-_The_GO_Zone_deductibility_period_will_end_2009.mp3" length="1193799" type="audio/mpeg" />
    </item>
    <item>
      <title>GO Zone Newsletter 11/22</title>
      <link>http://www.gozonegateway.com/articles/nov-22-go-zone-newsletter/</link>
      <comments>http://www.gozonegateway.com/articles/nov-22-go-zone-newsletter/#comments</comments>
      <pubDate>Sat, 22 Nov 2008 06:15:07 +0000</pubDate>
      <dc:creator>admin</dc:creator>
      <category><![CDATA[Articles]]></category>
      <guid isPermaLink="false">http://www.gozonegateway.com/?p=63</guid>
      <description>Dear GO Zone Gateway members,
We have had a very busy few weeks since the second round of the Small Rental Assistance Program (SRAP) opened up on October 15th. To all the members that have moved forward we want to personally take a minute and thank you for your support and patience, we know how excited [...]&lt;br&gt;&lt;a type="audio/mpeg" href="http://podcasts.odiogo.com/get_mp3.mp3?f=/go-zone-gateway/GO_Zone_Gateway-GO_Zone_Newsletter_1122.mp3"&gt;Click here to play&lt;/a&gt;&lt;br&gt;</description>
      <content:encoded><![CDATA[<p><a href="http://www.gozonegateway.com/wp-content/uploads/2008/11/boatontheroof.jpg"><img class="alignleft size-medium wp-image-257" style="border: 0pt none; margin: 10px;" title="boatontheroof" src="http://www.gozonegateway.com/wp-content/uploads/2008/11/boatontheroof-300x190.jpg" alt="" width="300" height="190" /></a>Dear GO Zone Gateway members,</p>
<p>We have had a very busy few weeks since the second round of the Small Rental Assistance Program (SRAP) opened up on October 15th. To all the members that have moved forward we want to personally take a minute and thank you for your support and patience, we know how excited you all are about this investment.</p>
<p><a href="http://www.gozonegateway.com/go-zone-property/ocean-springs.html" target="_blank">Click here to watch the video</a></p>
<p>As you know, the coordination efforts between the developer, lender, tax advisor and the MDA is alot of work, but we are committed to making this process as smooth as possible for you. The phenomenal response we have had to this project goes to show that even in these turbulent economic times a quality investment that has strong fundamentals is always in high demand.</p>
<p>For those of you that are still interested and have not yet had the time to connect with us or finish your due diligence we urge you to move forward quickly. Only 24 days remain before the second round of SRAP closes.</p>
<p>Also, don&#8217;t forget this investment is a qualified GO Zone rental property. As many of you already know, investing in the GO Zone can save you thousands of dollars on your federal income taxes. If you have not yet scheduled your one-on-one complimentary tax consultation we urge you to do so ASAP.</p>
<p>Call to get all your questions answered on the $73,000 governmental incentive, the development, and schedule a time with our tax advisor. He will specifically show you how much money you can save or get back from the government (amended tax returns).</p>
<p>Since time is running out on this program we will be hosting a live Webinar for our members on Tuesday night the (Nov 25th). We will be answering your questions about the development and the SRAP program. Also presenting will be our expert tax advisor of 33 years.</p>
<p>LIVE WEBINAR EVENT Tuesday November 25th at 9PM EST/8PM CST/7PM MST/6PM PST</p>
<p>REGISTER FOR THE LIVE EVENT AT</p>
<p><a href="https://www1.gotomeeting.com/register/979518618" target="_blank">https://www1.gotomeeting.com/register/979518618</a></p>
<p>(NOTE: Enter YAERD or GATEWAY in the Source Code field on the Registration Page)</p>
<p>Spots are limited for the Webinar and the second round is closing soon so Register for the Webinar right now.</p>
<p>If you haven&#8217;t watched the short video yet we urge you to do so at:</p>
<p><a href="http://www.gozonegateway.com/go-zone-property/ocean-springs.html" target="_blank">http://www.gozonegateway.com/go-zone-property/ocean-springs.html</a></p>
]]></content:encoded>
      <wfw:commentRss>http://www.gozonegateway.com/articles/nov-22-go-zone-newsletter/feed/</wfw:commentRss>
      <slash:comments>0</slash:comments>
      <enclosure url="http://podcasts.odiogo.com/get_mp3.mp3?f=/go-zone-gateway/GO_Zone_Gateway-GO_Zone_Newsletter_1122.mp3" length="1376407" type="audio/mpeg" />
    </item>
    <item>
      <title>GO Zone Newsletter 10/13</title>
      <link>http://www.gozonegateway.com/articles/october-13-go-zone-newsletter/</link>
      <comments>http://www.gozonegateway.com/articles/october-13-go-zone-newsletter/#comments</comments>
      <pubDate>Sun, 12 Oct 2008 17:41:06 +0000</pubDate>
      <dc:creator>admin</dc:creator>
      <category><![CDATA[Articles]]></category>
      <guid isPermaLink="false">http://www.gozonegateway.com/?p=62</guid>
      <description>The following is a copy of the newsletter that we sent out on October 13, 2008.
With the lack of positive news in the credit markets, turmoil in the stock markets, and government bailouts for Wall Street, the average investor has taken it on the chin. With the government handing out money to Wall Street CEOs [...]&lt;br&gt;&lt;a type="audio/mpeg" href="http://podcasts.odiogo.com/get_mp3.mp3?f=/go-zone-gateway/GO_Zone_Gateway-GO_Zone_Newsletter_1013.mp3"&gt;Click here to play&lt;/a&gt;&lt;br&gt;</description>
      <content:encoded><![CDATA[<p><a href="http://www.gozonegateway.com/wp-content/uploads/2008/10/damagedhouse.jpg"><img class="alignleft size-medium wp-image-259" style="border: 0pt none; margin: 10px;" title="damagedhouse" src="http://www.gozonegateway.com/wp-content/uploads/2008/10/damagedhouse-300x190.jpg" alt="" width="300" height="190" /></a>The following is a copy of the newsletter that we sent out on October 13, 2008.</p>
<p>With the lack of positive news in the credit markets, turmoil in the stock markets, and government bailouts for Wall Street, the average investor has taken it on the chin. With the government handing out money to Wall Street CEOs and institutions it would be nice if the small investor on Main Street could get one of these bailouts.</p>
<p>What if there was a way for you to get $73,000 from the government to invest in the #1 Real Estate Market in the U.S.? To good to be true you say? Well the government has already released millions of dollars to every-day investors like you in the first round of the <a href="http://www.gozonegateway.com/srap/">Small Rental Assistance Program</a> and in 48 hours (after one year of waiting) they are opening up the second round. If the government is giving away Billions to Wall Street fat cats, you should get in line on one of the rare opportunities when they offer it out to small Main Street investors as well.</p>
<p>We have spent over a year putting this project together and are giving our investors the first chance at it this week. It will open for reservation on Wednesday October 15th, 2008 at 1pm Eastern time when the Government opens the application process to this program. After this week, we are going to release this opportunity to our national network of brokers and expect it to sell-out within a few weeks. We even have an opportunity available on a limited number of units that is completely contingent upon approval to the government program!</p>
<p>Your investment could yield a 270.4% instant return thanks to this program. If you have $27,000 dollars to invest, you could without risk, get a return of $73,000!</p>
<p>We already have had successful history with this program, as we had over 70 investors get approvals in the first round.</p>
<p>In addition to this awesome government program this investment is in the <a href="http://www.gozonegateway.com">GO Zone</a> and is eligible for HUGE Federal Tax Benefits known as <a href="http://www.gozonegateway.com/depreciation/">Bonus Depreciation</a>.  The GO Zone can help you save tens of thousands and maybe even hundreds of thousands of dollars in federal income tax. We provide complimentary consultations with our 33 year veteran CPA to maximize your tax benefit. DO NOT dismiss this Bonus Depreciation Benefit! Most investors invest in the GO Zone just for this benefit alone!  You owe it to yourself to find out exactly how much you will save in taxes, so take advantage of the complimentary one-on-one consultation.</p>
<p>In this financial market, there could not be a better opportunity to put your money into, because the risk is removed from the equation. Have you ever seen an opportunity where the U.S. Government pays 54% annually for 5 years up front? You will probably never see it again in our lifetime.</p>
<p>This is a first come first serve basis for the <a href="http://www.gozonegateway.com/srap/">SRAP</a>, and we expect to sell out this project within weeks, so do not hesitate to contact us at 561-404-7375. We expect you to have questions and urge you to call us with them.</p>
<p>Most people are lucky to get any kind of a positive return in this environment so don&#8217;t miss your chance.</p>
<p>We also have a complete due diligence package completed for you to review by <a href="http://www.gozonegateway.com/go-zone-property/ocean-springs.html">clicking here</a>.</p>
]]></content:encoded>
      <wfw:commentRss>http://www.gozonegateway.com/articles/october-13-go-zone-newsletter/feed/</wfw:commentRss>
      <slash:comments>0</slash:comments>
      <enclosure url="http://podcasts.odiogo.com/get_mp3.mp3?f=/go-zone-gateway/GO_Zone_Gateway-GO_Zone_Newsletter_1013.mp3" length="1688484" type="audio/mpeg" />
    </item>
  </channel>
</rss>
<!-- 165352 -->
<!-- Generated by Odiogobot V5.309 / http://www.odiogo.com -->
