<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:wfw="http://wellformedweb.org/CommentAPI/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:sy="http://purl.org/rss/1.0/modules/syndication/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/">
  <channel>
    <title>My Weight Loss Boot Camp - Podcasts powered by Odiogo</title>
    <atom:link href="http://myweightlossbootcamp.com/feed/" rel="self" type="application/rss+xml" />
    <link>http://myweightlossbootcamp.com</link>
    <description>
    </description>
    <lastBuildDate>Fri, 11 May 2012 16:19:38 +0000</lastBuildDate>
    <language>en</language>
    <sy:updatePeriod>hourly</sy:updatePeriod>
    <sy:updateFrequency>1</sy:updateFrequency>
    <generator>http://wordpress.org/?v=3.3.2</generator>
    <item>
      <title>Body Sculpting</title>
      <link>http://myweightlossbootcamp.com/conversation/body-sculpting/</link>
      <comments>http://myweightlossbootcamp.com/conversation/body-sculpting/#comments</comments>
      <pubDate>Wed, 18 Apr 2012 13:44:13 +0000</pubDate>
      <dc:creator>bootcamp</dc:creator>
      <category><![CDATA[Conversation]]></category>
      <guid isPermaLink="false">http://myweightlossbootcamp.com/?p=168</guid>
      <description>&lt;p&gt;I was on the elliptical machine at the gym yesterday and on the t.v. was an infomercial for some exercise cd&amp;#8217;s.  Being a fitness trainer I know that it takes a very long time to get the ripped muscles those models have for the commercial and what kills me is that they show clients these [...]&lt;br&gt;&lt;a type="audio/mpeg" href="http://podcasts.odiogo.com/get_mp3.mp3?f=/my-weight-loss-boot-camp/My_Weight_Loss_Boot_Camp-Body_Sculpting.mp3"&gt;Click here to play&lt;/a&gt;&lt;br&gt;</description>
      <content:encoded><![CDATA[<p>I was on the elliptical machine at the gym yesterday and on the t.v. was an infomercial for some exercise cd&#8217;s.  Being a fitness trainer I know that it takes a very long time to get the ripped muscles those models have for the commercial and what kills me is that they show clients these pictures and the clients think &#8220;YES!  I want to look like that in 30 days!&#8221;</p>
<p>It&#8217;s not going to happen in 30 days unless you are already lean and spend hours in the gym every day lifting weights.</p>
<p>I want to let people know that yes, you can absolutely have great sculpted muscles but give your self a realistic time period in which to do so.</p>
<p>If you have extra weight on your frame you can be eating better and working out aerobically to burn calories and be lifting weights at the same time.  Once your body burns off enough of the fat you will see those toned muscles.  Plus muscle burns more calories during the course of the day so you want to be muscle building while dieting.</p>
<p>But please, don&#8217;t give up on your workouts or yourself when you don&#8217;t immediately see yourself turning into a super sculpted already beefed up model.</p>
<p>Keep Going!!!!!  Stick with us here and get it done.</p>
]]></content:encoded>
      <wfw:commentRss>http://myweightlossbootcamp.com/conversation/body-sculpting/feed/</wfw:commentRss>
      <slash:comments>0</slash:comments>
      <enclosure url="http://podcasts.odiogo.com/get_mp3.mp3?f=/my-weight-loss-boot-camp/My_Weight_Loss_Boot_Camp-Body_Sculpting.mp3" length="633044" type="audio/mpeg" />
    </item>
  </channel>
</rss>
<!-- 319669 -->
<!-- Generated by Odiogobot V5.309 / http://www.odiogo.com -->
