<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-15">
	<title>  </title>
	<style type="text/css">
	<!--
		body {
			background-color: #FFFFFF;
			color: #FFFFFF;
			font-size: 12;
			margin: 0;
			font-family:  Tahoma, Verdana, Arial;
		}
	//-->
	</style>
	</head>
<body>
<center>
<style type="text/css">
#ad-cfcd br {
		display: none;
}
</style>
<table height="102" id="ad-cfcd">
<tr>
<td height="102">
<iframe src="http://ads.webme.com/banner.php?pos=bw" frameborder="0" width="728" height="90" scrolling="no"></iframe></td>
</tr>
</table>
	<table height="400">
		<tr>
			<td>
				<center>
<link rel="shortcut icon" href="http://mrweed.mr.funpic.de/funchfun/images/funchfunicon.ico" type="image/x-icon">

<!-- saved from url=(0014)about:internet -->
<title>00000001</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"> <!--Fireworks 8 Dreamweaver 8 target.  Created Fri Oct 28 00:40:06 GMT+0200 2011-->   <img height="950" border="0" width="790" name="n00000001" src="http://funchfun.fu.funpic.de/images/funchfunhompage.png" id="n00000001" usemap="#m_00000001" alt="" /><map name="m_00000001" id="m_00000001">
<area shape="rect" coords="272,486,533,578" href="http://www.myvideo.de/Community/Mitglieder/Profil?searchMember=8274045" alt="" />
<area shape="rect" coords="272,586,533,678" href="http://www.clipfish.de/user/funchfun" alt="" />
<area shape="rect" coords="272,291,533,383" href="http://twitter.com/Funchfun" alt="" />
<area shape="rect" coords="272,193,533,285" href="http://funchfun.piranho.de/" alt="" />
<area shape="rect" coords="272,95,533,187" href="http://funchfun.de.tl/Home.htm" alt="" />
<area shape="rect" coords="272,390,533,482" href="http://www.youtube.com/user/Funchfun" alt="" />  </map>   </meta>
    <br />
    <br />
    <a href="/Home.htm" style="color:#000000;font-size:12px;background-color:#FFFFFF;">
        Weiter
    </a>
    <br />
    <br />
    <br />				</center>
			</td>
		</tr>
	</table>
</center>
                                                                                                                                                                                                                                                                                                                                                                                                                                <script type="text/javascript" src="http://ads.webme.com/layer.php"></script></body>
</html>
