<?xml version="1.0" encoding="ISO-8859-1" ?>    
<rss version="2.0">

    <channel><title>Storrys, Shitts und Audio-Müll</title>
    <description>Jetzt Sakki´s Podcast abonnieren - sich von der samtweichen, charismatischen Stimme verwöhnen lassen. - in den Bann seiner abstrus-ekligen und doch einzigartig schönen Poesie geraten - hecheln blasen wichsen fummeln grabbeln bohrn ritzen schlitzen spritzen (online) - ein Mikrokosmos aus uriger Sprachmagie, Wahnsinn und Gas – gebt´s Euch das! - Melodien für Millionen. Melodien für Melonen. Melons...</description>
    <link>http://www.sachs.netestate.de</link>
    <lastBuildDate>Thu, 07 Jun 2012 03:06:30 +0200</lastBuildDate>
    <language>de-de</language>
    <copyright>Tammo Sachs 2012</copyright>
    <generator>1.1</generator>
    <atom:link rel="self" type="application/rss+xml" title="Storrys, Shitts und Audio-Müll" href="http://www.sachs.netestate.de/psp/getpodcast.cgi" xmlns:atom="http://purl.org/atom/ns#" />
    
        <item><title>Ein Gespräch mit Michel Houellebecq</title><link>http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Elohim.mp3</link><description>Wir erbauen die neue Botschaft  Ihre Pfeiler und Säulengänge   Das neue Jerusalem   Elohim </description><author>Tammo Sachs</author><enclosure url="http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Elohim.mp3" length="1837765" type="audio/mpeg" /><pubDate>Thu, 27 Oct 2005 18:38:36 +0200</pubDate></item>
        
        <item><title>TSGP fun call at the Reichskanzlei</title><link>http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-I_want_to_talk_to_Hitler,_please_..._!.mp3</link><description>TammoSachsGagProductions   presents  "Wie ich Hitler aus einem Meeting holte und vollrülpste"  </description><author>Tammo Sachs</author><enclosure url="http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-I_want_to_talk_to_Hitler,_please_..._!.mp3" length="3240854" type="audio/mpeg" /><pubDate>Thu, 03 Nov 2005 18:51:07 +0200</pubDate></item>
        
        <item><title>... und sie hatten meine Gesicht!</title><link>http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Cheddar-Flies.mp3</link><description>Im stickigen Dunkel des Schranks  naschten die Fliegen ...  (FFB, 1995)</description><author>Tammo Sachs</author><enclosure url="http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Cheddar-Flies.mp3" length="670471" type="audio/mpeg" /><pubDate>Fri, 04 Nov 2005 19:41:18 +0200</pubDate></item>
        
        <item><title>Meilen- und Grundstein Sachs´schen Wortwitzes</title><link>http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Masters_of_the_Universe.mp3</link><description>Und so einfach geht´s:  Man nehme - 1 blöd klingenden Namen einer Comic-/TV etc. Figur - hänge einen typisch deutschen, auf jedenfalls nicht in näherem Zusammenhang stehenden Zweit-/Nachnamen daran - verstelle die Stimme beim Aufsagen Und schon ist Heiterkeit entfacht (man achte auf "Justus ´Kikakela´ Müller" ...)!!!  Viel Spass!  (FFB, 1984)</description><author>Tammo Sachs</author><enclosure url="http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Masters_of_the_Universe.mp3" length="2916480" type="audio/mpeg" /><pubDate>Fri, 04 Nov 2005 19:56:16 +0200</pubDate></item>
        
        <item><title>X-Ray-3 im Todeskampf</title><link>http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Larry_Brent_Hoerspiel.mp3</link><description>Der tapfere Top-Agent der PSA, der Psychoanalytischen Spezial-Abteilung (äääh, wieso eigentlich "psychoanalytisch"?)in seinem hoffnungslosestem Fall - im "Keller von Gebhardt Kraushaar" ...  EUROPA-HÖRSPIEL EDITION</description><author>Tammo Sachs</author><enclosure url="http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Larry_Brent_Hoerspiel.mp3" length="2390016" type="audio/mpeg" /><pubDate>Thu, 10 Nov 2005 17:28:55 +0200</pubDate></item>
        
        <item><title>Meister Yoda is gar nich gut drauf ...</title><link>http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-STAR_WARS.mp3</link><description> "Immer Yoda hat gesagt: hütet Euch vor der HARZIGEN Seite der Macht ... !"  hear how Obi Wan Kenobi gets fucked!</description><author>Tammo Sachs</author><enclosure url="http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-STAR_WARS.mp3" length="1603461" type="audio/mpeg" /><pubDate>Sat, 12 Nov 2005 19:27:11 +0200</pubDate></item>
        
        <item><title>Gimmicks, Gags und Grundschul-Terror</title><link>http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Im_YPS-Club.mp3</link><description>Von der vielzitierten "guten alten Zeit" zu sprechen wäre sicher übertrieben, dennoch spielte diese "Zeitschrift" mit ihrem billigen Platikschrott und noch billigeren "Comics" eine zentrale Rolle bei Sakkis Sozialisation - nicht zuletzt durch das TERRORREGIME im YPS-CLUB des Axel "Ak" Schneider, einem Vorläufer der AL QUAIDA. Denn auch wir sollten kämpfen und, wenns sein musste: Für YPS sterben ... </description><author>Tammo Sachs</author><enclosure url="http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Im_YPS-Club.mp3" length="6334171" type="audio/mpeg" /><pubDate>Sun, 20 Nov 2005 18:58:58 +0200</pubDate></item>
        
        <item><title>eine wirklich wahre Geschichte </title><link>http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Panshen_Lama.mp3</link><description>Gibt es ihn wirklich?  Oder ist er nur eine Legende?  Am PANSCHEN LAMA scheiden sich die Geister! Doch hört selber, was dieser wohl geheimnisvollste aller irdischen Götter dazu zu sagen hat ...   </description><author>Tammo Sachs</author><enclosure url="http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Panshen_Lama.mp3" length="820453" type="audio/mpeg" /><pubDate>Sun, 20 Nov 2005 19:34:14 +0200</pubDate></item>
        
        <item><title>und wie er die Djzschinsn fand !</title><link>http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-ARAFAT.mp3</link><description>Arafat  the Tschinsn saw and a  KWÄSTSCHN  formte ... DAS ORIGINAL!  (noch Fragen???) </description><author>Tammo Sachs</author><enclosure url="http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-ARAFAT.mp3" length="1105501" type="audio/mpeg" /><pubDate>Wed, 30 Nov 2005 21:02:29 +0200</pubDate></item>
        
        <item><title>Das Klagen der Ostdeutschen am Biertisch ...</title><link>http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Schaumburger.mp3</link><description>Zwei frustrierte ehemalige Mitarbeiter der VEB "Stinkmorchel" Dresden lassen mal ordentlich Dampf ab ... muss auch mal sein!   </description><author>Tammo Sachs</author><enclosure url="http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Schaumburger.mp3" length="1549373" type="audio/mpeg" /><pubDate>Sun, 04 Dec 2005 21:08:15 +0200</pubDate></item>
        
        <item><title>... mit Stargast James Hetfield / Metallica !</title><link>http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Guitar_Workshop_I_-_Heavy_Metal.mp3</link><description>JETZT NEU!  Start der Serie "Guitar Workshop" - DAS ideale Tool zum erfolgreichen Studium der wichtigsten Gitarren-Stile!   - Lern mit dem rennommierten Lehrer Brian die elementaren Spielrichtungen (nur seine ... Körperausdünstungen sind ... gewöhnungsbeduerftig!)  - Übt mit internationalen Stars aus der Gitarren-Szene (zum Auftakt: Metal-Gott James Hetfield/Metallica)   - Am Ende jeder Session seid ihr fit für einen richtig geilen SONG - zum live-Mitspielen! (diesmal: "Altar of Sacrifice" von Slayer)   Viel Spass beim Lernen!  </description><author>Tammo Sachs</author><enclosure url="http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Guitar_Workshop_I_-_Heavy_Metal.mp3" length="6790999" type="audio/mpeg" /><pubDate>Wed, 07 Dec 2005 18:45:45 +0200</pubDate></item>
        
        <item><title>Dt. Übersetzung von Slayers "Angel of Death"</title><link>http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Todesengel.mp3</link><description>Er war - und ist - der kontroverseste und gleichzeitig bekannteste Song der Gruppe, opener des all-time-trash-metal-masterpieces "Reign in Blood" - trotz, oder vielmehr WEGEN der gory lyrics welche die Bestialitäten des KZ-Arztes Josef Mengele zum Inhalte haben (Originaltext: Jeff Hanneman).  Die Presse wurde nicht müde, dem Quartett fortan Nazi-Attitüde und Gewaltverherrlichung zu unterstellen, letzteres natürlich zu recht.  Für T. Sax, einem der größten Slayer-Fans unter der Sonne Klaiforniens, jedoch, ist es vor allem eines: Poesie.  Ja.  Deshalb hat er den kühnen, wenn nicht un-möglichen Versuch unternommen, das un-sagbare sogar in eine entsprechend klingende, dem Original in Metrik und Wucht in nichts nachstehende Fassung zu giessen.  Und dem vorurteilsfeien Hörer wird es vielleicht ehrlicher klingen als so manch didaktisch-leiernder TV-Dokumentar-Bericht zu dem Thema (wenn es sich Sax auch hier nicht hat verkneifen könne, im Mittelteil, eigene groteske humoristische Elemente miteinzubinden) ... </description><author>Tammo Sachs</author><enclosure url="http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Todesengel.mp3" length="2125321" type="audio/mpeg" /><pubDate>Fri, 23 Dec 2005 20:50:07 +0200</pubDate></item>
        
        <item><title>... mit bluesy Bluesman Bama aus New Orleans</title><link>http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Guitar_Workshop_II_-_Blues____.mp3</link><description>Endlich!  Teil 2 unseres GUITAR WORKSHOPS - diesmal zum Thema Blues-Gitarre! Begleitet Euren persönlichen Guitar-Lehrer Brian ins Mississippi-Delta von New Orleans und erlebt BLUES-HISTORY hautnah - dazu spielt Bluegrass-Sklave BAMA seinen charakteristischen Shuffel-Blues, den ihr natürlich wieder sofort und kinderleicht erlernen könnt.  Brian gibt wie gewohnt Hilfestellungen ... nicht zuletzt mit Hilfe seines Darms!  Also nichts wie reingehört in dieses einzigartige musikalische Baumwollfeld - und für bluesy feeling ist gesorgt!</description><author>Tammo Sachs</author><enclosure url="http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Guitar_Workshop_II_-_Blues____.mp3" length="5662928" type="audio/mpeg" /><pubDate>Thu, 12 Jan 2006 22:18:01 +0200</pubDate></item>
        
        <item><title>feat. Umbesi - balla - balla </title><link>http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-The_Magic_of_the_Trullala.mp3</link><description>The magic of the Trullala. Unleash the magic Trullala. The Power of the Pullemann. The Trullala!   Ritueller Gesang der sambesischen Umbesi </description><author>Tammo Sachs</author><enclosure url="http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-The_Magic_of_the_Trullala.mp3" length="1576959" type="audio/mpeg" /><pubDate>Sun, 29 Jan 2006 21:05:24 +0200</pubDate></item>
        
        <item><title>Eine Hommage an das bekannteste YPS-Gimmick</title><link>http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Die_Urzeitkrebse_von_YPS.mp3</link><description>Wer hatte sie nicht? Aus verkrusteten krümeligen Eiern, die aus dem Grossen Salzssee des US-Bundesstaates Utah (!) entnommen wurden, schlüpfte ... LEBEN! Diese mikroskopisch kleinen Scheissehaufen von Piss-Krebsen verkörperten, ja WAREN YPS! Und erstand man auch noch das nächste Gimmick (Richtig: "Das Futter für deine Urzeitkrebse"!), wuchsen sie sogar auf stattliche 1,5 Zentimeter und nahmen die Form lebenden Spermas an! Die ersten (und, waren sie erstmal in lauwarmer Salz-Lake verreckt: meistens auch letzten)Haustieren im Leben eines Heranwachsenden! Ohne Zweifel ganz grosser "Mittelstrahl" aus dem Hause YPS! </description><author>Tammo Sachs</author><enclosure url="http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Die_Urzeitkrebse_von_YPS.mp3" length="1283552" type="audio/mpeg" /><pubDate>Mon, 13 Mar 2006 09:26:46 +0200</pubDate></item>
        
        <item><title>Bayerische Mundart von A wie Arschficker bis O wie Oarschficker...</title><link>http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Bayerisch_von_A_bis_Zett_-_Kursus.mp3</link><description>Starten Sie durch! Bayerisch in in! Charmant und deftig führt Sie GUSTL BAYRHAMMER durchs Programm und bringt Ihnen die schönsten bajuwarischen Ausdrücke bei ... nur Edmund Stoiber kanns noch besser! </description><author>Tammo Sachs</author><enclosure url="http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Bayerisch_von_A_bis_Zett_-_Kursus.mp3" length="5233767" type="audio/mpeg" /><pubDate>Mon, 27 Mar 2006 00:21:51 +0200</pubDate></item>
        
        <item><title>Neues aus Deutschland, Europa und den Palästinensergebieten</title><link>http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Nachrichten_2.April_2005.mp3</link><description>Informiert sein. Aktualisiert sein. Pikiert sein.   Das alles ab jetze bei SAKKIS News-Pods.  Satirische Aufarbeitung des aktuellen Tagesgeschehen für jung und alt, klug und dumm, stock und schwul.   Sax-Nachrichten ... und die Welt steht plötzlich still!</description><author>Tammo Sachs</author><enclosure url="http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Nachrichten_2.April_2005.mp3" length="5361579" type="audio/mpeg" /><pubDate>Sun, 02 Apr 2006 18:59:34 +0200</pubDate></item>
        
        <item><title>Die Ente mit dem Kribbelsack </title><link>http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Schorsche_Duck_Show.mp3</link><description>Wer kennt ihn nicht? Schorsche Duck, assozialer Spross aus Entenhausen, sorgt wieder für Furore. In seiner eigenen Show hat er zwar noch mit einigen Problemen zu kämpfen, aber ist auf dem besten Wege, seinen exorbitanten KRIBBELSACK bald auch einem - im wahrsten Sinne des Wortes - breiteren Publikum zu öffnen.   Check out the ENTENQUATSCH! Quak Quak!</description><author>Tammo Sachs</author><enclosure url="http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Schorsche_Duck_Show.mp3" length="2545788" type="audio/mpeg" /><pubDate>Sun, 13 Aug 2006 22:02:19 +0200</pubDate></item>
        
        <item><title>Besinnliches zum Jahresrückblick 2006</title><link>http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Weihnachtsansprache_des_Bundespraesidenten_Horst_Koehler.mp3</link><description>Heinz Köhler, der "unbequeme" Präsident, findet auch an Heilig Abend 2006 wieder heiter-mahnende Worte für die Bevölkerung.  </description><author>Tammo Sachs</author><enclosure url="http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Weihnachtsansprache_des_Bundespraesidenten_Horst_Koehler.mp3" length="2008030" type="audio/mpeg" /><pubDate>Sun, 24 Dec 2006 18:34:29 +0200</pubDate></item>
        
        <item><title>Ein Klassiker aus dem Jahre 1992</title><link>http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Pitbullterrier.mp3</link><description>Chris Howland erzählt und schwelgt in Erinnerungen an eine besondere Hunderasse...</description><author>Tammo Sachs</author><enclosure url="http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Pitbullterrier.mp3" length="3027695" type="audio/mpeg" /><pubDate>Sun, 31 Dec 2006 14:47:40 +0200</pubDate></item>
        
        <item><title>gesponsort vom YPS - vom Teufel verführt</title><link>http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Geheimagent.mp3</link><description>Schnell erkannte ich, dass die lustigen YPS-Agenten-Gimmicks wirklich nur Kinderkacke waren und ich begann sofort mit gezielten Terror-Anschläge auf meine damals noch kindliche Umwelt ... doch hört selbst! </description><author>Tammo Sachs</author><enclosure url="http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Geheimagent.mp3" length="1458844" type="audio/mpeg" /><pubDate>Sun, 04 Feb 2007 20:10:17 +0200</pubDate></item>
        
        <item><title>Hier treffen sich gays aus deinem ... äh ... Freundeskreis </title><link>http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Betonmischer.mp3</link><description>Höhepunkt eines jeglichen Besäufnisses zur damaligen "Kreis-Zeit" (FFB 1990-96) war der sog. "Betonmischer", bei dem sich die - ausschließlich männlichen - Trunkenbolde auf Kommando, einer Früh-Form des Homo-Wrestlings nicht unähnlich, auf-, über- und untereinander wälzten, wobei es nicht selten zu Verletzungen kam. Gemeinschaftsbildende Suff-Euphorie oder doch verklemmter homo sex ? - wir werden es wohl nie erfahren.   Na dann. BRILLEN AB ZUM BETONMISCHER! </description><author>Tammo Sachs</author><enclosure url="http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Betonmischer.mp3" length="200332" type="audio/mpeg" /><pubDate>Sun, 04 Feb 2007 22:00:07 +0200</pubDate></item>
        
        <item><title>Günther Jauch in Nöten</title><link>http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Wer_wird_Millionaer.mp3</link><description>Oder warum Dieter Marchlewski aus Berlin den sonst so besonnenen Showmaster zur Weißglut trieb</description><author>Tammo Sachs</author><enclosure url="http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Wer_wird_Millionaer.mp3" length="1798477" type="audio/mpeg" /><pubDate>Wed, 21 Feb 2007 21:24:08 +0200</pubDate></item>
        
        <item><title>Der Song zur Welle</title><link>http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Tsunami.mp3</link><description>Ich seh den Tsunami - Die Welle ist schon riesengroß Aber Angst, die habe ich nicht! Denn ich bin wasserdicht.  Da kommt der Tsunami - Die erste Welle bäumt sich auf Ich stehe auf und geh unter Deck,  Sonst ist mein Bierse weg.  Erst ging das Meer, dann kam es wieder Und riss ne ganze Menge nieder Es wurde nass und immer nasser Der schöne Urlaub fiel ins Wasser!  Verfickter Tsunami - Wo ist denn jetzt mein Bierse hin? Aber, ey, wen kümmert das Schon! Ich habe Vollpension!  Ich liebe Tsunamis - Sie hauen alles kurz und klein Egal ob Touris, ob Thais,  Das kümmert sie nen Scheiss  Ich lag am Strand von Khao Lak Die Sonne schien mir auf den Sack Die Sonne schien mir auf die Hoden Doch dann erkannt ich diese WOGEN!  </description><author>Tammo Sachs</author><enclosure url="http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Tsunami.mp3" length="786570" type="audio/mpeg" /><pubDate>Tue, 27 Feb 2007 21:02:38 +0200</pubDate></item>
        
        <item><title>sakkis mystic masterpiece</title><link>http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Bam_Chaou_I_Babu.mp3</link><description>Orientalische, ja hypnotische Klänge mit druckvollem groove, unterlegt mit wahnwitzigen samples und echtem sakkarabisch. Geniessen Sie dieses einzigartige Meisterwerk am besten ... äh ... bekifft!</description><author>Tammo Sachs</author><enclosure url="http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Bam_Chaou_I_Babu.mp3" length="4359812" type="audio/mpeg" /><pubDate>Thu, 01 Mar 2007 21:41:16 +0200</pubDate></item>
        
        <item><title>Ich schwöre, ich habs versucht ... doch so einfach ist das nicht</title><link>http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Arbeitslos.mp3</link><description>Chilliger sound zum aktuellen Reizthema.  Relaxter kann man wohl den Hartz VI Antrag nicht ausfüllen ... und mehr Autobahnen brauchen wir auch nicht wirklich, oder?  DENY - DELAY - DO NOTHING  </description><author>Tammo Sachs</author><enclosure url="http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Arbeitslos.mp3" length="1985787" type="audio/mpeg" /><pubDate>Sun, 04 Mar 2007 20:35:15 +0200</pubDate></item>
        
        <item><title>von den Klöthentaler Klötenknakkern</title><link>http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Volksmusik.mp3</link><description>ein neuer Hit - und sogar mal was kritisches. Ich kann also nicht NUR über Scheisse schreiben, hahahaaa ... ein Ska-Ohrwurm vom Feinsten. SOFORT ANHÖREN UND MITSINGEN!   Wir sind die Kastelruter Spatzen Und spatzengross ist unser Hirn Doch wir verdienen einen Batzen Vielen Dank, Ihr armen Irren!  Wir sind die echten Schürzenjäger Und kommen aus dem Zillertal Wir wissen: Volksmusik ist mega-  populär und scheiss-egal!  Grüss Gott im Musikanten-Stadl Erkennen Sie die Melodie? Millionen Zuschauer die haben Doch Geschmack, ich BITTE Sie ...! </description><author>Tammo Sachs</author><enclosure url="http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Volksmusik.mp3" length="4503183" type="audio/mpeg" /><pubDate>Mon, 12 Mar 2007 09:50:55 +0200</pubDate></item>
        
        <item><title>Denn genau DICH wollen sie</title><link>http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Komm_zu_Scientology.mp3</link><description>Komm zu Scientology, denn genau dich wollen sie Bald beherrschen sie die Welt Mit einem Zauberstab Komm zu Scientology, join our philosophy  IMMER NOCH AKTUELL. Geht alle hin! Lern to know! Use your brain! Support SYNANON and the kalter Entzug! Lick the balls of Tom Cruise and the Eier of Travolta!  Yourz Grozzer Thetan.  </description><author>Tammo Sachs</author><enclosure url="http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Komm_zu_Scientology.mp3" length="2225631" type="audio/mpeg" /><pubDate>Tue, 20 Mar 2007 22:00:10 +0200</pubDate></item>
        
        <item><title>Ranjid teaches you a Hindu Song</title><link>http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Elephant_Dance.mp3</link><description>The elephants are very big And they have large ears So please let them DANCE Or they break down in tears  Come and see the real India!</description><author>Tammo Sachs</author><enclosure url="http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Elephant_Dance.mp3" length="3883638" type="audio/mpeg" /><pubDate>Sat, 24 Mar 2007 14:39:37 +0200</pubDate></item>
        
        <item><title>verursachen viele Probleme. Ein Gedicht</title><link>http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Autos.mp3</link><description>Topaktuell zur Tempolimit-Diskussion.  Oder doch nur gereimter Nonsens? Egal.  Die Lösung der Klimakatastrophe bleibt in der Familie und kommt am Schluss.</description><author>Tammo Sachs</author><enclosure url="http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Autos.mp3" length="772882" type="audio/mpeg" /><pubDate>Wed, 04 Apr 2007 23:00:38 +0200</pubDate></item>
        
        <item><title>Was viel und oft verschwiegen wird</title><link>http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Unterm_Bett.mp3</link><description>Biotope können manchmal näher sein als man denken mag.  In Spüle oder Kühlschrank, unter Achseln, in Wasserhähnen ... oder eben: Unterm Bett. Lecker!</description><author>Tammo Sachs</author><enclosure url="http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Unterm_Bett.mp3" length="654190" type="audio/mpeg" /><pubDate>Mon, 30 Apr 2007 00:00:49 +0200</pubDate></item>
        
        <item><title>vom Ende des größten dt.sprachigen Sängers</title><link>http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Falcos_letzte_Fahrt.mp3</link><description>...und wie es so ist, der Abgang der ganz großen ist meistens eine eher banale bis lächerliche Angelegenheit. So auch hier.</description><author>Tammo Sachs</author><enclosure url="http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Falcos_letzte_Fahrt.mp3" length="1919456" type="audio/mpeg" /><pubDate>Fri, 11 May 2007 13:57:57 +0200</pubDate></item>
        
        <item><title>Lernen Sie chinesisch schnell und effektiv ... mit Tammo Sachs</title><link>http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Chinesisch_mit_Sakki.mp3</link><description>Sakki gilt ohne Zweifel als grosses Sprachgenie. Deshalb will er Sie an DER kommenden Sprache - Chinesisch - teilhaben und lernen lassen. Schon bald werden Sie erstaunliche kulturelle Fortschritte erzielen.  TSAU NI MA !</description><author>Tammo Sachs</author><enclosure url="http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Chinesisch_mit_Sakki.mp3" length="1460492" type="audio/mpeg" /><pubDate>Sun, 13 May 2007 20:29:55 +0200</pubDate></item>
        
        <item><title>Ein historisch bizarres Tondokument zur Ära Schröder und Co.</title><link>http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Mord_im_Land_der_Koenige.mp3</link><description>Fast schon in Vergessenheit geraten: Die Herrschaft Gehardt "Acker" Schröders (1998 - 2005). Dieser flotte Rap-Song aus dem Jahre 1998 (!) läßt noch einmal die vor-Bundestagswahl-igen SPD-internen Machtkämpfe der ebenso glorreichen wie machgeilen TROIKA um Schröder, Lafontaine und - schon fast vergessen - Rudolf "Ziege" Scharping in einer grotesken und drogenumnebelten Story Revue passieren. Echt lustig ... </description><author>Tammo Sachs</author><enclosure url="http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Mord_im_Land_der_Koenige.mp3" length="4167808" type="audio/mpeg" /><pubDate>Mon, 21 May 2007 10:20:15 +0200</pubDate></item>
        
        <item><title>Auf bayerisch: I wui hoam nach Tschernobyl</title><link>http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Ich_will_heim_nach_Tschernobyl.mp3</link><description>Coverversion des STS-Klassikers "Fürstenfeld" mit radioaktivem Text. Tja. Man ist halt in der 80ern gross geworden ... a tribute to the ukrain rain.</description><author>Tammo Sachs</author><enclosure url="http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Ich_will_heim_nach_Tschernobyl.mp3" length="2146012" type="audio/mpeg" /><pubDate>Wed, 23 May 2007 16:20:40 +0200</pubDate></item>
        
        <item><title>Audiocollage frei nach Edward Munch</title><link>http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Der_Schrei.mp3</link><description>was heißt hier Collage! Ich habe nur EINMAL geschnitten! Also los, reinhören, staunen und MITMACHEN!  Denn lautstarker Protest tut immer gut und erleichtert! Attac it!</description><author>Tammo Sachs</author><enclosure url="http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Der_Schrei.mp3" length="1709620" type="audio/mpeg" /><pubDate>Wed, 30 May 2007 13:55:38 +0200</pubDate></item>
        
        <item><title>Was ist moshen? Ein ananrchischer Telefonstreich aus Kindertagen</title><link>http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Telefeze.mp3</link><description>Zugegeben, nicht sonderlich originell.  Aber uns, d.h. mir und meinem damaligen Yps-Kumpel Ak Schneider, hats ne Menge Spass gemacht. Nur das ewige Hörer-an-den-Kassettenrekorder-Halten war auf Dauer etwas anstrengend ...</description><author>Tammo Sachs</author><enclosure url="http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Telefeze.mp3" length="3561360" type="audio/mpeg" /><pubDate>Fri, 01 Jun 2007 14:43:44 +0200</pubDate></item>
        
        <item><title>Mit Vertretern aller Fraktionen ...</title><link>http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Grosse_Klima-Diskussion.mp3</link><description>Jetze im Sakki-Blog: UNSER KLIMA GEHT ALLE AN! Meinungen, Streitigkeiten, Lösungsvorschläge ... Bis plötzlich ein veritabler Deus Ex Machina auf den Plan tritt ... Wolfgang Schäuble ... (don't expect too much .. .. .. ;-)  </description><author>Tammo Sachs</author><enclosure url="http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Grosse_Klima-Diskussion.mp3" length="4467503" type="audio/mpeg" /><pubDate>Mon, 09 Jul 2007 01:10:55 +0200</pubDate></item>
        
        <item><title>Ein ... Tabubruch.</title><link>http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-BIENEN_ESSEN_!.mp3</link><description>neu denken neues denken von problemen global akkurat ein  ver     such .  </description><author>Tammo Sachs</author><enclosure url="http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-BIENEN_ESSEN_!.mp3" length="942914" type="audio/mpeg" /><pubDate>Mon, 05 Nov 2007 02:14:29 +0200</pubDate></item>
        
        <item><title>Florian Silbereisen präsentiert die volkstümliche Kinder-Weihnacht</title><link>http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Weihnachten_mit_Florian_Silbereisen.mp3</link><description>Der junge Star der Volksmusik stellt vier Kinder aus verschiedenen Ländern mit ihren eigenen Gedichten für das Christkind vor. Einfach herzig, lustig und natürlich ... so macht die STAADE ZEIT allen Freude!</description><author>Tammo Sachs</author><enclosure url="http://www.sachs.netestate.de/psp/podcast/Tammo_Sachs-Weihnachten_mit_Florian_Silbereisen.mp3" length="5362859" type="audio/mpeg" /><pubDate>Mon, 03 Dec 2007 13:38:45 +0200</pubDate></item>
        </channel></rss>
    
    
