<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de">
<head>
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
<meta http-equiv="content-script-type" content="text/javascript" />
<meta http-equiv="content-style-type" content="text/css" />
<meta name="Language" content="de" />
<meta name="Keywords" content="WDR 2, wdr2, defaultError, fehlerseite, 404, NRW"/>
<meta name="Description" content="xxx"/>
<meta name="Author" content="WDR 2"/>
<meta name="DC.Rights" content="Nur WDR"/>
<meta name="Publisher" content="Westdeutscher Rundfunk" />
<meta http-equiv="expires" content="900" />
<meta name="DC.Date" content="2011-01-04T12:58+01:00" />
<meta name="robots" content="index,follow,noarchive" />
<link rel="start" href="http://www1.wdr.de/themen/" title="Startseite WDR.de" />
<link rel="bookmark" href="http://www.wdr.de/tv/" title="WDR Fernsehen" />
<link rel="bookmark" href="http://www.wdr.de/radio/" title="WDR Radioprogramme" />
<link rel="bookmark" href="http://www.wdr.de/themen/homepages/epg.jhtml" title="WDR Programmvorschau" />
<link rel="bookmark" href="http://www.wdr.de/unternehmen/" title="Informationen über das Unternehmen WDR" />
<link rel="bookmark" href="#wrapper" title="Zum Seitenanfang" />
<link rel="bookmark" href="#content" title="Zum Seiteninhalt" />
<link rel="bookmark" href="http://www1.wdr.de/themen/global/impressum/" title="Impressum" />
<link rel="search" href="http://www1.wdr.de/themen/suche/" title="Suche im WDR Online Angebot" />
<link rel="help" href="http://www1.wdr.de/themen/hilfe/" title="Hilfe zur Bedienung und Orientierung" />
<link rel="copyright" href="http://www1.wdr.de/themen/hilfe/urheberrecht102.html" title="Copyright" />
<link rel="icon" href="/resources/img/logos/favicon.ico" type="image/ico" />
<link rel="shortcut icon" href="/resources/img/logos/favicon.ico" type="image/ico" />
<link rel="stylesheet" href="/resources/css/basic.min.css" type="text/css" />
<!--[if gt IE 6 & lt IE 9]>
<link rel="stylesheet" href="/resources/css/global.min.css" type="text/css" />
<link rel="stylesheet" href="/resources/css/ie.min.css" type="text/css" />
<![endif]-->
<!--[if gte IE 9]>
<link rel="stylesheet" href="/resources/css/global.min.css" type="text/css" />
<![endif]-->
<!--[if !IE]> <-->
<link rel="stylesheet" media="all" href="/resources/css/global.min.css" type="text/css" id="cssGlobal" />
<link rel="stylesheet" href="/resources/css/map.css" type="text/css"/>
<!--> <![endif]-->
<script type="text/javascript">
<!-- <![CDATA[
var galleryObjArr = [];
document.writeln('<style type="text/css">@import "/resources/css/js.min.css";<\/style>');
// ]]> -->
</script>
<title>Fehler HTTP 404 - WDR 2 Der Sender</title>
</head>
<body>
<!--googleoff: index-->
<div id="wrapper">
<div id="bgImageCont">
<ul id="skipLinks">
<li><a href="#content">zum Inhalt</a></li>
<li><a href="#navigation">zur Navigation</a></li>
<li><a href="#search">zur Suche</a></li>
</ul>
<!--[if lt IE 7]>
<p id="ieAlert">
Lieber Nutzer,<br />
leider nutzen Sie eine veraltete Version Ihres Browsers. Deshalb können die an dieser Stelle vorgesehenen Inhalte nicht korrekt dargestellt werden. Bitte aktualisieren Sie auf eine aktuelle Version.
Unter <a href="http://www.browserchoice.eu/">http://www.browserchoice.eu/</a> stehen alternative Browser zur Verfügung.
Für eine Installation benötigen Sie gegebenenfalls Administrator-Rechte.</p>
</p>
<![endif]-->   <hr />
<div id="banner">
<img src="/resources/img/logos/wdr2.gif" alt="WDR 2" title="" id="wdr2Logo" />
<img src="/resources/img/logos/wdr2_banner.jpg" alt="WDR 2 Banner" title="" width="1000" height="80" id="wdr2Banner" />
</div>
<div class="printLocation" title="URL: http://www.wdr2.de/defaultError100.html">&nbsp;</div>
<hr/>
<p class="hidden">Sie befinden sich hier:</p>
<ul id="breadCrumb" class="">
<li><a href="http://www.wdr.de/radio">Radio</a></li>
<li><a href="/index.html">WDR 2</a></li>
<li>Fehler HTTP 404 <span class="hover">: Seite nicht gefunden</span></li>
</ul>
<!--googleon: index-->
<div id='content'>
<!-- wdr3.de -->
<hr/>
<div id="contentRow">
<div id="mainColumn">
<h1>
<span>
Fehler HTTP 404<span class="hidden">:</span>
</span>
Seite nicht gefunden
</h1>
<div class="pageContainer" id="page1">
<p>Liebe Nutzer, </p>
<p>leider ist die von Ihnen gewünschte Seite nicht verfügbar. Dies kann mehrere Ursachen haben. </p>
<p>Es könnte sein, dass wir den von Ihnen gesuchten Inhalt inzwischen aus dem Netz genommen haben. Dafür kann es verschiedene Gründe geben, zum Beispiel, dass ein Inhalt nicht mehr zutreffend ist oder dass bestimmte Rechte und Lizenzen am Inhalt abgelaufen sind. </p>
<p>Ein großer Teil an gelöschten Seiten ist auf die Bestimmungen des 12. Rundfunkänderungsstaatvertrags zurückzuführen. Dieses Gesetz, das seit dem 1.6.2009 in Kraft ist, schreibt uns unter anderem vor, unsere Inhalte nur noch zeitlich begrenzt anzubieten und sie danach ganz aus dem Netz zu nehmen. In diesen Fällen erhalten Sie also eine Fehlerseite.</p>
<p>Wenn Sie genauer wissen wollen, warum Sie diese Fehlerseite statt des gewünschten Inhalts sehen, dann schreiben Sie uns bitte eine Mail an warumweg@wdr.de mit einer möglichst konkreten Information darüber, welche Seite oder welchen Inhalt Sie gesucht haben.</p>
<p>Weitere grundsätzliche Informationen zum 12. Rundfunkänderungsstaatsvertrag finden sie hier:<br/><a href="http://www1.wdr.de/themen/medienseite/rundfunkstaatsvertrag100.html" title="12. Rundfunkänderungsstaatsvertrag: Das große Löschen">Informationen zum 12. Rundfunkänderungsstaatsvertrag</a></p>
<p>Wir bedauern, Ihnen die gewünschten Inhalte nicht mehr zur Verfügung stellen zu können. Für Ihr Interesse an unserem Internet-Angebot bedanken wir uns herzlich und hoffen, dass Sie uns trotzdem als Nutzer weiterhin treu bleiben.</p>
</div>
<hr/>
<p id="stand">Stand: 04.01.2011, 12.58 Uhr</p>
<hr/>

<div id="socialBookmarks">
<!--googleoff: index-->
<h2>Seite teilen</h2>
<ul>
<li>
<a href="http://de.facebook.com/sharer.php?u=http%3A%2F%2Fwww.wdr2.de%2FdefaultError100.html&amp;t=Fehler+HTTP+404%3A+Seite+nicht+gefunden" target="_blank" lang="en">
<img src="/resources/img/networks/facebook.gif" width="18" height="18" alt="" />
<span>Facebook</span>
<span class="hidden"> [Link &ouml;ffnet in neuem Fenster]</span>
</a>
</li>
<li>
<a href="http://twitter.com/home?status=http%3A%2F%2Fwww.wdr2.de%2FdefaultError100.html" target="_blank" lang="en">
<img src="/resources/img/networks/twitter.gif" width="18" height="18" alt="" />
<span>Twitter</span>
<span class="hidden"> [Link &ouml;ffnet in neuem Fenster]</span>
</a>
</li>
<li>
<a href="http://www.schuelervz.net/Link/ExternLink/Url/?u=http%3A%2F%2Fwww.wdr2.de%2FdefaultError100.html&amp;desc=Fehler+HTTP+404%3A+Seite+nicht+gefunden" target="_blank" lang="en">
<img src="/resources/img/networks/studi_vz.gif" width="18" height="18" alt="" />
<span>VZ-Netzwerke</span>
<span class="hidden"> [Link &ouml;ffnet in neuem Fenster]</span>
</a>
</li>
<li>
<a href="http://www.wer-kennt-wen.de/neues/gen?url=http%3A%2F%2Fwww.wdr2.de%2FdefaultError100.html&amp;title=Fehler+HTTP+404%3A+Seite+nicht+gefunden" target="_blank" lang="de">
<img src="/resources/img/networks/wer-kennt-wen.gif" width="18" height="18" alt="" />
<span>wer-kennt-wen</span>
<span class="hidden"> [Link &ouml;ffnet in neuem Fenster]</span>
</a>
</li>
<li>
<a href="http://del.icio.us/post?url=http%3A%2F%2Fwww.wdr2.de%2FdefaultError100.html&amp;title=Fehler+HTTP+404%3A+Seite+nicht+gefunden" target="_blank" lang="en">
<img src="/resources/img/networks/delicious.gif" width="18" height="18" alt="" />
<span>Delicious</span>
<span class="hidden"> [Link &ouml;ffnet in neuem Fenster]</span>
</a>
</li>
<li>
<a href="http://www.mister-wong.de/addurl/?bm_url=http%3A%2F%2Fwww.wdr2.de%2FdefaultError100.html&amp;bm_description=Fehler+HTTP+404%3A+Seite+nicht+gefunden" target="_blank" lang="en">
<img src="/resources/img/networks/mr_wong.gif" width="18" height="18" alt="" />
<span>Mister Wong</span>
<span class="hidden"> [Link &ouml;ffnet in neuem Fenster]</span>
</a>
</li>
</ul>
<p id="socialBookmarksHelp">
<a href="http://www.wdr.de/themen/global/bookmarks/hilfe.jhtml">
&Uuml;ber <span lang="en">Social Bookmarks</span>
</a>
</p>
<!--googleon: index-->
</div>
<hr/>
</div>
<!--googleoff: index-->
<div id="rightColumn">
<div class="teaserCont radioBox">
<ul class="boxSwitch">
<li id="a1-1" class="opened">
<h2>Jetzt im Programm</h2>
<div class="currentSongCont">
<!-- ajaxURL: /musik/playlist_neu100-akkordeon-playlist.html -->
<p>
<span class="colored">Jetzt läuft</span> <strong>Bruno Mars:</strong> Just The Way You Are
</p>
<p>
<a href="http://www.wdr2.de/musik/playlist116.html">Ausführliche Playlist und Titelsuche</a>
</p>
</div>
<div class="scrollContainer">
<!-- ajaxURL: /vorlagen/jetztimprogramm102-akkordeon-jetztimprogramm_wn-2.html -->
<table class="program" summary="Tabelle mit dem WDR 2 Programm von heute nach Uhrzeit">
<caption>WDR 2 Programm von heute</caption>
<thead>
<tr>
<th scope="col" id="jip-2-a1-1TimeId">Uhrzeit</th>
<th scope="col" id="jip-2-a1-1BroadcastId">Sendung</th>
</tr>
</thead>
<tbody>
<tr>
<th scope="row" headers="jip-2-a1-1TimeId">
00.03
<span class="hidden"> Uhr</span>
</th>
<td headers="jip-2-a1-1BroadcastId" >
<a href="http://www.wdr2.de/sendungen/ndr2undwdr2dienacht/index.html"><strong>NDR 2 und WDR 2: Die Nacht</strong></a>
</td>
</tr>
<tr>
<th scope="row" headers="jip-2-a1-1TimeId">
06.00
<span class="hidden"> Uhr</span>
</th>
<td headers="jip-2-a1-1BroadcastId" >
<a href="http://www.wdr.de/radio/home/nachrichten/index.phtml"><strong>Nachrichten, Wetter</strong></a>
</td>
</tr>
<tr>
<th scope="row" headers="jip-2-a1-1TimeId">
06.05
<span class="hidden"> Uhr</span>
</th>
<td headers="jip-2-a1-1BroadcastId" >
<a href="http://www.wdr2.de/sendungen/wdr2derfeiertag/derfeiertag100.html"><strong>WDR 2 Der Feiertag</strong></a>
<span class="subText">
mit
<a href="http://www.wdr2.de/moderatoren/simon100.html">Johannes Simon</a>
</span>
<img src="/musik/bildjohannessimon100_v-TeaserKlein.jpg"    title="Bildrechte: WDR" alt="Johannes Simon" height="82" width='146' />
</td>
</tr>
<tr>
<th scope="row" headers="jip-2-a1-1TimeId">
09.00
<span class="hidden"> Uhr</span>
</th>
<td headers="jip-2-a1-1BroadcastId" >
<a href="http://www.wdr.de/radio/home/nachrichten/index.phtml"><strong>Nachrichten, Wetter</strong></a>
</td>
</tr>
<tr>
<th scope="row" headers="jip-2-a1-1TimeId">
09.05
<span class="hidden"> Uhr</span>
</th>
<td headers="jip-2-a1-1BroadcastId" >
<a href="http://www.wdr2.de/sendungen/wdr2derfeiertag/derfeiertag100.html"><strong>WDR 2 Der Feiertag</strong></a>
<span class="subText">
mit
<a href="http://www.wdr2.de/moderatoren/hoepker100.html">Gudrun Höpker</a>
</span>
<img src="/musik/bildgudrunhoepker100_v-TeaserKlein.jpg"    title="Bildrechte: WDR" alt="Gudrun Höpker" height="82" width='146' />
</td>
</tr>
<tr>
<th scope="row" headers="jip-2-a1-1TimeId">
13.00
<span class="hidden"> Uhr</span>
</th>
<td headers="jip-2-a1-1BroadcastId" >
<a href="http://www.wdr.de/radio/home/nachrichten/index.phtml"><strong>Nachrichten, Wetter</strong></a>
</td>
</tr>
<tr>
<th scope="row" headers="jip-2-a1-1TimeId">
13.04
<span class="hidden"> Uhr</span>
</th>
<td headers="jip-2-a1-1BroadcastId" >
<a href="http://www.wdr2.de/sendungen/wdr2derfeiertag/derfeiertag100.html"><strong>WDR 2 Der Feiertag</strong></a>
<span class="subText">
mit
<a href="http://www.wdr2.de/moderatoren/brackmann100.html">Cathrin Brackmann</a>
</span>
<img src="/moderatoren/bildcathrinbrackmann100_v-TeaserKlein.jpg"    title="Bildrechte: WDR" alt="Cathrin Brackmann" height="82" width='146' />
</td>
</tr>
<tr>
<th scope="row" headers="jip-2-a1-1TimeId">
17.00
<span class="hidden"> Uhr</span>
</th>
<td headers="jip-2-a1-1BroadcastId" >
<a href="http://www.wdr.de/radio/home/nachrichten/index.phtml"><strong>Nachrichten, Wetter</strong></a>
</td>
</tr>
<tr>
<th scope="row" headers="jip-2-a1-1TimeId">
17.05
<span class="hidden"> Uhr</span>
</th>
<td headers="jip-2-a1-1BroadcastId" >
<a href="http://www.wdr2.de/sendungen/wdr2dertag/index.html"><strong>WDR 2 Der Tag</strong></a>
<span class="subText">
mit
<a href="http://www.wdr2.de/moderatoren/vogt100.html">Stefan Vogt</a>
</span>
<img src="/musik/bildstefanvogt100_v-TeaserKlein.jpg"    title="Bildrechte: WDR" alt="Stefan Vogt" height="82" width='146' />
</td>
</tr>
<tr>
<th scope="row" headers="jip-2-a1-1TimeId">
18.00
<span class="hidden"> Uhr</span>
</th>
<td headers="jip-2-a1-1BroadcastId" >
<a href="http://www.wdr.de/radio/home/nachrichten/index.phtml"><strong>Nachrichten, Wetter</strong></a>
</td>
</tr>
<tr>
<th scope="row" headers="jip-2-a1-1TimeId">
18.05
<span class="hidden"> Uhr</span>
</th>
<td headers="jip-2-a1-1BroadcastId" >
<a href="http://www.wdr2.de/sendungen/wdr2musikclub/index.html"><strong>WDR 2 Musikclub</strong></a>
<span class="subText">
mit
<a href="http://www.wdr2.de/moderatoren/vieth100.html">Udo Vieth</a>
</span>
<img src="/musik/bildudovieth100_v-TeaserKlein.jpg"    title="Bildrechte: WDR" alt="Udo Vieth" height="82" width='146' />
</td>
</tr>
<tr>
<th scope="row" headers="jip-2-a1-1TimeId">
00.00
<span class="hidden"> Uhr</span>
</th>
<td headers="jip-2-a1-1BroadcastId" >
<a href="http://www.wdr.de/radio/home/nachrichten/index.phtml"><strong>Nachrichten, Wetter</strong></a>
</td>
</tr>
</tbody>
</table>
</div>
<ul><li><a class="studioMail" href="/kontakt/mail-ins-studio100.html">Mail ins Studio</a></li></ul>
</li>
<li id="a1-2">
<!-- ajaxURL: /streams100-akkordeonLinkliste_akk-a1-2.html,/regionalstreams100-akkordeonLinkliste_akk-a1-2.html -->
<a href="/defaultError100_akk-a1-2.html#a1-2">Jetzt WDR 2 hören</a></li>
<li id="a1-3">
<!-- ajaxURL: /podcast102-akkordeonLinkliste_akk-a1-3.html,/podcast144-akkordeonLinkliste_akk-a1-3.html,/podcast146-akkordeonLinkliste_akk-a1-3.html,/podcast148-akkordeonLinkliste_akk-a1-3.html,/podcast150-akkordeonLinkliste_akk-a1-3.html,/podcast152-akkordeonLinkliste_akk-a1-3.html,/podcast154-akkordeonLinkliste_akk-a1-3.html,/podcast156-akkordeonLinkliste_akk-a1-3.html -->
<a href="/defaultError100_akk-a1-3.html#a1-3">Podcast</a></li>
<li id="a1-4"class="last">
<!-- ajaxURL: /frequenzen118-akkordeonLinkliste_akk-a1-4.html,/frequenzen100-akkordeonLinkliste_akk-a1-4.html,/frequenzen102-akkordeonLinkliste_akk-a1-4.html,/frequenzen104-akkordeonLinkliste_akk-a1-4.html,/frequenzen106-akkordeonLinkliste_akk-a1-4.html,/frequenzen108-akkordeonLinkliste_akk-a1-4.html,/frequenzen110-akkordeonLinkliste_akk-a1-4.html,/frequenzen112-akkordeonLinkliste_akk-a1-4.html,/frequenzen114-akkordeonLinkliste_akk-a1-4.html,/frequenzen116-akkordeonLinkliste_akk-a1-4.html -->
<a href="/defaultError100_akk-a1-4.html#a1-4">Frequenzen</a></li>
</ul>
</div>
</div>
<!--googleon: index-->
<hr/>
</div>
</div>
<h2 class="hidden">Seitenfunktionen</h2>
<div id="pageFunctions" class="isSmall">
<ul>
<li>
<a href="#wrapper">Seitenanfang</a>
</li>
</ul>
</div>
<hr/>
<!--googleoff: index-->
<div id="footer">
<h2 class="hidden">Service-Navigation</h2>
<ul>
<li id="newsletter"><a href="http://www.wdr.de/themen/global/newsletter/">Newsletter
+ RSS</a></li>
<li id="impressum"><a href="/impressum/impressum100.html">Impressum</a></li>
<li id="copyright"><a href="http://www.wdr.de/themen/global/urheber/">&copy; WDR 2012</a></li>
</ul>
</div>
<!-- footer -->
<hr />
<form method="post"
action="/suche/suche104.jsp"
id="search" accept-charset="UTF-8">
<h2 class="hidden">Suche</h2>
<fieldset>
<legend class="hidden">Suche im gesamten Angebot von WDR&nbsp;2</legend>
<label for="words" class="hidden">Suchbegriff:</label>
<input name="Q" value="" type="text" id="words" />
<input type="submit" value="suchen" />
</fieldset>
</form>
<hr/>
<div id="navigation">
<h2 class="hidden">Navigation</h2>
<h3 class="hidden">WDR 2-Navigation</h3>
<ul id="radioSubNavi">
<li class="active">
<a href="/index.html">WDR 2</a>
</li>
<li>
<a href="/nrw/index.html">NRW</a>
</li>
<li>
<a href="/politik/index.html">Politik</a>
<div class="hoverCont">
<ul>
<li><a href="/politik/klartext/index.html">WDR 2 Klartext</a></li>
<li><a href="/politik/wdr2arena/index.html">WDR 2 Arena</a></li>
<li><a href="/politik/wahlen/index.html">NRW-Landtagswahl 2012</a></li>
</ul>
</div>
</li>
<li>
<a href="/wirtschaft/index.html">Wirtschaft</a>
</li>
<li>
<a href="/panorama/index.html">Panorama</a>
<div class="hoverCont">
<ul>
<li><a href="/panorama/stichtag/index.html">Der Stichtag bei WDR.de</a></li>
<li><a href="/panorama/sonntagsfragen/index.html">WDR 2 Sonntagsfragen</a></li>
<li><a href="/panorama/fotostrecken/index.html">WDR 2 Fotostrecken</a></li>
<li><a href="/panorama/fruehling/index.html">Frühling 2012</a></li>
</ul>
</div>
</li>
<li>
<a href="/musik/index.html">Musik</a>
<div class="hoverCont">
<ul>
<li><a href="/musik/musiktipp/index.html">WDR 2 Musiktipp</a></li>
<li><a href="/musik/jukebox/index.html">Jukebox-Voting</a></li>
<li><a href="/musik/konzertbuebersichtslink/index.html">Konzerttermine</a></li>
<li><a href="/musik/konzertberichte/index.html">WDR 2 präsentierte</a></li>
<li><a href="/musik/neubeiwdr2/index.html">Neu bei WDR 2</a></li>
<li><a href="/musik/szenenrw/index.html">Szene NRW: Die Wahl</a></li>
<li><a href="/musik/musikquiz/index.html">WDR 2 Musikquiz</a></li>
<li><a href="/musik/musikclub/index.html">WDR 2 Musikclub</a></li>
<li><a href="/musik/classics/index.html">WDR 2 Musikclub - Classics</a></li>
<li><a href="/musik/yesterday/index.html">WDR 2 Yesterday</a></li>
<li><a href="/musik/playlist/index.html">Playlist</a></li>
</ul>
</div>
</li>
<li>
<a href="/unterhaltung/index.html">Unterhaltung</a>
<div class="hoverCont">
<ul>
<li><a href="/unterhaltung/comedy/index.html">WDR 2 Comedy</a></li>
<li><a href="/unterhaltung/paternoster/index.html">WDR 2 Paternoster</a></li>
<li><a href="/unterhaltung/lachenlive/index.html">WDR 2 Lachen Live</a></li>
<li><a href="/unterhaltung/kabarett/index.html">WDR 2 Kabarett</a></li>
<li><a href="/unterhaltung/wdr2montalk/index.html">WDR 2 MonTalk</a></li>
<li><a href="/unterhaltung/quizze/index.html">WDR 2 Quizze</a></li>
</ul>
</div>
</li>
<li>
<a href="/kultur/index.html">Kultur</a>
<div class="hoverCont">
<ul>
<li><a href="/kultur/tatortnrw/index.html">WDR 2 Tatort NRW</a></li>
<li><a href="/kultur/buecher/index.html">WDR 2 Bücher</a></li>
<li><a href="/kultur/kritiker/index.html">WDR 2 Die Kritiker</a></li>
<li><a href="/kultur/kino/index.html">WDR 2 Kinotipp</a></li>
</ul>
</div>
</li>
<li>
<a href="/service/index.html">Service</a>
<div class="hoverCont">
<ul>
<li><a href="/service/quintessenz/index.html">WDR 2 Quintessenz</a></li>
<li><a href="/service/gote/index.html">WDR 2 Einfach Gote</a></li>
<li><a href="/service/multimedia/index.html">WDR 2 Multimedia</a></li>
<li><a href="/service/servicezeit/index.html">WDR 2 Servicezeit</a></li>
</ul>
</div>
</li>
<li>
<a href="/sport/index.html">Sport</a>
<div class="hoverCont">
<ul>
<li><a href="/sport/pistor/index.html">Alle gegen Pistor</a></li>
<li><a href="/sport/torjaeger/index.html">WDR 2 Torjäger</a></li>
<li><a href="/sport/ligalive/index.html">Liga Live</a></li>
<li><a href="/sport/uefa_euro_2012/index.html">UEFA EURO 2012</a></li>
</ul>
</div>
</li>
<li>
<a href="/aktionen/index.html">Aktionen</a>
<div class="hoverCont">
<ul>
<li><a href="/aktionen/wdr2_fuer_eine_stadt/index.html">WDR 2 für eine Stadt</a></li>
<li><a href="/aktionen/hausparty/index.html">WDR 2 Hausparty</a></li>
<li><a href="/aktionen/lehrstellenaktion/index.html">WDR Lehrstellenaktion</a></li>
<li><a href="/aktionen/veranstaltungstermine/index.html">Veranstaltungstermine</a></li>
</ul>
</div>
</li>
<li>
<a href="/sendungen/index.html">Sendungen</a>
<div class="hoverCont">
<ul>
<li><a href="/sendungen/wdr2arena/index.html">WDR 2 Arena</a></li>
<li><a href="/sendungen/wdr2berichtevonheute/index.html">WDR 2 Berichte von heute</a></li>
<li><a href="/sendungen/wdr2amsamstag/index.html">WDR 2 am Samstag</a></li>
<li><a href="/sendungen/wdr2amsonntag/index.html">WDR 2 am Sonntag</a></li>
<li><a href="/sendungen/wdr2dertag/index.html">WDR 2 Der Tag</a></li>
<li><a href="/sendungen/wdr2ligalive/index.html">WDR 2 Liga Live/Sportzeit</a></li>
<li><a href="/sendungen/wdr2mittagsmagazin/index.html">WDR 2 Mittagsmagazin</a></li>
<li><a href="/sendungen/wdr2montalk/index.html">WDR 2 MonTalk</a></li>
<li><a href="/sendungen/wdr2morgenmagazin/index.html">WDR 2 Morgenmagazin</a></li>
<li><a href="/sendungen/wdr2musikclub/index.html">WDR 2 Musikclub</a></li>
<li><a href="/sendungen/wdr2musikclubclassics/index.html">WDR 2 Musikclub-Classics</a></li>
<li><a href="/sendungen/wdr2musikclubjukebox/index.html">WDR 2 Musikclub-Jukebox</a></li>
<li><a href="/sendungen/wdr2servicezeit/index.html">WDR 2 Servicezeit</a></li>
<li><a href="/sendungen/wdr2sonntagsfragen/index.html">WDR 2 Sonntagsfragen</a></li>
<li><a href="/sendungen/wdr2weltzeit/index.html">WDR 2 Weltzeit</a></li>
<li><a href="/sendungen/wdr2westzeit/index.html">WDR 2 Westzeit</a></li>
<li><a href="/sendungen/wdr2yesterday/index.html">WDR 2 Yesterday</a></li>
<li><a href="/sendungen/wdr2zugabe/index.html">WDR 2 Zugabe</a></li>
<li><a href="/sendungen/wdr2zwischenrheinundweser/index.html">WDR 2 Zwischen Rhein und Weser</a></li>
<li><a href="/sendungen/ndr2undwdr2dienacht/index.html">NDR 2 und WDR 2: Die Nacht</a></li>
</ul>
</div>
</li>
<li class="last">
<a href="/moderatoren/index.html">Moderation</a>
</li>
</ul>
<h3 class="hidden">Radio-Navigation</h3>
<ul id="radioNavi">
<li><a href="http://www.einslive.de">1LIVE</a></li>
<li class="active">
<a href="/index.html">WDR 2</a>
</li>
<li><a href="http://www.wdr3.de">WDR 3</a></li>
<li><a href="http://www.wdr.de/radio/wdr4">WDR 4</a></li>
<li><a href="http://www.wdr5.de">WDR 5</a></li>
<li><a href="http://www.funkhauseuropa.de/">Funkhaus Europa</a></li>
<li><a href="http://www.wdr.de/radio/orchester/index.html">Orchester + Chor</a></li>
</ul>
<img src="/resources/img/logos/wdr.gif" alt="WDR.de" title="" width="120" height="50" id="wdrLogo" />
<h3 class="hidden">WDR-Hauptnavigation</h3>
<ul id="wdrNavi">
<li><a href="http://www.wdr.de/">WDR.de</a></li>
<li><a href="http://www.wdr.de/tv/home/">Fernsehen</a></li>
<li class="active"><a href="http://www.wdr.de/radio/home/index.phtml">Radio</a></li>
<li><a href="http://www.wdr.de/mediathek/html/regional/index.xml">Mediathek</a></li>
<li><a href="http://www.wdr.de/programmvorschau/">Programmvorschau</a></li>
</ul>
<h3 class="hidden">Metanavigation</h3>
<ul id="wdrSubNavi">
<li id="weatherLink"><a href="http://www1.wdr.de/themen/infokompakt/wetter/wetter_nrw_ea100.html"><acronym title="Nordrhein-Westfalen">NRW</acronym>-Wetter</a></li>
<li id="trafficLink"><a href="http://www.wdr.de/verkehrslage/">Verkehrslage</a></li>
<li id="textLink"><a href="http://www1.wdr.de/themen/infokompakt/videotext_ea/index.html">WDR Text</a></li>
<li id="contactLink"><a href="/kontakt/kontakt102.html">Kontakt</a></li>
<li id="azLink"><a href="http://www.wdr.de/themen/global/a_z/index.jhtml">A - Z</a></li>
<li id="helpLink"><a href="http://www.wdr.de/themen/homepages/hilfe.jhtml">Hilfe</a></li>
<li id="companyLink"><a href="http://www.wdr.de/unternehmen/">Unternehmen</a></li>
</ul>
</div>
</div>
</div>
<div id="ivwPix">
<script type="text/javascript"><!-- <![CDATA[
var IVW='http://wdr.ivwbox.de/cgi-bin/ivw/CP/;www.wdr2.de/defaultError100.html';
document.write("<img src=\""+IVW+"?r="+escape(document.referrer)+"\" width=\"1\" height=\"1\" alt=\"\" />");
// ]]> --></script><noscript>
<div><img src="http://wdr.ivwbox.de/cgi-bin/ivw/CP/;www.wdr2.de/defaultError100.html" width="1" height="1" alt="" /></div>
</noscript>
</div>
<script type="text/javascript" charset="utf-8" src="/resources/js/jquery-1.6.2.min.js"></script>
<script type="text/javascript" charset="utf-8" src="/resources/js/jquery-ui-1.8.10.custom.min.js"></script>
<script type="text/javascript" charset="utf-8" src="/resources/js/plugins/jquery.requireScript-1.2.1.min.js"></script>
<script type="text/javascript">
<!--<![CDATA[
var $jsPath = '/resources/js/';
jQuery.noConflict();
// ]]>  -->
</script>
<script type="text/javascript" charset="utf-8" src="/resources/js/basic.min.js"></script>
<!--googleon: index-->
</body>
</html>