<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" media="screen" href="/~d/styles/rss2full.xsl"?>
<?xml-stylesheet type="text/css" media="screen" href="http://feeds.feedburner.com/~d/styles/itemcontent.css"?>
<rss xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:wfw="http://wellformedweb.org/CommentAPI/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:sy="http://purl.org/rss/1.0/modules/syndication/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:feedburner="http://rssnamespace.org/feedburner/ext/1.0" version="2.0">
  <channel>
    <title>LegalBuffet Blog - Podcasts powered by Odiogo</title>
    <link>http://legalbuffet.com/legalblog</link>
    <description>Tales from the Legal Side</description>
    <lastBuildDate>Thu, 01 Oct 2009 20:19:00 +0000</lastBuildDate>
    <generator>http://wordpress.org/?v=2.8.4</generator>
    <language>en</language>
    <sy:updatePeriod>hourly</sy:updatePeriod>
    <sy:updateFrequency>1</sy:updateFrequency>
    <atom10:link xmlns:atom10="http://www.w3.org/2005/Atom" rel="self" type="application/rss+xml" href="http://feeds.feedburner.com/LegalBuffetBlog" />
    <feedburner:info uri="legalbuffetblog" />
    <atom10:link xmlns:atom10="http://www.w3.org/2005/Atom" rel="hub" href="http://pubsubhubbub.appspot.com/" />
    <image>
      <link>http://www.legalbuffet.com/legalblog/</link>
      <url>http://www.feedburner.com/fb/images/pub/fb_pwrd.gif</url>
      <title>http://legalbuffet.com/images/lb-logo.jpg</title>
    </image>
    <feedburner:feedFlare href="http://add.my.yahoo.com/rss?url=http%3A%2F%2Ffeeds.feedburner.com%2FLegalBuffetBlog" src="http://us.i1.yimg.com/us.yimg.com/i/us/my/addtomyyahoo4.gif">Subscribe with My Yahoo!</feedburner:feedFlare>
    <feedburner:feedFlare href="http://www.newsgator.com/ngs/subscriber/subext.aspx?url=http%3A%2F%2Ffeeds.feedburner.com%2FLegalBuffetBlog" src="http://www.newsgator.com/images/ngsub1.gif">Subscribe with NewsGator</feedburner:feedFlare>
    <feedburner:feedFlare href="http://feeds.my.aol.com/add.jsp?url=http%3A%2F%2Ffeeds.feedburner.com%2FLegalBuffetBlog" src="http://o.aolcdn.com/favorites.my.aol.com/webmaster/ffclient/webroot/locale/en-US/images/myAOLButtonSmall.gif">Subscribe with My AOL</feedburner:feedFlare>
    <feedburner:feedFlare href="http://www.bloglines.com/sub/http://feeds.feedburner.com/LegalBuffetBlog" src="http://www.bloglines.com/images/sub_modern11.gif">Subscribe with Bloglines</feedburner:feedFlare>
    <feedburner:feedFlare href="http://www.netvibes.com/subscribe.php?url=http%3A%2F%2Ffeeds.feedburner.com%2FLegalBuffetBlog" src="http://www.netvibes.com/img/add2netvibes.gif">Subscribe with Netvibes</feedburner:feedFlare>
    <feedburner:feedFlare href="http://fusion.google.com/add?feedurl=http%3A%2F%2Ffeeds.feedburner.com%2FLegalBuffetBlog" src="http://buttons.googlesyndication.com/fusion/add.gif">Subscribe with Google</feedburner:feedFlare>
    <feedburner:feedFlare href="http://www.pageflakes.com/subscribe.aspx?url=http%3A%2F%2Ffeeds.feedburner.com%2FLegalBuffetBlog" src="http://www.pageflakes.com/ImageFile.ashx?instanceId=Static_4&amp;fileName=ATP_blu_91x17.gif">Subscribe with Pageflakes</feedburner:feedFlare>
    <item>
      <title>Just When is Fair Use Truly Fair?</title>
      <link>http://feedproxy.google.com/~r/LegalBuffetBlog/~3/j1MvFwLFGxk/</link>
      <comments>http://legalbuffet.com/legalblog/just-when-is-fair-use-truly-fair/#comments</comments>
      <pubDate>Fri, 18 Sep 2009 20:44:10 +0000</pubDate>
      <dc:creator>Heather Faucher</dc:creator>
      <category><![CDATA[Copyrights]]></category>
      <category><![CDATA[copyright infringement]]></category>
      <category><![CDATA[fair use]]></category>
      <guid isPermaLink="false">http://legalbuffet.com/legalblog/?p=987</guid>
      <description>Copyright infringement refers to the unauthorized or unlicensed copying of a copyrighted work.  Copyright law exists to provide protection to authors, artists, and developers or other copyright holders so they can make their livings off of their copyrighted work without fear that others will steal or copy their work for their own commercial or inappropriate [...]&lt;p&gt;&lt;a href="http://legalbuffet.com/legalblog/just-when-is-fair-use-truly-fair/"&gt;Just When is Fair Use Truly Fair?&lt;/a&gt; is a post from: &lt;a href="http://legalbuffet.com/legalblog"&gt;LegalBuffet Blog&lt;/a&gt;&lt;/p&gt;&lt;br&gt;&lt;a type="audio/mpeg" href="http://podcasts.odiogo.com/get_mp3.mp3?f=/legalbuffet-blog/LegalBuffet_Blog-Just_When_is_Fair_Use_Truly_Fair.mp3"&gt;Click here to play&lt;/a&gt;&lt;br&gt;</description>
      <content:encoded><![CDATA[<p><img class="alignleft size-full wp-image-989" src="http://legalbuffet.com/legalblog/wp-content/uploads/2009/09/copyright.JPG" alt="copyright" width="298" height="197" />Copyright infringement refers to the unauthorized or unlicensed copying of a copyrighted work.  Copyright law exists to provide protection to authors, artists, and developers or other copyright holders so they can make their livings off of their copyrighted work without fear that others will steal or copy their work for their own commercial or inappropriate use.  One potential defense for those accused of copyright infringement is that of &#8220;fair use.&#8221;  The fair use doctrine came into existence due to a succession of court decisions over the years that was later codified into U.S. law in Section 107 of the Copyright Law.</p>
<p>Sometimes it&#8217;s difficult to define just what constitutes fair use according to this law.  Unfortunately, the truth of the matter is that fair use can be best described as a murky land with invisible and hard-to-define boundaries.  Especially with the ever-increasing expansion of cyberspace.  So how can you tell just when fair use is, in fact, fair?  Well, the best method is, of course, to hire an experienced copyright attorney to go over the facts of your case.  Barring that, though, you can consider the following four factor fair use analysis and how the factors apply to your specific situation.</p>
<p><strong><span id="more-987"></span>1.  What is the character of the use?</strong></p>
<p>Basically, this factor takes a look at just how you intend to use the work you wish to reproduce.  Will your use be nonprofit, educational, personal, or commercial in nature?  Are you using it for purposes of criticism or commentary, or perhaps for the purposes of parody?  Perhaps you intend to engage in some otherwise &#8220;transformative&#8221; use.  Nonprofit, educational, and personal purposes tend to receive the most weight in copyright infringement cases.  The core fair uses of criticism, commentary, newsreporting, parody, and otherwise &#8220;transformative&#8221; uses tend to be those most staunchly protected by the Courts.  Commercial use, of course, tends to be viewed in the harshest light, with ruling typically erring on the side of the copyright holder rather than the person seeking to profit from the other&#8217;s copyrighted work.</p>
<p><strong>2.  What is the nature of the work to be used?</strong></p>
<p>If the nature of the work you want to use is fact-based or published, that tips the scale in favor of fair use, while imaginative-based or unpublished work will tend to tip toward requiring permission of the copyright holder.  Works that involve a mixture of fact and imaginative (such as true crime novels that mix fact and fantasy regarding real-life crimes) don&#8217;t really tip to either side of the scale.</p>
<p><strong>3.  How much of the work will you use?</strong></p>
<p>This factor can be a loaded one.  Are you going to use a &#8220;small amount&#8221; or more than a &#8220;small amount&#8221; of the work?  How the heck do you define a &#8220;small amount&#8221; in regards to copyright law, anyway?  If the first factor weighed in favor of fair use (such as copying an entire work for use in an educational setting, like a classroom), it may well be permissible to copy the entire work.  However, if a business wants to quote a work for commercial purposes, they will likely have to limit the quote to a much smaller portion than a professor using the work for educational purposes would.</p>
<p><strong>4.  What effect would this use have on the market for the original or for permissions if the use were widespread? </strong></p>
<p>This factor can be even more fluid.  Under certain circumstances, it can weigh the heaviest for or against fair use.  Under others, it weighs nothing!  It all comes down to how the first three factors panned out and this factor is most concerned with the question &#8220;If the use were widespread and not fair, would the copyright holder lose money due to the use?&#8221;  If the use is fair, the copyright holder wouldn&#8217;t be losing anything because he or she would not have been entitled to make any money off the work anyway.</p>
<p>Of course, considering the conclusion you are attempting to reach (assuming the use is not fair when trying to reason whether it is fair) is known as &#8220;circular reasoning&#8221; in the school of logical argument.  Because of that, Courts will first consider the first three factors before even thinking about the fourth.  If the first three factors lean toward fair use, Courts will not let the fourth factor alone make a use into copyright infringement.  On the other hand, if the first three factors seem to indicate that copyright infringement exists, Courts will consider lost revenues under the fourth factor.  This doesn&#8217;t engage in circular reasoning because they have already reached the conclusion that a use wasn&#8217;t fair use.</p>
<p>When you include in your assumptions the very conclusion that you are trying to reach (you assume a use is not fair in the process of trying to figure out whether it is fair), you violate a principle of logic &#8211; you engage in &#8220;circular reasoning.&#8221;</p>
<p>Sound simple?  Yeah, probably not.  You&#8217;ll probably be best served contacting one of those experienced and reputable copyright law attorneys to be on the safe side!!!</p>
<p>Learn <a href="http://legalbuffet.com/copyright-services/">how to copyright</a>. You&#8217;ll be glad you did.</p>
<p><a href="http://legalbuffet.com/legalblog/just-when-is-fair-use-truly-fair/">Just When is Fair Use Truly Fair?</a> is a post from: <a href="http://legalbuffet.com/legalblog">LegalBuffet Blog</a></p>
<div class="feedflare">
<a href="http://feeds.feedburner.com/~ff/LegalBuffetBlog?a=j1MvFwLFGxk:-FiHlUphzl4:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/LegalBuffetBlog?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/LegalBuffetBlog?a=j1MvFwLFGxk:-FiHlUphzl4:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/LegalBuffetBlog?i=j1MvFwLFGxk:-FiHlUphzl4:gIN9vFwOqvQ" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/LegalBuffetBlog?a=j1MvFwLFGxk:-FiHlUphzl4:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/LegalBuffetBlog?i=j1MvFwLFGxk:-FiHlUphzl4:V_sGLiPBpWU" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/LegalBuffetBlog?a=j1MvFwLFGxk:-FiHlUphzl4:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/LegalBuffetBlog?d=qj6IDK7rITs" border="0"></img></a>
</div><img src="http://feeds.feedburner.com/~r/LegalBuffetBlog/~4/j1MvFwLFGxk" height="1" width="1"/>]]></content:encoded>
      <wfw:commentRss>http://legalbuffet.com/legalblog/just-when-is-fair-use-truly-fair/feed/</wfw:commentRss>
      <slash:comments>0</slash:comments>
      <feedburner:origLink>http://legalbuffet.com/legalblog/just-when-is-fair-use-truly-fair/</feedburner:origLink>
      <enclosure url="http://podcasts.odiogo.com/get_mp3.mp3?f=/legalbuffet-blog/LegalBuffet_Blog-Just_When_is_Fair_Use_Truly_Fair.mp3" length="2604691" type="audio/mpeg" />
    </item>
    <item>
      <title>Bankruptcy Basics</title>
      <link>http://feedproxy.google.com/~r/LegalBuffetBlog/~3/mUFvO1ag2d0/</link>
      <comments>http://legalbuffet.com/legalblog/bankruptcy-basics/#comments</comments>
      <pubDate>Wed, 16 Sep 2009 21:13:18 +0000</pubDate>
      <dc:creator>Heather Faucher</dc:creator>
      <category><![CDATA[Bankruptcy]]></category>
      <category><![CDATA[backruptcy discharge]]></category>
      <category><![CDATA[Chapter 13]]></category>
      <category><![CDATA[Chapter 7]]></category>
      <category><![CDATA[filing bankruptcy]]></category>
      <guid isPermaLink="false">http://legalbuffet.com/legalblog/?p=975</guid>
      <description>Bankruptcy was created to benefit both debtors (consumers or businesses who owe money to others) and their creditors (a person or business who is owed money) by making sure that debtors get relief from debts that they truly can&amp;#8217;t afford to pay, as well as ensuring that creditors get paid from any assets that the [...]&lt;p&gt;&lt;a href="http://legalbuffet.com/legalblog/bankruptcy-basics/"&gt;Bankruptcy Basics&lt;/a&gt; is a post from: &lt;a href="http://legalbuffet.com/legalblog"&gt;LegalBuffet Blog&lt;/a&gt;&lt;/p&gt;&lt;br&gt;&lt;a type="audio/mpeg" href="http://podcasts.odiogo.com/get_mp3.mp3?f=/legalbuffet-blog/LegalBuffet_Blog-Bankruptcy_Basics.mp3"&gt;Click here to play&lt;/a&gt;&lt;br&gt;</description>
      <content:encoded><![CDATA[<p><img class="alignleft size-full wp-image-978" src="http://legalbuffet.com/legalblog/wp-content/uploads/2009/09/bankruptcypic5.JPG" alt="bankruptcypic5" width="298" height="197" />Bankruptcy was created to benefit both debtors (consumers or businesses who owe money to others) and their creditors (a person or business who is owed money) by making sure that debtors get relief from debts that they truly can&#8217;t afford to pay, as well as ensuring that creditors get paid from any assets that the creditor doesn&#8217;t need to live on.  In 2005, the U.S. Bankruptcy Code was modified to make it more difficult for debtors who can afford to pay off at least <span style="text-decoration: underline;">some</span> of their debts to file for Chapter 7 bankruptcy, which forgives most if not all of a consumer&#8217;s debt.  Instead, most of these debtors are required to file for Chapter 13 bankruptcy, under which they re-pay most or all of their debts under a 3 to 5 year payment plan.</p>
<p>So, how do you know whether you&#8217;ll need to file for Chapter 7 bankruptcy or Chapter 13?  <span id="more-975"></span>Easy enough&#8211;you need to take something called the means test.  This is a formula that was established in 2005 that determines whether or not a debtor has enough money&#8211;after deducting basic costs of living&#8211;to make payments of a minimal amount on his or her debt.  Those who do not have enough money left after paying their basic expenses will most likely qualify for Chapter 7 bankruptcy.  A Court-appointed Trustee will oversee the liquidation of the debtor&#8217;s non-exempt assets and re-pay as many creditors as possible.</p>
<p>During the bankruptcy process, a debtor files a Bankruptcy Petition with the United States Bankruptcy Court.  In certain circumstances, creditors can force a debtor to file for bankruptcy, though involuntary bankruptcies are exceedingly rare.  The goal of the bankruptcy process, from a debtor&#8217;s point of view, is to achieve what is called a discharge, or the forgiveness of debt.  A discharge is a permanent order which forbids creditors from making any more collection attempts on any debt that was disclosed during the bankruptcy proceedings.  This means that creditors can no longer call, write, or make any other kind of personal contact demanding that the debtor pay debts which have been discharged.</p>
<p>Sometimes, silence truly <span style="text-decoration: underline;">can</span> be golden!</p>
<p>Thinking about <a href="http://legalbuffet.com/bankruptcy-services/">filing bankruptcy</a>? Find more information <a href="http://legalbuffet.com/bankruptcy-services/">here</a>.</p>
<p><a href="http://legalbuffet.com/legalblog/bankruptcy-basics/">Bankruptcy Basics</a> is a post from: <a href="http://legalbuffet.com/legalblog">LegalBuffet Blog</a></p>
<div class="feedflare">
<a href="http://feeds.feedburner.com/~ff/LegalBuffetBlog?a=mUFvO1ag2d0:Nm1yO5Cl17s:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/LegalBuffetBlog?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/LegalBuffetBlog?a=mUFvO1ag2d0:Nm1yO5Cl17s:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/LegalBuffetBlog?i=mUFvO1ag2d0:Nm1yO5Cl17s:gIN9vFwOqvQ" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/LegalBuffetBlog?a=mUFvO1ag2d0:Nm1yO5Cl17s:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/LegalBuffetBlog?i=mUFvO1ag2d0:Nm1yO5Cl17s:V_sGLiPBpWU" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/LegalBuffetBlog?a=mUFvO1ag2d0:Nm1yO5Cl17s:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/LegalBuffetBlog?d=qj6IDK7rITs" border="0"></img></a>
</div><img src="http://feeds.feedburner.com/~r/LegalBuffetBlog/~4/mUFvO1ag2d0" height="1" width="1"/>]]></content:encoded>
      <wfw:commentRss>http://legalbuffet.com/legalblog/bankruptcy-basics/feed/</wfw:commentRss>
      <slash:comments>0</slash:comments>
      <feedburner:origLink>http://legalbuffet.com/legalblog/bankruptcy-basics/</feedburner:origLink>
      <enclosure url="http://podcasts.odiogo.com/get_mp3.mp3?f=/legalbuffet-blog/LegalBuffet_Blog-Bankruptcy_Basics.mp3" length="1171146" type="audio/mpeg" />
    </item>
    <item>
      <title>Sorry, No Tweet For You!!!</title>
      <link>http://feedproxy.google.com/~r/LegalBuffetBlog/~3/AXP0WCA7csg/</link>
      <comments>http://legalbuffet.com/legalblog/961/#comments</comments>
      <pubDate>Fri, 11 Sep 2009 03:00:11 +0000</pubDate>
      <dc:creator>Heather Faucher</dc:creator>
      <category><![CDATA[Trademarks]]></category>
      <category><![CDATA[trademark]]></category>
      <guid isPermaLink="false">http://legalbuffet.com/legalblog/?p=961</guid>
      <description>So social networking and micro-blogging phenomenon Twitter recently tried to trademark the word &amp;#8220;tweet,&amp;#8221; the term that many who Twitter use to describe their short, 140-character posts.  According to a blog post at the Twitter website, the company decided to apply for the trademark because “it is clearly attached to Twitter from a brand [...]&lt;p&gt;&lt;a href="http://legalbuffet.com/legalblog/961/"&gt;Sorry, No Tweet For You!!!&lt;/a&gt; is a post from: &lt;a href="http://legalbuffet.com/legalblog"&gt;LegalBuffet Blog&lt;/a&gt;&lt;/p&gt;&lt;br&gt;&lt;a type="audio/mpeg" href="http://podcasts.odiogo.com/get_mp3.mp3?f=/legalbuffet-blog/LegalBuffet_Blog-Sorry_No_Tweet_For_You.mp3"&gt;Click here to play&lt;/a&gt;&lt;br&gt;</description>
      <content:encoded><![CDATA[<div id="attachment_972" class="wp-caption alignleft" style="width: 117px"><img class="size-full wp-image-972   " src="http://legalbuffet.com/legalblog/wp-content/uploads/2009/09/nottweet2.jpg" alt="Photo: The Inquisitr" width="107" height="107" /><p class="wp-caption-text">Photo: The Inquisitr</p></div>
<p>So social networking and micro-blogging phenomenon Twitter recently tried to trademark the word &#8220;tweet,&#8221; the term that many who Twitter use to describe their short, 140-character posts.  According to a blog post at the Twitter website, the company decided to apply for the trademark because “it is clearly attached to Twitter from a brand perspective”.  An interesting claim, since it seems pretty well-established that Twitter users were actually the first to coin the term, rather than the company itself.</p>
<p>I use the term &#8220;tried&#8221; because the USPTO has preliminarily denied the trademark application.  I guess that Internet-using bird-lovers everywhere can breathe a sigh of relief now!  The USPTO remarked in its rejection that:  &#8220;marks in prior-filed pending applications may present a bar to registration of applicant’s mark. [...] If the marks in the referenced applications register, applicant’s mark may be refused registration under Trademark Act Section 2(d) because of a likelihood of confusion between the two marks&#8221; and went on to reference not one, not two, but three separate trademark applications:<span id="more-961"></span></p>
<p>* #77695071 for TWEETMARKS (pending receipt of Statement of Use)<br />
* #77697186 for COTWEET (pending clarification)<br />
* #77701645 for TWEETPHOTO (pending transfer to Supplemental Register).</p>
<p>Apparently, it&#8217;s at least partially a matter of, &#8220;You snooze, you lose.&#8221;  The USPTO&#8217;s response to Twitter&#8217;s trademark application pointed out that that each of the above trademark applications had been filed with its office prior to Twitter&#8217;s application.  While the USPTO didn&#8217;t say with definitive certainty that Twitter <span style="text-decoration: underline">would</span> be denied a trademark on the word &#8220;Tweet,&#8221; that was mostly because the other trademark applications are still pending.  If they&#8217;re accepted by the USPTO, however, chances are pretty much slim to none that Twitter will be allowed to trademark &#8220;Tweet.&#8221;</p>
<p>Twitter co-founded Biz Stone earlier wrote on the Twitter that:  &#8220;We have applied to trademark Tweet because it is clearly attached to Twitter from a brand perspective but we have no intention of &#8216;going after&#8217; the wonderful applications and services that use the word in their name when associated with Twitter&#8230;In fact, we encourage the use of the word Tweet. However, if we come across a confusing or damaging project, the recourse to act responsibly to protect both users and our brand is important.&#8221;</p>
<p>Interesting, since Twitter apparently wrote in an email to a developer that it was &#8220;uncomfortable with the use of the word Tweet (our trademark) and the similarity in your UI and our own.&#8221;  Only one problem.  At the time Twitter made that claim, it <span style="text-decoration: underline">didn&#8217;t</span> own the trademark on &#8220;Tweet&#8221;&#8211;and at this rate, it might never own it in the future, either.</p>
<p><a href="http://legalbuffet.com/trademark-services/">Trademark registration</a> doesn&#8217;t have to be difficult. Find out more <a href="http://legalbuffet.com/trademark-services/">here</a>.</p>
<p><a href="http://legalbuffet.com/legalblog/961/">Sorry, No Tweet For You!!!</a> is a post from: <a href="http://legalbuffet.com/legalblog">LegalBuffet Blog</a></p>
<div class="feedflare">
<a href="http://feeds.feedburner.com/~ff/LegalBuffetBlog?a=AXP0WCA7csg:PAz3m3U0MwE:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/LegalBuffetBlog?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/LegalBuffetBlog?a=AXP0WCA7csg:PAz3m3U0MwE:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/LegalBuffetBlog?i=AXP0WCA7csg:PAz3m3U0MwE:gIN9vFwOqvQ" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/LegalBuffetBlog?a=AXP0WCA7csg:PAz3m3U0MwE:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/LegalBuffetBlog?i=AXP0WCA7csg:PAz3m3U0MwE:V_sGLiPBpWU" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/LegalBuffetBlog?a=AXP0WCA7csg:PAz3m3U0MwE:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/LegalBuffetBlog?d=qj6IDK7rITs" border="0"></img></a>
</div><img src="http://feeds.feedburner.com/~r/LegalBuffetBlog/~4/AXP0WCA7csg" height="1" width="1"/>]]></content:encoded>
      <wfw:commentRss>http://legalbuffet.com/legalblog/961/feed/</wfw:commentRss>
      <slash:comments>0</slash:comments>
      <feedburner:origLink>http://legalbuffet.com/legalblog/961/</feedburner:origLink>
      <enclosure url="http://podcasts.odiogo.com/get_mp3.mp3?f=/legalbuffet-blog/LegalBuffet_Blog-Sorry_No_Tweet_For_You.mp3" length="1558858" type="audio/mpeg" />
    </item>
    <item>
      <title>Gosselin Claws Come Out…</title>
      <link>http://feedproxy.google.com/~r/LegalBuffetBlog/~3/i9CaAH7_bMY/</link>
      <comments>http://legalbuffet.com/legalblog/gosselin-claws-come-out/#comments</comments>
      <pubDate>Thu, 10 Sep 2009 04:03:18 +0000</pubDate>
      <dc:creator>Heather Faucher</dc:creator>
      <category><![CDATA[Divorce]]></category>
      <category><![CDATA[celebrity divorce]]></category>
      <category><![CDATA[children and divorce]]></category>
      <category><![CDATA[reality show divorce]]></category>
      <guid isPermaLink="false">http://legalbuffet.com/legalblog/?p=955</guid>
      <description>Wow, things are really getting heated between Jon and Kate Gosselin post-divorce.  Jon has finally started speaking out publicly about his failed relationship and why he felt he had to get away from his wife&amp;#8211;and her alleged abuse.  &amp;#8220;I was verbally abused. I was beaten down,&amp;#8221; the 32-year-old &amp;#8216;Jon and Kate Plus 8&amp;#8242; [...]&lt;p&gt;&lt;a href="http://legalbuffet.com/legalblog/gosselin-claws-come-out/"&gt;Gosselin Claws Come Out&amp;#8230;&lt;/a&gt; is a post from: &lt;a href="http://legalbuffet.com/legalblog"&gt;LegalBuffet Blog&lt;/a&gt;&lt;/p&gt;&lt;br&gt;&lt;a type="audio/mpeg" href="http://podcasts.odiogo.com/get_mp3.mp3?f=/legalbuffet-blog/LegalBuffet_Blog-Gosselin_Claws_Come_Out.mp3"&gt;Click here to play&lt;/a&gt;&lt;br&gt;</description>
      <content:encoded><![CDATA[<p><img class="alignleft size-medium wp-image-956" src="http://legalbuffet.com/legalblog/wp-content/uploads/2009/09/clawsout-300x198.jpg" alt="clawsout" width="300" height="198" />Wow, things are really getting heated between Jon and Kate Gosselin post-divorce.  Jon has finally started speaking out publicly about his failed relationship and why he felt he had to get away from his wife&#8211;and her alleged abuse.  &#8220;I was verbally abused. I was beaten down,&#8221; the 32-year-old &#8216;Jon and Kate Plus 8&#8242; dad said on Good Morning America.</p>
<p>&#8220;She separated me from my family. She used to hold the kids over my head and say, &#8216;Don&#8217;t spend time with your mom, spend time with your kids.&#8217; Why can&#8217;t I spend time with my mom and kids together?&#8221; he said. &#8220;Our relationship will never be fixed. I think down the road we might be friends, but at this point in time I don&#8217;t think so,&#8221; he said.</p>
<p>&#8220;It&#8217;s just like the change from America&#8217;s favorite dad to dirt-bag. Tomorrow I could be maybe&#8230; America&#8217;s favorite dad again. It could be after this interview. I don&#8217;t know. Whatever they want to write, let them write it. They&#8217;re going to write it anyway. I&#8217;ve learned that lesson,&#8221; he added.<span id="more-955"></span></p>
<p>Kate, on the other hand, is now apparently deciding that mum&#8217;s the better word.   &#8220;While I certainly have a very different perception of how our marriage dissolved, for the sake of my children I maintain that I&#8217;m not going to go into details of aspects I believe should remain private,&#8221; she said.</p>
<p>Jon went on to say about filming the show:  &#8220;We film it separately. She has her film crew. And I have my film crew. But I can&#8217;t sit on the sofa with that woman. I can&#8217;t sit on someone right now that I despise. I despise [her] because she&#8217;s not speaking from the heart. Please &#8212; the stuff you tell me in private should be the stuff you tell me on TV.&#8221;</p>
<p>Jon claimed that he thinks Kate still wears her wedding ring for less than noble reasons:  &#8220;I think she still wears the ring for public perception. I don&#8217;t wear my ring because she took my ring. I don&#8217;t have it&#8230; I laid it down one night. It was gone. Who else would take it? I checked all the &#8212; underneath my kids&#8217; pillows. That&#8217;s where everything ends up in the house anyway. So it wasn&#8217;t there.&#8221;</p>
<p>He also said that he wasn&#8217;t 100% sure whether Kate had strayed from the marriage: &#8220;I speculate, but I don&#8217;t know &#8212; that&#8217;s a general feel. You know, almost like when they were traveling together, I felt jealous. Here, I&#8217;m Mr. Mom. And then there&#8217;s some other guy traveling with my wife. Whether it&#8217;s protection or not, it&#8217;s all in &#8212; it&#8217;s in the back of my mind.&#8221;</p>
<p>Of course, he can&#8217;t exactly throw stones due to his relationship with 22-year-old girlfriend, Hailey Glassman, even though he did say this:  &#8220;I didn&#8217;t leave Kate for Hailey. People think I left Kate for Hailey&#8230; because of the time-frame and what they printed in the tabloids. You can&#8217;t control who you love. I strongly believe that. You cannot control that. It&#8217;s two people joined together. [Glassman] is polar opposite of Kate. I feel like I love &#8230; love her more than I did Kate. I get encouragement from her, I get respect from her. Two things that a man needs. This is someone, I mean, like soul mate &#8212; like people joke about that. But I&#8217;m not joking about that.&#8221;</p>
<p>It may just be time for both Gosselins to learn that silence can be the better part of valor&#8211;for their children&#8217;s sake if not their own.  It&#8217;s important to make sure divorce has as little negative impact on the kids as possible, something that they both seem to have forgotten.</p>
<p>Would you like more information about <a href="http://legalbuffet.com/divorce-services/">how to get a divorce</a>? Look no further.</p>
<p><a href="http://legalbuffet.com/legalblog/gosselin-claws-come-out/">Gosselin Claws Come Out&#8230;</a> is a post from: <a href="http://legalbuffet.com/legalblog">LegalBuffet Blog</a></p>
<div class="feedflare">
<a href="http://feeds.feedburner.com/~ff/LegalBuffetBlog?a=i9CaAH7_bMY:Q7m-n410plA:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/LegalBuffetBlog?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/LegalBuffetBlog?a=i9CaAH7_bMY:Q7m-n410plA:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/LegalBuffetBlog?i=i9CaAH7_bMY:Q7m-n410plA:gIN9vFwOqvQ" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/LegalBuffetBlog?a=i9CaAH7_bMY:Q7m-n410plA:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/LegalBuffetBlog?i=i9CaAH7_bMY:Q7m-n410plA:V_sGLiPBpWU" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/LegalBuffetBlog?a=i9CaAH7_bMY:Q7m-n410plA:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/LegalBuffetBlog?d=qj6IDK7rITs" border="0"></img></a>
</div><img src="http://feeds.feedburner.com/~r/LegalBuffetBlog/~4/i9CaAH7_bMY" height="1" width="1"/>]]></content:encoded>
      <wfw:commentRss>http://legalbuffet.com/legalblog/gosselin-claws-come-out/feed/</wfw:commentRss>
      <slash:comments>0</slash:comments>
      <feedburner:origLink>http://legalbuffet.com/legalblog/gosselin-claws-come-out/</feedburner:origLink>
      <enclosure url="http://podcasts.odiogo.com/get_mp3.mp3?f=/legalbuffet-blog/LegalBuffet_Blog-Gosselin_Claws_Come_Out.mp3" length="1913873" type="audio/mpeg" />
    </item>
    <item>
      <title>We’ve Come a Long Way Baby!</title>
      <link>http://feedproxy.google.com/~r/LegalBuffetBlog/~3/uqOUanZ8DOA/</link>
      <comments>http://legalbuffet.com/legalblog/weve-come-a-long-way-baby/#comments</comments>
      <pubDate>Tue, 01 Sep 2009 16:16:49 +0000</pubDate>
      <dc:creator>Heather Faucher</dc:creator>
      <category><![CDATA[Name Change]]></category>
      <category><![CDATA[marriage]]></category>
      <category><![CDATA[Name Changes]]></category>
      <guid isPermaLink="false">http://legalbuffet.com/legalblog/?p=934</guid>
      <description>We&amp;#8217;ve come a long way since the days when society raised its collective eyebrows whenever women chose to keep their own last names after marriage.  Nowadays, women who wish to hold on to the surnames they&amp;#8217;ve had since birth don&amp;#8217;t suffer nearly the stigma they did in the 1970&amp;#8217;s and 1980&amp;#8217;s.  One might [...]&lt;p&gt;&lt;a href="http://legalbuffet.com/legalblog/weve-come-a-long-way-baby/"&gt;We&amp;#8217;ve Come a Long Way Baby!&lt;/a&gt; is a post from: &lt;a href="http://legalbuffet.com/legalblog"&gt;LegalBuffet Blog&lt;/a&gt;&lt;/p&gt;&lt;br&gt;&lt;a type="audio/mpeg" href="http://podcasts.odiogo.com/get_mp3.mp3?f=/legalbuffet-blog/LegalBuffet_Blog-Weve_Come_a_Long_Way_Baby.mp3"&gt;Click here to play&lt;/a&gt;&lt;br&gt;</description>
      <content:encoded><![CDATA[<p><img class="alignleft size-medium wp-image-936" src="http://legalbuffet.com/legalblog/wp-content/uploads/2009/09/marriagelicense-200x300.jpg" alt="marriagelicense" width="200" height="300" /><br />
We&#8217;ve come a long way since the days when society raised its collective eyebrows whenever women chose to keep their own last names after marriage.  Nowadays, women who wish to hold on to the surnames they&#8217;ve had since birth don&#8217;t suffer nearly the stigma they did in the 1970&#8217;s and 1980&#8217;s.  One might suppose, then, that the percentage of women declining to take their husband&#8217;s surnames has skyrocketed in the intervening years…Right?</p>
<p>But studies show that the vast majority of women are still choosing to take their husbands&#8217; surnames after marriage, either completely or in part.  Some choose to keep their maiden names as a middle name and tack on their husband&#8217;s name at the end.  Others decide to drop their maiden names entirely, seeing it as a symbolic statement that they are declaring independence and setting out on the adventure of creating their own families.</p>
<p>One popular wedding website, theknot.com, ran a survey of 18,000 married couples in 2008.  Rebecca Dolgin, Executive Editor, stated that 88 percent of women reported changing their names upon marriage.  &#8220;I think that there was a point in time where women felt very strongly that they had to [keep their names] to assert their feminist leanings or to say that women are equal to men,&#8221; Dolgin said. &#8220;Now, women are a little more comfortable and it&#8217;s not as threatening to them.&#8221;</p>
<p>Family is a major motivation for many women to change their names after marriage.  They often choose to make that change so that all members of their new family&#8211;including future children&#8211;share the cohesive bond of the same surname.</p>
<p>Prudence Moylan, who serves as the graduate program director for women&#8217;s studies and gender studies at Loyola University, points out that while it&#8217;s no longer a shock when women choose to keep their last names after marriage, the movement has lost a lot of its steam lately.  She views modern brides&#8217; decisions to take on their husbands&#8217; names as indicative that they are choosing to keep with tradition, or, at the very least, that women are now acknowledging that making a stand over name change is perhaps not the best way to fight for equality.</p>
<p>Katie Kozak&#8211;now Katie Smith&#8211;perhaps puts this sentiment best:  &#8220;I think we still have our independence, but we hold family values a lot higher than we used to,&#8221; said Smith, 30, of Aurora, Illinois.  &#8220;I&#8217;m still a Kozak under it all.&#8221;</p>
<p>And thanks to those women who fought to establish a sense of feminine independence, we have indeed come a long way, baby!</p>
<p><b>Are you getting married soon and debating whether or not to change your name? Maybe you&#8217;ve decided to change your name. Find the information you&#8217;re looking for regarding a <a href="http://legalbuffet.com/name-change-services/">legal name change</a> here!</b></p>
<p><a href="http://legalbuffet.com/legalblog/weve-come-a-long-way-baby/">We&#8217;ve Come a Long Way Baby!</a> is a post from: <a href="http://legalbuffet.com/legalblog">LegalBuffet Blog</a></p>
<div class="feedflare">
<a href="http://feeds.feedburner.com/~ff/LegalBuffetBlog?a=uqOUanZ8DOA:jBKmDUgeVSI:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/LegalBuffetBlog?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/LegalBuffetBlog?a=uqOUanZ8DOA:jBKmDUgeVSI:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/LegalBuffetBlog?i=uqOUanZ8DOA:jBKmDUgeVSI:gIN9vFwOqvQ" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/LegalBuffetBlog?a=uqOUanZ8DOA:jBKmDUgeVSI:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/LegalBuffetBlog?i=uqOUanZ8DOA:jBKmDUgeVSI:V_sGLiPBpWU" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/LegalBuffetBlog?a=uqOUanZ8DOA:jBKmDUgeVSI:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/LegalBuffetBlog?d=qj6IDK7rITs" border="0"></img></a>
</div><img src="http://feeds.feedburner.com/~r/LegalBuffetBlog/~4/uqOUanZ8DOA" height="1" width="1"/>]]></content:encoded>
      <wfw:commentRss>http://legalbuffet.com/legalblog/weve-come-a-long-way-baby/feed/</wfw:commentRss>
      <slash:comments>0</slash:comments>
      <feedburner:origLink>http://legalbuffet.com/legalblog/weve-come-a-long-way-baby/</feedburner:origLink>
      <enclosure url="http://podcasts.odiogo.com/get_mp3.mp3?f=/legalbuffet-blog/LegalBuffet_Blog-Weve_Come_a_Long_Way_Baby.mp3" length="1431240" type="audio/mpeg" />
    </item>
    <item>
      <title>Tell Me No More Lies…Or Else!</title>
      <link>http://feedproxy.google.com/~r/LegalBuffetBlog/~3/--TfY6LXnkk/</link>
      <comments>http://legalbuffet.com/legalblog/tell-me-no-more-lies-or-else/#comments</comments>
      <pubDate>Fri, 28 Aug 2009 03:39:36 +0000</pubDate>
      <dc:creator>Heather Faucher</dc:creator>
      <category><![CDATA[Patents]]></category>
      <category><![CDATA[intellectual property]]></category>
      <category><![CDATA[inventions]]></category>
      <guid isPermaLink="false">http://legalbuffet.com/legalblog/?p=926</guid>
      <description>The USPTO has awarded National Institute for Truth Verification (NITV) founder Charles Humble a second patent for his CVSA (Computer Voice Stress Analyzer) II.  The CVSA II accurately measures voice patterns for stress levels and then rates the person being tested as having &amp;#8220;No Deception Indicated&amp;#8221; or &amp;#8220;Deception Indicated.&amp;#8221;  Just what makes this device superior [...]&lt;p&gt;&lt;a href="http://legalbuffet.com/legalblog/tell-me-no-more-lies-or-else/"&gt;Tell Me No More Lies&amp;#8230;Or Else!&lt;/a&gt; is a post from: &lt;a href="http://legalbuffet.com/legalblog"&gt;LegalBuffet Blog&lt;/a&gt;&lt;/p&gt;&lt;br&gt;&lt;a type="audio/mpeg" href="http://podcasts.odiogo.com/get_mp3.mp3?f=/legalbuffet-blog/LegalBuffet_Blog-Tell_Me_No_More_LiesOr_Else.mp3"&gt;Click here to play&lt;/a&gt;&lt;br&gt;</description>
      <content:encoded><![CDATA[<p><img src="http://legalbuffet.com/legalblog/wp-content/uploads/2009/08/liedetector2.JPG" alt="liedetector2" width="247" height="176" class="alignleft size-full wp-image-931" />The USPTO has awarded National Institute for Truth Verification (NITV) founder Charles Humble a second <span class='bm_keywordlink'><a href="http://legalbuffet.com/patent-services/">patent</a></span> for his CVSA (Computer Voice Stress Analyzer) II.  The CVSA II accurately measures voice patterns for stress levels and then rates the person being tested as having &#8220;No Deception Indicated&#8221; or &#8220;Deception Indicated.&#8221;  Just what makes this device superior to polygraph testing in certain situations?  Several aspects.</p>
<p>Firstly, the embedded software&#8211;which runs on a laptop computer&#8211;can be used to test live conversations, telephone conversations, or even recorded audio files.  Also, with the new algorithm, Humble claims that &#8220;recorded audio is just as good as live audio.&#8221;  And more than 1,800 federal and local law enforcement agencies, not to mention the U.S. military, recognize its value for helping catch criminals and use the CVSA II already.</p>
<p>A second benefit to the CVSA II is the fact it has a reported accuracy rating of greater than 96 percent.  And since it allows for real-time or post-interview analysis and an evaluation of the entire exam, it does away with potential bias during the exam process.</p>
<p><span id="more-926"></span>Both the patents awarded to Humble for the CVSA II relate to the establishment of numerical values for stress levels associated with someone being deceptive.  According to Humble, the device monitors the frequency changes and voice modulation whenever individuals are lying.  “From the Atlanta P.D. to the Nashville P.D. to the California Highway Patrol, this is an investigative tool that has proved itself to be invaluable in the field,” says Alan Hall, operations administrator at the NITV and a former military intelligence officer.</p>
<p>The NITV claims that the CVSA II has helped bring tens of thousands of criminals to justice.  A number of high-profile cases have occurred in the last few months.  One particularly heinous case involved a Louisiana man accused of raping his son.  The man was about to be released due to lack of physical evidence, but after being confronted by the results of his CVSA II exam, he ended up confessing to the crime.  A second high-profile case involved a Utah man confessing to a brutal murder and providing the murder weapon to the police when also confronted with the results from his CVSA II exam.</p>
<p>“CVSA is much less complicated than a polygraph,” Humble says. “A polygraph uses a lot of squiggly lines that you do not necessarily know what they mean. This uses simple graphs that chart their stress levels.”  Humble envisions a time when more people than law enforcement officials utilize CVSA technology in situations where it&#8217;s important to find out if someone isn&#8217;t being completely truthful.</p>
<p>Which just goes to show how important it is to patent those inventions just as soon as possible!</p>
<p><b>Looking for <a href="http://legalbuffet.com/patent-services/">information on patents</a>? Find it here.</b></p>
<p><a href="http://legalbuffet.com/legalblog/tell-me-no-more-lies-or-else/">Tell Me No More Lies&#8230;Or Else!</a> is a post from: <a href="http://legalbuffet.com/legalblog">LegalBuffet Blog</a></p>
<div class="feedflare">
<a href="http://feeds.feedburner.com/~ff/LegalBuffetBlog?a=--TfY6LXnkk:jMByvLm3_Lo:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/LegalBuffetBlog?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/LegalBuffetBlog?a=--TfY6LXnkk:jMByvLm3_Lo:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/LegalBuffetBlog?i=--TfY6LXnkk:jMByvLm3_Lo:gIN9vFwOqvQ" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/LegalBuffetBlog?a=--TfY6LXnkk:jMByvLm3_Lo:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/LegalBuffetBlog?i=--TfY6LXnkk:jMByvLm3_Lo:V_sGLiPBpWU" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/LegalBuffetBlog?a=--TfY6LXnkk:jMByvLm3_Lo:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/LegalBuffetBlog?d=qj6IDK7rITs" border="0"></img></a>
</div><img src="http://feeds.feedburner.com/~r/LegalBuffetBlog/~4/--TfY6LXnkk" height="1" width="1"/>]]></content:encoded>
      <wfw:commentRss>http://legalbuffet.com/legalblog/tell-me-no-more-lies-or-else/feed/</wfw:commentRss>
      <slash:comments>0</slash:comments>
      <feedburner:origLink>http://legalbuffet.com/legalblog/tell-me-no-more-lies-or-else/</feedburner:origLink>
      <enclosure url="http://podcasts.odiogo.com/get_mp3.mp3?f=/legalbuffet-blog/LegalBuffet_Blog-Tell_Me_No_More_LiesOr_Else.mp3" length="1613806" type="audio/mpeg" />
    </item>
    <item>
      <title>First-Time Homebuyers Q&amp;A:  Part 6..</title>
      <link>http://feedproxy.google.com/~r/LegalBuffetBlog/~3/BhdyKHtNdnY/</link>
      <comments>http://legalbuffet.com/legalblog/first-time-homebuyers-qa-part-6/#comments</comments>
      <pubDate>Wed, 26 Aug 2009 16:29:39 +0000</pubDate>
      <dc:creator>Heather Faucher</dc:creator>
      <category><![CDATA[Real Estate]]></category>
      <category><![CDATA[first-time homebuyers]]></category>
      <category><![CDATA[home inspection]]></category>
      <category><![CDATA[home inspector]]></category>
      <category><![CDATA[homebuyer]]></category>
      <category><![CDATA[homebuyer q&a]]></category>
      <guid isPermaLink="false">http://legalbuffet.com/legalblog/?p=914</guid>
      <description>Check out Part 1, Part 2, Part 3, Part 4 and Part 5 of this semi-regular series.
Okay, so what steps can I take to protect my family and myself?
22.  WHAT CAN I DO TO KEEP MY FAMILY SAFE FROM LEAD IN THE HOME?
For all houses built before 1978, it&amp;#8217;s absolutely crucial to have an [...]&lt;p&gt;&lt;a href="http://legalbuffet.com/legalblog/first-time-homebuyers-qa-part-6/"&gt;First-Time Homebuyers Q&amp;amp;A:  Part 6..&lt;/a&gt; is a post from: &lt;a href="http://legalbuffet.com/legalblog"&gt;LegalBuffet Blog&lt;/a&gt;&lt;/p&gt;&lt;br&gt;&lt;a type="audio/mpeg" href="http://podcasts.odiogo.com/get_mp3.mp3?f=/legalbuffet-blog/LegalBuffet_Blog-First-Time_Homebuyers_QA-__Part_6.mp3"&gt;Click here to play&lt;/a&gt;&lt;br&gt;</description>
      <content:encoded><![CDATA[<p><img class="alignleft size-medium wp-image-922" src="http://legalbuffet.com/legalblog/wp-content/uploads/2009/08/leadpaint-300x199.jpg" alt="leadpaint" width="300" height="199" />Check out <a href="../first-time-homebuyer-qa-part-1/">Part 1</a>, <a href="../first-time-homebuyer-qa-part-2/">Part 2</a>, <a href="../first-time-homebuyer-qa-part-3/">Part 3</a>, <a href="../first-time-homebuyers-qa-part-4/">Part 4</a> and <a href="http://legalbuffet.com/legalblog/first-time-homebuyers-qa-part-5/#more-873">Part 5</a> of this semi-regular series.</p>
<p>Okay, so what steps can I take to protect my family and myself?</p>
<p>22.  WHAT CAN I DO TO KEEP MY FAMILY SAFE FROM LEAD IN THE HOME?</p>
<p>For all houses built before 1978, it&#8217;s absolutely crucial to have an inspection for lead-based paint if you have children under 7 years old.  Lead flakes from paint can be contained in both the home and the soil surrounding the house, so make sure all potentially dangerous areas are checked.  Temporary solutions include repairing damaged paint areas or planting grass over contaminated soil, but a more permanent fix is hiring a lead abatement contractor to remove the lead-filled paint chips and seal all damaged areas.</p>
<p>23.  SHOULD I BE WORRIED ABOUT POWER LINES?</p>
<p>There haven&#8217;t been any definitive findings in studies that indicate exposure to power lines brings about greater amounts of disease or illness.  So the answer is, most likely not.</p>
<p>24.  SHOULD I HIRE A LAWYER TO BUY A HOME?</p>
<p><span id="more-914"></span>The answer to this depends on what state you&#8217;re purchasing a home in, since laws vary.  Some states require that a lawyer participates in several different aspects of the home buying process, while others only require a qualified real estate profession be involved.  However, even in states that don&#8217;t require a lawyer be involved, you may choose to hire one for complex paperwork or legal contracts.  Lawyers can review contracts, point out considerations you may not have thought about, and help in the closing project.  You should be able to shop around for a reputable attorney who also has a reasonable hourly fee to help you out.  In fact, your real estate agent may be able to recommend someone they particularly trust.  Just make sure you find one who is experienced in representing homebuyers and not just commercial real estate, as the two can involve slightly different skill sets.</p>
<p>25.  DO I ABSOLUTELY HAVE TO HAVE HOMEOWNER&#8217;S INSURANCE?</p>
<p>Yes!  First, you&#8217;ll have to show a paid homeowner&#8217;s insurance policy, or a paid receipt, at closing.  Secondly, it really is for your own protection.  Involving an insurance agent earlier on in the process can save you money, since agents can give excellent tips on home safety and methods for keeping insurance premiums low.</p>
<p>26. SPEAKING OF WHICH, CAN I DO ANYTHING TO KEEP MY HOMEOWNER&#8217;S INSURANCE RATES REASONABLE?</p>
<p>Again, absolutely.  One important step is to shop, shop, shop!  Don&#8217;t just sign up with the first insurance company you contact.  Make sure you compare both premium amounts as well as differences in insurance coverage.  Also think about things like flood plains or construction materials when you&#8217;re shopping around for the right house.  Newer homes and those constructed of sturdier material like brick tend to have lower insurance premiums.</p>
<p><b>Looking for information about <a href="http://legalbuffet.com/real-estate-legal-forms/">real estate contracts</a>? Find it here!</b></p>
<p><a href="http://legalbuffet.com/legalblog/first-time-homebuyers-qa-part-6/">First-Time Homebuyers Q&amp;A:  Part 6..</a> is a post from: <a href="http://legalbuffet.com/legalblog">LegalBuffet Blog</a></p>
<div class="feedflare">
<a href="http://feeds.feedburner.com/~ff/LegalBuffetBlog?a=BhdyKHtNdnY:AXVN03_NOSM:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/LegalBuffetBlog?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/LegalBuffetBlog?a=BhdyKHtNdnY:AXVN03_NOSM:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/LegalBuffetBlog?i=BhdyKHtNdnY:AXVN03_NOSM:gIN9vFwOqvQ" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/LegalBuffetBlog?a=BhdyKHtNdnY:AXVN03_NOSM:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/LegalBuffetBlog?i=BhdyKHtNdnY:AXVN03_NOSM:V_sGLiPBpWU" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/LegalBuffetBlog?a=BhdyKHtNdnY:AXVN03_NOSM:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/LegalBuffetBlog?d=qj6IDK7rITs" border="0"></img></a>
</div><img src="http://feeds.feedburner.com/~r/LegalBuffetBlog/~4/BhdyKHtNdnY" height="1" width="1"/>]]></content:encoded>
      <wfw:commentRss>http://legalbuffet.com/legalblog/first-time-homebuyers-qa-part-6/feed/</wfw:commentRss>
      <slash:comments>0</slash:comments>
      <feedburner:origLink>http://legalbuffet.com/legalblog/first-time-homebuyers-qa-part-6/</feedburner:origLink>
      <enclosure url="http://podcasts.odiogo.com/get_mp3.mp3?f=/legalbuffet-blog/LegalBuffet_Blog-First-Time_Homebuyers_QA-__Part_6.mp3" length="1665724" type="audio/mpeg" />
    </item>
    <item>
      <title>Back to School Basics:  When Are Student Loans Dischargeable Through Bankruptcy?</title>
      <link>http://feedproxy.google.com/~r/LegalBuffetBlog/~3/nKrYV3RbjEA/</link>
      <comments>http://legalbuffet.com/legalblog/back-to-school-basics-when-are-student-loans-dischargeable-through-bankruptcy/#comments</comments>
      <pubDate>Thu, 20 Aug 2009 14:38:21 +0000</pubDate>
      <dc:creator>Heather Faucher</dc:creator>
      <category><![CDATA[Bankruptcy]]></category>
      <category><![CDATA[student loan debt]]></category>
      <category><![CDATA[student loans]]></category>
      <guid isPermaLink="false">http://legalbuffet.com/legalblog/?p=909</guid>
      <description>Ahhh, fall is in the air.  Back to school time for many across the land&amp;#8211;including college students and recent college grads now swimming in student loan debt and struggling to make ends meet in the current economy.  For those whose finances are dire enough, it may be time to consider bankruptcy.  One [...]&lt;p&gt;&lt;a href="http://legalbuffet.com/legalblog/back-to-school-basics-when-are-student-loans-dischargeable-through-bankruptcy/"&gt;Back to School Basics:  When Are Student Loans Dischargeable Through Bankruptcy?&lt;/a&gt; is a post from: &lt;a href="http://legalbuffet.com/legalblog"&gt;LegalBuffet Blog&lt;/a&gt;&lt;/p&gt;&lt;br&gt;&lt;a type="audio/mpeg" href="http://podcasts.odiogo.com/get_mp3.mp3?f=/legalbuffet-blog/LegalBuffet_Blog-Back_to_School_Basics-__When_Are_Student_Loans_Dischargeable_Through_Bankruptcy.mp3"&gt;Click here to play&lt;/a&gt;&lt;br&gt;</description>
      <content:encoded><![CDATA[<p><img class="alignleft size-medium wp-image-912" src="http://legalbuffet.com/legalblog/wp-content/uploads/2009/08/happyman-200x300.jpg" alt="happyman" width="200" height="300" />Ahhh, fall is in the air.  Back to school time for many across the land&#8211;including college students and recent college grads now swimming in student loan debt and struggling to make ends meet in the current economy.  For those whose finances are dire enough, it may be time to consider bankruptcy.  One often-asked question from people considering filing for bankruptcy is, &#8220;Can I get my student loans like the Federal Stafford, Federal PLUS and private loans forgiven through bankruptcy?&#8221;</p>
<p>Unfortunately, the answer to that question is probably not.  <span style="text-decoration: underline">Section 523(a)(8) of the US Bankruptcy Code, at 11 U.S.C.</span> states that &#8220;an educational benefit overpayment or loan made, insured, or guaranteed by a governmental unit, or made under any program funded in whole or in part by a governmental unit or nonprofit institution; or an obligation to repay funds received as an educational benefit, scholarship, or stipend; or any other educational loan that is a qualified education loan, as defined in section 221(d)(1) of the Internal Revenue Code of 1986, incurred by a debtor who is an individual&#8221; are <span style="text-decoration: underline">not</span> dischargeable through bankruptcy <span style="text-decoration: underline">unless</span> &#8220;excepting such debt from discharge under this paragraph would impose an undue hardship on the debtor and the debtor&#8217;s dependents&#8221;.</p>
<p>This means that all qualifying educational loans made solely to pay the higher education expenses of an eligible in situations where the student is the debtor, the debtor&#8217;s spouse, or the debtor&#8217;s dependent will not be forgiven during the bankruptcy process.  The loans must apply to schools that are Title IV eligible and the student must be enrolled on at least a half-time basis.  Of course, if the student used credit cards to finance tuition, that type of debt still will be dischargeable even if it was used to finance higher education expenses.</p>
<p><span id="more-909"></span>The only exception allowing federally-funded student loans and education loans funded or guaranteed by private nonprofit organizations to become dischargeable through bankruptcy is when the borrower files an undue hardship petition and the bankruptcy judge rules that the loan <span style="text-decoration: underline">can</span> be discharged.  Of course, that brings about a new question.  What&#8217;s going to make a judge find that a student meets the standard for &#8220;undue hardship?&#8221;</p>
<p>Most court cases cite <span style="text-decoration: underline">Brunner v. New York State Higher Education Services Corp.</span> for a definition of &#8220;undue hardship&#8221;.  (See Brunner v. NY HESC (In re Brunner), 831 F.2d 395 (2d Cir. 1987), aff&#8217;g 46 B.R. 752 (Bankr. S.D.N.Y. 1985) ).  In order to qualify for this exception, the student loan borrower must show:</p>
<p>1. That the debtor cannot both repay the student loan and maintain a minimal standard of living based on current income and expenses;</p>
<p>2. That this situation is likely to persist for a significant portion of the repayment period of the student loans; and</p>
<p>3. That the debtor has made good faith efforts to repay the loans.</p>
<p>If the borrower demonstrates these three elements to the court, then chances are their student loan debt will be ruled dischargeable through bankruptcy.</p>
<p><b>Thinking about <a href="http://legalbuffet.com/bankruptcy-services/">filing bankruptcy</a>? Find more information here. </b></p>
<p><a href="http://legalbuffet.com/legalblog/back-to-school-basics-when-are-student-loans-dischargeable-through-bankruptcy/">Back to School Basics:  When Are Student Loans Dischargeable Through Bankruptcy?</a> is a post from: <a href="http://legalbuffet.com/legalblog">LegalBuffet Blog</a></p>
<div class="feedflare">
<a href="http://feeds.feedburner.com/~ff/LegalBuffetBlog?a=nKrYV3RbjEA:_vyEFBrXdvo:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/LegalBuffetBlog?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/LegalBuffetBlog?a=nKrYV3RbjEA:_vyEFBrXdvo:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/LegalBuffetBlog?i=nKrYV3RbjEA:_vyEFBrXdvo:gIN9vFwOqvQ" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/LegalBuffetBlog?a=nKrYV3RbjEA:_vyEFBrXdvo:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/LegalBuffetBlog?i=nKrYV3RbjEA:_vyEFBrXdvo:V_sGLiPBpWU" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/LegalBuffetBlog?a=nKrYV3RbjEA:_vyEFBrXdvo:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/LegalBuffetBlog?d=qj6IDK7rITs" border="0"></img></a>
</div><img src="http://feeds.feedburner.com/~r/LegalBuffetBlog/~4/nKrYV3RbjEA" height="1" width="1"/>]]></content:encoded>
      <wfw:commentRss>http://legalbuffet.com/legalblog/back-to-school-basics-when-are-student-loans-dischargeable-through-bankruptcy/feed/</wfw:commentRss>
      <slash:comments>1</slash:comments>
      <feedburner:origLink>http://legalbuffet.com/legalblog/back-to-school-basics-when-are-student-loans-dischargeable-through-bankruptcy/</feedburner:origLink>
      <enclosure url="http://podcasts.odiogo.com/get_mp3.mp3?f=/legalbuffet-blog/LegalBuffet_Blog-Back_to_School_Basics-__When_Are_Student_Loans_Dischargeable_Through_Bankruptcy.mp3" length="1816290" type="audio/mpeg" />
    </item>
    <item>
      <title>Prenuptial Contracts Gaining Traction Worldwide…</title>
      <link>http://feedproxy.google.com/~r/LegalBuffetBlog/~3/2C3VY56h9RU/</link>
      <comments>http://legalbuffet.com/legalblog/prenuptial-contracts-gaining-traction-worldwide/#comments</comments>
      <pubDate>Tue, 18 Aug 2009 23:01:29 +0000</pubDate>
      <dc:creator>Heather Faucher</dc:creator>
      <category><![CDATA[Prenups]]></category>
      <category><![CDATA[prenuptial agreements]]></category>
      <guid isPermaLink="false">http://legalbuffet.com/legalblog/?p=903</guid>
      <description>British law, which generally doesn&amp;#8217;t recognize prenuptial contracts, is going to have to start taking them a whole lot more seriously now.  An appeals court judge recently strengthened their status in the Britain when he ruled that a German heiress&amp;#8217; prenuptial agreement with her husband should influence how the couple&amp;#8217;s assets are divided.  [...]&lt;p&gt;&lt;a href="http://legalbuffet.com/legalblog/prenuptial-contracts-gaining-traction-worldwide/"&gt;Prenuptial Contracts Gaining Traction Worldwide&amp;#8230;&lt;/a&gt; is a post from: &lt;a href="http://legalbuffet.com/legalblog"&gt;LegalBuffet Blog&lt;/a&gt;&lt;/p&gt;&lt;br&gt;&lt;a type="audio/mpeg" href="http://podcasts.odiogo.com/get_mp3.mp3?f=/legalbuffet-blog/LegalBuffet_Blog-Prenuptial_Contracts_Gaining_Traction_Worldwide.mp3"&gt;Click here to play&lt;/a&gt;&lt;br&gt;</description>
      <content:encoded><![CDATA[<p><img class="alignleft size-medium wp-image-906" src="http://legalbuffet.com/legalblog/wp-content/uploads/2009/08/prenuptial-300x199.jpg" alt="prenuptial" width="300" height="199" />British law, which generally doesn&#8217;t recognize prenuptial contracts, is going to have to start taking them a whole lot more seriously now.  An appeals court judge recently strengthened their status in the Britain when he ruled that a German heiress&#8217; prenuptial agreement with her husband should influence how the couple&#8217;s assets are divided.  Lord Justice Mathew Thorpe, who presided over the case of Katrin Radmacher and her ex-husband Nicolas Granatino, stated that the current low status of prenuptial agreements under British law reflects the moral and legal values of earlier generations.</p>
<p>&#8220;It does not sufficiently recognize the rights of autonomous adults to govern their future financial relationship by agreement in an age when marriage is not generally regarded as a sacrament and divorce is a statistical commonplace,&#8221; he said.</p>
<p>Thorpe overruled a lower court&#8217;s ruling that awarded Radmacher&#8217;s former husband Granatino 5.85 million pounds ($9.6 million US).  The judge reduced Radmacher&#8217;s obligation to her ex-husband to approximately 1 million pounds ($1.6 million US) in place of maintenance and a 2.5 million pound ($3.6 million US) loan for a house that will be returned when the couple&#8217;s youngest daughter, now aged 6, reaches 22 years.  Radmacher also consented to pay off 700,000 pounds ($1.15 million US) in debts that her ex-husband owes.</p>
<p><span id="more-903"></span>The couple&#8217;s prenuptial agreement stated that Granatino would receive <span style="text-decoration: underline">none</span> of Radmacher&#8217;s fortune in the event they divorced.  The agreement would have been enforceable in Germany, where they signed it, but the couple divorced in Britain instead, a country with a history of courts refusing to enforce such agreements.  Thorpe wrote in his ruling that Britain is &#8220;in danger of isolation in the wider common law world if we do not give greater force and effect to ante-nuptial contracts.&#8221;</p>
<p>Radmacher previously argued that her former husband earned plenty of money as a banker to easily support himself, so the prenuptial agreement should hold firm.  But Granatino quit his job in 2003 in order to obtain a doctorate in biotechnology from Oxford University.  The original trial judge, Florence Baron, pointed out several factors in Granatino&#8217;s favor:  he had not had independent counsel before signing the prenuptial agreement, the marriage produced two children, and ruling out support for the husband would be patently unfair if he was genuinely in need.</p>
<p>Radmacher said in a statement that to her, the case was about a broken promise.</p>
<p>&#8220;When we met and married, Nicolas and I were broadly on an equal footing financially. He, too, is an heir to a multimillion-pound fortune and, when we met, was an investment banker earning up to 330,000 pounds ($520,000) a year,&#8221; she said. &#8220;The agreement was at my father&#8217;s insistence as he wanted to protect my inheritance. This is perfectly normal in our countries of origin, France and Germany.&#8221;  And, on the up side, she said that her daughters were now assured to live comfortably when residing with Granatino.</p>
<p>Britain&#8217;s Law Commission is said to be currently reviewing the status of prenuptial agreements, though it&#8217;s not expected to draw up any conclusions for at least three years.</p>
<p><b>Is a <a href="http://legalbuffet.com/divorce-premarital-name-change/prenuptial-agreements/">prenup</a> something you need to consider? Find the documents you need here.</b></p>
<p><a href="http://legalbuffet.com/legalblog/prenuptial-contracts-gaining-traction-worldwide/">Prenuptial Contracts Gaining Traction Worldwide&#8230;</a> is a post from: <a href="http://legalbuffet.com/legalblog">LegalBuffet Blog</a></p>
<div class="feedflare">
<a href="http://feeds.feedburner.com/~ff/LegalBuffetBlog?a=2C3VY56h9RU:ZIU_QwFS5ic:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/LegalBuffetBlog?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/LegalBuffetBlog?a=2C3VY56h9RU:ZIU_QwFS5ic:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/LegalBuffetBlog?i=2C3VY56h9RU:ZIU_QwFS5ic:gIN9vFwOqvQ" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/LegalBuffetBlog?a=2C3VY56h9RU:ZIU_QwFS5ic:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/LegalBuffetBlog?i=2C3VY56h9RU:ZIU_QwFS5ic:V_sGLiPBpWU" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/LegalBuffetBlog?a=2C3VY56h9RU:ZIU_QwFS5ic:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/LegalBuffetBlog?d=qj6IDK7rITs" border="0"></img></a>
</div><img src="http://feeds.feedburner.com/~r/LegalBuffetBlog/~4/2C3VY56h9RU" height="1" width="1"/>]]></content:encoded>
      <wfw:commentRss>http://legalbuffet.com/legalblog/prenuptial-contracts-gaining-traction-worldwide/feed/</wfw:commentRss>
      <slash:comments>0</slash:comments>
      <feedburner:origLink>http://legalbuffet.com/legalblog/prenuptial-contracts-gaining-traction-worldwide/</feedburner:origLink>
      <enclosure url="http://podcasts.odiogo.com/get_mp3.mp3?f=/legalbuffet-blog/LegalBuffet_Blog-Prenuptial_Contracts_Gaining_Traction_Worldwide.mp3" length="1788588" type="audio/mpeg" />
    </item>
    <item>
      <title>There May Be Hope for the Real Estate Market Yet!</title>
      <link>http://feedproxy.google.com/~r/LegalBuffetBlog/~3/CRQZiEoC8wk/</link>
      <comments>http://legalbuffet.com/legalblog/there-may-be-hope-for-the-real-estate-market-yet/#comments</comments>
      <pubDate>Thu, 13 Aug 2009 16:18:59 +0000</pubDate>
      <dc:creator>Heather Faucher</dc:creator>
      <category><![CDATA[Real Estate]]></category>
      <category><![CDATA[existing-home sales]]></category>
      <category><![CDATA[housing]]></category>
      <category><![CDATA[housing market]]></category>
      <category><![CDATA[real estate market]]></category>
      <guid isPermaLink="false">http://legalbuffet.com/legalblog/?p=897</guid>
      <description>There may be hope for consumers who have spent months&amp;#8211;if not years&amp;#8211;trying to sell their homes in a housing market that has been not-so-hot for the past couple of years.  According to the latest survey conducted by the National Association of REALTORS®, existing-home sales showed healthy gains in the second quarter versus the first [...]&lt;p&gt;&lt;a href="http://legalbuffet.com/legalblog/there-may-be-hope-for-the-real-estate-market-yet/"&gt;There May Be Hope for the Real Estate Market Yet!&lt;/a&gt; is a post from: &lt;a href="http://legalbuffet.com/legalblog"&gt;LegalBuffet Blog&lt;/a&gt;&lt;/p&gt;&lt;br&gt;&lt;a type="audio/mpeg" href="http://podcasts.odiogo.com/get_mp3.mp3?f=/legalbuffet-blog/LegalBuffet_Blog-There_May_Be_Hope_for_the_Real_Estate_Market_Yet.mp3"&gt;Click here to play&lt;/a&gt;&lt;br&gt;</description>
      <content:encoded><![CDATA[<p><img class="alignleft size-medium wp-image-898" src="http://legalbuffet.com/legalblog/wp-content/uploads/2009/08/monopolyhouses-300x225.jpg" alt="monopolyhouses" width="300" height="225" />There may be hope for consumers who have spent months&#8211;if not years&#8211;trying to sell their homes in a housing market that has been not-so-hot for the past couple of years.  According to the latest survey conducted by the National Association of REALTORS®, existing-home sales showed healthy gains in the second quarter versus the first quarter in most states.  Additionally, the decline in home prices has increased the affordability in most metro areas.</p>
<p>Thirty-nine states showed increased sales compared to the first quarter, and nine states had higher sales than those from a year ago; the District of Columbia enjoyed both quarterly and annual increases.  According to the survey, the nation&#8217;s total existing-home sales (which includes single-family as well as condo properties) increased by 3.8 percent in the second quarter compared to the first, although it remains 2.9 percent lower than the amount of sales in the second quarter of 2008.  Still, the fact that sales are once again increasing is definitely a positive sign.</p>
<p><span id="more-897"></span> “With low interest rates, lower home prices, and a first-time buyer tax credit, we’ve been seeing healthy increases in home sales, which are a hopeful sign for the economy,” said Lawrence Yun, NAR chief economist.  “There have been sustained sales gains in Arizona, Nevada, and Florida, as well as diverse areas such as Maryland, the District of Columbia, and Nebraska.  More recently, we’ve seen strong double-digit gains in Idaho, Utah, New Mexico, Washington, Hawaii, New York, New Jersey, Maine, Vermont, Wisconsin, Indiana, South Dakota, and Montana.”</p>
<p>Yun went on to relate the housing industry&#8217;s effect on the economy at large. “Given the need for related goods and services, each home sale pumps an additional $63,000 into the economy – that’s how the housing engine traditionally pulls us out of recession.  In addition, sales are drawing down inventory and that will help stabilize home values, which in turn will lessen foreclosure pressure and boost credit availability for other sectors of the economy.”</p>
<p>The biggest sales increases from the first to second quarters were in the following states:</p>
<p>1. Idaho, by 67.5 percent<br />
2. Hawaii, by 24.2 percent<br />
3. New York, by 22.3 percent<br />
4. Wisconsin, by 21.7 percent<br />
5. Nebraska, by 20.3 percent</p>
<p><b>Are you considering buying a home while prices and interest rates are low? Get more information aout <a href="http://legalbuffet.com/real-estate-legal-forms/">real estate contracts</a> here.</b></p>
<p><a href="http://legalbuffet.com/legalblog/there-may-be-hope-for-the-real-estate-market-yet/">There May Be Hope for the Real Estate Market Yet!</a> is a post from: <a href="http://legalbuffet.com/legalblog">LegalBuffet Blog</a></p>
<div class="feedflare">
<a href="http://feeds.feedburner.com/~ff/LegalBuffetBlog?a=CRQZiEoC8wk:oOkTBqMXy5E:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/LegalBuffetBlog?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/LegalBuffetBlog?a=CRQZiEoC8wk:oOkTBqMXy5E:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/LegalBuffetBlog?i=CRQZiEoC8wk:oOkTBqMXy5E:gIN9vFwOqvQ" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/LegalBuffetBlog?a=CRQZiEoC8wk:oOkTBqMXy5E:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/LegalBuffetBlog?i=CRQZiEoC8wk:oOkTBqMXy5E:V_sGLiPBpWU" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/LegalBuffetBlog?a=CRQZiEoC8wk:oOkTBqMXy5E:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/LegalBuffetBlog?d=qj6IDK7rITs" border="0"></img></a>
</div><img src="http://feeds.feedburner.com/~r/LegalBuffetBlog/~4/CRQZiEoC8wk" height="1" width="1"/>]]></content:encoded>
      <wfw:commentRss>http://legalbuffet.com/legalblog/there-may-be-hope-for-the-real-estate-market-yet/feed/</wfw:commentRss>
      <slash:comments>0</slash:comments>
      <feedburner:origLink>http://legalbuffet.com/legalblog/there-may-be-hope-for-the-real-estate-market-yet/</feedburner:origLink>
      <enclosure url="http://podcasts.odiogo.com/get_mp3.mp3?f=/legalbuffet-blog/LegalBuffet_Blog-There_May_Be_Hope_for_the_Real_Estate_Market_Yet.mp3" length="1428293" type="audio/mpeg" />
    </item>
  </channel>
</rss>
<!-- 216465 -->
<!-- Generated by Odiogobot V5.309 / http://www.odiogo.com -->
